export type ScheduleUnplacedDiagnostic={id:string;scenario_id:string;subject:string;reason:string;block_hours:number;diagnostic:Record<string,number>|null};
export type ScheduleRepairSignal={scenario_id:string;action_code:string;title:string;legal_safe:boolean;hard_rule_impact:boolean;estimated_gain:number|null};
export type BottleneckSignal={key:string;label:string;occurrences:number;affectedHours:number;scenarioCount:number;severity:"HARD_PRESSURE"|"CAPACITY_PRESSURE"|"QUALITY_PRESSURE";explanation:string};
export type PersistentSubjectBottleneck={key:string;subject:string;reason:string;scenarioCount:number;occurrences:number;affectedHours:number;diagnosticKeys:string[];explanation:string};

const LABEL:Record<string,string>={teacher_busy:"Öğretmen aynı anda dolu",class_busy:"Sınıf aynı anda dolu",teacher_unavailable:"Öğretmen kesin uygun değil",daily_limit:"Öğretmen günlük yük limiti",working_days_limit:"Öğretmen çalışma günü limiti",consecutive_limit:"Öğretmen ardışık ders limiti",course_time_rule:"Ders zaman kuralı",valid_windows:"Geçerli zaman penceresi kıtlığı",candidate_windows:"Aday zaman penceresi kıtlığı",room_busy:"Derslik aynı anda dolu",room_capacity:"Derslik kapasitesi",room_rule:"Derslik türü/özellik kuralı",student_conflict:"Öğrenci çakışması"};
function severity(key:string):BottleneckSignal["severity"]{if(["teacher_busy","class_busy","teacher_unavailable","course_time_rule","student_conflict","room_busy","room_capacity","room_rule"].includes(key))return "HARD_PRESSURE";if(["daily_limit","working_days_limit","consecutive_limit","valid_windows","candidate_windows"].includes(key))return "CAPACITY_PRESSURE";return "QUALITY_PRESSURE"}
function explain(key:string){if(key==="valid_windows"||key==="candidate_windows")return "Bu sinyal düşük oldukça dersin yerleşebileceği güvenli zaman alanı daralır.";if(key.includes("room"))return "Zaman uygun görünse bile oda havuzu veya oda çakışması yerleşimi engelleyebilir.";if(key.includes("teacher"))return "Öğretmen kaynaklı kapasite/çakışma aynı dersin farklı adaylarda tekrar dışarıda kalmasına yol açabilir.";if(key.includes("class"))return "Sınıf zaman çakışması ortak slot havuzunu daraltıyor.";if(key.includes("student"))return "Öğrenci talepleri veya grup üyelikleri aynı zaman penceresinde çakışıyor.";return "Bu sinyal birden fazla adayda tekrar ettiği için yapısal darboğaz adayıdır."}
const normalize=(v:string)=>v.trim().toLocaleLowerCase("tr-TR");

export function analyzeScheduleGenerationBottlenecks(unplaced:ScheduleUnplacedDiagnostic[],suggestions:ScheduleRepairSignal[]=[]){
 const map=new Map<string,{occ:number;hours:number;scenarios:Set<string>}>(),subjectMap=new Map<string,{subject:string;reason:string;occ:number;hours:number;scenarios:Set<string>;diag:Set<string>}>();
 for(const row of unplaced){const diag=row.diagnostic??{};let used=false;for(const [key,value] of Object.entries(diag)){const n=Number(value);if(!Number.isFinite(n)||n<=0||key==="candidate_windows"||key==="valid_windows")continue;const x=map.get(key)??{occ:0,hours:0,scenarios:new Set<string>()};x.occ+=n;x.hours+=Math.max(1,row.block_hours||1);x.scenarios.add(row.scenario_id);map.set(key,x);used=true}if(!used){const key=row.reason||"unplaced";const x=map.get(key)??{occ:0,hours:0,scenarios:new Set<string>()};x.occ+=1;x.hours+=Math.max(1,row.block_hours||1);x.scenarios.add(row.scenario_id);map.set(key,x)}
  const subject=row.subject?.trim()||"Bilinmeyen ders",reason=row.reason?.trim()||"UNPLACED",subjectKey=`${normalize(subject)}|${normalize(reason)}`,sx=subjectMap.get(subjectKey)??{subject,reason,occ:0,hours:0,scenarios:new Set<string>(),diag:new Set<string>()};sx.occ+=1;sx.hours+=Math.max(1,row.block_hours||1);sx.scenarios.add(row.scenario_id);for(const [key,value] of Object.entries(diag))if(Number(value)>0)sx.diag.add(key);subjectMap.set(subjectKey,sx)
 }
 const signals:Array<BottleneckSignal>=Array.from(map.entries()).map(([key,x])=>({key,label:LABEL[key]??key.replaceAll("_"," "),occurrences:x.occ,affectedHours:x.hours,scenarioCount:x.scenarios.size,severity:severity(key),explanation:explain(key)})).sort((a,b)=>{const s={HARD_PRESSURE:0,CAPACITY_PRESSURE:1,QUALITY_PRESSURE:2};return s[a.severity]-s[b.severity]||b.scenarioCount-a.scenarioCount||b.occurrences-a.occurrences||b.affectedHours-a.affectedHours});
 const scenarioCount=new Set(unplaced.map(x=>x.scenario_id)).size,threshold=Math.max(2,Math.ceil(scenarioCount/2));
 const persistentSubjects:Array<PersistentSubjectBottleneck>=Array.from(subjectMap.entries()).map(([key,x])=>({key,subject:x.subject,reason:x.reason,scenarioCount:x.scenarios.size,occurrences:x.occ,affectedHours:x.hours,diagnosticKeys:[...x.diag].sort(),explanation:`${x.subject} aynı nedenle ${x.scenarios.size} farklı adayda yerleşemedi. Tek senaryo hatası yerine kalıcı ders/kural kesişimi olarak incelenmeli.`})).filter(x=>x.scenarioCount>=threshold).sort((a,b)=>b.scenarioCount-a.scenarioCount||b.affectedHours-a.affectedHours||b.occurrences-a.occurrences);
 const safeSuggestions=suggestions.filter(x=>x.legal_safe&&!x.hard_rule_impact).sort((a,b)=>(b.estimated_gain??0)-(a.estimated_gain??0));
 return {scenarioCount,unplacedCount:unplaced.length,signals,safeSuggestions,persistentSubjects,structural:signals.filter(x=>x.scenarioCount>=threshold),policy:"Tek bir adayda görülen hata yerine adaylar boyunca tekrar eden canonical sinyaller ve aynı ders/neden kesişimleri önce ele alınır; HARD kurallar otomatik gevşetilmez." as const};
}
