import {supabase} from "@/lib/supabase";
import {evaluatePlanningRelations,type PlanningActivity,type PlanningRelation} from "@/lib/schedule-planning-relations";

export type EjectionMove={schedule_id:string;weekday:number;period:number;classroom_id?:string|null};
export type EjectionCandidate={depth:number;moves:EjectionMove[];score:{medium:number;soft:number;moveCost:number};explanation:string};
type Row={id:string;teacher_id:string;class_id:string|null;classroom_id:string|null;subgroup_id:string|null;teacher_assignment_id:string|null;weekday:number;period:number;locked:boolean};
type Assignment={teacher_assignment_id:string;teacher_id:string;class_id:string;course_id:string};
type ConflictWeight={left_assignment_id:string;right_assignment_id:string;severity_weight:number;student_weight:number};
type Profile={teaching_days:number[];periods_per_day:number};
type AtomicPlan={ok:boolean;error?:string;moves?:EjectionMove[];duration?:number;block?:boolean};

type PlanningInput={rows:Row[];assignmentById:Map<string,Assignment>;relations:PlanningRelation[];conflictWeights:ConflictWeight[]};
const slotKey=(d:number,p:number)=>`${d}|${p}`;
const pairKey=(a:string,b:string)=>a<b?`${a}|${b}`:`${b}|${a}`;

export function mergeEjectionMoves(base:EjectionMove[],extra:EjectionMove[]):EjectionMove[]|null{
 const m=new Map<string,EjectionMove>();
 for(const x of [...base,...extra]){const old=m.get(x.schedule_id);if(old&&(old.weekday!==x.weekday||old.period!==x.period||(old.classroom_id??null)!==(x.classroom_id??null)))return null;m.set(x.schedule_id,x)}
 return [...m.values()];
}

export function applyMoves(rows:Row[],moves:EjectionMove[]){const mm=new Map(moves.map(x=>[x.schedule_id,x]));return rows.map(r=>{const m=mm.get(r.id);return m?{...r,weekday:m.weekday,period:m.period,classroom_id:m.classroom_id===undefined?r.classroom_id:m.classroom_id??null}:r})}

export function findDirectBlockers(rows:Row[],moves:EjectionMove[],conflictWeights:ConflictWeight[]=[]){
 const movedIds=new Set(moves.map(x=>x.schedule_id)),after=applyMoves(rows,moves),byId=new Map(after.map(x=>[x.id,x])),weights=new Set(conflictWeights.filter(x=>(Number(x.severity_weight)||Number(x.student_weight))>0).map(x=>pairKey(x.left_assignment_id,x.right_assignment_id))),out=new Map<string,Row>();
 for(const mv of moves){const r=byId.get(mv.schedule_id);if(!r)continue;for(const other of after){if(other.id===r.id||movedIds.has(other.id)||other.weekday!==r.weekday||other.period!==r.period)continue;const sameTeacher=other.teacher_id===r.teacher_id,sameClass=Boolean(r.class_id&&other.class_id===r.class_id),sameRoom=Boolean(r.classroom_id&&other.classroom_id===r.classroom_id),student=Boolean(r.teacher_assignment_id&&other.teacher_assignment_id&&weights.has(pairKey(r.teacher_assignment_id,other.teacher_assignment_id)));if(sameTeacher||sameClass||sameRoom||student)out.set(other.id,other)}}
 return [...out.values()].sort((a,b)=>Number(a.locked)-Number(b.locked)||a.id.localeCompare(b.id));
}

function contiguousActivities(rows:Row[],assignmentById:Map<string,Assignment>):PlanningActivity[]{const groups=new Map<string,Row[]>();for(const r of rows){if(!r.teacher_assignment_id)continue;const k=`${r.teacher_assignment_id}|${r.weekday}`,a=groups.get(k);if(a)a.push(r);else groups.set(k,[r])}const out:PlanningActivity[]=[];for(const rs of groups.values()){rs.sort((a,b)=>a.period-b.period);let bucket:Row[]=[];for(const r of rs){if(!bucket.length||r.period===(bucket.at(-1)!.period+1))bucket.push(r);else{push(bucket);bucket=[r]}}push(bucket)}return out;function push(bucket:Row[]){if(!bucket.length)return;const first=bucket[0]!,a=assignmentById.get(first.teacher_assignment_id??"");if(!a)return;out.push({activity_key:`${a.teacher_assignment_id}:${first.weekday}:${bucket[0]!.period}`,assignment_id:a.teacher_assignment_id,course_id:a.course_id,teacher_id:a.teacher_id,class_id:a.class_id,weekday:first.weekday,start:bucket[0]!.period,end:bucket.at(-1)!.period})}}

export function scoreEjectionCandidate(input:PlanningInput,moves:EjectionMove[]){const after=applyMoves(input.rows,moves),weights=new Map(input.conflictWeights.map(x=>[pairKey(x.left_assignment_id,x.right_assignment_id),Number(x.severity_weight)||Number(x.student_weight)||0]));let medium=0,late=0,gaps=0,moveCost=0;const bySlot=new Map<string,Row[]>(),byTeacherDay=new Map<string,number[]>(),byClassDay=new Map<string,number[]>();for(const r of after){const sk=slotKey(r.weekday,r.period);bySlot.set(sk,[...(bySlot.get(sk)??[]),r]);late+=Math.max(0,r.period-6);byTeacherDay.set(`${r.teacher_id}|${r.weekday}`,[...(byTeacherDay.get(`${r.teacher_id}|${r.weekday}`)??[]),r.period]);if(r.class_id)byClassDay.set(`${r.class_id}|${r.weekday}`,[...(byClassDay.get(`${r.class_id}|${r.weekday}`)??[]),r.period])}for(const rs of bySlot.values())for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i]!.teacher_assignment_id,b=rs[j]!.teacher_assignment_id;if(a&&b)medium+=weights.get(pairKey(a,b))??0}for(const ps of [...byTeacherDay.values(),...byClassDay.values()]){const u=[...new Set(ps)].sort((a,b)=>a-b);if(u.length>1)gaps+=(u.at(-1)??0)-(u[0]??0)+1-u.length}for(const m of moves){const old=input.rows.find(r=>r.id===m.schedule_id);if(old)moveCost+=1+Math.abs(old.weekday-m.weekday)*2+Math.abs(old.period-m.period)+(old.classroom_id!==(m.classroom_id===undefined?old.classroom_id:m.classroom_id??null)?3:0)}const rel=evaluatePlanningRelations(contiguousActivities(after,input.assignmentById),input.relations);return{medium:medium+rel.medium,soft:gaps*8+late*2+rel.soft+moveCost,moveCost}}

async function atomicPlan(id:string,weekday:number,period:number,classroomId:string|null){const q=await supabase.rpc("get_schedule_atomic_move_plan_v1",{p_schedule_id:id,p_weekday:weekday,p_period:period,p_classroom_id:classroomId});if(q.error)return{ok:false,error:q.error.message} as AtomicPlan;return (q.data??{ok:false,error:"ATOMIC_PLAN_EMPTY"}) as AtomicPlan}
async function preview(moves:EjectionMove[]){const q=await supabase.rpc("preview_schedule_batch_move_v1",{p_moves:moves});if(q.error)return{ok:false,error:q.error.message};return (q.data??{ok:false,error:"PREVIEW_EMPTY"}) as {ok:boolean;error?:string}}

export async function suggestDeepEjectionChains(opts:{scheduleId:string;weekday:number;period:number;maxDepth?:number;limit?:number;maxExpanded?:number}):Promise<EjectionCandidate[]>{
 const maxDepth=Math.max(3,Math.min(5,opts.maxDepth??5)),limit=Math.max(1,Math.min(12,opts.limit??8)),maxExpanded=Math.max(20,Math.min(240,opts.maxExpanded??120));
 const [r,a,p,rel,cw]=await Promise.all([supabase.from("teacher_schedule").select("id,teacher_id,class_id,classroom_id,subgroup_id,teacher_assignment_id,weekday,period,locked").eq("active",true),supabase.from("schedule_assignment_options").select("teacher_assignment_id,teacher_id,class_id,course_id"),supabase.rpc("get_active_schedule_time_profile"),supabase.rpc("get_schedule_planning_relations_v1"),supabase.rpc("get_schedule_assignment_student_conflict_weights_v2")]);
 const err=r.error??a.error??p.error??rel.error??cw.error;if(err)throw err;const rows=(r.data??[]) as Row[],source=rows.find(x=>x.id===opts.scheduleId);if(!source)throw new Error("SCHEDULE_ROW_NOT_FOUND");if(source.locked)throw new Error("SCHEDULE_ROW_LOCKED");const profile=p.data as Profile,assignments=(a.data??[]) as Assignment[],assignmentById=new Map(assignments.map(x=>[x.teacher_assignment_id,x])),relations=(rel.data??[]) as PlanningRelation[],conflicts=(cw.data??[]) as ConflictWeight[],planning={rows,assignmentById,relations,conflictWeights:conflicts};
 const first=await atomicPlan(source.id,opts.weekday,opts.period,source.classroom_id);if(!first.ok||!first.moves?.length)throw new Error(first.error??"ATOMIC_PLAN_FAILED");const out:EjectionCandidate[]=[];let expanded=0;const seen=new Set<string>();
 async function walk(moves:EjectionMove[],depth:number,visited:Set<string>):Promise<void>{if(out.length>=limit||expanded>=maxExpanded)return;expanded++;const sig=moves.slice().sort((x,y)=>x.schedule_id.localeCompare(y.schedule_id)).map(x=>`${x.schedule_id}:${x.weekday}:${x.period}`).join(";");if(seen.has(sig))return;seen.add(sig);const pr=await preview(moves);if(pr.ok){const score=scoreEjectionCandidate(planning,moves);out.push({depth,moves,score,explanation:`${depth} halkalı zincir · ${moves.length} atomik satır · MEDIUM ${score.medium} · SOFT ${score.soft}`});return}if(depth>=maxDepth)return;const blockers=findDirectBlockers(rows,moves,conflicts).filter(x=>!x.locked&&!visited.has(x.id));if(!blockers.length)return;const blocker=blockers[0]!;const slots:Array<{d:number;p:number;cost:number}>=[];for(const d of profile.teaching_days)for(let period=1;period<=profile.periods_per_day;period++){if(d===blocker.weekday&&period===blocker.period)continue;slots.push({d,p:period,cost:Math.abs(d-blocker.weekday)*2+Math.abs(period-blocker.period)+Math.max(0,period-6)})}slots.sort((x,y)=>x.cost-y.cost);for(const s of slots.slice(0,18)){if(out.length>=limit||expanded>=maxExpanded)break;const ap=await atomicPlan(blocker.id,s.d,s.p,blocker.classroom_id);if(!ap.ok||!ap.moves?.length)continue;const merged=mergeEjectionMoves(moves,ap.moves);if(!merged)continue;const nextVisited=new Set(visited);for(const m of ap.moves)nextVisited.add(m.schedule_id);await walk(merged,depth+1,nextVisited)}}
 await walk(first.moves,1,new Set(first.moves.map(x=>x.schedule_id)));return out.sort((x,y)=>x.score.medium-y.score.medium||x.score.soft-y.score.soft||x.depth-y.depth||x.moves.length-y.moves.length).slice(0,limit)}

export async function applyEjectionChain(candidate:EjectionCandidate){const pre=await preview(candidate.moves);if(!pre.ok)throw new Error(pre.error??"EJECTION_PREVIEW_FAILED");const q=await supabase.rpc("move_schedule_slots_batch_v1",{p_moves:candidate.moves});if(q.error)throw q.error;return q.data}
