import { evaluateCandidateRelations,evaluatePlanningRelations,type PlanningActivity,type PlanningRelation,type PlanningSelector } from "@/lib/schedule-planning-relations";

export type WeekPattern="ALL"|"ODD"|"EVEN";
export type LocalAssignment={assignment_id:string;teacher_id:string;additional_teacher_ids?:string[]|null;class_id:string;course_id:string;assigned_hours:number;week_pattern?:WeekPattern;valid_from?:string|null;valid_to?:string|null;term_no?:number|null;schedule_session_id?:string|null;allowed_periods?:number[]|null;preferred_periods?:number[]|null;preferred_period_weight?:number|null;subgroup_id?:string|null;student_count?:number|null};
export type LocalLockedRow={assignment_id:string;teacher_id:string;class_id:string|null;weekday:number;period:number;classroom_id?:string|null;subgroup_id?:string|null;schedule_session_id?:string|null;locked:boolean;activity_key?:string|null;activity_duration?:number|null};
export type LocalUnavailable={teacher_id:string;weekday:number;period:number;schedule_session_id?:string|null};
export type LocalTeacherConstraint={teacher_id:string;max_daily_hours:number|null;max_consecutive_hours:number|null};
export type LocalCourseRule={course_id:string;block_pattern?:number[]|null;max_per_day:number|null;prohibited_days:number[]|null;prohibited_periods:number[]|null};
export type LocalStudentConflictWeight={left_assignment_id:string;right_assignment_id:string;student_weight:number;severity_weight:number};
export type LocalSearchStrategy="AUTO"|"LATE_ACCEPTANCE"|"TABU"|"SIMULATED_ANNEALING"|"GREAT_DELUGE"|"VND";
export type LnsNeighborhood="RANDOM_SMALL"|"TEACHER_DAY"|"CLASS_DAY"|"COURSE_BLOCK"|"CONFLICT_HOTSPOT"|"LOW_QUALITY_ZONE";
export type LocalProblem={days:number[];periods:number;assignments:LocalAssignment[];locked:LocalLockedRow[];unavailable:LocalUnavailable[];teacherConstraints:LocalTeacherConstraint[];courseRules:LocalCourseRule[];planningRelations?:PlanningRelation[];studentConflictWeights?:LocalStudentConflictWeight[];seed:number;strategy?:LocalSearchStrategy;maxSearchIterations?:number;enableLns?:boolean;lnsIterations?:number};
export type LocalScore={hard:number;medium:number;soft:number};
export type LnsStats={enabled:boolean;iterations:number;accepted:number;improved:number;rejected:number;ruinedActivities:number;neighborhoods:Record<LnsNeighborhood,number>};
export type LocalCandidate={rows:LocalLockedRow[];failed:number;complete:boolean;seed:number;score:LocalScore;iterations:number;strategy:LocalSearchStrategy;lns:LnsStats};
type Cell={d:number;s:number;score:number};type Task={a:LocalAssignment;duration:number;activityKey:string};type ActivityPlacement={key:string;assignment:LocalAssignment;duration:number;rows:LocalLockedRow[];locked:boolean};
const ZERO_LNS=():LnsStats=>({enabled:false,iterations:0,accepted:0,improved:0,rejected:0,ruinedActivities:0,neighborhoods:{RANDOM_SMALL:0,TEACHER_DAY:0,CLASS_DAY:0,COURSE_BLOCK:0,CONFLICT_HOTSPOT:0,LOW_QUALITY_ZONE:0}});
const key=(...v:(string|number|null|undefined)[])=>v.join("|");
function rng(seed:number){let s=seed|0;return()=>((s=(Math.imul(1664525,s)+1013904223)|0)>>>0)/4294967296}
function lexCompare(a:LocalScore,b:LocalScore){if(a.hard!==b.hard)return a.hard-b.hard;if(a.medium!==b.medium)return a.medium-b.medium;return a.soft-b.soft}
const lexBetter=(a:LocalScore,b:LocalScore)=>lexCompare(a,b)<0,lexNotWorse=(a:LocalScore,b:LocalScore)=>lexCompare(a,b)<=0;
const cloneRows=(r:LocalLockedRow[])=>r.map(x=>({...x}));
export const localAssignmentTeacherIds=(a:LocalAssignment)=>[...new Set([a.teacher_id,...(a.additional_teacher_ids??[])].filter(Boolean))];
export const localAssignmentsShareTeacher=(a?:LocalAssignment,b?:LocalAssignment)=>Boolean(a&&b&&localAssignmentTeacherIds(a).some(id=>localAssignmentTeacherIds(b).includes(id)));
export function localScopesOverlap(a?:LocalAssignment,b?:LocalAssignment){if(!a||!b)return true;if(a.term_no!=null&&b.term_no!=null&&a.term_no!==b.term_no)return false;if((a.week_pattern==="ODD"&&b.week_pattern==="EVEN")||(a.week_pattern==="EVEN"&&b.week_pattern==="ODD"))return false;if(a.valid_from&&b.valid_to&&a.valid_from>b.valid_to)return false;if(b.valid_from&&a.valid_to&&b.valid_from>a.valid_to)return false;return true}
export function localStudentScopesOverlap(a?:LocalAssignment,b?:LocalAssignment){if(!a||!b||a.class_id!==b.class_id)return false;if(a.subgroup_id==null||b.subgroup_id==null)return true;return a.subgroup_id===b.subgroup_id}
function normalizePattern(rule:LocalCourseRule|undefined,total:number){const p=(rule?.block_pattern??[]).map(Number).filter(x=>Number.isInteger(x)&&x>0);return p.length&&p.reduce((a,b)=>a+b,0)===total?p:Array.from({length:total},()=>1)}
function runs(rs:LocalLockedRow[]){const m=new Map<number,number[]>();for(const r of rs)m.set(r.weekday,[...(m.get(r.weekday)??[]),r.period]);const out:{day:number;periods:number[]}[]=[];for(const[d,p0]of m){const ps=[...new Set(p0)].sort((a,b)=>a-b);let q:number[]=[];for(const p of ps){if(!q.length||p===q[q.length-1]!+1)q.push(p);else{out.push({day:d,periods:q});q=[p]}}if(q.length)out.push({day:d,periods:q})}return out}

export function solveLocalSchedule(p:LocalProblem):LocalCandidate{
 const R=rng(p.seed),strategy=p.strategy??"AUTO",relations=p.planningRelations??[],weights=p.studentConflictWeights??[],assignmentMap=new Map(p.assignments.map(a=>[a.assignment_id,a])),rules=new Map(p.courseRules.map(r=>[r.course_id,r])),constraints=new Map(p.teacherConstraints.map(c=>[c.teacher_id,c]));
 const conflictMap=new Map<string,number>();for(const w of weights){const[a,b]=w.left_assignment_id<w.right_assignment_id?[w.left_assignment_id,w.right_assignment_id]:[w.right_assignment_id,w.left_assignment_id];conflictMap.set(key(a,b),Number(w.severity_weight)||Number(w.student_weight)||0)}
 const pairPenalty=(a:string,b:string)=>{const aa=assignmentMap.get(a),bb=assignmentMap.get(b);if(a===b||!localScopesOverlap(aa,bb))return 0;return conflictMap.get(a<b?key(a,b):key(b,a))??0};
 let baseHard=0,failed=0;const rows:LocalLockedRow[]=[],tasks:Task[]=[];const lockedBy=new Map<string,LocalLockedRow[]>();for(const r of p.locked)lockedBy.set(r.assignment_id,[...(lockedBy.get(r.assignment_id)??[]),{...r,locked:true}]);
 for(const a of p.assignments){const pattern=normalizePattern(rules.get(a.course_id),a.assigned_hours),locked=lockedBy.get(a.assignment_id)??[],left=[...pattern];let n=0;for(const run of runs(locked)){const i=left.indexOf(run.periods.length);if(i<0){baseHard++;continue}left.splice(i,1);const ak=`${a.assignment_id}:locked:${++n}`;for(const period of run.periods){const o=locked.find(x=>x.weekday===run.day&&x.period===period)!;if(a.allowed_periods?.length&&!a.allowed_periods.includes(period))baseHard++;rows.push({...o,schedule_session_id:a.schedule_session_id??o.schedule_session_id??null,activity_key:ak,activity_duration:run.periods.length,locked:true})}}left.forEach((d,i)=>tasks.push({a,duration:d,activityKey:`${a.assignment_id}:component:${i+1}:${d}`}))}
 function groups(){const m=new Map<string,LocalLockedRow[]>();for(const r of rows){const k=r.activity_key??`${r.assignment_id}:row:${r.weekday}:${r.period}`;m.set(k,[...(m.get(k)??[]),r])}const out:ActivityPlacement[]=[];for(const[k,rs]of m){const a=assignmentMap.get(rs[0]!.assignment_id);if(a)out.push({key:k,assignment:a,duration:rs.length,rows:rs.sort((x,y)=>x.period-y.period),locked:rs.some(x=>x.locked)})}return out}
 const activities=():PlanningActivity[]=>groups().map(g=>({activity_key:g.key,assignment_id:g.assignment.assignment_id,course_id:g.assignment.course_id,teacher_id:g.assignment.teacher_id,class_id:g.assignment.class_id,weekday:g.rows[0]!.weekday,start:g.rows[0]!.period,end:g.rows[g.rows.length-1]!.period}));
 const taskActivity=(t:Task,d:number,s:number):PlanningActivity=>({activity_key:t.activityKey,assignment_id:t.a.assignment_id,course_id:t.a.course_id,teacher_id:t.a.teacher_id,class_id:t.a.class_id,weekday:d,start:s,end:s+t.duration-1});
 const selectorMatches=(t:Task,s:PlanningSelector)=>(!s.activity_key||s.activity_key===t.activityKey)&&(!s.assignment_id||s.assignment_id===t.a.assignment_id)&&(!s.course_id||s.course_id===t.a.course_id)&&(!s.teacher_id||localAssignmentTeacherIds(t.a).includes(s.teacher_id))&&(!s.class_id||s.class_id===t.a.class_id);
 const dependencyBias=(t:Task)=>relations.reduce((v,r)=>r.mode==="HARD"&&(r.relation_type==="ORDERED"||r.relation_type==="CONSECUTIVE")?(v+(selectorMatches(t,r.left_selector)?1000:0)-(selectorMatches(t,r.right_selector)?1000:0)):v,0);
 const overlappingRows=(a:LocalAssignment)=>rows.filter(r=>localScopesOverlap(a,assignmentMap.get(r.assignment_id)));
 const unavailable=(a:LocalAssignment,d:number,s:number)=>p.unavailable.some(u=>localAssignmentTeacherIds(a).includes(u.teacher_id)&&u.weekday===d&&u.period===s&&(u.schedule_session_id==null||u.schedule_session_id===a.schedule_session_id));
 const occupied=(a:LocalAssignment,d:number,s:number)=>overlappingRows(a).some(r=>r.weekday===d&&r.period===s&&(localAssignmentsShareTeacher(a,assignmentMap.get(r.assignment_id))||localStudentScopesOverlap(a,assignmentMap.get(r.assignment_id))));
 const dailyTeacher=(a:LocalAssignment,teacherId:string,d:number)=>overlappingRows(a).filter(r=>localAssignmentTeacherIds(assignmentMap.get(r.assignment_id)??a).includes(teacherId)&&r.weekday===d).length;
 const dailyCourse=(a:LocalAssignment,d:number)=>overlappingRows(a).filter(r=>r.class_id===a.class_id&&assignmentMap.get(r.assignment_id)?.course_id===a.course_id&&r.weekday===d).length;
 const consecutiveOk=(a:LocalAssignment,teacherId:string,d:number,start:number,duration:number,max:number|null|undefined)=>{if(!max)return true;const ps=new Set(overlappingRows(a).filter(r=>localAssignmentTeacherIds(assignmentMap.get(r.assignment_id)??a).includes(teacherId)&&r.weekday===d).map(r=>r.period));for(let x=start;x<start+duration;x++)ps.add(x);let run=0,best=0;for(let i=1;i<=p.periods;i++){run=ps.has(i)?run+1:0;best=Math.max(best,run)}return best<=max};
 const studentPenalty=(id:string,d:number,s:number,duration:number)=>{let v=0;for(let x=s;x<s+duration;x++)for(const r of rows)if(r.weekday===d&&r.period===x)v+=pairPenalty(id,r.assignment_id);return v};
 const candidateCells=(t:Task):Cell[]=>{const a=t.a,rule=rules.get(a.course_id),teachers=localAssignmentTeacherIds(a),out:Cell[]=[],placed=relations.length?activities():[];for(const d of p.days)for(let s=1;s<=p.periods-t.duration+1;s++){if(rule?.prohibited_days?.includes(d))continue;let bad=false;for(let x=s;x<s+t.duration;x++){if((a.allowed_periods?.length&&!a.allowed_periods.includes(x))||rule?.prohibited_periods?.includes(x)||unavailable(a,d,x)||occupied(a,d,x)){bad=true;break}}if(bad)continue;const tds=teachers.map(id=>dailyTeacher(a,id,d)),cd=dailyCourse(a,d);if(teachers.some((id,i)=>{const c=constraints.get(id);return Boolean(c?.max_daily_hours&&tds[i]!+t.duration>c.max_daily_hours)||!consecutiveOk(a,id,d,s,t.duration,c?.max_consecutive_hours)}))continue;if(rule?.max_per_day&&cd+t.duration>rule.max_per_day)continue;const rel=relations.length?evaluateCandidateRelations(taskActivity(t,d,s),placed,relations):{hard:0,medium:0,soft:0};if(rel.hard>0)continue;const student=studentPenalty(a.assignment_id,d,s,t.duration);let score=tds.reduce((n,v)=>n+v,0)*3+cd*8+Math.max(0,s+t.duration-1-6)*2+(rel.medium+student)*100+rel.soft+R()*.35;out.push({d,s,score})}return out.sort((a,b)=>a.score-b.score)};
 const place=(t:Task,d:number,s:number)=>{for(let x=s;x<s+t.duration;x++)rows.push({assignment_id:t.a.assignment_id,teacher_id:t.a.teacher_id,class_id:t.a.class_id,weekday:d,period:x,subgroup_id:t.a.subgroup_id??null,schedule_session_id:t.a.schedule_session_id??null,locked:false,activity_key:t.activityKey,activity_duration:t.duration})};
 const remove=(rs:LocalLockedRow[])=>{for(const r of rs){const i=rows.indexOf(r);if(i>=0)rows.splice(i,1)}};const toTask=(g:ActivityPlacement):Task=>({a:g.assignment,duration:g.duration,activityKey:g.key});
 const construct=(q0:Task[])=>{const q=[...q0];let f=0;while(q.length){let bi=0,bc:Cell[]|null=null,dep=-Infinity,reg=-1,scar=1e9;for(let i=0;i<q.length;i++){const t=q[i]!,cs=candidateCells(t),dd=dependencyBias(t),rr=cs.length?(cs[1]?.score??cs[0]!.score+50)-cs[0]!.score:Infinity;if(dd>dep||(dd===dep&&(rr>reg||(rr===reg&&cs.length<scar)))){bi=i;bc=cs;dep=dd;reg=rr;scar=cs.length}}const t=q.splice(bi,1)[0]!;if(!bc?.length){f+=t.duration;continue}const pick=bc[Math.floor(R()*Math.min(2,bc.length))]!;place(t,pick.d,pick.s)}return f};
 failed+=construct(tasks);
 const scoreNow=(unplaced=failed):LocalScore=>{const teacherDay=new Map<string,number[]>(),classDay=new Map<string,number[]>();let late=0,student=0;for(const r of rows){late+=Math.max(0,r.period-6);const a=assignmentMap.get(r.assignment_id),sig=`${a?.week_pattern??"ALL"}:${a?.term_no??0}:${a?.valid_from??""}:${a?.valid_to??""}`;for(const id of a?localAssignmentTeacherIds(a):[r.teacher_id])teacherDay.set(key(id,r.weekday,sig),[...(teacherDay.get(key(id,r.weekday,sig))??[]),r.period]);classDay.set(key(r.class_id,r.weekday,sig),[...(classDay.get(key(r.class_id,r.weekday,sig))??[]),r.period])}for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i]!,b=rows[j]!;if(a.weekday===b.weekday&&a.period===b.period)student+=pairPenalty(a.assignment_id,b.assignment_id)}let gaps=0;for(const ps of[...teacherDay.values(),...classDay.values()]){const a=[...new Set(ps)].sort((x,y)=>x-y);if(a.length>1)gaps+=(a.at(-1)??0)-(a[0]??0)+1-a.length}const rel=relations.length?evaluatePlanningRelations(activities(),relations):{hard:0,medium:0,soft:0};return{hard:baseHard+unplaced+rel.hard,medium:rel.medium+student,soft:gaps*8+late*2+rel.soft}};
 let iterations=0,current=scoreNow(),best=current,bestRows=cloneRows(rows);
 if(failed===0&&current.hard===0){const initial=Math.max(1,current.medium*100+current.soft),hist=Array.from({length:Math.max(32,Math.min(400,rows.length*2))},()=>initial),portfolio:LocalSearchStrategy[]=["LATE_ACCEPTANCE","TABU","SIMULATED_ANNEALING","GREAT_DELUGE","VND"],limit=Math.min(5000,Math.max(600,rows.length*22)),tabu=new Map<string,number>();for(let it=0;it<limit;it++){iterations=it+1;const mode=strategy==="AUTO"?portfolio[Math.min(portfolio.length-1,Math.floor(it/Math.max(1,Math.floor(limit/5))))]!:strategy,mov=groups().filter(g=>!g.locked);if(!mov.length)break;const g=mov[Math.floor(R()*mov.length)]!,beforeRows=cloneRows(g.rows);remove(g.rows);const t=toTask(g),choices=candidateCells(t).slice(0,mode==="VND"?16:8);let accepted=false;for(const c of choices){place(t,c.d,c.s);const next=scoreNow(0),cur=current.medium*100+current.soft,nv=next.medium*100+next.soft,bv=best.medium*100+best.soft,asp=lexBetter(next,best),isTabu=(tabu.get(g.key)??-1)>it,delta=nv-cur,temp=Math.max(.25,initial*(1-it/limit)),water=bv+(initial-bv)*Math.max(0,1-it/limit);let ok=mode==="LATE_ACCEPTANCE"?(nv<=cur||nv<=hist[it%hist.length]!):mode==="TABU"?(!isTabu||asp):mode==="SIMULATED_ANNEALING"?(delta<=0||R()<Math.exp(-delta/temp)):mode==="GREAT_DELUGE"?nv<=water:nv<cur;if(next.hard===0&&ok){current=next;accepted=true;tabu.set(g.key,it+Math.max(5,Math.min(31,Math.ceil(rows.length*.04))));if(lexBetter(next,best)){best=next;bestRows=cloneRows(rows)}break}const placed=groups().find(x=>x.key===g.key);if(placed)remove(placed.rows)}if(!accepted)rows.push(...beforeRows);hist[it%hist.length]=current.medium*100+current.soft;if(best.medium===0&&best.soft===0)break}rows.splice(0,rows.length,...bestRows);current=best}
 const lns=ZERO_LNS();lns.enabled=p.enableLns!==false&&failed===0&&current.hard===0;if(lns.enabled){const kinds:LnsNeighborhood[]=["TEACHER_DAY","CLASS_DAY","COURSE_BLOCK","CONFLICT_HOTSPOT","LOW_QUALITY_ZONE","RANDOM_SMALL"],limit=Math.max(12,Math.min(180,p.lnsIterations??Math.ceil(rows.length*.7)));const penalty=(g:ActivityPlacement)=>g.rows.reduce((v,r)=>v+Math.max(0,r.period-6)*2+studentPenalty(r.assignment_id,r.weekday,r.period,1)*100,0);const ruin=(kind:LnsNeighborhood)=>{const all=groups().filter(g=>!g.locked);if(!all.length)return[];const seed=all[Math.floor(R()*all.length)]!;if(kind==="TEACHER_DAY")return all.filter(g=>localAssignmentsShareTeacher(g.assignment,seed.assignment)&&g.rows[0]!.weekday===seed.rows[0]!.weekday);if(kind==="CLASS_DAY")return all.filter(g=>g.assignment.class_id===seed.assignment.class_id&&g.rows[0]!.weekday===seed.rows[0]!.weekday);if(kind==="COURSE_BLOCK")return all.filter(g=>g.assignment.class_id===seed.assignment.class_id&&g.assignment.course_id===seed.assignment.course_id);if(kind==="CONFLICT_HOTSPOT"||kind==="LOW_QUALITY_ZONE")return all.map(g=>({g,p:penalty(g)})).sort((a,b)=>b.p-a.p).slice(0,Math.max(2,Math.min(10,Math.ceil(all.length*.15)))).map(x=>x.g);return[...all].sort(()=>R()-.5).slice(0,Math.max(2,Math.min(6,Math.ceil(all.length*.08))))};for(let it=0;it<limit;it++){lns.iterations++;const kind=kinds[it%kinds.length]!;lns.neighborhoods[kind]++;const rr=ruin(kind);if(!rr.length)continue;lns.ruinedActivities+=rr.length;const beforeRows=cloneRows(rows),before=scoreNow(0);rr.forEach(g=>remove(g.rows));const f=construct(rr.map(toTask)),after=scoreNow(f);if(f===0&&after.hard===0&&lexNotWorse(after,before)){lns.accepted++;if(lexBetter(after,before))lns.improved++;if(lexBetter(after,best)){best=after;bestRows=cloneRows(rows)}}else{lns.rejected++;rows.splice(0,rows.length,...beforeRows)}}rows.splice(0,rows.length,...bestRows)}
 const finalScore=scoreNow(failed);return{rows,failed,complete:failed===0&&finalScore.hard===0,seed:p.seed,score:finalScore,iterations,strategy,lns};
}
