import {supabase} from "@/lib/supabase";
import {detectLocalScheduleCompute} from "@/lib/schedule-local-compute";
import {gpuScoreScheduleCandidates} from "@/lib/schedule-gpu-compute";
import type {LocalSearchStrategy} from "@/lib/schedule-local-solver-core";
import type {PlanningRelation} from "@/lib/schedule-planning-relations";
export type LocalSolveMode="AUTO"|"CPU"|"GPU"|"HYBRID"|"DB";
export type LocalSolveProgress={worker:number;kind:"CPU"|"GPU";status:"running"|"done"|"error";completed:number;total:number;durationMs?:number};
type Row={assignment_id:string;teacher_id:string;class_id:string|null;weekday:number;period:number;classroom_id?:string|null;subgroup_id?:string|null;locked:boolean};type Candidate={rows:Row[];failed:number;complete:boolean;seed:number;strategy?:LocalSearchStrategy};
const strategies:LocalSearchStrategy[]=["AUTO","LATE_ACCEPTANCE","TABU","SIMULATED_ANNEALING","GREAT_DELUGE","VND"];
async function problem(){const[a,l,u,t,c,p,rel]=await Promise.all([supabase.from("schedule_assignment_options").select("teacher_assignment_id,teacher_id,class_id,course_id,assigned_hours"),supabase.from("teacher_schedule").select("teacher_assignment_id,teacher_id,class_id,weekday,period,classroom_id,subgroup_id,locked").eq("active",true).eq("locked",true),supabase.from("teacher_unavailability").select("teacher_id,weekday,period").eq("active",true),supabase.from("teacher_schedule_constraints").select("teacher_id,max_daily_hours,max_consecutive_hours"),supabase.from("course_schedule_rules").select("course_id,block_pattern,max_per_day,prohibited_days,prohibited_periods").eq("active",true),supabase.rpc("get_active_schedule_time_profile"),supabase.rpc("get_schedule_planning_relations_v1")]);const e=a.error||l.error||u.error||t.error||c.error||p.error||rel.error;if(e)throw e;const prof=p.data as {teaching_days:number[];periods_per_day:number};return{days:prof.teaching_days,periods:prof.periods_per_day,assignments:(a.data??[]).filter((x:any)=>x.teacher_assignment_id).map((x:any)=>({assignment_id:String(x.teacher_assignment_id),teacher_id:String(x.teacher_id),class_id:String(x.class_id),course_id:String(x.course_id),assigned_hours:Number(x.assigned_hours)})),locked:(l.data??[]).filter((x:any)=>x.teacher_assignment_id).map((x:any)=>({assignment_id:String(x.teacher_assignment_id),teacher_id:String(x.teacher_id),class_id:x.class_id?String(x.class_id):null,weekday:Number(x.weekday),period:Number(x.period),classroom_id:x.classroom_id?String(x.classroom_id):null,subgroup_id:x.subgroup_id?String(x.subgroup_id):null,locked:true})),unavailable:u.data??[],teacherConstraints:t.data??[],courseRules:(c.data??[]).map((x:any)=>({...x,block_pattern:Array.isArray(x.block_pattern)?x.block_pattern.map(Number):null})),planningRelations:(rel.data??[]).map((x:any)=>({...x,weight:Number(x.weight),left_selector:x.left_selector??{},right_selector:x.right_selector??{},parameters:x.parameters??{}})) as PlanningRelation[]}}
function runWorker(payload:unknown){return new Promise<Candidate>((resolve,reject)=>{const w=new Worker(new URL("../workers/schedule-local-solver-worker.ts",import.meta.url),{type:"module"});const timer=setTimeout(()=>{w.terminate();reject(new Error("LOCAL_WORKER_TIMEOUT"))},30000);w.onmessage=e=>{clearTimeout(timer);w.terminate();resolve(e.data as Candidate)};w.onerror=e=>{clearTimeout(timer);w.terminate();reject(new Error(e.message))};w.postMessage(payload)})}
function metrics(c:Candidate){const byTeacher=new Map<string,number[]>(),byClass=new Map<string,number[]>();let late=0;for(const r of c.rows){late+=Math.max(0,r.period-6);const tk=`${r.teacher_id}|${r.weekday}`,ck=`${r.class_id}|${r.weekday}`;byTeacher.set(tk,[...(byTeacher.get(tk)??[]),r.period]);byClass.set(ck,[...(byClass.get(ck)??[]),r.period])}let gap=0;for(const v of[...byTeacher.values(),...byClass.values()]){const a=[...new Set(v)].sort((x,y)=>x-y);if(a.length){const first=a[0]??0,last=a.at(-1)??first;gap+=Math.max(0,last-first+1-a.length)}}return{hard:c.complete?0:1,unplaced:c.failed,gap,late,repeat:0,preference:0}}
export async function runLocalScheduleSolve(opts:{candidateCount:number;mode:LocalSolveMode;onProgress?:(p:LocalSolveProgress)=>void}){if(opts.mode==="DB")return{scenarioIds:[],capability:await detectLocalScheduleCompute(),generated:0,complete:0,useGpu:false};const cap=await detectLocalScheduleCompute(),p=await problem(),useGpu=(opts.mode==="GPU"||opts.mode==="HYBRID"||opts.mode==="AUTO")&&cap.webGpu,oversample=useGpu?Math.max(opts.candidateCount*4,8):Math.max(opts.candidateCount,strategies.length),workers=opts.mode==="GPU"?1:Math.max(1,Math.min(cap.recommendedCpuWorkers,oversample));let next=0,done=0;const out:Candidate[]=[];await Promise.all(Array.from({length:workers},async(_,wi)=>{while(true){const i=next++;if(i>=oversample)break;opts.onProgress?.({worker:wi+1,kind:"CPU",status:"running",completed:done,total:oversample});const st=performance.now();try{const candidate=await runWorker({...p,seed:(Date.now()+i*7919)>>>0,strategy:strategies[i%strategies.length]});out.push(candidate);done++;opts.onProgress?.({worker:wi+1,kind:"CPU",status:"done",completed:done,total:oversample,durationMs:Math.round(performance.now()-st)})}catch{done++;opts.onProgress?.({worker:wi+1,kind:"CPU",status:"error",completed:done,total:oversample})}}}));const complete=out.filter(x=>x.complete&&x.failed===0);let chosen=complete.slice(0,opts.candidateCount);if(useGpu&&complete.length){opts.onProgress?.({worker:1,kind:"GPU",status:"running",completed:0,total:complete.length});const st=performance.now();try{const scores=await gpuScoreScheduleCandidates(complete.map(metrics));chosen=complete.map((c,i)=>({c,s:scores[i]??Number.POSITIVE_INFINITY})).sort((a,b)=>a.s-b.s).slice(0,opts.candidateCount).map(x=>x.c);opts.onProgress?.({worker:1,kind:"GPU",status:"done",completed:complete.length,total:complete.length,durationMs:Math.round(performance.now()-st)})}catch{chosen=complete.slice(0,opts.candidateCount);opts.onProgress?.({worker:1,kind:"GPU",status:"error",completed:0,total:complete.length})}}const scenarioIds:string[]=[];for(let i=0;i<chosen.length;i++){const candidate=chosen[i];if(!candidate)continue;const rows=candidate.rows.map(r=>({assignment_id:r.assignment_id,weekday:r.weekday,period:r.period,classroom_id:r.classroom_id??null,subgroup_id:r.subgroup_id??null,locked:r.locked}));const q=await supabase.rpc("import_local_schedule_candidate_v1",{p_rows:rows,p_title:`Yerel ${candidate.strategy??(useGpu?"GPU/CPU":"CPU")} Adayı ${i+1}`});if(!q.error&&q.data)scenarioIds.push(String(q.data))}return{scenarioIds,capability:cap,generated:out.length,complete:complete.length,useGpu}}
