import type {LocalAssignment,LocalCourseRule,LocalLockedRow,LocalProblem,LocalScore} from "@/lib/schedule-local-solver-time-core";

export type OracleUnsupported={code:string;detail:string};
export type OracleTask={assignment:LocalAssignment;duration:number;key:string};
export type OracleModel={version:1;days:number[];periods:number;assignments:LocalAssignment[];locked:LocalLockedRow[];unavailable:LocalProblem["unavailable"];teacherConstraints:LocalProblem["teacherConstraints"];courseRules:LocalCourseRule[];studentConflictWeights:NonNullable<LocalProblem["studentConflictWeights"]>;unsupported:OracleUnsupported[]};
export type OracleResult={status:"OPTIMAL"|"FEASIBLE"|"INFEASIBLE"|"UNSUPPORTED";rows:LocalLockedRow[];score:LocalScore;nodes:number;elapsedMs:number;unsupported:OracleUnsupported[];lowerBound:{medium:number;soft:number};gap:{medium:number;soft:number}|null};

const key=(...x:(string|number|null|undefined)[])=>x.join("|");
const overlaps=(a:LocalAssignment,b:LocalAssignment)=>{if(a.term_no!=null&&b.term_no!=null&&a.term_no!==b.term_no)return false;if((a.week_pattern==="ODD"&&b.week_pattern==="EVEN")||(a.week_pattern==="EVEN"&&b.week_pattern==="ODD"))return false;if(a.valid_from&&b.valid_to&&a.valid_from>b.valid_to)return false;if(b.valid_from&&a.valid_to&&b.valid_from>a.valid_to)return false;return true};
const pattern=(a:LocalAssignment,r?:LocalCourseRule)=>{const p=(r?.block_pattern??[]).map(Number).filter(n=>Number.isInteger(n)&&n>0);return p.length&&p.reduce((s,n)=>s+n,0)===a.assigned_hours?p:Array.from({length:a.assigned_hours},()=>1)};

export function normalizeOracleModel(p:LocalProblem):OracleModel{
 const unsupported:OracleUnsupported[]=[];
 for(const r of p.planningRelations??[])unsupported.push({code:`RELATION_${r.relation_type}`,detail:`Generic relation ${r.relation_type} exact oracle mapping is not enabled yet.`});
 const lockedBy=new Set(p.locked.map(r=>r.assignment_id));
 for(const a of p.assignments)if(lockedBy.has(a.assignment_id)&&p.locked.filter(r=>r.assignment_id===a.assignment_id).some(r=>!r.locked))unsupported.push({code:"LOCK_STATE",detail:`${a.assignment_id} has non-locked rows in locked input.`});
 return{version:1,days:[...p.days],periods:p.periods,assignments:p.assignments.map(a=>({...a,allowed_periods:a.allowed_periods?[...a.allowed_periods]:a.allowed_periods})),locked:p.locked.map(r=>({...r})),unavailable:p.unavailable.map(x=>({...x})),teacherConstraints:p.teacherConstraints.map(x=>({...x})),courseRules:p.courseRules.map(x=>({...x,block_pattern:x.block_pattern?[...x.block_pattern]:x.block_pattern,prohibited_days:x.prohibited_days?[...x.prohibited_days]:x.prohibited_days,prohibited_periods:x.prohibited_periods?[...x.prohibited_periods]:x.prohibited_periods})),studentConflictWeights:(p.studentConflictWeights??[]).map(x=>({...x})),unsupported};
}

function tasks(m:OracleModel){const rules=new Map(m.courseRules.map(r=>[r.course_id,r])),out:OracleTask[]=[];for(const a of m.assignments){const locked=m.locked.filter(r=>r.assignment_id===a.assignment_id).length,left=Math.max(0,a.assigned_hours-locked),parts=pattern({...a,assigned_hours:left},rules.get(a.course_id));for(let i=0;i<parts.length;i++)out.push({assignment:a,duration:parts[i]!,key:`${a.assignment_id}:${i+1}`})}return out.sort((a,b)=>b.duration-a.duration||a.assignment.assignment_id.localeCompare(b.assignment.assignment_id));}

export function solveExactOracle(model:OracleModel,opts:{timeLimitMs?:number;nodeLimit?:number}={}):OracleResult{
 const start=Date.now(),timeLimit=opts.timeLimitMs??5000,nodeLimit=opts.nodeLimit??250000;if(model.unsupported.length)return{status:"UNSUPPORTED",rows:[],score:{hard:0,medium:0,soft:0},nodes:0,elapsedMs:Date.now()-start,unsupported:model.unsupported,lowerBound:{medium:0,soft:0},gap:null};
 const asg=new Map(model.assignments.map(a=>[a.assignment_id,a])),rules=new Map(model.courseRules.map(r=>[r.course_id,r])),cons=new Map(model.teacherConstraints.map(c=>[c.teacher_id,c])),rows=model.locked.map(r=>({...r,locked:true})),ts=tasks(model),weights=new Map<string,number>();for(const w of model.studentConflictWeights){const[a,b]=w.left_assignment_id<w.right_assignment_id?[w.left_assignment_id,w.right_assignment_id]:[w.right_assignment_id,w.left_assignment_id];weights.set(key(a,b),Number(w.severity_weight)||Number(w.student_weight)||0)}
 const pair=(a:string,b:string)=>{const aa=asg.get(a),bb=asg.get(b);if(a===b||!aa||!bb||!overlaps(aa,bb))return 0;return weights.get(a<b?key(a,b):key(b,a))??0};
 const overlapRows=(a:LocalAssignment)=>rows.filter(r=>overlaps(a,asg.get(r.assignment_id)!));
 const can=(t:OracleTask,d:number,s:number)=>{const a=t.assignment,r=rules.get(a.course_id),c=cons.get(a.teacher_id);if(r?.prohibited_days?.includes(d))return false;for(let p=s;p<s+t.duration;p++){if(p>model.periods||a.allowed_periods?.length&&!a.allowed_periods.includes(p)||r?.prohibited_periods?.includes(p)||model.unavailable.some(u=>u.teacher_id===a.teacher_id&&u.weekday===d&&u.period===p&&(u.schedule_session_id==null||u.schedule_session_id===a.schedule_session_id)))return false;if(overlapRows(a).some(x=>x.weekday===d&&x.period===p&&(x.teacher_id===a.teacher_id||x.class_id===a.class_id)))return false}const same=overlapRows(a);if(c?.max_daily_hours&&same.filter(x=>x.teacher_id===a.teacher_id&&x.weekday===d).length+t.duration>c.max_daily_hours)return false;if(r?.max_per_day&&same.filter(x=>x.class_id===a.class_id&&asg.get(x.assignment_id)?.course_id===a.course_id&&x.weekday===d).length+t.duration>r.max_per_day)return false;if(c?.max_consecutive_hours){const ps=new Set(same.filter(x=>x.teacher_id===a.teacher_id&&x.weekday===d).map(x=>x.period));for(let p=s;p<s+t.duration;p++)ps.add(p);let run=0;for(let p=1;p<=model.periods;p++){run=ps.has(p)?run+1:0;if(run>c.max_consecutive_hours)return false}}return true};
 const score=()=>{let medium=0,late=0,gaps=0;for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i]!,b=rows[j]!;if(a.weekday===b.weekday&&a.period===b.period)medium+=pair(a.assignment_id,b.assignment_id)}const maps=[new Map<string,number[]>(),new Map<string,number[]>()];for(const r of rows){late+=Math.max(0,r.period-6);const a=asg.get(r.assignment_id)!;const sig=`${a.week_pattern??"ALL"}:${a.term_no??0}:${a.valid_from??""}:${a.valid_to??""}`;for(const [i,k] of [[0,key(r.teacher_id,r.weekday,sig)],[1,key(r.class_id,r.weekday,sig)]] as const)maps[i].set(k,[...(maps[i].get(k)??[]),r.period])}for(const m of maps)for(const ps of m.values()){const q=[...new Set(ps)].sort((a,b)=>a-b);if(q.length>1)gaps+=(q.at(-1)??0)-(q[0]??0)+1-q.length}return{hard:0,medium,soft:gaps*8+late*2}};
 let nodes=0,bestRows:LocalLockedRow[]|null=null,best:LocalScore|null=null,timedOut=false;const lex=(a:LocalScore,b:LocalScore)=>a.hard-b.hard||a.medium-b.medium||a.soft-b.soft;
 const dfs=(i:number)=>{if(Date.now()-start>=timeLimit||nodes>=nodeLimit){timedOut=true;return}nodes++;if(i===ts.length){const sc=score();if(!best||lex(sc,best)<0){best=sc;bestRows=rows.map(r=>({...r}))}return}const t=ts[i]!;for(const d of model.days)for(let s=1;s<=model.periods-t.duration+1;s++){if(!can(t,d,s))continue;const before=rows.length;for(let p=s;p<s+t.duration;p++)rows.push({assignment_id:t.assignment.assignment_id,teacher_id:t.assignment.teacher_id,class_id:t.assignment.class_id,weekday:d,period:p,schedule_session_id:t.assignment.schedule_session_id??null,locked:false,activity_key:t.key,activity_duration:t.duration});dfs(i+1);rows.length=before;if(timedOut&&Date.now()-start>=timeLimit)return}};dfs(0);
 if(!best||!bestRows)return{status:timedOut?"FEASIBLE":"INFEASIBLE",rows:[],score:{hard:1,medium:0,soft:0},nodes,elapsedMs:Date.now()-start,unsupported:[],lowerBound:{medium:0,soft:0},gap:null};const lowerBound={medium:0,soft:0};return{status:timedOut?"FEASIBLE":"OPTIMAL",rows:bestRows,score:best,nodes,elapsedMs:Date.now()-start,unsupported:[],lowerBound,gap:{medium:best.medium-lowerBound.medium,soft:best.soft-lowerBound.soft}};
}

export function objectiveGap(candidate:LocalScore,oracle:OracleResult){if(oracle.status!=="OPTIMAL"&&oracle.status!=="FEASIBLE")return null;return{hard:candidate.hard-oracle.score.hard,medium:candidate.medium-oracle.score.medium,soft:candidate.soft-oracle.score.soft};}
