export type GpuScoreInput={hard:number;unplaced:number;medium:number;gap:number;late:number;repeat:number;preference:number};
export const GPU_RANKING_POLICY="GPU receives only complete HARD=0/unplaced=0 candidates and emits a monotonic MEDIUM key. Canonical CPU byScore remains the final MEDIUM→SOFT tie-break authority; GPU cannot override the lexicographic objective.";
export async function gpuScoreScheduleCandidates(items:GpuScoreInput[]):Promise<Float32Array>{
 const nav=navigator as Navigator&{gpu?:{requestAdapter:(o?:unknown)=>Promise<any>}};if(!nav.gpu)throw new Error("WEBGPU_UNAVAILABLE");
 const adapter=await nav.gpu.requestAdapter({powerPreference:"high-performance"});if(!adapter)throw new Error("WEBGPU_ADAPTER_UNAVAILABLE");const device=await adapter.requestDevice();
 /* Keep the seven-field buffer contract stable for callers. Only canonical MEDIUM is emitted as the GPU sort key. Float32 conversion is monotonic; values that collapse to the same float are resolved by canonical CPU byScore. */
 const stride=7,input=new Float32Array(items.length*stride);items.forEach((x,i)=>input.set([x.hard,x.unplaced,x.medium,x.gap,x.late,x.repeat,x.preference],i*stride));
 const usage=(globalThis as any).GPUBufferUsage;const mapMode=(globalThis as any).GPUMapMode;if(!usage||!mapMode)throw new Error("WEBGPU_CONSTANTS_UNAVAILABLE");
 const inBuf=device.createBuffer({size:Math.max(4,input.byteLength),usage:usage.STORAGE|usage.COPY_DST});const outBuf=device.createBuffer({size:Math.max(4,items.length*4),usage:usage.STORAGE|usage.COPY_SRC});const readBuf=device.createBuffer({size:Math.max(4,items.length*4),usage:usage.COPY_DST|usage.MAP_READ});device.queue.writeBuffer(inBuf,0,input);
 const shader=device.createShaderModule({code:`@group(0) @binding(0) var<storage,read> a:array<f32>;@group(0) @binding(1) var<storage,read_write> o:array<f32>;@compute @workgroup_size(128) fn main(@builtin(global_invocation_id) id:vec3<u32>){let i=id.x;if(i>=${items.length}u){return;}let b=i*7u;o[i]=a[b+2u];}`});
 const pipeline=device.createComputePipeline({layout:"auto",compute:{module:shader,entryPoint:"main"}});const bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:inBuf}},{binding:1,resource:{buffer:outBuf}}]});const enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil(items.length/128));pass.end();enc.copyBufferToBuffer(outBuf,0,readBuf,0,items.length*4);device.queue.submit([enc.finish()]);await readBuf.mapAsync(mapMode.READ);const out=new Float32Array(readBuf.getMappedRange().slice(0));readBuf.unmap();inBuf.destroy();outBuf.destroy();readBuf.destroy();return out;
}
