export type VoiceIntent=
 |{kind:"PLACE_COURSE";classText:string;courseText:string;weekday:number;period:number;hours:number;lock:boolean}
 |{kind:"BLOCK_TEACHER";teacherText:string;weekday:number;periods:number[]}
 |{kind:"UNKNOWN";raw:string};
const days:Record<string,number>={pazartesi:1,sali:2,salı:2,carsamba:3,çarşamba:3,persembe:4,perşembe:4,cuma:5,cumartesi:6,pazar:7};
const ord:Record<string,number>={birinci:1,ilk:1,ikinci:2,ucuncu:3,üçüncü:3,dorduncu:4,dördüncü:4,besinci:5,beşinci:5,altinci:6,altıncı:6,yedinci:7,sekizinci:8,dokuzuncu:9,onuncu:10};
const qty:Record<string,number>={bir:1,iki:2,uc:3,üç:3,dort:4,dört:4,bes:5,beş:5,alti:6,altı:6};
export function normTr(s:string){return s.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9/\s]/g," ").replace(/\s+/g," ").trim()}
function findDay(raw:string){const n=normTr(raw);for(const[k,v]of Object.entries(days))if(n.includes(normTr(k)))return v;return 0}
function findPeriod(raw:string){const n=normTr(raw),m=n.match(/(?:saat|ders)?\s*(\d{1,2})\b/);if(m?.[1])return Number(m[1]);for(const[k,v]of Object.entries(ord))if(n.includes(normTr(k)+" saat")||n.includes(normTr(k)+" ders")||n.includes(" "+normTr(k)+" "))return v;return 1}
function findHours(raw:string){const n=normTr(raw),m=n.match(/(\d{1,2})\s*(?:saat|ders)\b/);if(m?.[1])return Math.max(1,Number(m[1]));for(const[k,v]of Object.entries(qty))if(new RegExp(`\\b${normTr(k)}\\s+(saat|ders)\\b`).test(n))return v;return 1}
export function parseScheduleVoiceCommand(raw:string):VoiceIntent{const n=normTr(raw),weekday=findDay(raw);if(!weekday)return{kind:"UNKNOWN",raw};const block=n.match(/^(.+?)\s+(pazartesi|sali|carsamba|persembe|cuma|cumartesi|pazar)\s+(.+?)\s+(kapali|bos|musait degil|uygun degil)$/);if(block?.[1]){const cm=n.match(/ilk\s+(\d+)/),count=cm?.[1]?Number(cm[1]):n.includes("ilk iki")?2:n.includes("ilk uc")?3:1,start=findPeriod(raw);return{kind:"BLOCK_TEACHER",teacherText:block[1].trim(),weekday,periods:Array.from({length:count},(_,i)=>start+i)}}const cls=n.match(/\b(\d{1,2}\s*[/\-]\s*[a-z])\b/);if(cls?.[1]){const classText=cls[1].replace(/\s/g,"").replace("-","/").toUpperCase(),dayWord=Object.keys(days).find(d=>n.includes(normTr(d)));if(dayWord){const afterDay=n.split(normTr(dayWord))[1]??"",p=findPeriod(afterDay),course=afterDay.replace(/ilk\s+(iki|uc|\d+)/g,"").replace(/\b(birinci|ikinci|ucuncu|dorduncu|besinci|altinci|yedinci|sekizinci|dokuzuncu|onuncu|\d+)\s*(saat|ders)?\b/g,"").replace(/\b(\d+|bir|iki|uc|dort|bes|alti)\s*(saat|ders)\b/g,"").replace(/\b(kilitle|kilitli|yerlestir|ata)\b/g,"").trim();if(course)return{kind:"PLACE_COURSE",classText,courseText:course,weekday,period:p,hours:findHours(raw),lock:true}}}return{kind:"UNKNOWN",raw}}
