export type LocalAssignment={assignment_id:string;teacher_id:string;class_id:string;course_id:string;assigned_hours:number};
export type LocalLockedRow={assignment_id:string;teacher_id:string;class_id:string|null;weekday:number;period:number;classroom_id?:string|null;subgroup_id?:string|null;locked:boolean};
export type LocalUnavailable={teacher_id:string;weekday:number;period:number};
export type LocalTeacherConstraint={teacher_id:string;max_daily_hours:number|null;max_consecutive_hours:number|null};
export type LocalCourseRule={course_id:string;max_per_day:number|null;prohibited_days:number[]|null;prohibited_periods:number[]|null};
export type LocalProblem={days:number[];periods:number;assignments:LocalAssignment[];locked:LocalLockedRow[];unavailable:LocalUnavailable[];teacherConstraints:LocalTeacherConstraint[];courseRules:LocalCourseRule[];seed:number};
export type LocalScore={hard:number;medium:number;soft:number};
export type LocalCandidate={rows:LocalLockedRow[];failed:number;complete:boolean;seed:number;score:LocalScore;iterations:number};
type Cell={d:number;s:number;score:number};
const key=(...v:(string|number|null)[])=>v.join('|');
function rng(seed:number){let s=seed|0;return()=>((s=Math.imul(1664525,s)+1013904223|0)>>>0)/4294967296}
function lexBetter(a:LocalScore,b:LocalScore){return a.hard!==b.hard?a.hard<b.hard:a.medium!==b.medium?a.medium<b.medium:a.soft<b.soft}
function cloneRows(rows:LocalLockedRow[]){return rows.map(x=>({...x}))}
export function solveLocalSchedule(p:LocalProblem):LocalCandidate{const R=rng(p.seed),rows:LocalLockedRow[]=[...p.locked],tb=new Set<string>(),cb=new Set<string>(),un=new Set(p.unavailable.map(x=>key(x.teacher_id,x.weekday,x.period))),td=new Map<string,number>(),cd=new Map<string,number>(),tp=new Map<string,Set<number>>(),cc=new Map(p.courseRules.map(x=>[x.course_id,x])),tc=new Map(p.teacherConstraints.map(x=>[x.teacher_id,x])),am=new Map(p.assignments.map(x=>[x.assignment_id,x]));
 const add=(a:LocalAssignment,d:number,s:number,locked=false)=>{rows.push({assignment_id:a.assignment_id,teacher_id:a.teacher_id,class_id:a.class_id,weekday:d,period:s,locked});tb.add(key(a.teacher_id,d,s));cb.add(key(a.class_id,d,s));const tk=key(a.teacher_id,d),ck=key(a.class_id,a.course_id,d);td.set(tk,(td.get(tk)??0)+1);cd.set(ck,(cd.get(ck)??0)+1);const ps=tp.get(tk)??new Set<number>();ps.add(s);tp.set(tk,ps)};
 const del=(r:LocalLockedRow)=>{tb.delete(key(r.teacher_id,r.weekday,r.period));if(r.class_id)cb.delete(key(r.class_id,r.weekday,r.period));const a=am.get(r.assignment_id),tk=key(r.teacher_id,r.weekday);td.set(tk,Math.max(0,(td.get(tk)??1)-1));tp.get(tk)?.delete(r.period);if(a&&r.class_id){const ck=key(r.class_id,a.course_id,r.weekday);cd.set(ck,Math.max(0,(cd.get(ck)??1)-1))}};
 const consecutiveOk=(teacher:string,d:number,s:number,max:number|null|undefined)=>{if(!max)return true;const ps=new Set(tp.get(key(teacher,d))??[]);ps.add(s);let run=0,best=0;for(let i=1;i<=p.periods;i++){run=ps.has(i)?run+1:0;if(run>best)best=run}return best<=max};
 const cand=(a:LocalAssignment):Cell[]=>{const rule=cc.get(a.course_id),cons=tc.get(a.teacher_id),out:Cell[]=[];for(const d of p.days)for(let s=1;s<=p.periods;s++){if(tb.has(key(a.teacher_id,d,s))||cb.has(key(a.class_id,d,s))||un.has(key(a.teacher_id,d,s)))continue;if(rule?.prohibited_days?.includes(d)||rule?.prohibited_periods?.includes(s))continue;const tdk=key(a.teacher_id,d),cdk=key(a.class_id,a.course_id,d),teacherDaily=td.get(tdk)??0,courseDaily=cd.get(cdk)??0;if(cons?.max_daily_hours&&teacherDaily>=cons.max_daily_hours)continue;if(rule?.max_per_day&&courseDaily>=rule.max_per_day)continue;if(!consecutiveOk(a.teacher_id,d,s,cons?.max_consecutive_hours))continue;let score=teacherDaily*3+courseDaily*8+Math.max(0,s-6)*2+R()*.35;if(tb.has(key(a.teacher_id,d,s-1))||tb.has(key(a.teacher_id,d,s+1)))score-=2;out.push({d,s,score})}return out.sort((x,y)=>x.score-y.score)};
 const lockedCount=new Map<string,number>();for(const x of p.locked){tb.add(key(x.teacher_id,x.weekday,x.period));if(x.class_id)cb.add(key(x.class_id,x.weekday,x.period));const tk=key(x.teacher_id,x.weekday);td.set(tk,(td.get(tk)??0)+1);const ps=tp.get(tk)??new Set<number>();ps.add(x.period);tp.set(tk,ps);const a=am.get(x.assignment_id);if(a&&x.class_id){const ck=key(x.class_id,a.course_id,x.weekday);cd.set(ck,(cd.get(ck)??0)+1)}lockedCount.set(x.assignment_id,(lockedCount.get(x.assignment_id)??0)+1)}
 const tasks=p.assignments.flatMap(a=>Array.from({length:Math.max(0,a.assigned_hours-(lockedCount.get(a.assignment_id)??0))},()=>a));let failed=0;
 // Regret-2 + fail-first construction: prioritize assignments that lose most if their best slot is consumed.
 while(tasks.length){let bi=0,bc:Cell[]|null=null,bestRegret=-1,bestScarcity=1e9;for(let i=0;i<tasks.length;i++){const cs=cand(tasks[i]!);if(!cs.length){bi=i;bc=cs;bestRegret=Number.POSITIVE_INFINITY;break}const regret=(cs[1]?.score??cs[0]!.score+50)-cs[0]!.score,scarcity=cs.length;if(regret>bestRegret+1e-9||(Math.abs(regret-bestRegret)<1e-9&&scarcity<bestScarcity)){bi=i;bc=cs;bestRegret=regret;bestScarcity=scarcity}}const a=tasks.splice(bi,1)[0]!;if(!bc?.length){failed++;continue}const width=Math.min(2,bc.length),pick=bc[Math.floor(R()*width)]!;add(a,pick.d,pick.s)}
 const scoreNow=(hard=failed):LocalScore=>{const teacherDay=new Map<string,number[]>(),classDay=new Map<string,number[]>(),courseDay=new Map<string,number>();let late=0;for(const r of rows){const a=am.get(r.assignment_id);late+=Math.max(0,r.period-6);const tk=key(r.teacher_id,r.weekday),ck=key(r.class_id,r.weekday);teacherDay.set(tk,[...(teacherDay.get(tk)??[]),r.period]);classDay.set(ck,[...(classDay.get(ck)??[]),r.period]);if(a){const dk=key(a.class_id,a.course_id,r.weekday);courseDay.set(dk,(courseDay.get(dk)??0)+1)}}let gaps=0;for(const ps of[...teacherDay.values(),...classDay.values()]){const a=[...new Set(ps)].sort((x,y)=>x-y);if(a.length>1)gaps+=(a.at(-1)??0)-(a[0]??0)+1-a.length}let spreadPenalty=0;for(const a of p.assignments){const counts=p.days.map(d=>courseDay.get(key(a.class_id,a.course_id,d))??0),used=counts.filter(Boolean);if(used.length>1)spreadPenalty+=Math.max(...used)-Math.min(...used)}return{hard,medium:hard?hard:0,soft:gaps*8+late*2+spreadPenalty*3}};
 let iterations=0;
 if(!failed){let current=scoreNow(0),best=current,bestRows=cloneRows(rows);const lateSize=Math.max(32,Math.min(400,rows.length*2)),history=Array.from({length:lateSize},()=>current.soft),tabuTenure=Math.max(5,Math.min(31,Math.ceil(rows.length*.04))),tabuUntil=new Map<string,number>(),limit=Math.min(5000,Math.max(500,rows.length*24));
  for(let it=0;it<limit;it++){iterations=it+1;const movable=rows.filter(x=>!x.locked);if(!movable.length)break;const r=movable[Math.floor(R()*movable.length)]!,a=am.get(r.assignment_id);if(!a)continue;const idx=rows.indexOf(r),oldD=r.weekday,oldS=r.period;del(r);rows.splice(idx,1);const choices=cand(a).slice(0,Math.min(8,cand(a).length));let accepted=false;for(const target of choices){add(a,target.d,target.s,false);const next=scoreNow(0),aspiration=lexBetter(next,best),tabu=(tabuUntil.get(a.assignment_id)??-1)>it,lateOk=next.soft<=current.soft||next.soft<=history[it%lateSize]!;if((!tabu||aspiration)&&lateOk){current=next;accepted=true;tabuUntil.set(a.assignment_id,it+tabuTenure);if(lexBetter(next,best)){best=next;bestRows=cloneRows(rows)}break}const rr=rows.pop();if(rr)del(rr)}if(!accepted)add(a,oldD,oldS,false);history[it%lateSize]=current.soft;if(best.soft===0)break}
  rows.splice(0,rows.length,...bestRows);return{rows,failed:0,complete:true,seed:p.seed,score:best,iterations}}
 const finalScore=scoreNow(failed);return{rows,failed,complete:failed===0,seed:p.seed,score:finalScore,iterations}}
