export type PlanningMode="HARD"|"MEDIUM"|"SOFT"|"OFF";
export type PlanningSelector={activity_key?:string;assignment_id?:string;course_id?:string;teacher_id?:string;class_id?:string};
export type PlanningRelation={id:string;relation_type:string;mode:PlanningMode;weight:number;left_selector:PlanningSelector;right_selector:PlanningSelector;parameters:Record<string,unknown>};
export type PlanningActivity={activity_key:string;assignment_id:string;course_id:string;teacher_id:string;class_id:string|null;weekday:number;start:number;end:number};
export type RelationScore={hard:number;medium:number;soft:number};
const zero=():RelationScore=>({hard:0,medium:0,soft:0});
function matches(a:PlanningActivity,s:PlanningSelector){return(!s.activity_key||a.activity_key===s.activity_key)&&(!s.assignment_id||a.assignment_id===s.assignment_id)&&(!s.course_id||a.course_id===s.course_id)&&(!s.teacher_id||a.teacher_id===s.teacher_id)&&(!s.class_id||a.class_id===s.class_id)}
function before(a:PlanningActivity,b:PlanningActivity){return a.weekday<b.weekday||(a.weekday===b.weekday&&a.end<b.start)}
function gap(a:PlanningActivity,b:PlanningActivity){if(a.weekday!==b.weekday)return Number.POSITIVE_INFINITY;if(a.end<b.start)return b.start-a.end-1;if(b.end<a.start)return a.start-b.end-1;return-1}
function violates(t:string,l:PlanningActivity,r:PlanningActivity,p:Record<string,unknown>){const type=t.toUpperCase(),n=Number(p.periods??p.gap??p.value??0);if(type==="SAME_TIME")return l.weekday!==r.weekday||l.start!==r.start;if(type==="DIFFERENT_TIME")return l.weekday===r.weekday&&l.start===r.start;if(type==="SAME_DAY")return l.weekday!==r.weekday;if(type==="DIFFERENT_DAY")return l.weekday===r.weekday;if(type==="ORDERED")return!before(l,r);if(type==="CONSECUTIVE")return l.weekday!==r.weekday||r.start!==l.end+1;if(type==="MIN_GAP")return gap(l,r)<n;if(type==="MAX_GAP")return!Number.isFinite(gap(l,r))||gap(l,r)>n;return false}
function add(out:RelationScore,r:PlanningRelation,count=1){const v=Math.max(0,Number(r.weight)||0)*count;if(r.mode==="HARD")out.hard+=v||count;else if(r.mode==="MEDIUM")out.medium+=v;else if(r.mode==="SOFT")out.soft+=v}
export function evaluateCandidateRelations(candidate:PlanningActivity,placed:PlanningActivity[],relations:PlanningRelation[]){const out=zero();for(const r of relations){if(r.mode==="OFF")continue;const left=matches(candidate,r.left_selector),right=matches(candidate,r.right_selector);if(left)for(const other of placed)if(other.activity_key!==candidate.activity_key&&matches(other,r.right_selector)&&violates(r.relation_type,candidate,other,r.parameters))add(out,r);if(right)for(const other of placed)if(other.activity_key!==candidate.activity_key&&matches(other,r.left_selector)&&violates(r.relation_type,other,candidate,r.parameters))add(out,r)}return out}
export function evaluatePlanningRelations(activities:PlanningActivity[],relations:PlanningRelation[]){const out=zero();for(const r of relations){if(r.mode==="OFF")continue;const seen=new Set<string>(),left=activities.filter(a=>matches(a,r.left_selector)),right=activities.filter(a=>matches(a,r.right_selector));for(const l of left)for(const rr of right){if(l.activity_key===rr.activity_key)continue;const symmetric=["SAME_TIME","DIFFERENT_TIME","SAME_DAY","DIFFERENT_DAY","MIN_GAP","MAX_GAP"].includes(r.relation_type.toUpperCase()),k=symmetric?[l.activity_key,rr.activity_key].sort().join("|"):`${l.activity_key}|${rr.activity_key}`;if(seen.has(k))continue;seen.add(k);if(violates(r.relation_type,l,rr,r.parameters))add(out,r)}}return out}
