import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CheckCircle2, FileSpreadsheet, RefreshCw, Send, ShieldCheck, UploadCloud } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";
import { parseMebCalendar, SCHOOL_LEVELS, type CalendarImportRow } from "@/lib/meb-data-import";

export const Route=createFileRoute("/calendar")({head:()=>({meta:[{title:"Çalışma Takvimi — OkulOS"}]}),component:CalendarCenter});
type AcademicYear={id:string;code:string;title:string;starts_on:string;ends_on:string;active:boolean};
type CalendarEvent={id:string;academic_year_id:string;event_type:string;title:string;starts_on:string;ends_on:string;blocks_teaching:boolean;counts_as_workday:boolean;note:string|null;school_levels:string[];school_types:string[];grade_levels:string[];audiences:string[];conditional:boolean;source_file_name:string|null;parsed_from_source:boolean};
type Person={user_id:string;full_name:string|null;role:string};
type Responsibility={id:string;name:string;parent_title:string|null};
const eventLabels:Record<string,string>={holiday:"Resmî Tatil",break:"Ara Tatil / Yarıyıl",professional_work:"Mesleki Çalışma",teaching_day:"Eğitim Günü",exam_window:"Sınav Aralığı",common_exam_window:"Ortak Sınav Aralığı",responsibility_exam_window:"Sorumluluk Sınavı Aralığı",ceremony:"Tören / Etkinlik",other:"Diğer"};
const schoolTypeOptions=["İmam Hatip Ortaokulu","Anadolu Lisesi","Anadolu İmam Hatip Lisesi","Mesleki ve Teknik Anadolu Lisesi","Mesleki Eğitim Merkezi","Özel Eğitim Meslek Okulu / İş Okulu","Pansiyonlu Okul","Taşımalı Eğitim"];
const recurrenceOptions=["none","daily","weekly","monthly","semester","yearly"];
const recurrenceLabels:Record<string,string>={none:"Tek Seferlik",daily:"Günlük",weekly:"Haftalık",monthly:"Aylık",semester:"Dönemlik",yearly:"Yıllık"};

function CalendarCenter(){
 const fileRef=useRef<HTMLInputElement>(null);const {can,loading:permissionLoading}=usePermissions();const editable=can("settings.manage");
 const [years,setYears]=useState<AcademicYear[]>([]),[events,setEvents]=useState<CalendarEvent[]>([]),[people,setPeople]=useState<Person[]>([]),[responsibilities,setResponsibilities]=useState<Responsibility[]>([]),[message,setMessage]=useState<string|null>(null),[preview,setPreview]=useState<CalendarImportRow[]>([]),[selectedFile,setSelectedFile]=useState<File|null>(null),[selectedEvent,setSelectedEvent]=useState<CalendarEvent|null>(null);
 const [eventYear,setEventYear]=useState(""),[eventType,setEventType]=useState("holiday"),[eventTitle,setEventTitle]=useState(""),[eventStart,setEventStart]=useState(""),[eventEnd,setEventEnd]=useState(""),[blocksTeaching,setBlocksTeaching]=useState(true),[countsWorkday,setCountsWorkday]=useState(false),[eventNote,setEventNote]=useState(""),[eventLevels,setEventLevels]=useState<string[]>([]),[eventSchoolTypes,setEventSchoolTypes]=useState<string[]>([]);
 const [assignedUser,setAssignedUser]=useState(""),[assignedResponsibility,setAssignedResponsibility]=useState(""),[taskStart,setTaskStart]=useState(""),[taskDue,setTaskDue]=useState(""),[recurrence,setRecurrence]=useState("none"),[reportRequired,setReportRequired]=useState(false),[reportFrequency,setReportFrequency]=useState("monthly"),[fileRequired,setFileRequired]=useState(false),[taskNote,setTaskNote]=useState("");
 const activeYear=useMemo(()=>years.find(y=>y.active)??null,[years]);
 const load=useCallback(async()=>{const [y,e,p,r]=await Promise.all([
   supabase.from("academic_years").select("id,code,title,starts_on,ends_on,active").order("starts_on",{ascending:false}),
   supabase.from("school_calendar_events").select("id,academic_year_id,event_type,title,starts_on,ends_on,blocks_teaching,counts_as_workday,note,school_levels,school_types,grade_levels,audiences,conditional,source_file_name,parsed_from_source").order("starts_on"),
   supabase.from("profiles").select("user_id,full_name,role").order("full_name"),
   supabase.from("responsibility_catalog").select("id,name,parent_title").eq("active",true).order("sort_order")
 ]);const firstError=y.error??e.error??p.error??r.error;if(firstError){setMessage("Çalışma takvimi verilerinin bir bölümü okunamadı. Yetki ve kurum kapsamını kontrol edin.");return;}setYears((y.data??[]) as AcademicYear[]);setEvents((e.data??[]) as CalendarEvent[]);setPeople((p.data??[]) as Person[]);setResponsibilities((r.data??[]) as Responsibility[]);const active=(y.data??[]).find((row:AcademicYear)=>row.active);if(active)setEventYear(current=>current||active.id);},[]);
 useEffect(()=>{void load()},[load]);
 const toggle=(arr:string[],value:string,setter:(x:string[])=>void)=>setter(arr.includes(value)?arr.filter(x=>x!==value):[...arr,value]);
 async function addEvent(){if(!editable)return;if(!eventYear||!eventTitle.trim()||!eventStart||!eventEnd)return setMessage("Yıl, olay başlığı ve tarih aralığı zorunludur.");const targetYear=years.find(y=>y.id===eventYear);if(!targetYear)return setMessage("Seçilen eğitim-öğretim yılı bulunamadı.");if(eventStart>eventEnd)return setMessage("Olay bitiş tarihi başlangıç tarihinden önce olamaz.");if(eventStart<targetYear.starts_on||eventEnd>targetYear.ends_on)return setMessage("Takvim olayı seçilen eğitim-öğretim yılının tarih aralığında olmalıdır.");const {data:userData}=await supabase.auth.getUser();const {error}=await supabase.from("school_calendar_events").insert({academic_year_id:eventYear,event_type:eventType,title:eventTitle.trim(),starts_on:eventStart,ends_on:eventEnd,blocks_teaching:blocksTeaching,counts_as_workday:countsWorkday,note:eventNote||null,school_levels:eventLevels,school_types:eventSchoolTypes,created_by:userData.user?.id??null});if(error)return setMessage("Takvim olayı kaydedilemedi.");setEventTitle("");setEventStart("");setEventEnd("");setEventNote("");setEventLevels([]);setEventSchoolTypes([]);setMessage("Takvim olayı kaydedildi.");await load()}
 async function handleCalendarFile(file:File){if(!editable)return;if(!activeYear){setMessage("Takvim içe aktarmadan önce Eğitim-Öğretim Yılları ekranından aktif yılı seçin.");return;}setMessage(null);setSelectedFile(file);setPreview([]);try{setPreview(await parseMebCalendar(file,Number(activeYear.starts_on.slice(0,4))))}catch(e){console.error(e);setSelectedFile(null);setMessage("Çalışma takvimi PDF/XLS/XLSX dosyası tanınamadı.")}}
 async function importCalendar(){if(!activeYear||!selectedFile||!preview.length)return;const outside=preview.find(r=>r.startsOn<activeYear.starts_on||r.endsOn>activeYear.ends_on);if(outside){setMessage(`İçe aktarımdaki “${outside.title}” olayı aktif yılın dışında kalıyor. Tarihleri kontrol edin.`);return;}const {data:userData}=await supabase.auth.getUser();const payload=preview.map(r=>({academic_year_id:activeYear.id,event_type:r.eventType,title:r.title,starts_on:r.startsOn,ends_on:r.endsOn,blocks_teaching:r.eventType==="holiday"||r.eventType==="break",counts_as_workday:r.eventType==="professional_work",note:r.note||null,school_levels:r.schoolLevels,school_types:r.schoolTypes,grade_levels:r.gradeLevels,audiences:r.audiences,conditional:r.conditional,source_file_name:selectedFile.name,parsed_from_source:true,created_by:userData.user?.id??null}));const {error}=await supabase.from("school_calendar_events").insert(payload);if(error){setMessage("Takvim olayları aktarılamadı.");return;}setMessage(`${payload.length} takvim olayı aktif yıla aktarıldı.`);setPreview([]);setSelectedFile(null);if(fileRef.current)fileRef.current.value="";await load()}
 async function saveTask(){if(!editable)return;if(!selectedEvent)return;if(!assignedUser&&!assignedResponsibility)return setMessage("Görev için kişi veya alt görev/sorumluluk seçin.");const start=taskStart||selectedEvent.starts_on,due=taskDue||selectedEvent.ends_on;if(start>due)return setMessage("Görev son tarihi başlangıç tarihinden önce olamaz.");const {error}=await supabase.from("calendar_event_tasks").insert({calendar_event_id:selectedEvent.id,assigned_user_id:assignedUser||null,assigned_responsibility_id:assignedResponsibility||null,starts_on:start,due_on:due,recurrence,report_required:reportRequired,report_frequency:reportRequired?reportFrequency:null,file_required:fileRequired,note:taskNote||null});if(error){setMessage("Görev oluşturulamadı.");return;}if(assignedUser){await supabase.from("notifications").insert({user_id:assignedUser,type:"system",priority:"normal",title:"Yeni görev atandı",message:`${selectedEvent.title} · ${start} → ${due}`,action_label:"Görevi Aç",action_url:"/calendar"});}setMessage("Görev oluşturuldu ve ilgili kullanıcıya bildirim gönderildi.");setAssignedUser("");setAssignedResponsibility("");setTaskStart("");setTaskDue("");setRecurrence("none");setReportRequired(false);setFileRequired(false);setTaskNote("");}
 return <AppShell title="Çalışma Takvimi" subtitle="Aktif yıl · MEB takvim içe aktarma · okul türüne göre kapsam · iş/görev atama" action={<CalendarDays className="size-5"/>}>
  {permissionLoading?<div className="mb-4 rounded-xl border bg-muted/30 p-3 text-xs text-muted-foreground">Yetki kontrol ediliyor…</div>:!editable?<div className="mb-4 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-100"><ShieldCheck className="size-4"/>Takvim salt okunur.</div>:null}
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  {activeYear?<div className="mb-4 flex items-start justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5"/><div><b>Aktif yıl: {activeYear.title}</b><p className="mt-1 text-xs">Takvim işlemleri bu merkezi yıl kapsamında çalışır.</p></div></div><Link to="/academic-years" className="rounded-md border px-3 py-1.5 text-xs font-semibold">Yıl Yönetimi</Link></div>:<div className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><b>Aktif eğitim-öğretim yılı yok.</b> <Link to="/academic-years" className="underline">Yıl Yönetimi</Link> ekranından yılı açıp aktif yapın.</div>}
  <Tabs defaultValue="import"><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="import">İçe Aktar</TabsTrigger><TabsTrigger value="events">Olay Ekle</TabsTrigger><TabsTrigger value="list">Takvim</TabsTrigger></TabsList>
   <TabsContent value="import" className="mt-4 space-y-4">{editable?<><input ref={fileRef} className="hidden" type="file" accept=".pdf,.xls,.xlsx" onChange={e=>{const f=e.target.files?.[0];if(f)void handleCalendarFile(f)}}/><button type="button" disabled={!activeYear} onClick={()=>fileRef.current?.click()} className="w-full rounded-xl border-2 border-dashed bg-card p-7 text-center hover:border-primary/50 disabled:cursor-not-allowed disabled:opacity-50"><UploadCloud className="mx-auto size-7 text-primary"/><p className="mt-2 font-medium">MEB / İl / İlçe yıllık çalışma takvimini yükleyin</p><p className="mt-1 text-xs text-muted-foreground">PDF, XLS veya XLSX · yalnız aktif eğitim-öğretim yılına aktarılır</p></button></>:null}
    {preview.length?<section className="rounded-xl border border-primary/20 bg-primary-soft p-4"><div className="flex gap-2"><FileSpreadsheet className="size-5 text-primary"/><div><b>{selectedFile?.name}</b><p className="text-xs text-muted-foreground">{preview.length} olay tanındı.</p></div></div><div className="mt-3 overflow-x-auto rounded-lg border bg-card"><table className="min-w-[900px] w-full text-xs"><thead><tr><th className="p-2 text-left">Tarih</th><th className="p-2 text-left">İş/Olay</th><th className="p-2 text-left">Kademe/Okul</th><th className="p-2 text-left">Sınıf</th><th className="p-2 text-left">İlgili</th><th className="p-2">Güven</th></tr></thead><tbody>{preview.slice(0,20).map((r,i)=><tr key={i} className="border-t align-top"><td className="p-2 whitespace-nowrap">{r.startsOn}{r.endsOn!==r.startsOn?` → ${r.endsOn}`:""}</td><td className="p-2 font-medium">{r.title}</td><td className="p-2">{[...r.schoolLevels,...r.schoolTypes].join(", ")||"Genel / kontrol et"}</td><td className="p-2">{r.gradeLevels.join(", ")||"Tümü"}</td><td className="p-2">{r.audiences.join(", ")||"Belirtilmemiş"}</td><td className="p-2 text-center">{r.confidence}</td></tr>)}</tbody></table></div><div className="mt-3 flex gap-2"><Button className="flex-1" onClick={()=>void importCalendar()}>Onayla ve Aktif Yıla Aktar</Button><Button variant="outline" onClick={()=>{setPreview([]);setSelectedFile(null)}}>İptal</Button></div></section>:null}
   </TabsContent>
   <TabsContent value="events" className="mt-4">{editable?<section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Takvim Olayı Ekle</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><div><Label>Eğitim Yılı</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={eventYear} onChange={e=>setEventYear(e.target.value)}><option value="">Seçiniz</option>{years.map(y=><option key={y.id} value={y.id}>{y.title}{y.active?" · Aktif":""}</option>)}</select></div><div><Label>Tür</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={eventType} onChange={e=>setEventType(e.target.value)}>{Object.entries(eventLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><Label>Başlık</Label><Input value={eventTitle} onChange={e=>setEventTitle(e.target.value)}/></div><div><Label>Açıklama</Label><Input value={eventNote} onChange={e=>setEventNote(e.target.value)}/></div><div><Label>Başlangıç</Label><Input type="date" value={eventStart} onChange={e=>{setEventStart(e.target.value);if(!eventEnd)setEventEnd(e.target.value)}}/></div><div><Label>Bitiş</Label><Input type="date" value={eventEnd} onChange={e=>setEventEnd(e.target.value)}/></div></div><div className="mt-4"><Label>Kademe / Okul Seviyesi</Label><div className="mt-2 flex flex-wrap gap-1">{SCHOOL_LEVELS.map(x=><Button type="button" key={x} size="sm" variant={eventLevels.includes(x)?"default":"outline"} onClick={()=>toggle(eventLevels,x,setEventLevels)}>{x}</Button>)}</div></div><div className="mt-4"><Label>Okul Türü / Özellik</Label><div className="mt-2 flex flex-wrap gap-1">{schoolTypeOptions.map(x=><Button type="button" key={x} size="sm" variant={eventSchoolTypes.includes(x)?"default":"outline"} onClick={()=>toggle(eventSchoolTypes,x,setEventSchoolTypes)}>{x}</Button>)}</div></div><div className="mt-4 flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={blocksTeaching} onChange={e=>setBlocksTeaching(e.target.checked)}/>Ders yapılmasını engeller</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={countsWorkday} onChange={e=>setCountsWorkday(e.target.checked)}/>Çalışma günü</label></div><Button className="mt-4 w-full" onClick={()=>void addEvent()}>Olayı Kaydet</Button></section>:null}</TabsContent>
   <TabsContent value="list" className="mt-4 grid gap-4 lg:grid-cols-[1fr_420px]"><div className="space-y-2">{events.filter(e=>!activeYear||e.academic_year_id===activeYear.id).map(e=><button type="button" key={e.id} onClick={()=>{setSelectedEvent(e);setTaskStart(e.starts_on);setTaskDue(e.ends_on)}} className={`w-full rounded-xl border bg-card p-3 text-left text-sm hover:border-primary/50 ${selectedEvent?.id===e.id?"border-primary":""}`}><div className="flex flex-wrap items-center gap-2"><b>{e.title}</b><span className="rounded-full bg-muted px-2 py-0.5 text-[10px]">{eventLabels[e.event_type]??e.event_type}</span>{e.conditional?<span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-800">Koşullu</span>:null}</div><p className="mt-1 text-xs text-muted-foreground">{e.starts_on}{e.ends_on!==e.starts_on?` → ${e.ends_on}`:""}</p><p className="mt-1 text-[10px] text-muted-foreground">Kapsam: {[...(e.school_levels??[]),...(e.school_types??[])].join(", ")||"Genel"}{e.grade_levels?.length?` · Sınıf: ${e.grade_levels.join(", ")}`:""}</p></button>)}</div>
    <aside className="h-fit rounded-xl border bg-card p-4 lg:sticky lg:top-20">{selectedEvent?<><h3 className="font-semibold">İş / Görev Tanımla</h3><p className="mt-1 text-xs text-muted-foreground">{selectedEvent.title}</p>{editable?<div className="mt-4 space-y-3"><div><Label>İlgili Personel</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={assignedUser} onChange={e=>setAssignedUser(e.target.value)}><option value="">Kişi seçmeden alt göreve ata</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.full_name||"Personel"} · {p.role}</option>)}</select></div><div><Label>Alt Görev / Sorumluluk</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={assignedResponsibility} onChange={e=>setAssignedResponsibility(e.target.value)}><option value="">Seçiniz</option>{responsibilities.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><div><Label>Başlangıç</Label><Input type="date" value={taskStart} onChange={e=>setTaskStart(e.target.value)}/></div><div><Label>Son Tarih</Label><Input type="date" value={taskDue} onChange={e=>setTaskDue(e.target.value)}/></div></div><div><Label>Süre / Tekrar</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={recurrence} onChange={e=>setRecurrence(e.target.value)}>{recurrenceOptions.map(x=><option key={x} value={x}>{recurrenceLabels[x]}</option>)}</select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={reportRequired} onChange={e=>setReportRequired(e.target.checked)}/>Rapor istenecek</label>{reportRequired?<div><Label>Rapor Sıklığı</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={reportFrequency} onChange={e=>setReportFrequency(e.target.value)}><option value="weekly">Haftalık</option><option value="monthly">Aylık</option><option value="semester">Dönemlik</option><option value="on_completion">İş bitiminde</option></select></div>:null}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fileRequired} onChange={e=>setFileRequired(e.target.checked)}/>Dosya/kanıt yükleme zorunlu</label><div><Label>Not</Label><Input value={taskNote} onChange={e=>setTaskNote(e.target.value)}/></div><Button className="w-full gap-2" onClick={()=>void saveTask()}><Send className="size-4"/>Görevi Ata ve Bildir</Button></div>:<p className="mt-3 text-xs text-muted-foreground">Bu alanı değiştirmek için Ayarlar yönetim yetkisi gerekir.</p>}</>:<p className="text-sm text-muted-foreground">Bir takvim olayına tıklayın; sorumlu kişi/alt görev, süre, rapor ve dosya koşullarını tanımlayın.</p>}</aside>
   </TabsContent>
  </Tabs><Button variant="ghost" className="mt-5 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button>
 </AppShell>;
}
