import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, BookOpenCheck, ChevronDown, Plus, RefreshCw, UserRoundCheck } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/curriculum")({head:()=>({meta:[{title:"Ders Havuzu & Atamalar — OkulOS"}]}),component:CurriculumManager});

type SchoolClass={id:string;class_name:string;composite_key:string|null;program_type:string|null;expected_weekly_hours:number|null;curriculum_status:string;academic_year_id:string|null};
type Course={id:string;name:string;short_name:string|null;category:string};
type Teacher={user_id:string;full_name:string|null};
type Requirement={id:string;class_id:string;course_id:string;weekly_hours:number;category:string;source_kind?:string};
type Assignment={id:string;class_course_requirement_id:string;teacher_id:string;assigned_hours:number;assignment_group:string};
type Summary={class_id:string;expected_weekly_hours:number|null;planned_weekly_hours:number;assigned_teacher_hours:number;curriculum_status:string};
type PoolItem={course_id:string;course_name:string;short_name:string|null;category:string;hour_options:number[];repeat_across_years:boolean;elective_group_key:string|null;eligible:boolean;reason:string|null;already_assigned:boolean;current_hours:number|null;planned_hours:number;expected_hours:number|null};

const categoryLabel:Record<string,string>={zorunlu:"Zorunlu",secmeli:"Seçmeli",rehberlik:"Rehberlik",uygulama:"Uygulama",diger:"Diğer"};

function CurriculumManager(){
 const [classes,setClasses]=useState<SchoolClass[]>([]),[courses,setCourses]=useState<Course[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[summaries,setSummaries]=useState<Summary[]>([]),[pool,setPool]=useState<PoolItem[]>([]);
 const [classId,setClassId]=useState(""),[poolCourse,setPoolCourse]=useState(""),[poolHours,setPoolHours]=useState(""),[assignRequirement,setAssignRequirement]=useState(""),[assignTeacher,setAssignTeacher]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[manualOpen,setManualOpen]=useState(false),[manualName,setManualName]=useState(""),[manualHours,setManualHours]=useState("1"),[manualCategory,setManualCategory]=useState("diger");

 const load=useCallback(async()=>{const [c,co,t,r,a,s]=await Promise.all([
  supabase.from("school_classes").select("id,class_name,composite_key,program_type,expected_weekly_hours,curriculum_status,academic_year_id").eq("active",true).order("composite_key"),
  supabase.from("course_catalog").select("id,name,short_name,category").eq("active",true).order("name"),
  supabase.from("profiles").select("user_id,full_name").eq("role","teacher").order("full_name"),
  supabase.from("class_course_requirements").select("id,class_id,course_id,weekly_hours,category,source_kind"),
  supabase.from("teacher_course_assignments").select("id,class_course_requirement_id,teacher_id,assigned_hours,assignment_group"),
  supabase.from("class_curriculum_summary").select("class_id,expected_weekly_hours,planned_weekly_hours,assigned_teacher_hours,curriculum_status")]);
  if(c.error||co.error||t.error||r.error||a.error||s.error){setMessage("Ders havuzu ve atama verileri yüklenemedi.");return}
  setClasses((c.data??[]) as SchoolClass[]);setCourses((co.data??[]) as Course[]);setTeachers((t.data??[]) as Teacher[]);setRequirements((r.data??[]) as Requirement[]);setAssignments((a.data??[]) as Assignment[]);setSummaries((s.data??[]) as Summary[])
 },[]);
 useEffect(()=>{void load()},[load]);
 const loadPool=useCallback(async(id:string)=>{if(!id){setPool([]);return}const {data,error}=await supabase.rpc("get_class_course_pool_v1",{p_class_id:id});if(error){setPool([]);setMessage(`Resmî ders havuzu okunamadı: ${error.message}`);return}setPool((data??[]) as PoolItem[])},[]);
 useEffect(()=>{void loadPool(classId)},[classId,loadPool]);

 const selectedClass=classes.find(c=>c.id===classId),selectedSummary=summaries.find(s=>s.class_id===classId),classRequirements=requirements.filter(r=>r.class_id===classId),courseMap=useMemo(()=>Object.fromEntries(courses.map(c=>[c.id,c])),[courses]),teacherMap=useMemo(()=>Object.fromEntries(teachers.map(t=>[t.user_id,t.full_name??"Öğretmen"])),[teachers]);
 const assignmentMap=useMemo(()=>{const m:Record<string,Assignment[]>={};for(const a of assignments)(m[a.class_course_requirement_id]??=[]).push(a);return m},[assignments]);
 const selectedPool=pool.find(p=>p.course_id===poolCourse),expected=selectedSummary?.expected_weekly_hours??selectedClass?.expected_weekly_hours??0,planned=selectedSummary?.planned_weekly_hours??0,assigned=selectedSummary?.assigned_teacher_hours??0,percent=expected?Math.min(100,Math.round(planned/expected*100)):0;

 async function assignFromPool(){if(!classId||!poolCourse||!poolHours)return;setBusy(true);setMessage(null);const {error}=await supabase.rpc("assign_class_course_from_pool_v1",{p_class_id:classId,p_course_id:poolCourse,p_hours:Number(poolHours)});setBusy(false);if(error){const m=error.message;setMessage(m.includes("MAX_WEEKLY")?"Bu atama sınıfın maksimum haftalık ders saatini aşar.":m.includes("PREVIOUS_YEAR")?"Bu ders önceki eğitim-öğretim yılında okutulduğu için tekrar alınamaz.":m.includes("HOUR_OPTION")?"Bu ders saati resmî çizelgede izin verilen seçeneklerden biri değil.":`Ders atanamadı: ${m}`);return}setPoolCourse("");setPoolHours("");setMessage("Ders resmî çizelge kuralına göre sınıfa atandı.");await load();await loadPool(classId)}

 async function addLocalCourse(){if(!classId||!manualName.trim())return;const hours=Number(manualHours);if(!Number.isInteger(hours)||hours<1||hours>20)return setMessage("Yerel ders saati 1-20 arasında olmalıdır.");if(expected&&planned+hours>expected)return setMessage("Yerel ders sınıfın maksimum haftalık ders saatini aşar.");setBusy(true);let course=courses.find(c=>c.name.toLocaleLowerCase("tr-TR")===manualName.trim().toLocaleLowerCase("tr-TR"));if(!course){const {data,error}=await supabase.from("course_catalog").insert({name:manualName.trim(),category:manualCategory}).select("id,name,short_name,category").single();if(error||!data){setBusy(false);return setMessage("Yerel ders kataloğa eklenemedi.")}course=data as Course}
  const {error}=await supabase.from("class_course_requirements").upsert({class_id:classId,course_id:course.id,weekly_hours:hours,category:manualCategory,source_kind:"local",academic_year_id:selectedClass?.academic_year_id??null},{onConflict:"class_id,course_id"});if(!error)await supabase.rpc("refresh_class_curriculum_status",{p_class_id:classId});setBusy(false);if(error)return setMessage("Yerel ders sınıfa eklenemedi.");setManualName("");setMessage("Yerel/kurum özel ders eklendi.");await load();await loadPool(classId)}

 async function assignTeacher(){if(!assignRequirement||!assignTeacher)return;setBusy(true);const {error}=await supabase.rpc("assign_teacher_to_class_course",{p_requirement_id:assignRequirement,p_teacher_id:assignTeacher,p_group:"main"});setBusy(false);if(error)return setMessage(error.message.includes("EXCEED")?"Atanan öğretmen saatleri ders saatini aşamaz.":"Öğretmen derse atanamadı.");setMessage("Öğretmen derse atandı.");await load()}
 async function removeRequirement(id:string){setBusy(true);const {error}=await supabase.from("class_course_requirements").delete().eq("id",id);if(!error&&classId)await supabase.rpc("refresh_class_curriculum_status",{p_class_id:classId});setBusy(false);if(error)return setMessage("Ders kaldırılamadı.");await load();await loadPool(classId)}

 return <AppShell title="Ders Havuzu & Atamalar" subtitle="Resmî çizelge → uygun ders → saat seçimi → öğretmen ataması">
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <section className="rounded-xl border bg-card p-4"><Label>Sınıf / Program</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={classId} onChange={e=>{setClassId(e.target.value);setPoolCourse("");setPoolHours("")}}><option value="">Sınıf seçiniz</option>{classes.map(c=><option key={c.id} value={c.id}>{c.composite_key??c.class_name}{c.program_type?` · ${c.program_type}`:""}</option>)}</select>{classId?<div className="mt-4 rounded-xl border p-3"><div className="flex items-center justify-between"><div><b className="text-sm">Haftalık ders yükü</b><p className="text-xs text-muted-foreground">{planned} saat planlandı · {assigned} saat öğretmene atandı</p></div><Badge variant={expected&&planned>expected?"destructive":expected&&planned===expected?"default":"secondary"}>{planned}/{expected||"?"}</Badge></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-muted"><div className={expected&&planned>expected?"h-full bg-destructive":"h-full bg-primary"} style={{width:`${percent}%`}}/></div><p className="mt-1 text-right text-[11px] text-muted-foreground">{expected?`${Math.max(0,expected-planned)} saat kaldı`:"Resmî haftalık hedef henüz tanımlı değil"}</p></div>:null}</section>

  {classId?<div className="mt-5 grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
   <section className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><BookOpenCheck className="size-4"/>Bu sınıfta okutulabilecek dersler</h2><p className="mt-1 text-xs text-muted-foreground">Okul türü, program, sınıf seviyesi, eğitim yılı ve resmî çizelgeye göre filtrelenir.</p></div><Button variant="ghost" size="sm" onClick={()=>void loadPool(classId)}><RefreshCw className="size-4"/></Button></div>
    {!pool.length?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertCircle className="mr-2 inline size-4"/><b>Bu sınıf için resmî çizelge kuralı henüz yüklenmemiş.</b> Çizelge parser'ı `course_offering_rules` katmanını doldurduğunda havuz otomatik oluşur. Yerel ders ekleme aşağıda istisna olarak kullanılabilir.</div>:<div className="mt-4 max-h-[430px] space-y-2 overflow-auto pr-1">{pool.map(p=><button key={p.course_id} type="button" disabled={!p.eligible} onClick={()=>{setPoolCourse(p.course_id);setPoolHours(String(p.current_hours??p.hour_options[0]??1))}} className={`w-full rounded-xl border p-3 text-left ${!p.eligible?"cursor-not-allowed bg-muted/40 opacity-60":poolCourse===p.course_id?"border-primary bg-primary/5":"hover:border-primary/40"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{p.course_name}</div><div className="mt-1 flex flex-wrap gap-1"><Badge variant={p.category==="zorunlu"?"default":"secondary"}>{categoryLabel[p.category]??p.category}</Badge>{p.elective_group_key?<Badge variant="outline">{p.elective_group_key}</Badge>:null}{!p.repeat_across_years?<Badge variant="outline">Tekrar alınamaz</Badge>:null}</div>{p.reason?<p className="mt-2 text-xs text-destructive">{p.reason}</p>:null}</div><span className="whitespace-nowrap text-xs text-muted-foreground">{p.hour_options.join(" / ")} saat</span></div></button>)}</div>}
    {selectedPool?.eligible?<div className="mt-4 rounded-xl border bg-muted/20 p-3"><Label>Haftalık ders saati</Label><div className="mt-2 flex flex-wrap gap-2">{selectedPool.hour_options.map(h=><Button key={h} type="button" size="sm" variant={poolHours===String(h)?"default":"outline"} onClick={()=>setPoolHours(String(h))}>{h} saat</Button>)}</div><Button className="mt-3 w-full" disabled={busy||!poolHours||Boolean(expected&&planned-Number(selectedPool.current_hours??0)+Number(poolHours)>expected)} onClick={()=>void assignFromPool()}>Sınıfa Ata</Button></div>:null}
    <button type="button" className="mt-4 flex w-full items-center justify-between rounded-lg border px-3 py-2 text-sm" onClick={()=>setManualOpen(v=>!v)}><span><b>Yerel / kurum özel ders</b> <span className="text-muted-foreground">— istisnai kullanım</span></span><ChevronDown className={`size-4 transition ${manualOpen?"rotate-180":""}`}/></button>{manualOpen?<div className="mt-2 grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_90px_140px_auto]"><Input value={manualName} onChange={e=>setManualName(e.target.value)} placeholder="Ders adı"/><Input value={manualHours} onChange={e=>setManualHours(e.target.value.replace(/\D/g,""))}/><select className="h-10 rounded-md border bg-background px-2 text-sm" value={manualCategory} onChange={e=>setManualCategory(e.target.value)}><option value="diger">Diğer</option><option value="secmeli">Seçmeli</option><option value="uygulama">Uygulama</option></select><Button disabled={busy} onClick={()=>void addLocalCourse()}><Plus className="mr-1 size-4"/>Ekle</Button></div>:null}
   </section>

   <section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><UserRoundCheck className="size-4"/>Öğretmen Ata</h2><p className="mt-1 text-xs text-muted-foreground">Bir derse birden fazla öğretmen atanabilir; toplam atanan saat ders saatini aşamaz.</p><select className="mt-4 h-10 w-full rounded-md border bg-background px-3 text-sm" value={assignRequirement} onChange={e=>setAssignRequirement(e.target.value)}><option value="">Ders seçiniz</option>{classRequirements.map(r=><option key={r.id} value={r.id}>{courseMap[r.course_id]?.name??"Ders"} · {r.weekly_hours}s</option>)}</select><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={assignTeacher} onChange={e=>setAssignTeacher(e.target.value)}><option value="">Öğretmen seçiniz</option>{teachers.map(t=><option key={t.user_id} value={t.user_id}>{t.full_name}</option>)}</select><Button className="mt-2 w-full" disabled={busy||!assignRequirement||!assignTeacher} onClick={()=>void assignTeacher()}>Derse Ata</Button>
    <div className="mt-4 space-y-2">{classRequirements.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><div><b className="text-sm">{courseMap[r.course_id]?.name??"Ders"}</b><p className="text-xs text-muted-foreground">{r.weekly_hours} saat · {categoryLabel[r.category]??r.category} · {r.source_kind==="local"?"Yerel":"Resmî"}</p></div><Button size="sm" variant="ghost" onClick={()=>void removeRequirement(r.id)}>Kaldır</Button></div><div className="mt-2 flex flex-wrap gap-1">{(assignmentMap[r.id]??[]).map(a=><Badge key={a.id} variant="outline">{teacherMap[a.teacher_id]} · {a.assigned_hours}s</Badge>)}</div></div>)}</div>
   </section>
  </div>:<div className="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Ders havuzunu görmek için sınıf seçin.</div>}
 </AppShell>
}
