import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, FileText, Search, Send, UploadCloud } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";
import { SCHOOL_LEVELS } from "@/lib/meb-data-import";

export const Route=createFileRoute("/legislation")({head:()=>({meta:[{title:"Mevzuat Kütüphanesi — OkulOS"}]}),component:LegislationLibrary});
type Law={id:string;title:string;legislation_type:string;topic:string|null;school_levels:string[];school_types:string[];source_url:string|null;file_url:string|null;effective_on:string|null;notes:string|null;tags:string[]};
type Person={user_id:string;full_name:string|null;role:string};
const types=["Kanun","Yönetmelik","Yönerge","Genelge","Kılavuz","Tebliğ","Diğer"];

function LegislationLibrary(){
 const fileRef=useRef<HTMLInputElement>(null);const {can}=usePermissions();const editable=can("settings.manage");
 const [laws,setLaws]=useState<Law[]>([]),[people,setPeople]=useState<Person[]>([]),[q,setQ]=useState(""),[message,setMessage]=useState<string|null>(null),[title,setTitle]=useState(""),[type,setType]=useState("Yönetmelik"),[topic,setTopic]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[effectiveOn,setEffectiveOn]=useState(""),[notes,setNotes]=useState(""),[tags,setTags]=useState(""),[levels,setLevels]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[selectedLaw,setSelectedLaw]=useState<Law|null>(null),[shareUsers,setShareUsers]=useState<string[]>([]);
 const load=useCallback(async()=>{const [l,p]=await Promise.all([supabase.from("legislation_library").select("id,title,legislation_type,topic,school_levels,school_types,source_url,file_url,effective_on,notes,tags").eq("active",true).order("title"),supabase.from("profiles").select("user_id,full_name,role").order("full_name")]);setLaws((l.data??[]) as Law[]);setPeople((p.data??[]) as Person[])},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const s=q.trim().toLocaleLowerCase("tr-TR");if(!s)return laws;return laws.filter(x=>[x.title,x.topic??"",...(x.tags??[])].join(" ").toLocaleLowerCase("tr-TR").includes(s))},[laws,q]);
 const toggle=(arr:string[],value:string,setter:(x:string[])=>void)=>setter(arr.includes(value)?arr.filter(x=>x!==value):[...arr,value]);
 async function save(){if(!editable||!title.trim())return;setMessage(null);let fileUrl:string|null=null;if(file){const ext=file.name.split(".").pop()||"bin";const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("legislation").upload(path,file,{upsert:false});if(up.error)return setMessage("Mevzuat dosyası yüklenemedi.");fileUrl=path;}const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from("legislation_library").insert({title:title.trim(),legislation_type:type,topic:topic||null,school_levels:levels,source_url:sourceUrl||null,file_url:fileUrl,effective_on:effectiveOn||null,notes:notes||null,tags:tags.split(",").map(x=>x.trim()).filter(Boolean),created_by:u.user?.id??null});if(error)return setMessage("Mevzuat kaydedilemedi.");setTitle("");setTopic("");setSourceUrl("");setEffectiveOn("");setNotes("");setTags("");setLevels([]);setFile(null);if(fileRef.current)fileRef.current.value="";setMessage("Mevzuat kütüphaneye kaydedildi.");await load()}
 async function openLaw(law:Law){setSelectedLaw(law);if(law.file_url){const {data}=await supabase.storage.from("legislation").createSignedUrl(law.file_url,3600);if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer");else setMessage("Dosya açılamadı.");return;}if(law.source_url)window.open(law.source_url,"_blank","noopener,noreferrer");}
 async function share(){if(!selectedLaw||!shareUsers.length)return;const {data:u}=await supabase.auth.getUser();const rows=shareUsers.map(user_id=>({legislation_id:selectedLaw.id,user_id,created_by:u.user?.id??null}));const {error}=await supabase.from("legislation_shares").upsert(rows,{onConflict:"legislation_id,user_id"});if(error)return setMessage("Mevzuat gönderilemedi.");await supabase.from("notifications").insert(shareUsers.map(user_id=>({user_id,type:"system",priority:"normal",title:"Mevzuat bilgilendirmesi",message:selectedLaw.title,action_label:"Mevzuatı Aç",action_url:"/legislation"})));setMessage(`${shareUsers.length} personele mevzuat bildirimi gönderildi.`);setShareUsers([])}
 return <AppShell title="Mevzuat Kütüphanesi" subtitle="Kaydet · ara · oku · personele gönder" action={<BookOpen className="size-5"/>}>
   <div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Mevzuat, konu veya etiket ara..."/></div>{message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
   {editable?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Mevzuat Ekle</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><div><Label>Başlık</Label><Input value={title} onChange={e=>setTitle(e.target.value)}/></div><div><Label>Tür</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Konu</Label><Input value={topic} onChange={e=>setTopic(e.target.value)}/></div><div><Label>Yürürlük Tarihi</Label><Input type="date" value={effectiveOn} onChange={e=>setEffectiveOn(e.target.value)}/></div><div><Label>Kaynak Bağlantısı</Label><Input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://..."/></div><div><Label>Etiketler</Label><Input value={tags} onChange={e=>setTags(e.target.value)} placeholder="sınav, disiplin, kurul"/></div><div className="md:col-span-2"><Label>Not</Label><Input value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="mt-3"><Label>İlgili Kademe / Okul Seviyesi</Label><div className="mt-2 flex flex-wrap gap-1">{SCHOOL_LEVELS.map(x=><Button key={x} type="button" size="sm" variant={levels.includes(x)?"default":"outline"} onClick={()=>toggle(levels,x,setLevels)}>{x}</Button>)}</div></div><input ref={fileRef} type="file" accept=".pdf,.doc,.docx" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/><div className="mt-3 flex gap-2"><Button type="button" variant="outline" className="gap-2" onClick={()=>fileRef.current?.click()}><UploadCloud className="size-4"/>{file?file.name:"Dosya Ekle"}</Button><Button className="flex-1" onClick={()=>void save()}>Kaydet</Button></div></section>:null}
   <div className="mt-5 grid gap-3 md:grid-cols-2">{filtered.map(l=><button key={l.id} type="button" onClick={()=>setSelectedLaw(l)} className={`rounded-xl border bg-card p-4 text-left hover:border-primary/40 ${selectedLaw?.id===l.id?"border-primary":""}`}><div className="flex gap-3"><FileText className="mt-0.5 size-5 text-primary"/><div><b>{l.title}</b><p className="mt-1 text-xs text-muted-foreground">{l.legislation_type}{l.topic?` · ${l.topic}`:""}</p><p className="mt-2 text-[10px] text-muted-foreground">{l.school_levels?.join(", ")||"Tüm kademeler"}</p></div></div></button>)}</div>
   {selectedLaw?<section className="mt-5 rounded-xl border bg-card p-4"><h2 className="font-semibold">{selectedLaw.title}</h2><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void openLaw(selectedLaw)}>Oku / Aç</Button>{editable?<><select multiple className="min-h-24 min-w-[280px] rounded-md border bg-background p-2 text-sm" value={shareUsers} onChange={e=>setShareUsers(Array.from(e.currentTarget.selectedOptions).map(o=>o.value))}>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.full_name||"Personel"} · {p.role}</option>)}</select><Button className="gap-2" onClick={()=>void share()}><Send className="size-4"/>Seçililere Gönder</Button></>:null}</div></section>:null}
 </AppShell>;
}
