import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Crown, Plus, Scale } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/norm-settings")({head:()=>({meta:[{title:"Norm Eşleştirmeleri — OkulOS"}]}),component:NormSettings});
type Area={id:string;name:string};type Course={id:string;name:string};type Source={id:string;code:string;title:string};type Rule={id:string;name:string;code:string};
type CourseMap={id:string;course_id:string;teaching_area_id:string;source_id:string|null;effective_from:string;note:string|null};
type AreaRule={id:string;teaching_area_id:string;rule_set_id:string;source_id:string|null;effective_from:string;note:string|null};
function NormSettings(){
 const [allowed,setAllowed]=useState<boolean|null>(null);const [areas,setAreas]=useState<Area[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [sources,setSources]=useState<Source[]>([]);const [rules,setRules]=useState<Rule[]>([]);const [courseMaps,setCourseMaps]=useState<CourseMap[]>([]);const [areaRules,setAreaRules]=useState<AreaRule[]>([]);const [message,setMessage]=useState<string|null>(null);
 const [course,setCourse]=useState("");const [area,setArea]=useState("");const [courseSource,setCourseSource]=useState("");const [courseFrom,setCourseFrom]=useState("");const [courseNote,setCourseNote]=useState("");
 const [ruleArea,setRuleArea]=useState("");const [rule,setRule]=useState("");const [ruleSource,setRuleSource]=useState("");const [ruleFrom,setRuleFrom]=useState("");const [ruleNote,setRuleNote]=useState("");
 const areaMap=useMemo(()=>Object.fromEntries(areas.map(x=>[x.id,x.name])),[areas]);const courseMap=useMemo(()=>Object.fromEntries(courses.map(x=>[x.id,x.name])),[courses]);const ruleMap=useMemo(()=>Object.fromEntries(rules.map(x=>[x.id,x.name])),[rules]);
 const load=useCallback(async()=>{const {data:can}=await supabase.rpc("is_super_admin");setAllowed(Boolean(can));if(!can)return;const [a,c,s,r,cm,ar]=await Promise.all([
  supabase.from("teaching_areas").select("id,name").eq("active",true).order("name"),
  supabase.from("course_catalog").select("id,name").eq("active",true).order("name"),
  supabase.from("legal_rule_sources").select("id,code,title").eq("active",true).order("code"),
  supabase.from("norm_rule_sets").select("id,name,code").eq("active",true).order("name"),
  supabase.from("norm_course_area_rules").select("id,course_id,teaching_area_id,source_id,effective_from,note").eq("active",true).order("effective_from",{ascending:false}),
  supabase.from("norm_area_rule_assignments").select("id,teaching_area_id,rule_set_id,source_id,effective_from,note").eq("active",true).order("effective_from",{ascending:false}),
 ]);setAreas((a.data??[]) as Area[]);setCourses((c.data??[]) as Course[]);setSources((s.data??[]) as Source[]);setRules((r.data??[]) as Rule[]);setCourseMaps((cm.data??[]) as CourseMap[]);setAreaRules((ar.data??[]) as AreaRule[]);},[]);
 useEffect(()=>{void load();},[load]);
 async function addCourseMap(){if(!course||!area||!courseFrom)return setMessage("Ders, norm alanı ve yürürlük tarihi zorunludur.");const {error}=await supabase.from("norm_course_area_rules").insert({course_id:course,teaching_area_id:area,source_id:courseSource||null,effective_from:courseFrom,note:courseNote||null,active:true});if(error)return setMessage("Ders → norm alanı eşleşmesi kaydedilemedi.");setCourseNote("");setMessage("Ders → norm alanı eşleşmesi kaydedildi.");await load();}
 async function addAreaRule(){if(!ruleArea||!rule||!ruleFrom)return setMessage("Alan, kural seti ve yürürlük tarihi zorunludur.");const {error}=await supabase.from("norm_area_rule_assignments").insert({teaching_area_id:ruleArea,rule_set_id:rule,source_id:ruleSource||null,effective_from:ruleFrom,note:ruleNote||null,active:true});if(error)return setMessage("Alan → norm kuralı eşleşmesi kaydedilemedi.");setRuleNote("");setMessage("Alan → norm kuralı eşleşmesi kaydedildi.");await load();}
 if(allowed===null)return <AppShell title="Norm Eşleştirmeleri"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;
 if(!allowed)return <AppShell title="Norm Eşleştirmeleri"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Bu ekran yalnız Süper Admin hesabına açıktır.</div></AppShell>;
 return <AppShell title="Norm Eşleştirmeleri" subtitle="Ders → alan → yürürlükteki norm kuralı" action={<Crown className="size-5 text-amber-500"/>}>
  <div className="grid gap-2 sm:grid-cols-2"><Link to="/norm-analysis"><Button variant="outline" className="w-full"><Scale className="mr-2 size-4"/>Norm Analizine Dön</Button></Link><Link to="/super-admin"><Button variant="outline" className="w-full">Süper Admin Merkezi</Button></Link></div>{message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <div className="mt-4 grid gap-4 lg:grid-cols-2">
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Ders → Norm Alanı</h2><p className="mt-1 text-xs text-muted-foreground">Bir dersin formal norm hesabında hangi alana yazılacağını kaynaklı ve tarihli tanımlayın.</p><div className="mt-3 grid gap-3"><div><Label>Ders</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={course} onChange={e=>setCourse(e.target.value)}><option value="">Seçiniz</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Norm Alanı</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={area} onChange={e=>setArea(e.target.value)}><option value="">Seçiniz</option>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Kaynak</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={courseSource} onChange={e=>setCourseSource(e.target.value)}><option value="">Kaynak seçilmedi</option>{sources.map(x=><option key={x.id} value={x.id}>{x.code} · {x.title}</option>)}</select></div><div><Label>Yürürlük Tarihi</Label><input type="date" value={courseFrom} onChange={e=>setCourseFrom(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></div><div><Label>Not</Label><input value={courseNote} onChange={e=>setCourseNote(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></div></div><Button className="mt-3 w-full gap-2" onClick={()=>void addCourseMap()}><Plus className="size-4"/>Eşleşmeyi Kaydet</Button></section>
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Alan → Norm Kural Seti</h2><p className="mt-1 text-xs text-muted-foreground">Alan için hangi norm saat kuralının hangi tarihten itibaren geçerli olduğunu tanımlayın.</p><div className="mt-3 grid gap-3"><div><Label>Alan</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={ruleArea} onChange={e=>setRuleArea(e.target.value)}><option value="">Seçiniz</option>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Norm Kural Seti</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={rule} onChange={e=>setRule(e.target.value)}><option value="">Seçiniz</option>{rules.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></div><div><Label>Kaynak</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={ruleSource} onChange={e=>setRuleSource(e.target.value)}><option value="">Kaynak seçilmedi</option>{sources.map(x=><option key={x.id} value={x.id}>{x.code} · {x.title}</option>)}</select></div><div><Label>Yürürlük Tarihi</Label><input type="date" value={ruleFrom} onChange={e=>setRuleFrom(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></div><div><Label>Not</Label><input value={ruleNote} onChange={e=>setRuleNote(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></div></div><Button className="mt-3 w-full gap-2" onClick={()=>void addAreaRule()}><Plus className="size-4"/>Kural Eşleşmesini Kaydet</Button></section>
  </div>
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Mevcut Ders Eşleşmeleri</h3><div className="mt-3 max-h-80 overflow-auto divide-y rounded-lg border">{courseMaps.map(x=><div key={x.id} className="p-3 text-sm"><b>{courseMap[x.course_id]??"Ders"}</b> → {areaMap[x.teaching_area_id]??"Alan"}<p className="text-xs text-muted-foreground">{x.effective_from}{x.note?` · ${x.note}`:""}</p></div>)}{!courseMaps.length?<p className="p-4 text-sm text-muted-foreground">Henüz eşleşme yok.</p>:null}</div></section><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Mevcut Alan Kural Eşleşmeleri</h3><div className="mt-3 max-h-80 overflow-auto divide-y rounded-lg border">{areaRules.map(x=><div key={x.id} className="p-3 text-sm"><b>{areaMap[x.teaching_area_id]??"Alan"}</b> → {ruleMap[x.rule_set_id]??"Kural"}<p className="text-xs text-muted-foreground">{x.effective_from}{x.note?` · ${x.note}`:""}</p></div>)}{!areaRules.length?<p className="p-4 text-sm text-muted-foreground">Henüz eşleşme yok.</p>:null}</div></section></div>
 </AppShell>;
}
