import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { BookOpenCheck, Plus, RefreshCw } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/payroll-rules")({head:()=>({meta:[{title:"Ek Ders Kuralları — OkulOS"}]}),component:PayrollRules});
type Source={id:string;code:string;title:string};
type Rule={id:string;code:string;name:string;category:string;kbs_data_type:string;rate_multiplier:number;weekly_cap_hours:number|null;monthly_cap_hours:number|null;requires_actual_performance:boolean;effective_from:string;effective_to:string|null;condition_note:string|null;source_id:string|null;active:boolean};
const categories=[['gunduz','Gündüz'],['nobet','Nöbet'],['rehberlik','Rehberlik'],['hazirlik_planlama','Hazırlık / Planlama'],['dyk','DYK'],['destek_egitim','Destek Eğitim'],['seminer','Seminer'],['kurs','Kurs'],['egzersiz','Egzersiz'],['gece_haftasonu','Gece / Hafta Sonu'],['yonetim','Yönetim'],['diger','Diğer']];

function PayrollRules(){
 const [rules,setRules]=useState<Rule[]>([]);const[sources,setSources]=useState<Source[]>([]);const[msg,setMsg]=useState<string|null>(null);
 const[code,setCode]=useState('');const[name,setName]=useState('');const[category,setCategory]=useState('gunduz');const[kbs,setKbs]=useState('101');const[mult,setMult]=useState('1');const[weekCap,setWeekCap]=useState('');const[monthCap,setMonthCap]=useState('');const[actual,setActual]=useState(true);const[from,setFrom]=useState('');const[to,setTo]=useState('');const[source,setSource]=useState('');const[note,setNote]=useState('');
 const load=useCallback(async()=>{const[r,s]=await Promise.all([supabase.from('payroll_rule_registry').select('id,code,name,category,kbs_data_type,rate_multiplier,weekly_cap_hours,monthly_cap_hours,requires_actual_performance,effective_from,effective_to,condition_note,source_id,active').order('effective_from',{ascending:false}),supabase.from('legal_rule_sources').select('id,code,title').eq('active',true).order('effective_from',{ascending:false})]);setRules((r.data??[])as Rule[]);setSources((s.data??[])as Source[]);},[]);useEffect(()=>{void load()},[load]);
 async function save(){if(!code.trim()||!name.trim()||!from||!kbs.trim())return setMsg('Kod, ad, KBS veri tipi ve yürürlük tarihi zorunludur.');const{data:user}=await supabase.auth.getUser();const{error}=await supabase.from('payroll_rule_registry').insert({code:code.trim().toUpperCase(),name:name.trim(),category,kbs_data_type:kbs.trim(),rate_multiplier:Number(mult||1),weekly_cap_hours:weekCap?Number(weekCap):null,monthly_cap_hours:monthCap?Number(monthCap):null,requires_actual_performance:actual,source_id:source||null,effective_from:from,effective_to:to||null,condition_note:note||null,active:true,created_by:user.user?.id??null});if(error)return setMsg(`Kural kaydedilemedi: ${error.message}`);setCode('');setName('');setWeekCap('');setMonthCap('');setNote('');setMsg('Ek ders kuralı yürürlük tarihiyle kaydedildi.');await load();}
 return <AppShell title="Ek Ders Kuralları" subtitle="Yürürlük tarihli · kaynaklı · KBS veri tipli kural kayıtları" action={<BookOpenCheck className="size-5"/>}>
  {msg?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{msg}</div>:null}
  <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Yeni Kural</h2><p className="mt-1 text-xs text-muted-foreground">Oran ve saat sınırlarını doğrulanmış mevzuat kaynağına göre girin; kod içine sabitlenmez.</p><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-3">
   <div><Label>Kural Kodu</Label><Input value={code} onChange={e=>setCode(e.target.value)} placeholder="DYK-2026"/></div><div><Label>Kural Adı</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Kategori</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
   <div><Label>KBS Veri Tipi</Label><Input value={kbs} onChange={e=>setKbs(e.target.value)}/></div><div><Label>Ücret Katsayısı</Label><Input type="number" min="0.001" step="0.001" value={mult} onChange={e=>setMult(e.target.value)}/></div><div><Label>Haftalık Tavan Saat</Label><Input type="number" step="0.5" value={weekCap} onChange={e=>setWeekCap(e.target.value)}/></div>
   <div><Label>Aylık Tavan Saat</Label><Input type="number" step="0.5" value={monthCap} onChange={e=>setMonthCap(e.target.value)}/></div><div><Label>Yürürlük Başlangıcı</Label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><Label>Yürürlük Bitişi</Label><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>
   <div><Label>Kaynak</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={source} onChange={e=>setSource(e.target.value)}><option value="">Kaynak seçilmedi</option>{sources.map(s=><option key={s.id} value={s.id}>{s.code} · {s.title}</option>)}</select></div><div className="lg:col-span-2"><Label>Koşul / Açıklama</Label><Input value={note} onChange={e=>setNote(e.target.value)}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={actual} onChange={e=>setActual(e.target.checked)}/> Fiilen yerine getirme şartı var</label>
  </div><Button className="mt-3 w-full gap-2" onClick={()=>void save()}><Plus className="size-4"/>Kuralı Kaydet</Button></section>
  <div className="mt-4 space-y-2">{rules.map(r=><div key={r.id} className="rounded-xl border bg-card p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><b>{r.code} · {r.name}</b><span className="rounded-full bg-muted px-2 py-0.5 text-[10px]">{categories.find(x=>x[0]===r.category)?.[1]??r.category}</span><span className="text-[10px]">KBS {r.kbs_data_type}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.effective_from}{r.effective_to?` → ${r.effective_to}`:''} · katsayı {r.rate_multiplier}{r.weekly_cap_hours!=null?` · haftalık ≤ ${r.weekly_cap_hours}`:''}{r.monthly_cap_hours!=null?` · aylık ≤ ${r.monthly_cap_hours}`:''}</p>{r.condition_note?<p className="mt-1 text-xs">{r.condition_note}</p>:null}</div>)}{!rules.length?<div className="rounded-xl border p-5 text-center text-sm text-muted-foreground">Henüz ek ders kuralı girilmedi.</div>:null}</div>
  <Button variant="ghost" className="mt-5 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button>
 </AppShell>;
}
