import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { FileSpreadsheet, Settings2, ShieldCheck, UploadCloud } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { getPersonnelColumns, parsePersonnelSummaryReport, type PersonnelImportRow } from "@/lib/personnel-report-import";

export const Route=createFileRoute("/personnel-import")({head:()=>({meta:[{title:"Personel Veri İçe Aktarma — OkulOS"}]}),component:PersonnelImport});
function PersonnelImport(){
 const fileRef=useRef<HTMLInputElement>(null);const [allowed,setAllowed]=useState<boolean|null>(null),[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<PersonnelImportRow[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const columns=useMemo(()=>getPersonnelColumns(rows),[rows]);
 useEffect(()=>{void(async()=>{const {data}=await supabase.rpc("can_manage_personnel_private_data");setAllowed(Boolean(data));})()},[]);
 async function selectFile(next:File){setMessage(null);setRows([]);setFile(next);try{setRows(await parsePersonnelSummaryReport(next));}catch(e){console.error(e);setFile(null);setMessage("Personel özet raporu tanınamadı. MEBBİS Personel Listesi Özet Bilgiler XLS/XLSX veya metin tabanlı PDF kullanın.");}}
 async function doImport(){if(!file||!rows.length)return;setBusy(true);const {data,error}=await supabase.rpc("import_personnel_registry",{p_file_name:file.name,p_rows:rows});setBusy(false);if(error){setMessage("Personel verileri içe aktarılamadı: "+error.message);return;}const result=Array.isArray(data)?data[0]:data;setMessage(`${result?.affected_personnel??rows.length} personel; ${columns.length} kaynak/ayrıştırılmış alan ile içe aktarıldı. Müdür, alan kullanımını kurum bazında belirleyebilir.`);setRows([]);setFile(null);if(fileRef.current)fileRef.current.value="";}
 if(allowed===null)return <AppShell title="Personel Veri İçe Aktarma"><p className="text-sm text-muted-foreground">Müdür yetkisi kontrol ediliyor…</p></AppShell>;
 if(!allowed)return <AppShell title="Personel Veri İçe Aktarma"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><b>Gizli personel verisi.</b> Bu ekran öğretmen, Rehberlik/PDR öğretmeni ve müdür yardımcılarına kapalıdır. Personel özet bilgilerini yalnız kurum müdürü içe aktarabilir ve görüntüleyebilir.</div></AppShell>;
 return <AppShell title="Personel Veri İçe Aktarma" subtitle="MEBBİS PDF/Excel raporundaki tüm alanları kaybetmeden, müdür kontrollü personel veri havuzuna al">
  <div className="grid gap-2 sm:grid-cols-2"><Link to="/personnel-admin"><Button variant="outline" className="w-full">Personel Yönetimi</Button></Link><Link to="/personnel-field-settings"><Button variant="outline" className="w-full gap-2"><Settings2 className="size-4"/>Alan Görünürlük / Kullanım Ayarları</Button></Link></div>
  <div className="mt-4 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-950"><ShieldCheck className="mt-0.5 size-4 shrink-0"/><p><b>Müdüre özel:</b> T.C. kimlik, sicil, arşiv, cinsiyet, kan grubu, doğum tarihi ve hizmet başlangıcı dahil kaynakta bulunan tüm bilgiler veritabanına alınır; bu detaylar öğretmen, Rehberlik/PDR öğretmeni ve müdür yardımcısına açılmaz. Süper Admin yalnız sistem varsayılanlarını belirler.</p></div>
  {message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <input ref={fileRef} className="hidden" type="file" accept=".xls,.xlsx,.pdf,application/pdf,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>{const f=e.target.files?.[0];if(f)void selectFile(f)}}/>
  <button type="button" onClick={()=>fileRef.current?.click()} className="mt-4 w-full rounded-xl border-2 border-dashed bg-card p-7 text-center transition hover:border-primary/50"><UploadCloud className="mx-auto size-7 text-primary"/><p className="mt-2 font-medium">MEBBİS Personel Listesi Özet Bilgiler PDF / Excel yükle</p><p className="mt-1 text-xs text-muted-foreground">13 fiziksel sütun korunur; birleşik hücreler ayrıca anlamlı alanlara ayrıştırılır.</p></button>
  {rows.length?<section className="mt-4 rounded-xl border border-primary/20 bg-primary-soft p-4"><div className="flex items-start gap-2"><FileSpreadsheet className="mt-0.5 size-5 text-primary"/><div><p className="text-sm font-semibold">{file?.name}</p><p className="text-xs text-muted-foreground">{rows.length} personel · {columns.length} kaynak/normalize alan algılandı. Müdür önizlemesi ilk 12 kaydı gösterir.</p></div></div>
    <div className="mt-3 overflow-x-auto rounded-lg border bg-card"><table className="min-w-max text-xs"><thead><tr className="border-b bg-muted/40"><th className="sticky left-0 z-10 bg-muted p-2 text-left">Ad Soyad</th><th className="p-2 text-left">Otomatik Rol</th><th className="p-2 text-left">Branş</th>{columns.map(c=><th key={c.key} className="max-w-64 whitespace-nowrap p-2 text-left">{c.label}</th>)}</tr></thead><tbody>{rows.slice(0,12).map((row,i)=><tr key={`${row.fullName}-${i}`} className="border-b"><td className="sticky left-0 bg-card p-2 font-medium">{row.fullName}</td><td className="p-2">{row.derivedRoles.join(", ")||row.systemRole}</td><td className="p-2">{row.teachingArea||"—"}</td>{columns.map(c=><td key={c.key} className="max-w-64 truncate p-2" title={row.rawFields[c.key]||""}>{row.rawFields[c.key]||"—"}</td>)}</tr>)}</tbody></table></div>
    <div className="mt-3 flex gap-2"><Button className="flex-1" disabled={busy} onClick={()=>void doImport()}>{busy?"Aktarılıyor…":"Onayla ve Tüm Bilgileri Aktar"}</Button><Button variant="outline" onClick={()=>{setRows([]);setFile(null);if(fileRef.current)fileRef.current.value=""}}>İptal</Button></div>
  </section>:null}
 </AppShell>;
}
