import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Database, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/personnel-field-settings")({head:()=>({meta:[{title:"Personel Alan Kullanımı — OkulOS"}]}),component:PersonnelFieldSettings});
type Field={field_key:string;display_name:string;source_headers:string[];default_enabled:boolean;default_module_keys:string[];effective_enabled:boolean;effective_module_keys:string[];institution_code:string|null;mode:"super_default"|"principal_override"};
const COMMON_MODULES=["personnel","schedule","norm","duty","payroll","guidance","exams","isg","discipline","committees","transport","reports"];
function PersonnelFieldSettings(){
 const [fields,setFields]=useState<Field[]>([]),[mode,setMode]=useState<Field["mode"]|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[custom,setCustom]=useState<Record<string,string>>({});
 async function load(){const {data,error}=await supabase.rpc("get_personnel_field_settings");if(error){setMessage("Bu ekran yalnız Süper Admin veya kurum müdürü tarafından kullanılabilir.");setMode(null);return;}const rows=(data??[]) as Field[];setFields(rows);setMode(rows[0]?.mode??null);}
 useEffect(()=>{void load()},[]);const moduleSet=useMemo(()=>new Set(COMMON_MODULES),[]);
 async function save(field:Field,nextEnabled=field.effective_enabled,nextModules=field.effective_module_keys){setBusy(field.field_key);setMessage(null);const fn=field.mode==="super_default"?"set_personnel_field_rule":"set_personnel_field_override";const {error}=await supabase.rpc(fn,{p_field_key:field.field_key,p_enabled:nextEnabled,p_module_keys:nextModules});setBusy(null);if(error){setMessage("Alan kuralı kaydedilemedi: "+error.message);return;}await load();}
 function toggleModule(field:Field,module:string,checked:boolean){const next=checked?[...new Set([...field.effective_module_keys,module])]:field.effective_module_keys.filter(x=>x!==module);void save(field,field.effective_enabled,next);}
 function addCustom(field:Field){const value=(custom[field.field_key]??"").trim().toLocaleLowerCase("tr-TR").replace(/\s+/g,"-");if(!value)return;setCustom(v=>({...v,[field.field_key]:""}));void save(field,field.effective_enabled,[...new Set([...field.effective_module_keys,value])]);}
 if(mode===null&&message)return <AppShell title="Personel Alan Kullanımı"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{message}</div></AppShell>;
 return <AppShell title={mode==="super_default"?"Personel Alan Varsayılanları":"Kurum Personel Alanları"} subtitle={mode==="super_default"?"Süper Admin yalnız sistemin varsayılan alan politikasını belirler":"Kurum müdürü, kendi kurumunda hangi alanların kullanılacağını belirler"}>
  <div className="grid gap-2 sm:grid-cols-2"><Link to={mode==="super_default"?"/super-admin":"/personnel-import"}><Button variant="outline" className="w-full">{mode==="super_default"?"Süper Admin":"Personel Veri İçe Aktarma"}</Button></Link><Link to="/management"><Button variant="outline" className="w-full">Yönetim Merkezi</Button></Link></div>
  <div className="mt-4 flex items-start gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950"><ShieldCheck className="mt-0.5 size-4 shrink-0"/><p>{mode==="super_default"?<><b>Varsayılan politika:</b> Buradaki seçimler yeni kurumların başlangıç ayarıdır. Süper Admin kurum personel detayını görmez ve kurumun son kararını değiştirmez.</>:<><b>Müdür kararı:</b> Sistem varsayılanını kurumunuz için değiştirebilirsiniz. Bu özel personel alanları öğretmen, Rehberlik/PDR öğretmeni veya müdür yardımcısına gösterilmez; seçimler modüllerin müdür ekranında kullanacağı alanları belirler.</>}</p></div>
  {message&&mode?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <div className="mt-4 space-y-3">{fields.map(field=><section key={field.field_key} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Database className="size-4 text-primary"/><h2 className="font-semibold">{field.display_name}</h2></div><p className="mt-1 text-[11px] text-muted-foreground">Anahtar: {field.field_key} · Kaynak: {field.source_headers.join(" / ")}{field.institution_code?` · Kurum: ${field.institution_code}`:""}</p>{field.mode==="principal_override"?<p className="mt-1 text-[11px] text-muted-foreground">Sistem varsayılanı: {field.default_enabled?"Açık":"Kapalı"} · {field.default_module_keys.join(", ")||"modül yok"}</p>:null}</div><label className="flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs"><input type="checkbox" checked={field.effective_enabled} disabled={busy===field.field_key} onChange={e=>void save(field,e.target.checked,field.effective_module_keys)}/>{field.mode==="super_default"?"Varsayılan açık":"Kurumda kullan"}</label></div>
    <div className="mt-3"><p className="mb-2 text-xs font-medium">Kullanabilecek modüller</p><div className="flex flex-wrap gap-1.5">{COMMON_MODULES.map(module=><label key={module} className={`rounded-full border px-2 py-1 text-[11px] ${field.effective_module_keys.includes(module)?"border-primary bg-primary-soft text-primary":"text-muted-foreground"}`}><input className="mr-1" type="checkbox" checked={field.effective_module_keys.includes(module)} disabled={busy===field.field_key||!field.effective_enabled} onChange={e=>toggleModule(field,module,e.target.checked)}/>{module}</label>)}{field.effective_module_keys.filter(x=>!moduleSet.has(x)).map(module=><button key={module} disabled={busy===field.field_key||!field.effective_enabled} onClick={()=>toggleModule(field,module,false)} className="rounded-full border border-primary bg-primary-soft px-2 py-1 text-[11px] text-primary">{module} ×</button>)}</div></div>
    <div className="mt-3 flex gap-2"><Input value={custom[field.field_key]??""} disabled={!field.effective_enabled} onChange={e=>setCustom(v=>({...v,[field.field_key]:e.target.value}))} placeholder="Yeni modül anahtarı"/><Button variant="secondary" disabled={!field.effective_enabled||busy===field.field_key} onClick={()=>addCustom(field)}>Modüle Ekle</Button></div>
  </section>)}{!fields.length&&!message?<div className="rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Henüz personel alanı keşfedilmedi.</div>:null}</div>
 </AppShell>;
}
