import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { FileSpreadsheet, RefreshCw, ShieldCheck, UploadCloud, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";
import { parseMebPersonnel, type PersonnelImportRow } from "@/lib/meb-data-import";

export const Route=createFileRoute("/personnel-admin")({head:()=>({meta:[{title:"Personel Yönetimi — OkulOS"}]}),component:PersonnelAdmin});
type Area={id:string;name:string};
type Person={user_id:string;full_name:string|null;email:string|null;role:string;teaching_area_id:string|null;permission_mode:"role"|"delegated";is_super_admin:boolean;updated_at:string};
type Registry={id:string;full_name:string;title:string|null;duty_title:string|null;teaching_area_raw:string|null;teaching_area_id:string|null;employment_status:string|null;system_role:string|null;linked_user_id:string|null;active:boolean};
type Responsibility={id:string;code:string;name:string;parent_title:string|null;applicable_school_types:string[];legal_basis:string|null};
type PersonResponsibility={id:string;personnel_id:string|null;user_id:string|null;responsibility_id:string;active:boolean};

function PersonnelAdmin(){
 const fileRef=useRef<HTMLInputElement>(null);const {can,any,loading:permissionLoading}=usePermissions();
 const [areas,setAreas]=useState<Area[]>([]),[people,setPeople]=useState<Person[]>([]),[registry,setRegistry]=useState<Registry[]>([]),[responsibilities,setResponsibilities]=useState<Responsibility[]>([]),[personResponsibilities,setPersonResponsibilities]=useState<PersonResponsibility[]>([]);
 const [busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[loadError,setLoadError]=useState<string|null>(null),[preview,setPreview]=useState<PersonnelImportRow[]>([]),[selectedFile,setSelectedFile]=useState<File|null>(null);
 const allowed=any("personnel.view","personnel.manage"),editable=can("personnel.manage");
 const load=useCallback(async()=>{if(permissionLoading||!allowed)return;setLoadError(null);const [a,p,r,c,pr]=await Promise.all([
   supabase.from("teaching_areas").select("id,name").eq("active",true).order("name"),supabase.rpc("get_personnel_admin_list"),
   supabase.from("personnel_registry").select("id,full_name,title,duty_title,teaching_area_raw,teaching_area_id,employment_status,system_role,linked_user_id,active").eq("active",true).order("full_name"),
   supabase.from("responsibility_catalog").select("id,code,name,parent_title,applicable_school_types,legal_basis").eq("active",true).order("sort_order"),
   supabase.from("personnel_responsibilities").select("id,personnel_id,user_id,responsibility_id,active").eq("active",true)
 ]);if(a.error||p.error||r.error||c.error||pr.error){setLoadError("Personel bilgileri yüklenemedi. Migration/yetki durumunu kontrol edin.");return;}setAreas((a.data??[]) as Area[]);setPeople((p.data??[]) as Person[]);setRegistry((r.data??[]) as Registry[]);setResponsibilities((c.data??[]) as Responsibility[]);setPersonResponsibilities((pr.data??[]) as PersonResponsibility[]);},[allowed,permissionLoading]);
 useEffect(()=>{void load()},[load]);
 async function setArea(userId:string,areaId:string){if(!editable)return;setBusy(userId);setMessage(null);const {error}=await supabase.rpc("set_personnel_teaching_area",{p_user_id:userId,p_teaching_area_id:areaId||null});setBusy(null);if(error){setMessage(error.message.includes("CANNOT_MODIFY_SUPER_ADMIN")?"Süper Admin hesabı değiştirilemez.":"Atama alanı güncellenemedi.");return;}setMessage("Atama alanı güncellendi.");await load()}
 async function setRegistryArea(id:string,areaId:string){if(!editable)return;setBusy(id);const {error}=await supabase.from("personnel_registry").update({teaching_area_id:areaId||null,updated_at:new Date().toISOString()}).eq("id",id);setBusy(null);setMessage(error?"Atama alanı güncellenemedi.":"Atama alanı güncellendi.");if(!error)await load()}
 async function toggleResponsibility(owner:{personnelId?:string;userId?:string},responsibilityId:string,checked:boolean){if(!editable)return;setBusy(owner.personnelId??owner.userId??"resp");if(checked){const {error}=await supabase.from("personnel_responsibilities").insert({personnel_id:owner.personnelId??null,user_id:owner.userId??null,responsibility_id:responsibilityId,active:true});if(error)setMessage("Alt görev eklenemedi.");}else{let q=supabase.from("personnel_responsibilities").update({active:false}).eq("responsibility_id",responsibilityId);q=owner.personnelId?q.eq("personnel_id",owner.personnelId):q.eq("user_id",owner.userId!);const {error}=await q;if(error)setMessage("Alt görev kaldırılamadı.");}setBusy(null);await load()}
 async function handleFile(file:File){if(!editable)return;setMessage(null);setPreview([]);setSelectedFile(file);try{const rows=await parseMebPersonnel(file);setPreview(rows);}catch(e){console.error(e);setSelectedFile(null);setMessage("MEB personel XLS/XLSX raporu tanınamadı.")}}
 async function importPersonnel(){if(!selectedFile||!preview.length)return;setBusy("import");const {data,error}=await supabase.rpc("import_personnel_registry",{p_file_name:selectedFile.name,p_rows:preview});setBusy(null);if(error){setMessage("Personel içe aktarılamadı.");return;}const result=Array.isArray(data)?data[0]:data;setMessage(`${result?.affected_personnel??preview.length} personel kaydı aktarıldı.`);setPreview([]);setSelectedFile(null);if(fileRef.current)fileRef.current.value="";await load()}
 async function deactivateRegistry(id:string){if(!editable||!confirm("Bu personel kaydı pasife alınsın mı?"))return;const {error}=await supabase.from("personnel_registry").update({active:false,updated_at:new Date().toISOString()}).eq("id",id);setMessage(error?"Personel pasife alınamadı.":"Personel pasife alındı.");if(!error)await load()}
 const selected=(owner:{personnelId?:string;userId?:string})=>new Set(personResponsibilities.filter(x=>x.active&&(owner.personnelId?x.personnel_id===owner.personnelId:x.user_id===owner.userId)).map(x=>x.responsibility_id));
 const roleLabel=(p:Registry)=>p.system_role==="principal"?"Müdür":p.system_role==="vice_principal"?"Müdür Yardımcısı":p.system_role==="teacher"?"Öğretmen":p.duty_title||p.title||"Diğer";
 const RespPicker=({owner}:{owner:{personnelId?:string;userId?:string}})=>{const set=selected(owner);return <div className="flex min-w-[280px] flex-wrap gap-1">{responsibilities.map(r=><label key={r.id} className={`inline-flex cursor-pointer items-center gap-1 rounded-full border px-2 py-1 text-[10px] ${set.has(r.id)?"border-primary bg-primary-soft text-primary":"bg-background text-muted-foreground"}`}><input type="checkbox" className="sr-only" checked={set.has(r.id)} disabled={!editable||busy===(owner.personnelId??owner.userId)} onChange={e=>void toggleResponsibility(owner,r.id,e.target.checked)}/>{r.name}</label>)}</div>};
 if(permissionLoading)return <AppShell title="Personel Yönetimi"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;
 if(!allowed)return <AppShell title="Personel Yönetimi"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Personel görüntüleme/yönetme görevi yok.</div></AppShell>;
 return <AppShell title="Personel Yönetimi" subtitle="Kayıtlı kullanıcılar · MEB personel aktarımı · birden fazla alt görev" action={<Users className="size-5"/>}>
   <div className="grid gap-2 sm:grid-cols-2"><Link to="/management"><Button variant="outline" className="w-full">Yönetim Merkezi</Button></Link>{can("permissions.manage")?<Link to="/settings-permissions"><Button variant="outline" className="w-full">Görev ve Yetki Atama</Button></Link>:<Link to="/norm-analysis"><Button variant="outline" className="w-full">Norm Analizi</Button></Link>}</div>
   {message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}{loadError?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{loadError}</div>:null}{!editable?<div className="mt-3 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950"><ShieldCheck className="size-4"/>Salt okunur.</div>:null}

   <Tabs defaultValue="registry" className="mt-4"><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="registry">MEB Personel Havuzu</TabsTrigger><TabsTrigger value="accounts">Kullanıcı Hesapları</TabsTrigger></TabsList>
    <TabsContent value="registry" className="mt-4 space-y-4">{editable?<><input ref={fileRef} className="hidden" type="file" accept=".xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>{const f=e.target.files?.[0];if(f)void handleFile(f)}}/><button type="button" onClick={()=>fileRef.current?.click()} className="w-full rounded-xl border-2 border-dashed bg-card p-6 text-center hover:border-primary/50"><UploadCloud className="mx-auto size-6 text-primary"/><p className="mt-2 text-sm font-medium">MEB Personel Özet Bilgiler XLS/XLSX yükle</p><p className="mt-1 text-xs text-muted-foreground">Ad Soyad · Ünvan/Görev · Atama Alanı/Branş · Kadro/Statü</p></button></>:null}
      {preview.length?<section className="rounded-xl border border-primary/20 bg-primary-soft p-4"><div className="flex gap-2"><FileSpreadsheet className="size-5 text-primary"/><div><b className="text-sm">{selectedFile?.name}</b><p className="text-xs text-muted-foreground">{preview.length} kayıt tanındı. Rehberlik/PDR dahil atama alanları ham haliyle korunur; müdür ve müdür yardımcılarının öğretmen branşı da kaybolmaz.</p></div></div><div className="mt-3 overflow-x-auto rounded-lg border bg-card"><table className="min-w-[700px] w-full text-xs"><thead><tr><th className="p-2 text-left">Ad Soyad</th><th className="p-2 text-left">Görev</th><th className="p-2 text-left">Atama Alanı</th><th className="p-2 text-left">Statü</th></tr></thead><tbody>{preview.slice(0,10).map((p,i)=><tr className="border-t" key={i}><td className="p-2 font-medium">{p.fullName}</td><td className="p-2">{p.dutyTitle||p.title}</td><td className="p-2">{p.teachingArea||"—"}</td><td className="p-2">{p.employmentStatus||"—"}</td></tr>)}</tbody></table></div><div className="mt-3 flex gap-2"><Button className="flex-1" disabled={busy==="import"} onClick={()=>void importPersonnel()}>Onayla ve Aktar</Button><Button variant="outline" onClick={()=>{setPreview([]);setSelectedFile(null)}}>İptal</Button></div></section>:null}
      <div className="overflow-x-auto rounded-xl border bg-card"><table className="min-w-[1100px] w-full text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Ad Soyad</th><th className="p-3 text-left">Ana Görev</th><th className="p-3 text-left">Atama Alanı / Branş</th><th className="p-3 text-left">Statü</th><th className="p-3 text-left">Alt Görevler / Sorumluluklar</th><th className="p-3">İşlem</th></tr></thead><tbody>{registry.map(p=><tr key={p.id} className="border-b align-top"><td className="p-3 font-medium">{p.full_name}</td><td className="p-3">{roleLabel(p)}</td><td className="p-3"><select className="h-9 min-w-56 rounded-md border bg-background px-2" value={p.teaching_area_id??""} disabled={!editable||busy===p.id} onChange={e=>void setRegistryArea(p.id,e.target.value)}><option value="">{p.teaching_area_raw||"Atama alanı tanımsız"}</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{p.teaching_area_raw?<p className="mt-1 text-[10px] text-muted-foreground">Ham: {p.teaching_area_raw}</p>:null}</td><td className="p-3 text-xs">{p.employment_status||"—"}</td><td className="p-3"><RespPicker owner={{personnelId:p.id}}/></td><td className="p-3 text-center">{editable?<Button variant="ghost" size="sm" className="text-destructive" onClick={()=>void deactivateRegistry(p.id)}>Pasife Al</Button>:null}</td></tr>)}{!registry.length?<tr><td colSpan={6} className="p-6 text-center text-muted-foreground">Henüz MEB personel havuzu yok.</td></tr>:null}</tbody></table></div>
    </TabsContent>
    <TabsContent value="accounts" className="mt-4"><div className="overflow-x-auto rounded-xl border bg-card"><table className="min-w-[1050px] w-full text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Ad Soyad</th><th className="p-3 text-left">E-posta</th><th className="p-3 text-left">Rol</th><th className="p-3 text-left">Atama Alanı</th><th className="p-3 text-left">Alt Görevler</th></tr></thead><tbody>{people.map(p=><tr key={p.user_id} className="border-b align-top"><td className="p-3 font-medium">{p.full_name??"—"}{p.is_super_admin?<span className="ml-2 rounded bg-amber-100 px-1.5 py-0.5 text-[10px] text-amber-800">Süper Admin</span>:null}</td><td className="p-3 text-muted-foreground">{p.email??"—"}</td><td className="p-3">{p.role}</td><td className="p-3"><select className="h-9 min-w-56 rounded-md border bg-background px-2" value={p.teaching_area_id??""} disabled={!editable||busy===p.user_id||(p.is_super_admin&&!can("permissions.manage"))} onChange={e=>void setArea(p.user_id,e.target.value)}><option value="">Atama alanı tanımsız</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></td><td className="p-3"><RespPicker owner={{userId:p.user_id}}/></td></tr>)}{!people.length?<tr><td colSpan={5} className="p-6 text-center text-muted-foreground">Kayıt olmuş personel yok.</td></tr>:null}</tbody></table></div></TabsContent>
   </Tabs>
   <Button variant="ghost" className="mt-4 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button><p className="mt-2 text-xs text-muted-foreground">Bir personelde aynı anda birden fazla alt görev seçilebilir. Ana görev ile mevzuat/kurum sorumlulukları ayrı tutulur.</p>
 </AppShell>;
}
