import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Crown, RefreshCw, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/personnel-admin")({head:()=>({meta:[{title:"Personel Yönetimi — OkulOS"}]}),component:PersonnelAdmin});
type Area={id:string;name:string};
type Person={user_id:string;full_name:string|null;email:string|null;role:string;teaching_area_id:string|null;is_super_admin:boolean;updated_at:string};
function PersonnelAdmin(){const [allowed,setAllowed]=useState<boolean|null>(null);const [areas,setAreas]=useState<Area[]>([]);const [people,setPeople]=useState<Person[]>([]);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{const {data:can}=await supabase.rpc("is_super_admin");setAllowed(Boolean(can));if(!can)return;const [a,p]=await Promise.all([supabase.from("teaching_areas").select("id,name").eq("active",true).order("name"),supabase.rpc("get_super_admin_registered_personnel")]);setAreas((a.data??[]) as Area[]);setPeople((p.data??[]) as Person[]);},[]);useEffect(()=>{void load();},[load]);
 async function setArea(userId:string,areaId:string){setBusy(userId);setMessage(null);const {error}=await supabase.rpc("super_admin_set_profile_teaching_area",{p_user_id:userId,p_teaching_area_id:areaId||null});setBusy(null);if(error)return setMessage("Personelin atama alanı güncellenemedi.");setMessage("Atama alanı güncellendi.");await load();}
 if(allowed===null)return <AppShell title="Personel Yönetimi"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;if(!allowed)return <AppShell title="Personel Yönetimi"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Bu ekran yalnız Süper Admin hesabına açıktır.</div></AppShell>;
 return <AppShell title="Kayıtlı Personel Yönetimi" subtitle="Hesabı açılmış personel · atama alanı" action={<Crown className="size-5 text-amber-500"/>}><div className="grid gap-2 sm:grid-cols-2"><Link to="/super-admin"><Button variant="outline" className="w-full">Süper Admin Merkezi</Button></Link><Link to="/norm-analysis"><Button variant="outline" className="w-full">Norm Analizi</Button></Link></div>{message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}<div className="mt-4 overflow-x-auto rounded-xl border bg-card"><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Ad Soyad</th><th className="p-3 text-left">E-posta</th><th className="p-3 text-left">Rol</th><th className="p-3 text-left">Atama Alanı</th><th className="p-3 text-left">Güncelleme</th></tr></thead><tbody>{people.map(p=><tr key={p.user_id} className="border-b"><td className="p-3 font-medium">{p.full_name??"—"}</td><td className="p-3 text-muted-foreground">{p.email??"—"}</td><td className="p-3">{p.role}</td><td className="p-3"><select className="h-9 min-w-56 rounded-md border bg-background px-2 text-sm" value={p.teaching_area_id??""} disabled={busy===p.user_id} onChange={e=>void setArea(p.user_id,e.target.value)}><option value="">Atama alanı tanımsız</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></td><td className="p-3 text-xs text-muted-foreground">{new Date(p.updated_at).toLocaleString("tr-TR")}</td></tr>)}{!people.length?<tr><td colSpan={5} className="p-6 text-center text-muted-foreground">Kayıt olmuş personel yok.</td></tr>:null}</tbody></table></div><Button variant="ghost" className="mt-4 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button><p className="mt-2 text-xs text-muted-foreground">Bu ekran ham T.C. Kimlik No göstermez. Atama alanı değişikliği yalnız Süper Admin yetkisiyle sunucu fonksiyonu üzerinden yapılır.</p></AppShell>}
