import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Building2, CheckCircle2, RefreshCw, Sparkles } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/room-assignment")({head:()=>({meta:[{title:"Derslik Atama — OkulOS"}]}),component:RoomAssignment});
type Scenario={id:string;generation_group:string;scenario_no:number;title:string;score:number;unplaced_count:number;row_count:number;generated_at:string};
type Status={total_rows:number;assigned_rows:number;unassigned_rows:number;room_issue_count:number;rooms_configured:boolean};
type Issue={id:string;scenario_id:string;reason:string;detail:string|null;schedule_scenario_rows?:{class_name:string;subject:string;weekday:number;period:number}|null};
function RoomAssignment(){const [scenarios,setScenarios]=useState<Scenario[]>([]);const [statuses,setStatuses]=useState<Record<string,Status>>({});const [issues,setIssues]=useState<Issue[]>([]);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{const {data}=await supabase.from("schedule_scenarios").select("id,generation_group,scenario_no,title,score,unplaced_count,row_count,generated_at").order("generated_at",{ascending:false}).limit(8);const next=(data??[]) as Scenario[];setScenarios(next);const statusPairs=await Promise.all(next.map(async s=>{const {data:d}=await supabase.rpc("get_scenario_room_status",{p_scenario_id:s.id});return [s.id,((d??[])[0]??{total_rows:0,assigned_rows:0,unassigned_rows:0,room_issue_count:0,rooms_configured:false}) as Status] as const;}));setStatuses(Object.fromEntries(statusPairs));if(next.length){const {data:i}=await supabase.from("schedule_room_assignment_issues").select("id,scenario_id,reason,detail,schedule_scenario_rows(class_name,subject,weekday,period)").in("scenario_id",next.map(x=>x.id));setIssues((i??[]) as unknown as Issue[]);}else setIssues([]);},[]);
 useEffect(()=>{void load();},[load]);
 async function assign(id:string){setBusy(id);setMessage(null);const {data,error}=await supabase.rpc("assign_classrooms_to_scenario",{p_scenario_id:id});setBusy(null);if(error)return setMessage(`Derslik ataması yapılamadı: ${error.message}`);const result=((data??[])[0]??{assigned_count:0,unassigned_count:0}) as {assigned_count:number;unassigned_count:number};setMessage(`${result.assigned_count} ders için derslik atandı; ${result.unassigned_count} ders uygun derslik bekliyor.`);await load();}
 return <AppShell title="Otomatik Derslik Atama" subtitle="Kapasite · derslik tipi · donanım · çakışma" action={<Building2 className="size-5"/>}><div className="grid gap-2 sm:grid-cols-3"><Link to="/schedule-solver"><Button variant="outline" className="w-full">Program Çözücü</Button></Link><Link to="/schedule"><Button variant="outline" className="w-full">Çalışma Programı</Button></Link><Link to="/management"><Button variant="outline" className="w-full">Yönetim Merkezi</Button></Link></div>{message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
 <div className="mt-4 grid gap-3 lg:grid-cols-2">{scenarios.map(s=>{const st=statuses[s.id];const si=issues.filter(x=>x.scenario_id===s.id);return <section key={s.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Senaryo {s.scenario_no}</h2><p className="mt-1 text-xs text-muted-foreground">Puan {s.score} · {s.row_count} ders · {s.unplaced_count} programda yerleşmeyen</p></div>{st?.rooms_configured&&st.room_issue_count===0&&st.unassigned_rows===0?<CheckCircle2 className="size-5 text-emerald-600"/>:null}</div>{st?<div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-muted/50 p-2"><p className="text-lg font-semibold">{st.assigned_rows}</p><p className="text-[10px] text-muted-foreground">Derslikli</p></div><div className="rounded-lg bg-muted/50 p-2"><p className="text-lg font-semibold">{st.unassigned_rows}</p><p className="text-[10px] text-muted-foreground">Dersliksiz</p></div><div className="rounded-lg bg-muted/50 p-2"><p className="text-lg font-semibold">{st.room_issue_count}</p><p className="text-[10px] text-muted-foreground">Sorun</p></div></div>:null}{st&&!st.rooms_configured?<p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800">Aktif derslik tanımı yok. Önce derslik envanterini girin.</p>:null}{si.length?<div className="mt-3 max-h-36 overflow-auto rounded-lg border border-red-200 bg-red-50 p-2 text-xs text-red-800">{si.map(x=><div key={x.id} className="py-1">{x.schedule_scenario_rows?.class_name} · {x.schedule_scenario_rows?.subject} · {x.detail??x.reason}</div>)}</div>:null}<Button className="mt-3 w-full gap-2" onClick={()=>void assign(s.id)} disabled={busy===s.id||!st?.rooms_configured}><Sparkles className="size-4"/>{busy===s.id?"Atanıyor…":"Derslikleri Otomatik Ata"}</Button></section>})}</div>{!scenarios.length?<div className="mt-4 rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Önce Program Çözücü ile senaryo üretin.</div>:null}<Button variant="ghost" className="mt-4 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></AppShell>}
