import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Columns3, RefreshCw, Sparkles, TriangleAlert } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";

type Scenario={id:string;generation_group:string;scenario_no:number;title:string;score:number;unplaced_count:number;row_count:number;status:string;generated_at:string};
type Explanation={scenario_id:string;profile_key:string|null;total_score:number;hard_issue_count:number;unplaced_count:number;classroom_issue_count:number;teacher_gap_score:number;teacher_balance_score:number;duty_score:number;pedagogy_score:number;workshop_score:number;course_repeat_score:number;positive_reasons:unknown;negative_reasons:unknown;updated_at:string|null};

export const Route=createFileRoute("/schedule-scenario-comparison")({head:()=>({meta:[{title:"Senaryo Karşılaştırma — OkulOS"}]}),component:ScenarioComparison});

function asStrings(value:unknown){if(!Array.isArray(value))return[];return value.map((item)=>typeof item==="string"?item:JSON.stringify(item)).filter(Boolean)}
function ScenarioComparison(){
 const {can}=usePermissions();const canGenerate=can("schedule.generate");
 const [scenarios,setScenarios]=useState<Scenario[]>([]),[explanations,setExplanations]=useState<Explanation[]>([]),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setMessage(null);const latest=await supabase.from("schedule_scenarios").select("generation_group,generated_at").order("generated_at",{ascending:false}).limit(1).maybeSingle();if(latest.error){setMessage(`Senaryolar okunamadı: ${latest.error.message}`);return;}if(!latest.data){setScenarios([]);setExplanations([]);return;}const s=await supabase.from("schedule_scenarios").select("id,generation_group,scenario_no,title,score,unplaced_count,row_count,status,generated_at").eq("generation_group",latest.data.generation_group).order("scenario_no");if(s.error){setMessage(`Senaryo grubu okunamadı: ${s.error.message}`);return;}const list=(s.data??[]) as Scenario[];setScenarios(list);if(!list.length){setExplanations([]);return;}const e=await supabase.from("schedule_scenario_explanations").select("scenario_id,profile_key,total_score,hard_issue_count,unplaced_count,classroom_issue_count,teacher_gap_score,teacher_balance_score,duty_score,pedagogy_score,workshop_score,course_repeat_score,positive_reasons,negative_reasons,updated_at").in("scenario_id",list.map((x)=>x.id));if(e.error){setMessage(`Senaryo açıklamaları okunamadı: ${e.error.message}`);setExplanations([]);return;}setExplanations((e.data??[]) as Explanation[])},[]);
 useEffect(()=>{void load()},[load]);
 const explanationMap=useMemo(()=>Object.fromEntries(explanations.map((x)=>[x.scenario_id,x])),[explanations]);
 const recommended=useMemo(()=>scenarios.filter((s)=>{const e=explanationMap[s.id];return e&&e.hard_issue_count===0&&e.unplaced_count===0&&e.classroom_issue_count===0}).sort((a,b)=>(explanationMap[a.id]?.total_score??a.score)-(explanationMap[b.id]?.total_score??b.score))[0]?.id??null,[scenarios,explanationMap]);
 async function refreshAll(){if(!canGenerate||!scenarios.length)return;setBusy(true);setMessage(null);for(const s of scenarios){const {error}=await supabase.rpc("refresh_schedule_scenario_explanation_v1",{p_scenario_id:s.id});if(error){setMessage(`Açıklama yenileme durdu: ${error.message}`);setBusy(false);return;}}setBusy(false);setMessage("Tüm senaryo açıklamaları güncellendi.");await load()}
 return <AppShell title="Senaryo Karşılaştırma" subtitle="Aynı üretim grubunu hard güvenlik, öğretmen, öğrenci, nöbet ve atölye kalitesiyle yan yana karşılaştır">
  <div className="mb-4 flex flex-wrap gap-2"><Link to="/timetable" className="rounded-md border px-3 py-2 text-sm">← Ders Programı</Link><Link to="/schedule-solver" className="rounded-md border px-3 py-2 text-sm">Program Üret</Link>{canGenerate?<Button variant="outline" disabled={busy||!scenarios.length} onClick={()=>void refreshAll()}><RefreshCw className="mr-2 size-4"/>{busy?"Yenileniyor…":"Açıklamaları Yenile"}</Button>:null}</div>
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  {!scenarios.length?<div className="rounded-2xl border border-dashed p-10 text-center"><Columns3 className="mx-auto size-8 text-muted-foreground"/><h2 className="mt-3 font-semibold">Karşılaştırılacak senaryo yok</h2><p className="mt-1 text-sm text-muted-foreground">Önce Program Üret ekranından bir senaryo grubu oluşturun.</p></div>:<div className="grid gap-4 xl:grid-cols-4">{scenarios.map((s)=>{const e=explanationMap[s.id];const valid=e?e.hard_issue_count===0&&e.unplaced_count===0&&e.classroom_issue_count===0:false;const positives=asStrings(e?.positive_reasons);const negatives=asStrings(e?.negative_reasons);return <article key={s.id} className={`rounded-2xl border bg-card p-4 ${recommended===s.id?"border-emerald-500 ring-1 ring-emerald-500/30":""}`}><div className="flex items-start justify-between gap-2"><div><p className="text-xs text-muted-foreground">Senaryo {s.scenario_no}</p><h2 className="font-semibold">{s.title}</h2></div>{recommended===s.id?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-800"><Sparkles className="size-3"/>ÖNERİLEN</span>:valid?<CheckCircle2 className="size-5 text-emerald-600"/>:<TriangleAlert className="size-5 text-amber-600"/>}</div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Metric label="Toplam skor" value={e?.total_score??s.score}/><Metric label="Hard hata" value={e?.hard_issue_count??"—"}/><Metric label="Yerleşmeyen" value={e?.unplaced_count??s.unplaced_count}/><Metric label="Derslik sorunu" value={e?.classroom_issue_count??"—"}/><Metric label="Öğretmen boşluğu" value={e?.teacher_gap_score??"—"}/><Metric label="Öğretmen dengesi" value={e?.teacher_balance_score??"—"}/><Metric label="Nöbet" value={e?.duty_score??"—"}/><Metric label="Pedagoji" value={e?.pedagogy_score??"—"}/><Metric label="Atölye" value={e?.workshop_score??"—"}/><Metric label="Ders tekrarı" value={e?.course_repeat_score??"—"}/></div>{e?<><div className="mt-4"><p className="text-xs font-semibold text-emerald-700">Olumlu</p>{positives.length?<ul className="mt-1 space-y-1 text-xs text-muted-foreground">{positives.slice(0,5).map((x,i)=><li key={i}>+ {x}</li>)}</ul>:<p className="mt-1 text-xs text-muted-foreground">Belirgin artı gerekçe kaydedilmemiş.</p>}</div><div className="mt-3"><p className="text-xs font-semibold text-amber-700">Ödün / Sorun</p>{negatives.length?<ul className="mt-1 space-y-1 text-xs text-muted-foreground">{negatives.slice(0,5).map((x,i)=><li key={i}>− {x}</li>)}</ul>:<p className="mt-1 text-xs text-muted-foreground">Belirgin negatif gerekçe yok.</p>}</div></>:<div className="mt-4 rounded-lg border border-dashed p-3 text-xs text-muted-foreground">Açıklama henüz üretilmemiş. {canGenerate?"Açıklamaları Yenile ile hesaplayabilirsiniz.":"Program üretme yetkili kullanıcı açıklamayı yenileyebilir."}</div>}</article>})}</div>}
 </AppShell>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-lg border bg-muted/20 p-2"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-0.5 font-semibold">{value}</p></div>}
