import {createFileRoute} from "@tanstack/react-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {CheckCircle2,ClipboardCheck,Printer,RefreshCw,Send,ShieldCheck,Trash2,Wand2} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {usePermissions} from "@/lib/permissions";
import {solveSupervisionSchedule,type SupervisionProblem,type SupervisionResult} from "@/lib/schedule-supervision-solver";
import {supabase} from "@/lib/supabase";

export const Route=createFileRoute("/schedule-supervision")({head:()=>({meta:[{title:"Gözetim Planı — OkulOS"}]}),component:ScheduleSupervision});
type NamedTeacher={id:string;name:string|null;min_load:number;max_load:number};
type ProblemPayload=Omit<SupervisionProblem,"teachers">&{signature:string;teachers:NamedTeacher[]};
type Requirement={id:string;label:string;weekday:number;period:number;required_count:number};
type Plan={id:string;title:string;seed:number;status:string;basis_signature:string;hard_score:number;unplaced_score:number;medium_score:number;soft_score:number;created_at:string;approved_at:string|null;published_at:string|null};
type PlanRow={id:string;plan_id:string;requirement_id:string;teacher_id:string;weekday:number;period:number};
const days=["","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];

function ScheduleSupervision(){
 const {can,any,loading:permissionLoading}=usePermissions(),mayView=any("duty.view","duty.manage","duty.generate","duty.lock"),mayManage=can("duty.manage"),mayGenerate=can("duty.generate"),mayApprove=can("duty.lock");
 const [problem,setProblem]=useState<ProblemPayload|null>(null),[requirements,setRequirements]=useState<Requirement[]>([]),[plans,setPlans]=useState<Plan[]>([]),[rows,setRows]=useState<PlanRow[]>([]),[selected,setSelected]=useState<string|null>(null),[preview,setPreview]=useState<SupervisionResult|null>(null);
 const [label,setLabel]=useState(""),[weekday,setWeekday]=useState(1),[period,setPeriod]=useState(1),[requiredCount,setRequiredCount]=useState(1),[title,setTitle]=useState("Haftalık gözetim planı"),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{if(permissionLoading||!mayView)return;setBusy(true);const [p,r,pl]=await Promise.all([supabase.rpc("get_schedule_supervision_problem_v1"),supabase.from("schedule_supervision_requirements").select("id,label,weekday,period,required_count").eq("active",true).order("weekday").order("period"),supabase.from("schedule_supervision_plans").select("id,title,seed,status,basis_signature,hard_score,unplaced_score,medium_score,soft_score,created_at,approved_at,published_at").order("created_at",{ascending:false}).limit(30)]);setBusy(false);const error=p.error??r.error??pl.error;if(error){setMessage(`Gözetim verisi okunamadı: ${error.message}`);return}setProblem(p.data as ProblemPayload);setRequirements((r.data??[]) as Requirement[]);const next=(pl.data??[]) as Plan[];setPlans(next);setSelected(old=>old&&next.some(x=>x.id===old)?old:next[0]?.id??null)},[mayView,permissionLoading]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!selected){setRows([]);return}void(async()=>{const q=await supabase.from("schedule_supervision_plan_rows").select("id,plan_id,requirement_id,teacher_id,weekday,period").eq("plan_id",selected).order("weekday").order("period");if(q.error)setMessage(`Plan satırları okunamadı: ${q.error.message}`);else setRows((q.data??[]) as PlanRow[])})()},[selected]);
 const teacherNames=useMemo(()=>Object.fromEntries((problem?.teachers??[]).map(x=>[x.id,x.name??"Öğretmen"])),[problem]),requirementNames=useMemo(()=>Object.fromEntries(requirements.map(x=>[x.id,x.label])),[requirements]);
 const activePlan=plans.find(x=>x.id===selected)??null;
 const stale=Boolean(activePlan&&problem&&activePlan.basis_signature!==problem.signature);
 async function addRequirement(){if(!mayManage||!label.trim())return;setBusy(true);const q=await supabase.from("schedule_supervision_requirements").insert({label:label.trim(),weekday,period,required_count:requiredCount});setBusy(false);if(q.error)return setMessage(`İhtiyaç kaydedilemedi: ${q.error.message}`);setLabel("");setMessage("Gözetim ihtiyacı kaydedildi.");await load()}
 async function removeRequirement(id:string){if(!mayManage)return;const q=await supabase.from("schedule_supervision_requirements").update({active:false}).eq("id",id);if(q.error)return setMessage(`İhtiyaç kaldırılamadı: ${q.error.message}`);await load()}
 function makePreview(){if(!problem)return;if(!problem.positions.length||!problem.teachers.length){setMessage("Önce en az bir ihtiyaç ve öğretmen bulunmalıdır.");return}const result=solveSupervisionSchedule({...problem,seed:Date.now()&0x7fffffff});setPreview(result);setMessage(result.complete?"Önizleme hazır; henüz yürürlükte değil.":`Önizleme tamamlanamadı: ${result.score.hard} HARD, ${result.score.unplaced} yerleşmeyen.`)}
 async function persistPreview(){if(!preview||!mayGenerate)return;setBusy(true);const q=await supabase.rpc("create_schedule_supervision_plan_v1",{p_title:title,p_seed:preview.seed,p_assignments:preview.assignments.map(x=>({position_id:x.position_id,teacher_id:x.teacher_id,weekday:x.weekday,period:x.period})),p_score:preview.score});setBusy(false);if(q.error)return setMessage(`Taslak kaydedilemedi: ${q.error.message}`);setPreview(null);setMessage("Taslak sunucuda canlı çizelgeyle yeniden doğrulanıp kaydedildi.");await load();setSelected(String(q.data))}
 async function decide(approve:boolean){if(!selected||!mayApprove)return;setBusy(true);const q=await supabase.rpc("decide_schedule_supervision_plan_v1",{p_plan_id:selected,p_approve:approve,p_note:approve?"İdari kontrol tamamlandı":"İdari incelemede reddedildi"});setBusy(false);if(q.error)return setMessage(`Karar uygulanamadı: ${q.error.message}`);setMessage(approve?"Plan idari olarak onaylandı; henüz yayımlanmadı.":"Plan reddedildi.");await load()}
 async function publish(){if(!selected||!mayApprove)return;setBusy(true);const q=await supabase.rpc("publish_schedule_supervision_plan_v1",{p_plan_id:selected});setBusy(false);if(q.error)return setMessage(`Plan yayımlanamadı: ${q.error.message}`);setMessage("Onaylı plan son canlı ders doluluğuyla doğrulanıp yürürlüğe alındı.");await load()}
 if(!permissionLoading&&!mayView)return <AppShell title="Gözetim Planı"><div className="rounded-xl border p-5 text-sm">Bu ekran için nöbet görüntüleme yetkisi gerekir.</div></AppShell>;
 return <AppShell title="Gözetim & Alan Nöbeti" subtitle="Canlı ders doluluğu → solver önizlemesi → idari onay → yayın → rapor">
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <section className="rounded-xl border bg-card p-4 print:hidden"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Gözetim ihtiyaçları</h2><p className="text-xs text-muted-foreground">Her konum ve ders aralığı için gerekli öğretmen sayısı.</p></div><Button variant="outline" onClick={()=>void load()} disabled={busy} className="gap-2"><RefreshCw className="size-4"/>Yenile</Button></div>
   {mayManage?<div className="mt-4 grid gap-2 md:grid-cols-5"><div><Label>Konum</Label><Input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Bahçe / 1. kat"/></div><div><Label>Gün</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{days.slice(1).map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select></div><div><Label>Aralık</Label><Input type="number" min={1} max={24} value={period} onChange={e=>setPeriod(Number(e.target.value))}/></div><div><Label>Kişi</Label><Input type="number" min={1} max={20} value={requiredCount} onChange={e=>setRequiredCount(Number(e.target.value))}/></div><div className="flex items-end"><Button className="w-full" onClick={()=>void addRequirement()} disabled={busy}>Ekle</Button></div></div>:null}
   <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{requirements.map(r=><div key={r.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span><b>{r.label}</b><br/><span className="text-xs text-muted-foreground">{days[r.weekday]} · {r.period}. aralık · {r.required_count} kişi</span></span>{mayManage?<Button size="icon" variant="ghost" aria-label="İhtiyacı kaldır" onClick={()=>void removeRequirement(r.id)}><Trash2 className="size-4"/></Button>:null}</div>)}{!requirements.length?<p className="text-sm text-muted-foreground">Henüz gözetim ihtiyacı tanımlanmadı.</p>:null}</div>
  </section>
  <section className="mt-4 rounded-xl border bg-card p-4 print:hidden"><h2 className="flex items-center gap-2 font-semibold"><Wand2 className="size-4"/>Canlı önizleme</h2><p className="mt-1 text-xs text-muted-foreground">Ana ve eş öğretmen dersleri ile uygunsuzluklar HARD doluluk olarak solver’a verilir. Tarayıcı sonucu sunucuda tekrar doğrulanır.</p><div className="mt-3 flex flex-wrap gap-2"><Input className="max-w-sm" value={title} onChange={e=>setTitle(e.target.value)}/><Button onClick={makePreview} disabled={!mayGenerate||busy}>Önizleme üret</Button>{preview?<Button variant="secondary" onClick={()=>void persistPreview()} disabled={!mayGenerate||busy}>Sunucuya taslak kaydet</Button>:null}</div>{preview?<div className={`mt-3 rounded-lg border p-3 text-sm ${preview.complete?"border-emerald-300 bg-emerald-50 text-emerald-900":"border-amber-300 bg-amber-50 text-amber-900"}`}>HARD {preview.score.hard} · Yerleşmeyen {preview.score.unplaced} · MEDIUM {preview.score.medium} · SOFT {preview.score.soft} · {preview.assignments.length} atama</div>:null}</section>
  <section className="mt-4 grid gap-4 lg:grid-cols-[320px_1fr]"><div className="rounded-xl border bg-card p-4 print:hidden"><h2 className="font-semibold">Taslak ve karar geçmişi</h2><div className="mt-3 space-y-2">{plans.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`w-full rounded-lg border p-3 text-left text-sm ${selected===p.id?"border-primary bg-primary/5":""}`}><b>{p.title}</b><br/><span className="text-xs text-muted-foreground">{p.status} · H {p.hard_score} / Y {p.unplaced_score} / M {p.medium_score} / S {p.soft_score}</span></button>)}</div></div>
   <div className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><ClipboardCheck className="size-4"/>Plan raporu</h2><p className="text-xs text-muted-foreground">{activePlan?`${activePlan.title} · ${activePlan.status}`:"Plan seçin"}</p></div><div className="flex gap-2 print:hidden">{activePlan?.status==="DRAFT"&&mayApprove?<><Button variant="outline" onClick={()=>void decide(false)}>Reddet</Button><Button disabled={stale} onClick={()=>void decide(true)} className="gap-2"><ShieldCheck className="size-4"/>İdari onay</Button></>:null}{activePlan?.status==="APPROVED"&&mayApprove?<Button disabled={stale} onClick={()=>void publish()} className="gap-2"><Send className="size-4"/>Yayımla</Button>:null}<Button variant="outline" onClick={()=>window.print()} className="gap-2"><Printer className="size-4"/>Yazdır</Button></div></div>
    {stale?<p className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Canlı ders veya gözetim verisi bu taslaktan sonra değişti. Plan yeniden üretilmeden onaylanamaz/yayımlanamaz.</p>:null}
    {activePlan?<div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs"><div className="rounded border p-2"><b>{activePlan.hard_score}</b><br/>HARD</div><div className="rounded border p-2"><b>{activePlan.unplaced_score}</b><br/>Yerleşmeyen</div><div className="rounded border p-2"><b>{activePlan.medium_score}</b><br/>MEDIUM</div><div className="rounded border p-2"><b>{activePlan.soft_score}</b><br/>SOFT</div></div>:null}
    <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Gün</th><th className="p-2">Aralık</th><th className="p-2">Konum</th><th className="p-2">Öğretmen</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-2">{days[r.weekday]}</td><td className="p-2">{r.period}</td><td className="p-2">{requirementNames[r.requirement_id]??"—"}</td><td className="p-2">{teacherNames[r.teacher_id]??r.teacher_id}</td></tr>)}</tbody></table>{activePlan?.status==="PUBLISHED"?<p className="mt-4 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 className="size-4"/>Bu plan idari onayla yürürlüktedir.</p>:null}</div>
   </div>
  </section>
 </AppShell>
}
