import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-validation")({head:()=>({meta:[{title:"Program Doğrulama — OkulOS"}]}),component:ValidationCenter});
type Item={severity:"error"|"warning";code:string;affected_count:number;detail:string};
const labels:Record<string,string>={UNLINKED_SCHEDULE_ROWS:"Müfredat bağı olmayan satırlar",SEMANTIC_LINK_MISMATCH:"Müfredat/öğretmen bağlantı hatası",ASSIGNMENT_HOURS_MISMATCH:"Öğretmen-ders saatleri",REQUIREMENT_HOURS_MISMATCH:"Sınıf-ders haftalık saati",CLASS_WEEKLY_HOURS_MISMATCH:"Sınıf toplam haftalık saati",TTKB_PERMISSION_PROBLEM:"TTKB alan-ders uygunluğu",TIME_PROFILE_VIOLATION:"Okul zaman şablonu",TEACHER_DOUBLE_BOOKING:"Öğretmen çakışması",CLASS_OR_STUDENT_GROUP_CONFLICT:"Sınıf/öğrenci grubu çakışması",CLASSROOM_REQUIRED:"Derslik ataması",CLASSROOM_DOUBLE_BOOKING:"Derslik çakışması",TEACHER_DAILY_LIMIT:"Öğretmen günlük limiti",TEACHER_WORKING_DAYS:"Öğretmen çalışma günleri",COURSE_TIME_RULE:"Ders gün/saat kuralı",COURSE_MINIMUM_SPREAD:"Dersin haftaya yayılımı",COURSE_BLOCK_PATTERN:"Blok ders deseni",SYNC_GROUP_HOURS:"Eşzamanlı grup saatleri",SYNC_GROUP_SLOT_MISMATCH:"Eşzamanlı grup saat eşleşmesi",SOFT_PREFERENCE_PENALTY:"Tercih kalite cezası"};
function ValidationCenter(){const [items,setItems]=useState<Item[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const load=useCallback(async()=>{setBusy(true);const {data,error}=await supabase.rpc("get_schedule_integrity_report");setBusy(false);if(error)return setMessage(error.message);setItems((data??[]) as Item[])},[]);useEffect(()=>{void load()},[load]);const errors=useMemo(()=>items.filter(x=>x.severity==="error"),[items]);const warnings=useMemo(()=>items.filter(x=>x.severity==="warning"),[items]);return <AppShell title="Program Doğrulama Merkezi" subtitle="Yayın öncesi sıfır hata kapısı" action={<ShieldCheck className="size-5"/>}>
 <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Hard constraint</p><p className={errors.length?"mt-1 text-2xl font-bold text-red-600":"mt-1 text-2xl font-bold text-emerald-600"}>{errors.reduce((n,x)=>n+x.affected_count,0)}</p></div><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Soft kalite uyarısı</p><p className="mt-1 text-2xl font-bold">{warnings.reduce((n,x)=>n+x.affected_count,0)}</p></div><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Yayın durumu</p><p className={errors.length?"mt-1 font-semibold text-red-600":"mt-1 font-semibold text-emerald-600"}>{errors.length?"BLOKE":"YAYINA HAZIR"}</p></div></div>
 {!items.length?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="mr-2 inline size-5"/><b>Tüm zorunlu kontroller geçti.</b> Program müfredat, öğretmen, TTKB, zaman, grup, blok ve derslik bütünlüğü açısından yayına hazır.</div>:<div className="mt-4 space-y-2">{items.map(x=><div key={x.code} className={x.severity==="error"?"rounded-xl border border-red-200 bg-red-50 p-4":"rounded-xl border border-amber-200 bg-amber-50 p-4"}><div className="flex items-start gap-3"><AlertTriangle className={x.severity==="error"?"mt-0.5 size-5 text-red-600":"mt-0.5 size-5 text-amber-600"}/><div><div className="font-semibold">{labels[x.code]??x.code} · {x.affected_count}</div><p className="mt-1 text-sm text-muted-foreground">{x.detail}</p><code className="mt-2 block text-[11px]">{x.code}</code></div></div></div>)}</div>}
 {message?<p className="mt-3 rounded-lg bg-muted p-3 text-sm">{message}</p>:null}<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()} disabled={busy} className="gap-2"><RefreshCw className="size-4"/>Yeniden Kontrol Et</Button><Link to="/schedule"><Button variant="outline">Programa Dön</Button></Link><Link to="/schedule-rules"><Button variant="outline">Program Kuralları</Button></Link><Link to="/schedule-archive"><Button disabled={errors.length>0}>Yayın / Arşiv</Button></Link></div>
 </AppShell>}
