import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, RefreshCw, SearchCheck, WandSparkles } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { buildScheduleConstraintPressureAdvisor } from "@/lib/schedule-constraint-pressure-advisor";

export const Route=createFileRoute("/schedule-preparation")({head:()=>({meta:[{title:"Program Hazırlık Kontrolü — OkulOS"}]}),component:Preparation});
type Item={category:string;code:string;status:string;affected_count:number;detail:string};
type Metrics={lockedCount:number;unavailabilityCount:number;softPreferenceCount:number};
const target:Record<string,string>={
 ACTIVE_TIME_PROFILE:"/schedule-rules",CURRICULUM_NOT_READY:"/curriculum",TEACHER_CONSTRAINT_ROW_MISSING:"/schedule-rules",
 TEACHER_ASSIGNED_HOURS_EXCEED_WEEKLY_LIMIT:"/schedule-rules",TEACHER_ASSIGNED_HOURS_EXCEED_DAY_CAPACITY:"/schedule-rules",
 LOCKED_ROW_UNLINKED:"/schedule",LOCKED_ROW_SEMANTIC_MISMATCH:"/schedule",LOCKED_TEACHER_UNAVAILABLE:"/schedule-rules",LOCKED_HOURS_EXCEED_ASSIGNMENT:"/schedule",
 SYNC_GROUP_EMPTY:"/schedule-rules",SYNC_MEMBER_BLOCK_LENGTH_MISMATCH:"/schedule-rules",SYNC_SUBGROUP_MISMATCH:"/schedule-rules",SYNC_SUBGROUP_HAS_NO_STUDENTS:"/schedule-rules",SYNC_SUBGROUP_STUDENT_OVERLAP:"/schedule-rules",
 QURAN_WEEKLY_SYNC_INCOMPLETE:"/quran-groups",ROOM_RULE_HAS_NO_MATCHING_ROOM:"/classrooms",BLOCK_PATTERN_ASSIGNMENT_MISMATCH:"/schedule-rules",
 TIME_PROFILE_CONFIGURATION_INVALID:"/schedule-rules",TEACHER_CONSTRAINT_CONFIGURATION_INVALID:"/schedule-rules",COURSE_RULE_CONFIGURATION_INVALID:"/schedule-rules",
 SYNC_GROUP_REQUIRES_TWO_MEMBERS:"/schedule-rules",SYNC_GROUP_CLASS_MISMATCH:"/schedule-rules",SYNC_TOTAL_HOURS_EXCEED_ASSIGNMENT:"/schedule-rules"
};
function Preparation(){const [items,setItems]=useState<Item[]>([]);const [metrics,setMetrics]=useState<Metrics>({lockedCount:0,unavailabilityCount:0,softPreferenceCount:0});const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [loadError,setLoadError]=useState<string|null>(null);const [loaded,setLoaded]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setLoaded(false);const [r,l,u,p]=await Promise.all([supabase.rpc("get_schedule_preparation_readiness"),supabase.from("teacher_schedule").select("id",{count:"exact",head:true}).eq("active",true).eq("locked",true),supabase.from("teacher_unavailability").select("id",{count:"exact",head:true}).eq("active",true),supabase.from("teacher_schedule_preferences").select("id",{count:"exact",head:true}).eq("active",true)]);setBusy(false);if(r.error){setItems([]);setLoadError(r.error.message);setLoaded(true);return}setLoadError(null);setItems((r.data??[]) as Item[]);setMetrics({lockedCount:l.error?0:l.count??0,unavailabilityCount:u.error?0:u.count??0,softPreferenceCount:p.error?0:p.count??0});setLoaded(true)},[]);useEffect(()=>{void load()},[load]);
 async function syncQuran(){setBusy(true);const {data,error}=await supabase.rpc("sync_all_quran_plans_to_timetable");setBusy(false);const result=Array.isArray(data)?data[0]:data;setMessage(error?error.message:`Kur’an planı senkronu tamamlandı. Başarılı: ${result?.synced??0}, eksik veri nedeniyle tamamlanamayan: ${result?.failed??0}.`);await load()}
 const ready=loaded&&!loadError&&items.length===0,advisor=useMemo(()=>buildScheduleConstraintPressureAdvisor(items,metrics),[items,metrics]);
 return <AppShell title="Program Hazırlık Kontrolü" subtitle="Canonical doğrulama + constraint pressure advisor" action={<WandSparkles className="size-5"/>}>
 {!loaded||busy?<div className="rounded-xl border bg-muted/30 p-5 text-sm text-muted-foreground">Program hazırlık kontrolleri çalıştırılıyor…</div>:loadError?<div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800"><AlertTriangle className="mr-2 inline size-5"/><b>Hazırlık doğrulaması çalıştırılamadı.</b><p className="mt-2 text-sm">{loadError}</p><p className="mt-2 text-xs">Kontrol tamamlanmadan çözücü çalıştırılamaz.</p></div>:ready?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="mr-2 inline size-5"/><b>Hazırlık tamam.</b> Ders programı çözücüsü çalıştırılabilir.</div>:<div className="space-y-3">{items.map(x=><div key={x.code} className="rounded-xl border border-red-200 bg-red-50 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 text-red-600"/><div className="flex-1"><p className="font-semibold">{x.category} · {x.code} · {x.affected_count}</p><p className="mt-1 text-sm text-red-800">{x.detail}</p>{target[x.code]?<Link to={target[x.code] as never}><Button size="sm" variant="outline" className="mt-3">Eksik Veriyi Düzenle</Button></Link>:null}</div></div></div>)}</div>}
 {loaded&&!loadError?<section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-start gap-3"><SearchCheck className="mt-0.5 size-5 text-primary"/><div><h2 className="font-semibold">Constraint Pressure Advisor</h2><p className="mt-1 text-sm text-muted-foreground">aSc Extended Tests yaklaşımındaki “darboğazı küçült” fikrinin Okulos karşılığı. Canonical HARD kurallar değiştirilmeden hangi katmanın önce ele alınacağını sıralar.</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="rounded-lg border p-3 text-sm"><b>{advisor.blockerFamilies}</b><p className="text-muted-foreground">bloklayan kural ailesi</p></div><div className="rounded-lg border p-3 text-sm"><b>{metrics.lockedCount}</b><p className="text-muted-foreground">kilitli manuel ders</p></div><div className="rounded-lg border p-3 text-sm"><b>{metrics.softPreferenceCount}</b><p className="text-muted-foreground">aktif SOFT tercih</p></div></div>{advisor.findings.length?<div className="mt-3 space-y-2">{advisor.findings.slice(0,6).map((f,i)=><div key={`${f.family}-${i}`} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm">{i+1}. {f.title}</b><span className="rounded-full bg-muted px-2 py-1 text-xs">{f.severity} · {f.affected}</span></div><p className="mt-1 text-xs text-muted-foreground">{f.explanation}</p><p className="mt-2 text-sm">{f.action}</p></div>)}</div>:<p className="mt-3 text-sm text-muted-foreground">Canonical hazırlık engeli yok. Kilitler ve SOFT tercihler yalnız kalite/aralık baskısı olarak izleniyor.</p>}<p className="mt-3 rounded-lg bg-muted/40 p-3 text-xs"><b>Güvenlik politikası:</b> {advisor.policy}</p></section>:null}
 {message?<p className="mt-3 rounded-lg bg-muted p-3 text-sm">{message}</p>:null}<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()} disabled={busy} className="gap-2"><RefreshCw className="size-4"/>Yeniden Kontrol Et</Button><Button variant="outline" onClick={()=>void syncQuran()} disabled={busy}>Kur’an Planlarını Senkronize Et</Button><Link to="/schedule-rules"><Button variant="outline">Program Kuralları</Button></Link><Link to="/schedule-solver"><Button disabled={!ready}>Çözücüye Geç</Button></Link></div></AppShell>}
