import {createFileRoute,Link} from "@tanstack/react-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ArrowRight,CheckCircle2,GitBranch,RefreshCw,ShieldCheck,Sparkles} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {Label} from "@/components/ui/label";
import {supabase} from "@/lib/supabase";
import {applyEjectionChain,suggestDeepEjectionChains,type EjectionCandidate} from "@/lib/schedule-ejection-chain";

export const Route=createFileRoute("/schedule-ejection-chain")({head:()=>({meta:[{title:"Derin Ejection-Chain — OkulOS"}]}),component:EjectionChainCenter});
type Row={id:string;teacher_id:string;class_id:string|null;teacher_assignment_id:string|null;class_name:string;subject:string;weekday:number;period:number;locked:boolean;profiles?:{full_name:string|null}|null};
type Profile={teaching_days:number[];periods_per_day:number};
const day:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};
function EjectionChainCenter(){const[rows,setRows]=useState<Row[]>([]),[profile,setProfile]=useState<Profile>({teaching_days:[1,2,3,4,5],periods_per_day:8}),[sourceId,setSourceId]=useState(""),[weekday,setWeekday]=useState(1),[period,setPeriod]=useState(1),[depth,setDepth]=useState(5),[items,setItems]=useState<EjectionCandidate[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const[r,p]=await Promise.all([supabase.from("teacher_schedule").select("id,teacher_id,class_id,teacher_assignment_id,class_name,subject,weekday,period,locked,profiles!teacher_schedule_teacher_id_fkey(full_name)").eq("active",true).order("class_name").order("subject"),supabase.rpc("get_active_schedule_time_profile")]);if(r.error||p.error){setError((r.error??p.error)?.message??"Program verisi okunamadı");return}setRows((r.data??[]) as unknown as Row[]);if(p.data){const x=p.data as Profile;setProfile(x);setWeekday(w=>x.teaching_days.includes(w)?w:(x.teaching_days[0]??1));setPeriod(v=>Math.min(v,x.periods_per_day))}},[]);useEffect(()=>{void load()},[load]);
 const source=useMemo(()=>rows.find(x=>x.id===sourceId)??null,[rows,sourceId]);
 async function search(){if(!sourceId)return setError("Önce taşınacak dersi seçin.");setBusy(true);setError(null);setMessage(null);setItems([]);try{const out=await suggestDeepEjectionChains({scheduleId:sourceId,weekday,period,maxDepth:depth,limit:8,maxExpanded:140});setItems(out);setMessage(out.length?`${out.length} canonical doğrulanmış zincir bulundu. En iyi seçenek MEDIUM → SOFT → hareket maliyeti sırasıyla üstte.`:"Bu hedef için depth sınırı içinde güvenli zincir bulunamadı.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function apply(c:EjectionCandidate){setBusy(true);setError(null);try{await applyEjectionChain(c);setMessage(`${c.depth} halkalı zincir atomik uygulandı. Geri dönüş noktası otomatik oluşturuldu.`);setItems([]);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <AppShell title="Derin Ejection-Chain" subtitle="Depth 3–5 · blok atomik · cycle-safe · canonical HARD preview · öğrenci/relation/kalite sıralaması" action={<GitBranch className="size-5"/>}>
  <div className="flex flex-wrap gap-2"><Link to="/schedule"><Button variant="outline">← Haftalık Program</Button></Link><Link to="/schedule-validation"><Button variant="outline" className="gap-2"><ShieldCheck className="size-4"/>Doğrulama</Button></Link><Button variant="outline" className="gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></div>
  {message?<div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
  <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><Sparkles className="size-5 text-primary"/><h2 className="font-semibold">Zincir Arama</h2></div><p className="mt-1 text-xs text-muted-foreground">Kaynak ders veya blok hedefe doğrudan gidemiyorsa gerçek blocker’ları iter. Her tamamlanmış zincir server canonical batch preview’dan geçmeden listelenmez.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><div className="md:col-span-2"><Label>Taşınacak ders</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Seçiniz</option>{rows.map(r=><option key={r.id} value={r.id} disabled={r.locked}>{r.class_name} · {r.subject} · {r.profiles?.full_name??"—"} · {day[r.weekday]} {r.period}. saat{r.locked?" · KİLİTLİ":""}</option>)}</select></div><div><Label>Hedef gün</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{profile.teaching_days.map(d=><option key={d} value={d}>{day[d]}</option>)}</select></div><div><Label>Hedef saat</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={period} onChange={e=>setPeriod(Number(e.target.value))}>{Array.from({length:profile.periods_per_day},(_,i)=>i+1).map(p=><option key={p} value={p}>{p}</option>)}</select></div></div><div className="mt-3 flex flex-wrap items-end gap-3"><div><Label>Maksimum zincir derinliği</Label><select className="mt-1 h-10 rounded-md border bg-background px-3 text-sm" value={depth} onChange={e=>setDepth(Number(e.target.value))}><option value={3}>3 · hızlı</option><option value={4}>4 · dengeli</option><option value={5}>5 · derin</option></select></div><Button disabled={busy||!sourceId} onClick={()=>void search()}>{busy?"Aranıyor…":"Güvenli Zincirleri Bul"}</Button>{source?<div className="text-xs text-muted-foreground">Kaynak: <b>{source.class_name} · {source.subject}</b> · {day[source.weekday]} {source.period}. saat</div>:null}</div></section>
  <section className="mt-4 space-y-3">{items.map((c,i)=><article key={c.moves.map(m=>`${m.schedule_id}-${m.weekday}-${m.period}`).join("|")} className={`rounded-xl border p-4 ${i===0?"border-emerald-400 bg-emerald-50/40":"bg-card"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div>{i===0?<div className="mb-1 flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle2 className="size-4"/>Önerilen zincir</div>:null}<h3 className="font-semibold">Depth {c.depth} · {c.moves.length} atomik satır</h3><p className="mt-1 text-xs text-muted-foreground">{c.explanation}</p></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded border bg-background px-2 py-1"><b>{c.score.medium}</b><br/>MEDIUM</div><div className="rounded border bg-background px-2 py-1"><b>{c.score.soft}</b><br/>SOFT</div><div className="rounded border bg-background px-2 py-1"><b>{c.score.moveCost}</b><br/>Hareket</div></div></div><div className="mt-3 space-y-1 rounded-lg border bg-background p-3 text-xs">{c.moves.map((m,n)=>{const r=rows.find(x=>x.id===m.schedule_id);return <div key={m.schedule_id} className="flex flex-wrap items-center gap-1"><span className="font-semibold">{n+1}. {r?`${r.class_name} · ${r.subject}`:m.schedule_id}</span><ArrowRight className="size-3"/><span>{day[m.weekday]} {m.period}. saat</span></div>})}</div><Button className="mt-3" disabled={busy} onClick={()=>void apply(c)}>Bu Zinciri Atomik Uygula</Button></article>)}{!items.length?<div className="rounded-xl border bg-muted/20 p-6 text-center text-sm text-muted-foreground">Kaynak ve hedef seçip zincir araması başlatın. Sonuç yoksa HARD kurallar gevşetilmez; daha derin zincir veya farklı hedef gerekir.</div>:null}</section>
 </AppShell>}
