import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Lock, RefreshCw, Sparkles, Unlock } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-solver")({head:()=>({meta:[{title:"Ders Programı Çözücü — OkulOS"}]}),component:ScheduleSolver});
type Scenario={generation_group:string;scenario_id:string;scenario_no:number;score:number;unplaced_count:number;row_count:number;hard_issue_count:number;room_issue_count:number;applicable:boolean};
type CurrentRow={id:string;teacher_id:string;class_name:string;subject:string;weekday:number;period:number;locked:boolean;profiles?:{full_name:string|null}|null};
type Unplaced={id:string;scenario_id:string;subject:string;reason:string;block_hours:number;diagnostic:Record<string,number>};
type Settings={periods_per_day:number;max_same_course_per_day:number;gap_penalty:number;late_period_penalty:number;repeated_course_penalty:number};
type Prep={category:string;code:string;status:string;affected_count:number;detail:string};
const dayNames=["","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];

function ScheduleSolver(){
 const [scenarios,setScenarios]=useState<Scenario[]>([]),[current,setCurrent]=useState<CurrentRow[]>([]),[unplaced,setUnplaced]=useState<Unplaced[]>([]),[prep,setPrep]=useState<Prep[]>([]);
 const [settings,setSettings]=useState<Settings>({periods_per_day:8,max_same_course_per_day:2,gap_penalty:8,late_period_penalty:2,repeated_course_penalty:12});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[prepLoadError,setPrepLoadError]=useState<string|null>(null),[loaded,setLoaded]=useState(false);
 const load=useCallback(async()=>{setLoaded(false);const [c,s,p]=await Promise.all([
  supabase.from("teacher_schedule").select("id,teacher_id,class_name,subject,weekday,period,locked,profiles!teacher_schedule_teacher_id_fkey(full_name)").eq("active",true).order("weekday").order("period"),
  supabase.from("schedule_generation_settings").select("periods_per_day,max_same_course_per_day,gap_penalty,late_period_penalty,repeated_course_penalty").eq("id",true).maybeSingle(),
  supabase.rpc("get_schedule_preparation_readiness")]);
  if(c.error){setError(`Çalışma programı okunamadı: ${c.error.message}`);setCurrent([])}else setCurrent((c.data??[]) as unknown as CurrentRow[]);
  if(s.error)setError(`Çözücü ayarları okunamadı: ${s.error.message}`);else if(s.data)setSettings(s.data as Settings);
  if(p.error){setPrep([]);setPrepLoadError(p.error.message)}else{setPrep((p.data??[]) as Prep[]);setPrepLoadError(null)}
  setLoaded(true)
 },[]);
 useEffect(()=>{void load()},[load]);
 async function toggleLock(row:CurrentRow){const {error:e}=await supabase.from("teacher_schedule").update({locked:!row.locked}).eq("id",row.id);if(e)return setError(e.message);await load()}
 async function saveSettings(){const invalid=settings.max_same_course_per_day<1||settings.gap_penalty<0||settings.late_period_penalty<0||settings.repeated_course_penalty<0;if(invalid)return setError("Çözücü kalite ağırlıkları geçersiz. Aynı ders/gün en az 1, ceza değerleri 0 veya daha büyük olmalıdır.");const {error:e}=await supabase.from("schedule_generation_settings").update({max_same_course_per_day:settings.max_same_course_per_day,gap_penalty:settings.gap_penalty,late_period_penalty:settings.late_period_penalty,repeated_course_penalty:settings.repeated_course_penalty,updated_at:new Date().toISOString()}).eq("id",true);if(e)return setError(e.message);setError(null);setMessage("Çözücü kalite ayarları kaydedildi. Günlük ders sayısı merkezi zaman şablonundan alınır.")}
 async function generate(){if(prepLoadError)return setError(`Hazırlık doğrulaması okunamadığı için çözücü başlatılamaz: ${prepLoadError}`);if(prep.some(x=>x.status==="error"))return setError("Hazırlık sorunları çözülmeden senaryo üretilemez.");setBusy(true);setError(null);setMessage(null);setScenarios([]);setUnplaced([]);const {data,error:e}=await supabase.rpc("generate_schedule_scenarios_v2");if(e){setBusy(false);await load();return setError(`Senaryolar üretilemedi: ${e.message}`)}const generated=(data??[]) as Array<{generation_group:string;scenario_id:string}>;if(!generated.length){setBusy(false);return setError("Çözücü senaryo üretmedi.")}
  for(const s of generated){const repair=await supabase.rpc("repair_schedule_scenario_v2",{p_scenario_id:s.scenario_id});if(repair.error){setBusy(false);return setError(`Senaryo ${s.scenario_id} repair/backtracking hatası: ${repair.error.message}`)}const rescore=await supabase.rpc("rescore_schedule_scenario_v2",{p_scenario_id:s.scenario_id});if(rescore.error){setBusy(false);return setError(`Senaryo ${s.scenario_id} kalite puanlama hatası: ${rescore.error.message}`)}}
  const group=generated[0]!.generation_group,ids=generated.map(x=>x.scenario_id);const [status,u]=await Promise.all([
   supabase.from("schedule_scenario_status_v2").select("generation_group,scenario_id,scenario_no,score,row_count,unplaced_count,hard_issue_count,room_issue_count,applicable").eq("generation_group",group).order("score"),
   supabase.from("schedule_unplaced_items").select("id,scenario_id,subject,reason,block_hours,diagnostic").in("scenario_id",ids)]);
  if(status.error){setBusy(false);return setError(`Senaryo bütünlük durumu okunamadı: ${status.error.message}`)}if(u.error){setBusy(false);return setError(`Yerleşmeyen ders teşhisi okunamadı: ${u.error.message}`)}setScenarios((status.data??[]) as Scenario[]);setUnplaced((u.data??[]) as Unplaced[]);setBusy(false);setMessage("4 senaryo üretildi; repair/backtracking, derslik, hard bütünlük ve kalite puanlaması tamamlandı.")}
 async function apply(id:string){const selected=scenarios.find(s=>s.scenario_id===id);if(!selected?.applicable)return setError("Yalnız uygulanabilir olarak doğrulanmış senaryo çalışma programına aktarılabilir.");setBusy(true);setError(null);const {data,error:e}=await supabase.rpc("apply_schedule_scenario",{p_scenario_id:id});setBusy(false);if(e)return setError(`Senaryo uygulanamadı: ${e.message}`);setMessage(`${Number(data??0)} ders çalışma programına uygulandı ve bütünlük kapısından geçti.`);await load()}
 const lockedCount=useMemo(()=>current.filter(x=>x.locked).length,[current]),prepErrors=prep.filter(x=>x.status==="error"),prepReady=loaded&&!prepLoadError&&prepErrors.length===0;
 const diagLabel:Record<string,string>={teacher_busy:"Öğretmen dolu",class_busy:"Sınıf dolu",teacher_unavailable:"Öğretmen uygun değil",daily_limit:"Günlük limit",working_days_limit:"Çalışma günü limiti",consecutive_limit:"Ardışık ders limiti",course_time_rule:"Ders zaman kuralı",valid_windows:"Geçerli pencere",candidate_windows:"Toplam aday"};
 return <AppShell title="Ders Programı Çözücü" subtitle="Hard constraint · blok · eşzamanlı grup · repair/backtracking" action={<Sparkles className="size-5"/>}>
  <div className="grid gap-2 sm:grid-cols-5"><Link to="/curriculum"><Button variant="outline" className="w-full">Müfredat</Button></Link><Link to="/schedule-rules"><Button variant="outline" className="w-full">Program Kuralları</Button></Link><Link to="/schedule-preparation"><Button variant={prepLoadError||prepErrors.length?"destructive":"outline"} className="w-full">Hazırlık {prepLoadError?"!":prepErrors.length?`(${prepErrors.length})`:loaded?"✓":"…"}</Button></Link><Link to="/schedule"><Button variant="outline" className="w-full">Çalışma Programı</Button></Link><Link to="/schedule-validation"><Button variant="outline" className="w-full">Doğrulama</Button></Link></div>
  {message?<div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
  {prepLoadError?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle className="mr-2 inline size-4"/><b>Hazırlık doğrulaması çalıştırılamadı.</b> {prepLoadError}</div>:prepErrors.length?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><b className="text-red-700">Program üretimi başlamadan önce {prepErrors.length} hazırlık sorunu çözülmeli.</b>{prepErrors.slice(0,5).map(x=><p key={x.code} className="mt-1 text-xs text-red-800">{x.category} · {x.code}: {x.detail} ({x.affected_count})</p>)}</div>:loaded?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>Program hazırlık girdileri tamam.</div>:<div className="mt-4 rounded-xl border bg-muted/30 p-3 text-sm text-muted-foreground">Hazırlık kontrolü yükleniyor…</div>}
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Kalite Ağırlıkları</h2><p className="mt-1 text-xs text-muted-foreground">Günlük ders sayısı: <b>{settings.periods_per_day}</b> · Merkezi zaman şablonundan gelir.</p><div className="mt-3 grid gap-3 sm:grid-cols-4"><div><Label>Aynı ders/gün</Label><Input type="number" min={1} value={settings.max_same_course_per_day} onChange={e=>setSettings({...settings,max_same_course_per_day:Number(e.target.value)})}/></div><div><Label>Boşluk cezası</Label><Input type="number" min={0} value={settings.gap_penalty} onChange={e=>setSettings({...settings,gap_penalty:Number(e.target.value)})}/></div><div><Label>Geç ders cezası</Label><Input type="number" min={0} value={settings.late_period_penalty} onChange={e=>setSettings({...settings,late_period_penalty:Number(e.target.value)})}/></div><div><Label>Tekrar cezası</Label><Input type="number" min={0} value={settings.repeated_course_penalty} onChange={e=>setSettings({...settings,repeated_course_penalty:Number(e.target.value)})}/></div></div><Button variant="secondary" className="mt-3" onClick={()=>void saveSettings()}>Kaydet</Button></section>
  <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Kilitli Dersler</h2><p className="text-xs text-muted-foreground">{lockedCount} saat kilitli; toplam atama saatinden düşülür.</p></div><Button onClick={()=>void generate()} disabled={busy||!prepReady} className="gap-2"><Sparkles className="size-4"/>{busy?"Çözülüyor...":"4 Senaryo Üret"}</Button></div><div className="mt-3 max-h-64 overflow-auto rounded-lg border"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-2 text-left">Gün/Saat</th><th className="p-2 text-left">Sınıf</th><th className="p-2 text-left">Ders</th><th className="p-2 text-left">Öğretmen</th><th className="p-2">Kilit</th></tr></thead><tbody>{current.map(r=><tr key={r.id} className="border-b"><td className="p-2">{dayNames[r.weekday]} · {r.period}</td><td className="p-2">{r.class_name}</td><td className="p-2">{r.subject}</td><td className="p-2">{r.profiles?.full_name??"—"}</td><td className="p-2 text-center"><Button size="sm" variant={r.locked?"secondary":"ghost"} onClick={()=>void toggleLock(r)}>{r.locked?<Lock className="size-4"/>:<Unlock className="size-4"/>}</Button></td></tr>)}</tbody></table></div></section>
  <div className="mt-4 grid gap-3 lg:grid-cols-2">{scenarios.map((s,index)=>{const problems=unplaced.filter(u=>u.scenario_id===s.scenario_id);return <section key={s.scenario_id} className={s.applicable&&index===0?"rounded-xl border-2 border-emerald-400 bg-emerald-50/30 p-4":"rounded-xl border bg-card p-4"}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">Senaryo {s.scenario_no}{s.applicable&&index===0?" · Önerilen":""}</h3><p className="text-xs text-muted-foreground">Puan {s.score} · {s.row_count} ders</p></div>{s.applicable?<CheckCircle2 className="size-5 text-emerald-600"/>:<AlertTriangle className="size-5 text-amber-600"/>}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg border p-2"><b>{s.unplaced_count}</b><br/>Yerleşmeyen</div><div className="rounded-lg border p-2"><b>{s.hard_issue_count}</b><br/>Hard hata</div><div className="rounded-lg border p-2"><b>{s.room_issue_count}</b><br/>Derslik sorunu</div></div>{problems.map(p=><div key={p.id} className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800"><b>{p.subject}</b> · {p.block_hours} saat · {p.reason}<div className="mt-2 flex flex-wrap gap-1">{Object.entries(p.diagnostic??{}).filter(([,v])=>v>0).map(([k,v])=><span key={k} className="rounded bg-white px-2 py-1">{diagLabel[k]??k}: {v}</span>)}</div></div>)}{!s.applicable?<p className="mt-3 text-xs text-amber-700">Bu senaryo uygulanamaz. Yerleşmeyen ders, hard constraint ve derslik sorunlarının tamamı sıfır olmalıdır.</p>:null}<Button className="mt-3 w-full" disabled={busy||!s.applicable} onClick={()=>void apply(s.scenario_id)}>Bu Senaryoyu Uygula</Button></section>})}</div>
  {!scenarios.length?<div className="mt-4 rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Senaryolar üretildiğinde uygulanabilirlik üç ayrı güvenlik kapısıyla gösterilir.</div>:null}<Button variant="ghost" className="mt-5 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button>
 </AppShell>
}
