import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BrainCircuit, RefreshCw, Save, ShieldCheck, Sparkles } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-optimization")({head:()=>({meta:[{title:"Program Optimizasyonu — OkulOS"}]}),component:ScheduleOptimization});

type Profile={profile_key:string;name:string;description:string|null;weights:Record<string,number>};
type Rule={rule_code:string;label:string;category:string;mode:"off"|"soft"|"hard";weight:number;config:Record<string,unknown>};
type Course={id:string;name:string};
type Pedagogy={course_id:string;academic_load:number;physical_load:number;practical_load:number;attention_load:number;difficulty:number;lesson_family:string|null;is_workshop:boolean;is_vocational_practice:boolean;prefer_early:boolean;avoid_early:boolean};
type Workshop={course_id:string;min_block:number;preferred_block:number;max_block:number;active:boolean};
type Teacher={user_id:string;full_name:string|null};
type Duty={teacher_id:string;weekday:number;max_duty_day_hours:number;anchor_period:number|null;overload_weight:number;adjacent_weight:number;hard_max:boolean;source:string};
type Scenario={id:string;title:string;score:number;scenario_no:number;generated_at:string};
type Explanation={scenario_id:string;total_score:number;pedagogic_score:number;teacher_score:number;room_score:number;duty_score:number;workshop_score:number;positives:Array<{metric:string;score:number;detail:string}>;negatives:Array<{metric:string;score:number;detail:string}>;metrics:Record<string,{score:number;detail:string}>};
type Repair={id:string;scenario_id:string;action_no:number;issue_code:string;description:string;score_delta:number|null;hard_issues_before:number|null;hard_issues_after:number|null;created_at:string};
const days:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};

function ScheduleOptimization(){
 const [profiles,setProfiles]=useState<Profile[]>([]),[activeProfile,setActiveProfile]=useState("balanced"),[rules,setRules]=useState<Rule[]>([]),[courses,setCourses]=useState<Course[]>([]),[pedagogy,setPedagogy]=useState<Pedagogy[]>([]),[workshops,setWorkshops]=useState<Workshop[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[duties,setDuties]=useState<Duty[]>([]),[scenarios,setScenarios]=useState<Scenario[]>([]),[explanations,setExplanations]=useState<Explanation[]>([]),[repairs,setRepairs]=useState<Repair[]>([]),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const [courseId,setCourseId]=useState(""),[academic,setAcademic]=useState(3),[physical,setPhysical]=useState(1),[practical,setPractical]=useState(1),[attention,setAttention]=useState(3),[difficulty,setDifficulty]=useState(3),[family,setFamily]=useState(""),[workshop,setWorkshop]=useState(false),[vocational,setVocational]=useState(false),[preferEarly,setPreferEarly]=useState(false),[avoidEarly,setAvoidEarly]=useState(false),[minBlock,setMinBlock]=useState(3),[preferredBlock,setPreferredBlock]=useState(5),[maxBlock,setMaxBlock]=useState(7);
 const [dutyTeacher,setDutyTeacher]=useState(""),[dutyDay,setDutyDay]=useState(1),[dutyMax,setDutyMax]=useState(5),[anchor,setAnchor]=useState(""),[dutyHard,setDutyHard]=useState(false);
 const [selectedScenario,setSelectedScenario]=useState("");
 const load=useCallback(async()=>{setError(null);const [pr,st,ru,co,pe,wo,te,du,sc,ex,re]=await Promise.all([
  supabase.from("schedule_optimization_profiles").select("profile_key,name,description,weights").eq("active",true).order("system_profile",{ascending:false}).order("name"),
  supabase.from("schedule_optimization_settings").select("active_profile_key").eq("id",true).maybeSingle(),
  supabase.from("schedule_rule_modes").select("rule_code,label,category,mode,weight,config").order("category").order("label"),
  supabase.from("course_catalog").select("id,name").eq("active",true).order("name"),
  supabase.from("course_pedagogy_profiles").select("course_id,academic_load,physical_load,practical_load,attention_load,difficulty,lesson_family,is_workshop,is_vocational_practice,prefer_early,avoid_early"),
  supabase.from("schedule_workshop_policies").select("course_id,min_block,preferred_block,max_block,active"),
  supabase.from("profiles").select("user_id,full_name").order("full_name"),
  supabase.from("schedule_duty_optimization").select("teacher_id,weekday,max_duty_day_hours,anchor_period,overload_weight,adjacent_weight,hard_max,source").order("weekday"),
  supabase.from("schedule_scenarios").select("id,title,score,scenario_no,generated_at").order("generated_at",{ascending:false}).limit(20),
  supabase.from("schedule_scenario_explanations").select("scenario_id,total_score,pedagogic_score,teacher_score,room_score,duty_score,workshop_score,positives,negatives,metrics"),
  supabase.from("schedule_repair_audit").select("id,scenario_id,action_no,issue_code,description,score_delta,hard_issues_before,hard_issues_after,created_at").order("created_at",{ascending:false}).limit(100)
 ]);const first=[pr,ru,co,pe,wo,te,du,sc,ex,re].find(x=>x.error);if(first?.error)setError(first.error.message);setProfiles((pr.data??[]) as Profile[]);setActiveProfile(st.data?.active_profile_key??"balanced");setRules((ru.data??[]) as Rule[]);setCourses((co.data??[]) as Course[]);setPedagogy((pe.data??[]) as Pedagogy[]);setWorkshops((wo.data??[]) as Workshop[]);setTeachers((te.data??[]) as Teacher[]);setDuties((du.data??[]) as Duty[]);setScenarios((sc.data??[]) as Scenario[]);setExplanations((ex.data??[]) as unknown as Explanation[]);setRepairs((re.data??[]) as Repair[]);if(!selectedScenario&&sc.data?.[0]?.id)setSelectedScenario(sc.data[0].id)},[selectedScenario]);useEffect(()=>{void load()},[load]);
 async function applyProfile(key:string){const {error:e}=await supabase.rpc("apply_schedule_optimization_profile_v1",{p_profile_key:key});if(e)return setError(e.message);setActiveProfile(key);setMessage("Optimizasyon profili uygulandı.");await load()}
 async function saveRule(rule:Rule){const {error:e}=await supabase.from("schedule_rule_modes").update({mode:rule.mode,weight:rule.weight,updated_at:new Date().toISOString()}).eq("rule_code",rule.rule_code);if(e)return setError(e.message);setMessage(`${rule.label} kaydedildi.`);await load()}
 function loadCourse(id:string){setCourseId(id);const p=pedagogy.find(x=>x.course_id===id);const w=workshops.find(x=>x.course_id===id);setAcademic(p?.academic_load??3);setPhysical(p?.physical_load??1);setPractical(p?.practical_load??1);setAttention(p?.attention_load??3);setDifficulty(p?.difficulty??3);setFamily(p?.lesson_family??"");setWorkshop(Boolean(p?.is_workshop));setVocational(Boolean(p?.is_vocational_practice));setPreferEarly(Boolean(p?.prefer_early));setAvoidEarly(Boolean(p?.avoid_early));setMinBlock(w?.min_block??3);setPreferredBlock(w?.preferred_block??5);setMaxBlock(w?.max_block??7)}
 async function saveCourse(){if(!courseId)return;const {error:e}=await supabase.from("course_pedagogy_profiles").upsert({course_id:courseId,academic_load:academic,physical_load:physical,practical_load:practical,attention_load:attention,difficulty,lesson_family:family||null,is_workshop:workshop,is_vocational_practice:vocational,prefer_early:preferEarly,avoid_early:avoidEarly,updated_at:new Date().toISOString()},{onConflict:"course_id"});if(e)return setError(e.message);if(workshop||vocational){const {error:w}=await supabase.from("schedule_workshop_policies").upsert({course_id:courseId,min_block:minBlock,preferred_block:preferredBlock,max_block:maxBlock,active:true,updated_at:new Date().toISOString()},{onConflict:"course_id"});if(w)return setError(w.message)}setMessage("Pedagojik ders profili kaydedildi.");await load()}
 async function syncDuty(){const {data,error:e}=await supabase.rpc("sync_schedule_duty_optimization_from_cycle");if(e)return setError(e.message);setMessage(`${Number(data??0)} nöbet günü program optimizasyonuna eşitlendi.`);await load()}
 async function saveDuty(){if(!dutyTeacher)return;const {error:e}=await supabase.from("schedule_duty_optimization").upsert({teacher_id:dutyTeacher,weekday:dutyDay,max_duty_day_hours:dutyMax,anchor_period:anchor?Number(anchor):null,hard_max:dutyHard,source:"manual",updated_at:new Date().toISOString()},{onConflict:"teacher_id,weekday"});if(e)return setError(e.message);setMessage("Nöbet günü program kuralı kaydedildi.");await load()}
 const explanation=explanations.find(x=>x.scenario_id===selectedScenario),scenarioRepairs=repairs.filter(x=>x.scenario_id===selectedScenario),active=profiles.find(x=>x.profile_key===activeProfile);
 const grouped=useMemo(()=>Object.entries(rules.reduce<Record<string,Rule[]>>((a,r)=>{(a[r.category]??=[]).push(r);return a},{})),[rules]);
 return <AppShell title="Program Optimizasyonu" subtitle="Hard/Soft kurallar · pedagojik yük · nöbet · atölye · açıklanabilir senaryo" action={<BrainCircuit className="size-5"/>}>
  <div className="mb-4 grid gap-2 sm:grid-cols-4"><Link to="/schedule-rules"><Button variant="outline" className="w-full">Temel Kurallar</Button></Link><Link to="/schedule-solver"><Button variant="outline" className="w-full">Çözücü</Button></Link><Link to="/schedule-validation"><Button variant="outline" className="w-full">Doğrulama</Button></Link><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Yenile</Button></div>
  {message?<div className="mb-4 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mb-4 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
  <Tabs defaultValue="profile"><TabsList className="grid h-auto w-full grid-cols-2 sm:grid-cols-5"><TabsTrigger value="profile">Profil</TabsTrigger><TabsTrigger value="rules">Kurallar</TabsTrigger><TabsTrigger value="pedagogy">Pedagoji</TabsTrigger><TabsTrigger value="duty">Nöbet</TabsTrigger><TabsTrigger value="explain">Senaryo</TabsTrigger></TabsList>
   <TabsContent value="profile" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Okul Türü / Optimizasyon Profili</h2><p className="mt-1 text-sm text-muted-foreground">Seçilen profil temel fitness ağırlıklarını değiştirir; ders ve öğretmen özel kuralları bunun üzerine uygulanır.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{profiles.map(p=><button key={p.profile_key} onClick={()=>void applyProfile(p.profile_key)} className={`rounded-xl border p-4 text-left transition ${activeProfile===p.profile_key?"border-primary bg-primary/5":"hover:border-primary/40"}`}><div className="flex items-center justify-between"><b>{p.name}</b>{activeProfile===p.profile_key?<ShieldCheck className="size-4 text-primary"/>:null}</div><p className="mt-1 text-xs text-muted-foreground">{p.description}</p></button>)}</div>{active?<div className="mt-4 rounded-lg bg-muted/40 p-3 text-xs">Aktif profil: <b>{active.name}</b> · Ağırlıklar: {Object.entries(active.weights).map(([k,v])=>`${k}=${v}`).join(" · ")}</div>:null}</section></TabsContent>
   <TabsContent value="rules" className="mt-4 space-y-4">{grouped.map(([category,list])=><section key={category} className="rounded-xl border bg-card p-4"><h2 className="font-semibold capitalize">{category}</h2><div className="mt-3 space-y-2">{list.map(r=><div key={r.rule_code} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_140px_110px_auto] sm:items-center"><div><b className="text-sm">{r.label}</b><p className="text-xs text-muted-foreground">{r.rule_code}</p></div><select className="h-9 rounded-md border bg-background px-2 text-sm" value={r.mode} onChange={e=>setRules(x=>x.map(q=>q.rule_code===r.rule_code?{...q,mode:e.target.value as Rule["mode"]}:q))}><option value="off">Kapalı</option><option value="soft">Soft</option><option value="hard">Hard</option></select><Input type="number" value={r.weight} onChange={e=>setRules(x=>x.map(q=>q.rule_code===r.rule_code?{...q,weight:Number(e.target.value)}:q))}/><Button size="sm" onClick={()=>void saveRule(r)}><Save className="mr-1 size-3"/>Kaydet</Button></div>)}</div></section>)}</TabsContent>
   <TabsContent value="pedagogy" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Ders Pedagojik Yük Profili</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={courseId} onChange={e=>loadCourse(e.target.value)}><option value="">Ders seçiniz</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{courseId?<><div className="mt-4 grid gap-3 sm:grid-cols-5">{[["Akademik",academic,setAcademic],["Fiziksel",physical,setPhysical],["Uygulama",practical,setPractical],["Dikkat",attention,setAttention],["Zorluk",difficulty,setDifficulty]].map(([label,value,setter])=><div key={String(label)}><Label>{String(label)} (1-5)</Label><Input type="number" min={1} max={5} value={value as number} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></div>)}</div><div className="mt-3"><Label>Ders ailesi</Label><Input value={family} onChange={e=>setFamily(e.target.value)} placeholder="sayısal, dil, sanat, spor, atölye..."/></div><div className="mt-3 flex flex-wrap gap-3 text-sm"><label><input type="checkbox" checked={preferEarly} onChange={e=>setPreferEarly(e.target.checked)}/> Sabahı tercih et</label><label><input type="checkbox" checked={avoidEarly} onChange={e=>setAvoidEarly(e.target.checked)}/> Sabahı tercih etme</label><label><input type="checkbox" checked={workshop} onChange={e=>setWorkshop(e.target.checked)}/> Atölye</label><label><input type="checkbox" checked={vocational} onChange={e=>setVocational(e.target.checked)}/> Meslek uygulama</label></div>{workshop||vocational?<div className="mt-4 grid gap-3 sm:grid-cols-3"><div><Label>Minimum blok</Label><Input type="number" min={1} max={12} value={minBlock} onChange={e=>setMinBlock(Number(e.target.value))}/></div><div><Label>Tercih edilen blok</Label><Input type="number" min={1} max={12} value={preferredBlock} onChange={e=>setPreferredBlock(Number(e.target.value))}/></div><div><Label>Maksimum blok</Label><Input type="number" min={1} max={12} value={maxBlock} onChange={e=>setMaxBlock(Number(e.target.value))}/></div></div>:null}<Button className="mt-4" onClick={()=>void saveCourse()}><Save className="mr-2 size-4"/>Ders Profilini Kaydet</Button></>:null}</section></TabsContent>
   <TabsContent value="duty" className="mt-4 space-y-4"><section className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">Nöbet ↔ Ders Programı</h2><p className="text-xs text-muted-foreground">Haftalık nöbet döngüsünü içeri al; öğretmen bazında soft/hard günlük yük tanımla.</p></div><Button variant="outline" onClick={()=>void syncDuty()}><RefreshCw className="mr-2 size-4"/>Nöbet Döngüsünden Eşitle</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-5"><select className="h-10 rounded-md border bg-background px-2 text-sm" value={dutyTeacher} onChange={e=>setDutyTeacher(e.target.value)}><option value="">Öğretmen</option>{teachers.map(t=><option key={t.user_id} value={t.user_id}>{t.full_name}</option>)}</select><select className="h-10 rounded-md border bg-background px-2 text-sm" value={dutyDay} onChange={e=>setDutyDay(Number(e.target.value))}>{Object.entries(days).map(([d,n])=><option key={d} value={d}>{n}</option>)}</select><Input type="number" min={0} max={12} value={dutyMax} onChange={e=>setDutyMax(Number(e.target.value))} placeholder="Azami ders"/><Input type="number" min={1} max={12} value={anchor} onChange={e=>setAnchor(e.target.value)} placeholder="Nöbet referans saati"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={dutyHard} onChange={e=>setDutyHard(e.target.checked)}/> Hard azami</label></div><Button className="mt-3" onClick={()=>void saveDuty()}>Kaydet</Button></section><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Aktif Nöbet Optimizasyonları</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{duties.map(d=><div key={`${d.teacher_id}-${d.weekday}`} className="rounded-lg border p-3 text-sm"><b>{teachers.find(t=>t.user_id===d.teacher_id)?.full_name??d.teacher_id}</b><p className="text-xs text-muted-foreground">{days[d.weekday]} · azami {d.max_duty_day_hours} ders · {d.hard_max?"HARD":"SOFT"} · {d.source}</p></div>)}</div></section></TabsContent>
   <TabsContent value="explain" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="size-4"/>Açıklanabilir Senaryo Karşılaştırması</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={selectedScenario} onChange={e=>setSelectedScenario(e.target.value)}><option value="">Senaryo seçiniz</option>{scenarios.map(s=><option key={s.id} value={s.id}>Senaryo {s.scenario_no} · {s.title} · skor {s.score}</option>)}</select>{explanation?<><div className="mt-4 grid gap-2 sm:grid-cols-4"><div className="rounded-lg border p-3"><b>{explanation.total_score}</b><p className="text-xs text-muted-foreground">Toplam skor</p></div><div className="rounded-lg border p-3"><b>{explanation.pedagogic_score}</b><p className="text-xs text-muted-foreground">Pedagojik</p></div><div className="rounded-lg border p-3"><b>{explanation.duty_score}</b><p className="text-xs text-muted-foreground">Nöbet</p></div><div className="rounded-lg border p-3"><b>{explanation.workshop_score}</b><p className="text-xs text-muted-foreground">Atölye</p></div></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-lg border p-3"><h3 className="text-sm font-semibold">Güçlü Yanlar</h3>{(explanation.positives??[]).length?(explanation.positives??[]).map((x,i)=><p key={i} className="mt-2 text-xs text-emerald-700">{x.detail} ({x.score})</p>):<p className="mt-2 text-xs text-muted-foreground">Ödül üreten özel metrik yok.</p>}</div><div className="rounded-lg border p-3"><h3 className="text-sm font-semibold">İyileştirme Alanları</h3>{(explanation.negatives??[]).length?(explanation.negatives??[]).map((x,i)=><p key={i} className="mt-2 text-xs text-amber-700">{x.detail} (+{x.score})</p>):<p className="mt-2 text-xs text-muted-foreground">Ek kalite cezası yok.</p>}</div></div></>:<p className="mt-4 text-sm text-muted-foreground">Senaryo yeniden puanlandığında açıklama otomatik oluşur.</p>}<div className="mt-5"><h3 className="font-semibold">Repair / Backtracking Geçmişi</h3>{scenarioRepairs.length?scenarioRepairs.map(r=><div key={r.id} className="mt-2 rounded-lg border p-3 text-sm"><div className="flex items-center justify-between"><b>#{r.action_no} {r.issue_code}</b><span className="text-xs">Skor Δ {r.score_delta??0}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.description}</p><p className="mt-1 text-xs">Hard hata: {r.hard_issues_before??0} → {r.hard_issues_after??0}</p></div>):<p className="mt-2 text-xs text-muted-foreground">Bu senaryoda kayıtlı repair işlemi yok.</p>}</div></section></TabsContent>
  </Tabs>
 </AppShell>
}
