import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, GitBranch, Layers3, RefreshCw, Trash2, UserRound } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-placement-rules")({head:()=>({meta:[{title:"Yerleşim Kuralları — OkulOS"}]}),component:PlacementRules});
type SlotMode="free"|"prefer"|"avoid"|"blocked";
type Teacher={user_id:string;full_name:string|null};type Course={id:string;name:string};
type Req={requirement_id:string;class_name:string;composite_key:string|null;course_name:string;assigned_hours:number};
type Relation={id:string;rule_type:string;left_requirement_id:string;right_requirement_id:string|null;lunch_after_period:number|null;note:string|null};
const days=[[1,"Pzt"],[2,"Sal"],[3,"Çar"],[4,"Per"],[5,"Cum"]] as const;
const modeText:Record<SlotMode,string>={free:"Uygun",prefer:"Tercih",avoid:"Kaçın",blocked:"Yasak"};
const modeClass:Record<SlotMode,string>={free:"bg-background",prefer:"border-emerald-400 bg-emerald-50 text-emerald-800",avoid:"border-amber-400 bg-amber-50 text-amber-800",blocked:"border-red-400 bg-red-50 text-red-800"};
const relationLabels:Record<string,string>={same_day:"Aynı güne gelsin",different_day:"Aynı güne gelmesin",same_slot:"Aynı saatte olsun",different_slot:"Aynı saate gelmesin",not_adjacent:"Art arda gelmesin",no_lunch_split:"Öğle arasını bölmesin"};

function key(d:number,p:number){return `${d}-${p}`}
function nextMode(m:SlotMode):SlotMode{return m==="free"?"prefer":m==="prefer"?"avoid":m==="avoid"?"blocked":"free"}
function blockPatterns(hours:number){const out:number[][]=[];function walk(left:number,max:number,a:number[]){if(!left){out.push(a);return}for(let n=Math.min(max,left);n>=1;n--)walk(left-n,n,[...a,n])}walk(hours,Math.min(hours,6),[]);return out.slice(0,20)}

function PlacementRules(){
 const [teachers,setTeachers]=useState<Teacher[]>([]),[courses,setCourses]=useState<Course[]>([]),[requirements,setRequirements]=useState<Req[]>([]),[relations,setRelations]=useState<Relation[]>([]),[periods,setPeriods]=useState(8),[teacherId,setTeacherId]=useState(""),[courseId,setCourseId]=useState(""),[teacherSlots,setTeacherSlots]=useState<Record<string,SlotMode>>({}),[courseSlots,setCourseSlots]=useState<Record<string,SlotMode>>({}),[reqId,setReqId]=useState(""),[patterns,setPatterns]=useState<number[][]>([]),[leftReq,setLeftReq]=useState(""),[rightReq,setRightReq]=useState(""),[relationType,setRelationType]=useState("different_day"),[lunchAfter,setLunchAfter]=useState("4"),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [t,c,a,r,p]=await Promise.all([supabase.from("profiles").select("user_id,full_name").in("role",["teacher","manager"]).order("full_name"),supabase.from("course_catalog").select("id,name").eq("active",true).order("name"),supabase.from("schedule_assignment_options").select("requirement_id,class_name,composite_key,course_name,assigned_hours").order("composite_key"),supabase.from("schedule_relation_rules").select("id,rule_type,left_requirement_id,right_requirement_id,lunch_after_period,note").eq("active",true),supabase.from("schedule_time_profiles").select("periods_per_day").eq("active",true).maybeSingle()]);if(t.error||c.error||a.error||r.error){setMessage("Yerleşim kuralı verileri yüklenemedi.");return}setTeachers((t.data??[]) as Teacher[]);setCourses((c.data??[]) as Course[]);setRequirements(Array.from(new Map(((a.data??[]) as Req[]).map(x=>[x.requirement_id,x])).values()));setRelations((r.data??[]) as Relation[]);if(p.data?.periods_per_day)setPeriods(Number(p.data.periods_per_day))},[]);
 useEffect(()=>{void load()},[load]);
 const req=useMemo(()=>requirements.find(x=>x.requirement_id===reqId),[requirements,reqId]);

 const loadTeacher=useCallback(async(id:string)=>{if(!id)return setTeacherSlots({});const [u,p]=await Promise.all([supabase.from("teacher_unavailability").select("weekday,period").eq("teacher_id",id).eq("active",true),supabase.from("teacher_schedule_preferences").select("weekday,period,preference").eq("teacher_id",id).eq("active",true)]);const m:Record<string,SlotMode>={};for(const x of u.data??[])m[key(x.weekday,x.period)]="blocked";for(const x of p.data??[])if(!m[key(x.weekday,x.period)])m[key(x.weekday,x.period)]=x.preference==="prefer"?"prefer":"avoid";setTeacherSlots(m)},[]);
 useEffect(()=>{void loadTeacher(teacherId)},[teacherId,loadTeacher]);
 const loadCourse=useCallback(async(id:string)=>{if(!id)return setCourseSlots({});const {data}=await supabase.from("course_time_preferences").select("weekday,period,mode").eq("course_id",id).eq("active",true);const m:Record<string,SlotMode>={};for(const x of data??[])m[key(x.weekday,x.period)]=x.mode as SlotMode;setCourseSlots(m)},[]);
 useEffect(()=>{void loadCourse(courseId)},[courseId,loadCourse]);
 const loadPatterns=useCallback(async(id:string)=>{if(!id)return setPatterns([]);const {data}=await supabase.from("course_block_preferences").select("priority,block_pattern").eq("class_course_requirement_id",id).eq("active",true).order("priority");setPatterns((data??[]).map(x=>x.block_pattern as number[]))},[]);
 useEffect(()=>{void loadPatterns(reqId)},[reqId,loadPatterns]);

 async function setTeacherCell(d:number,p:number){if(!teacherId)return;const k=key(d,p),n=nextMode(teacherSlots[k]??"free");setTeacherSlots(x=>({...x,[k]:n}));setBusy(true);await Promise.all([supabase.from("teacher_unavailability").delete().eq("teacher_id",teacherId).eq("weekday",d).eq("period",p),supabase.from("teacher_schedule_preferences").delete().eq("teacher_id",teacherId).eq("weekday",d).eq("period",p)]);if(n==="blocked")await supabase.from("teacher_unavailability").insert({teacher_id:teacherId,weekday:d,period:p,reason:"Ders programı yerleşim kuralı",active:true});else if(n!=="free")await supabase.from("teacher_schedule_preferences").insert({teacher_id:teacherId,weekday:d,period:p,preference:n,weight:10,active:true});setBusy(false)}
 async function setCourseCell(d:number,p:number){if(!courseId)return;const k=key(d,p),n=nextMode(courseSlots[k]??"free");setCourseSlots(x=>({...x,[k]:n}));setBusy(true);await supabase.from("course_time_preferences").delete().eq("course_id",courseId).eq("weekday",d).eq("period",p);if(n!=="free")await supabase.from("course_time_preferences").insert({course_id:courseId,weekday:d,period:p,mode:n,weight:10,active:true});setBusy(false)}
 async function savePatterns(next:number[][]){if(!reqId)return;setBusy(true);await supabase.from("course_block_preferences").delete().eq("class_course_requirement_id",reqId);if(next.length)await supabase.from("course_block_preferences").insert(next.map((x,i)=>({class_course_requirement_id:reqId,priority:i+1,block_pattern:x,active:true})));setPatterns(next);setBusy(false);setMessage("Blok öncelikleri kaydedildi. 4 senaryo ilk dört tercihi ayrı ayrı deneyebilir.")}
 async function addRelation(){if(!leftReq||(relationType!=="no_lunch_split"&&!rightReq))return;setBusy(true);const {error}=await supabase.from("schedule_relation_rules").insert({rule_type:relationType,left_requirement_id:leftReq,right_requirement_id:relationType==="no_lunch_split"?null:rightReq,lunch_after_period:relationType==="no_lunch_split"?Number(lunchAfter):null,hard:true,active:true});setBusy(false);if(error)return setMessage(`Kural eklenemedi: ${error.message}`);setMessage("Yerleşim kuralı solver'a eklendi.");await load()}
 async function removeRelation(id:string){await supabase.from("schedule_relation_rules").delete().eq("id",id);await load()}

 return <AppShell title="Yerleşim Kuralları" subtitle="Öğretmen zamanı · ders zamanı · blok önceliği · birlikte/ayrı dersler">
  <div className="mb-4 flex flex-wrap gap-2"><Link to="/timetable" className="rounded-md border px-3 py-2 text-sm">← Ders Programı</Link><Link to="/schedule-scoped-rules" className="rounded-md border px-3 py-2 text-sm">Sınıf / Öğretmen Override</Link><Link to="/schedule-validation" className="rounded-md border px-3 py-2 text-sm">Kontrol</Link></div>
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <div className="grid gap-4 xl:grid-cols-2">
   <Matrix title="Öğretmen Zamanı" icon={<UserRound className="size-5"/>} value={teacherId} setValue={setTeacherId} options={teachers.map(x=>[x.user_id,x.full_name??"Öğretmen"])} slots={teacherSlots} periods={periods} onCell={setTeacherCell} help="Hücreye dokun: Uygun → Tercih → Kaçın → Yasak. Solver yasak hücreye kesinlikle yerleştirmez."/>
   <Matrix title="Ders Zamanı" icon={<CalendarClock className="size-5"/>} value={courseId} setValue={setCourseId} options={courses.map(x=>[x.id,x.name])} slots={courseSlots} periods={periods} onCell={setCourseCell} help="Ders için gün+saat bazında gerçek hücre kuralı. Tercih/kaçın puana, yasak HARD kısıta dönüşür."/>
  </div>
  <div className="mt-4 grid gap-4 xl:grid-cols-2">
   <section className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2"><Layers3 className="size-5 text-primary"/><h2 className="font-semibold">Blok Öncelikleri</h2></div><p className="mt-1 text-xs text-muted-foreground">Örn. 5 saat için 2+2+1 → 3+2 → 2+1+1+1. Senaryolar farklı öncelikleri dener.</p><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={reqId} onChange={e=>setReqId(e.target.value)}><option value="">Sınıf-ders seçiniz</option>{requirements.map(x=><option key={x.requirement_id} value={x.requirement_id}>{x.composite_key??x.class_name} · {x.course_name} · {x.assigned_hours}s</option>)}</select>{req?<div className="mt-3 flex flex-wrap gap-2">{blockPatterns(req.assigned_hours).map(p=>{const selected=patterns.some(x=>x.join("+")===p.join("+"));return <Button key={p.join("+")} size="sm" variant={selected?"default":"outline"} disabled={busy} onClick={()=>{const next=selected?patterns.filter(x=>x.join("+")!==p.join("+")):[...patterns,p];void savePatterns(next.slice(0,4))}}>{selected?`${patterns.findIndex(x=>x.join("+")===p.join("+"))+1}. `:""}{p.join("+")}</Button>})}</div>:null}<p className="mt-3 text-[11px] text-muted-foreground">En fazla 4 öncelik seçilir; seçim sırası öncelik sırasıdır.</p></section>
   <section className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2"><GitBranch className="size-5 text-primary"/><h2 className="font-semibold">Birlikte / Ayrı Ders Kuralları</h2></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-2 text-sm" value={relationType} onChange={e=>setRelationType(e.target.value)}>{Object.entries(relationLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select className="h-10 rounded-md border bg-background px-2 text-sm" value={leftReq} onChange={e=>setLeftReq(e.target.value)}><option value="">1. ders</option>{requirements.map(x=><option key={x.requirement_id} value={x.requirement_id}>{x.composite_key??x.class_name} · {x.course_name}</option>)}</select>{relationType==="no_lunch_split"?<div><Label>Öğle arası kaçıncı dersten sonra?</Label><Input className="mt-1" value={lunchAfter} onChange={e=>setLunchAfter(e.target.value.replace(/\D/g,""))}/></div>:<select className="h-10 rounded-md border bg-background px-2 text-sm" value={rightReq} onChange={e=>setRightReq(e.target.value)}><option value="">2. ders</option>{requirements.filter(x=>x.requirement_id!==leftReq).map(x=><option key={x.requirement_id} value={x.requirement_id}>{x.composite_key??x.class_name} · {x.course_name}</option>)}</select>}<Button disabled={busy||!leftReq||(relationType!=="no_lunch_split"&&!rightReq)} onClick={()=>void addRelation()}>Kural Ekle</Button></div><div className="mt-4 space-y-2">{relations.map(r=><div key={r.id} className="flex items-center justify-between gap-2 rounded-lg border p-2 text-xs"><div><b>{relationLabels[r.rule_type]??r.rule_type}</b><p className="text-muted-foreground">{requirements.find(x=>x.requirement_id===r.left_requirement_id)?.course_name??"Ders"}{r.right_requirement_id?` ↔ ${requirements.find(x=>x.requirement_id===r.right_requirement_id)?.course_name??"Ders"}`:` · ${r.lunch_after_period}. dersten sonra`}</p></div><Button size="sm" variant="ghost" onClick={()=>void removeRelation(r.id)}><Trash2 className="size-4"/></Button></div>)}</div></section>
  </div>
  <div className="mt-4 rounded-xl border border-dashed p-3 text-xs text-muted-foreground"><RefreshCw className="mr-1 inline size-3.5"/>Bu ekranın kuralları senaryo üretiminde ve final doğrulamada aynı kaynaktan uygulanır; yalnızca görsel ayar değildir.</div>
 </AppShell>
}
function Matrix({title,icon,value,setValue,options,slots,periods,onCell,help}:{title:string;icon:React.ReactNode;value:string;setValue:(v:string)=>void;options:[string,string][];slots:Record<string,SlotMode>;periods:number;onCell:(d:number,p:number)=>Promise<void>;help:string}){return <section className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2 text-primary">{icon}<h2 className="font-semibold text-foreground">{title}</h2></div><p className="mt-1 text-xs text-muted-foreground">{help}</p><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={e=>setValue(e.target.value)}><option value="">Seçiniz</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>{value?<div className="mt-3 overflow-x-auto"><table className="min-w-[520px] w-full text-xs"><thead><tr><th className="p-1">Saat</th>{days.map(([d,n])=><th key={d} className="p-1">{n}</th>)}</tr></thead><tbody>{Array.from({length:periods},(_,i)=>i+1).map(p=><tr key={p}><td className="p-1 text-center font-semibold">{p}</td>{days.map(([d])=>{const m=slots[key(d,p)]??"free";return <td key={d} className="p-1"><button type="button" onClick={()=>void onCell(d,p)} className={`w-full rounded-md border px-1 py-2 text-[10px] font-medium ${modeClass[m]}`}>{modeText[m]}</button></td>})}</tr>)}</tbody></table></div>:null}<div className="mt-3 flex flex-wrap gap-2">{(["prefer","avoid","blocked"] as SlotMode[]).map(m=><Badge key={m} variant="outline" className={modeClass[m]}>{modeText[m]}</Badge>)}</div></section>}
