import {createFileRoute,Link} from "@tanstack/react-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,BarChart3,CheckCircle2,RefreshCw} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {supabase} from "@/lib/supabase";
import {analyzeScheduleGenerationBottlenecks,type ScheduleRepairSignal,type ScheduleUnplacedDiagnostic} from "@/lib/schedule-generation-bottleneck-analyzer";

export const Route=createFileRoute("/schedule-analysis")({head:()=>({meta:[{title:"Program Darboğaz Analizi — OkulOS"}]}),component:ScheduleAnalysis});
function ScheduleAnalysis(){const [unplaced,setUnplaced]=useState<ScheduleUnplacedDiagnostic[]>([]),[suggestions,setSuggestions]=useState<ScheduleRepairSignal[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setBusy(true);setError(null);const [u,s]=await Promise.all([supabase.from("schedule_unplaced_items").select("id,scenario_id,subject,reason,block_hours,diagnostic").limit(500),supabase.from("schedule_repair_suggestions").select("scenario_id,action_code,title,legal_safe,hard_rule_impact,estimated_gain").limit(300)]);setBusy(false);if(u.error||s.error){setError((u.error??s.error)?.message??"Darboğaz verileri okunamadı.");return}setUnplaced((u.data??[]) as ScheduleUnplacedDiagnostic[]);setSuggestions((s.data??[]) as ScheduleRepairSignal[])},[]);useEffect(()=>{void load()},[load]);const analysis=useMemo(()=>analyzeScheduleGenerationBottlenecks(unplaced,suggestions),[unplaced,suggestions]);
 return <AppShell title="Program Darboğaz Analizi" subtitle="Çoklu adaylarda tekrar eden HARD ve kapasite baskısını küçült" action={<BarChart3 className="size-5"/>}>
  <div className="flex flex-wrap gap-2"><Link to="/schedule-preparation"><Button variant="outline">← Hazırlık</Button></Link><Link to="/schedule-solver"><Button variant="outline">Çözücü</Button></Link><Button variant="outline" disabled={busy} onClick={()=>void load()} className="gap-2"><RefreshCw className="size-4"/>{busy?"Analiz ediliyor…":"Yeniden Analiz Et"}</Button></div>
  {error?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle className="mr-2 inline size-4"/>{error}</div>:null}
  <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.scenarioCount}</b><p className="text-sm text-muted-foreground">yerleşmeyen ders üreten aday</p></div><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.unplacedCount}</b><p className="text-sm text-muted-foreground">yerleşmeyen kayıt</p></div><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.structural.length}</b><p className="text-sm text-muted-foreground">tekrarlayan yapısal darboğaz</p></div></div>
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Önce bunları çöz</h2><p className="mt-1 text-sm text-muted-foreground">aSc Analyze by Generation fikrinin canonical Okulos karşılığı: tek senaryodan ziyade adaylar boyunca tekrar eden baskı yukarı çıkar.</p>{analysis.signals.length?<div className="mt-3 space-y-2">{analysis.signals.slice(0,12).map((x,i)=><div key={x.key} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm">{i+1}. {x.label}</b><span className="rounded-full bg-muted px-2 py-1 text-xs">{x.severity} · {x.scenarioCount} aday · {x.occurrences} sinyal</span></div><p className="mt-1 text-xs text-muted-foreground">{x.explanation}</p></div>)}</div>:<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>Kayıtlı adaylarda yerleşmeyen ders darboğazı görünmüyor.</div>}</section>
  {analysis.safeSuggestions.length?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Güvenli müdahale adayları</h2><div className="mt-3 space-y-2">{analysis.safeSuggestions.slice(0,8).map((x,i)=><div key={`${x.scenario_id}-${x.action_code}-${i}`} className="rounded-lg border p-3 text-sm"><b>{x.title}</b><div className="mt-1 text-xs text-muted-foreground">{x.action_code}{x.estimated_gain!=null?` · tahmini kazanım ${x.estimated_gain}`:""}</div></div>)}</div></section>:null}
  <p className="mt-4 rounded-xl bg-muted/40 p-3 text-xs"><b>Politika:</b> {analysis.policy}</p>
 </AppShell>}
