import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, Link2, Plus, RefreshCw, SlidersHorizontal, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-rules")({head:()=>({meta:[{title:"Program Kuralları — OkulOS"}]}),component:ScheduleRules});
type Teacher={user_id:string;full_name:string|null};type Course={id:string;name:string};type Assignment={teacher_assignment_id:string;teacher_name:string|null;class_id:string;composite_key:string|null;course_name:string;assigned_hours:number};type Group={id:string;name:string;class_id:string|null;required_simultaneous:boolean;note:string|null};type Subgroup={id:string;class_id:string;subgroup_key:string;label:string|null};
const days=[1,2,3,4,5,6,7];const dayName:Record<number,string>={1:"Pzt",2:"Sal",3:"Çar",4:"Per",5:"Cum",6:"Cmt",7:"Paz"};
const nums=(text:string)=>text.split(/[,+\s]+/).map(x=>Number(x)).filter(x=>Number.isInteger(x)&&x>0);
function ScheduleRules(){
 const [teachers,setTeachers]=useState<Teacher[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [groups,setGroups]=useState<Group[]>([]);const [subgroups,setSubgroups]=useState<Subgroup[]>([]);const [message,setMessage]=useState<string|null>(null);
 const [teachingDays,setTeachingDays]=useState<number[]>([1,2,3,4,5]);const [periods,setPeriods]=useState(8);const [lunch,setLunch]=useState("");
 const [teacherId,setTeacherId]=useState("");const [maxWeekly,setMaxWeekly]=useState("");const [maxDaily,setMaxDaily]=useState("");const [maxConsecutive,setMaxConsecutive]=useState("4");const [maxDays,setMaxDays]=useState("");const [minDays,setMinDays]=useState("");const [freeDay,setFreeDay]=useState("");const [unavailDay,setUnavailDay]=useState(1);const [unavailPeriod,setUnavailPeriod]=useState(1);const [prefType,setPrefType]=useState<"prefer"|"avoid">("avoid");const [prefWeight,setPrefWeight]=useState(5);
 const [courseId,setCourseId]=useState("");const [blockPattern,setBlockPattern]=useState("");const [maxPerDay,setMaxPerDay]=useState("");const [minSpread,setMinSpread]=useState("");const [preferredDays,setPreferredDays]=useState("");const [prohibitedDays,setProhibitedDays]=useState("");const [preferredPeriods,setPreferredPeriods]=useState("");const [prohibitedPeriods,setProhibitedPeriods]=useState("");const [avoidLast,setAvoidLast]=useState(false);
 const [groupName,setGroupName]=useState("");const [groupClass,setGroupClass]=useState("");const [selectedGroup,setSelectedGroup]=useState("");const [memberAssignment,setMemberAssignment]=useState("");const [memberSubgroup,setMemberSubgroup]=useState("");const [memberBlock,setMemberBlock]=useState(1);
 const load=useCallback(async()=>{const [t,c,a,g,sg,tp]=await Promise.all([supabase.from("profiles").select("user_id,full_name").eq("role","teacher").order("full_name"),supabase.from("course_catalog").select("id,name").eq("active",true).order("name"),supabase.from("schedule_assignment_options").select("teacher_assignment_id,teacher_name,class_id,composite_key,course_name,assigned_hours").order("composite_key"),supabase.from("schedule_sync_groups").select("id,name,class_id,required_simultaneous,note").eq("active",true).order("name"),supabase.from("class_subgroups").select("id,class_id,subgroup_key,label").eq("active",true),supabase.rpc("get_active_schedule_time_profile")]);setTeachers((t.data??[]) as Teacher[]);setCourses((c.data??[]) as Course[]);setAssignments((a.data??[]) as Assignment[]);setGroups((g.data??[]) as Group[]);setSubgroups((sg.data??[]) as Subgroup[]);if(tp.data){setTeachingDays(tp.data.teaching_days??[1,2,3,4,5]);setPeriods(tp.data.periods_per_day??8);setLunch(tp.data.lunch_after_period?String(tp.data.lunch_after_period):"")}},[]);useEffect(()=>{void load()},[load]);
 async function saveTime(){const {data:current}=await supabase.from("schedule_time_profiles").select("id").eq("active",true).maybeSingle();if(current?.id){const {error}=await supabase.from("schedule_time_profiles").update({teaching_days:teachingDays,periods_per_day:periods,lunch_after_period:lunch?Number(lunch):null,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return setMessage(error.message)}setMessage("Merkezi okul zaman şablonu kaydedildi.")}
 async function loadTeacher(id:string){setTeacherId(id);const {data}=await supabase.from("teacher_schedule_constraints").select("max_weekly_hours,max_daily_hours,max_consecutive_hours,max_working_days,min_working_days,preferred_free_day").eq("teacher_id",id).maybeSingle();setMaxWeekly(data?.max_weekly_hours?String(data.max_weekly_hours):"");setMaxDaily(data?.max_daily_hours?String(data.max_daily_hours):"");setMaxConsecutive(String(data?.max_consecutive_hours??4));setMaxDays(data?.max_working_days?String(data.max_working_days):"");setMinDays(data?.min_working_days?String(data.min_working_days):"");setFreeDay(data?.preferred_free_day?String(data.preferred_free_day):"")}
 async function saveTeacher(){if(!teacherId)return;const {error}=await supabase.from("teacher_schedule_constraints").upsert({teacher_id:teacherId,max_weekly_hours:maxWeekly?Number(maxWeekly):null,max_daily_hours:maxDaily?Number(maxDaily):null,max_consecutive_hours:Number(maxConsecutive||4),max_working_days:maxDays?Number(maxDays):null,min_working_days:minDays?Number(minDays):null,preferred_free_day:freeDay?Number(freeDay):null,updated_at:new Date().toISOString()},{onConflict:"teacher_id"});setMessage(error?error.message:"Öğretmen çalışma sınırları kaydedildi.")}
 async function addUnavailable(){if(!teacherId)return;const {error}=await supabase.from("teacher_unavailability").upsert({teacher_id:teacherId,weekday:unavailDay,period:unavailPeriod,reason:"program kuralı",active:true},{onConflict:"teacher_id,weekday,period"});setMessage(error?error.message:"Öğretmenin kesin uygun olmadığı saat kaydedildi.")}
 async function addPreference(){if(!teacherId)return;const {error}=await supabase.from("teacher_schedule_preferences").upsert({teacher_id:teacherId,weekday:unavailDay,period:unavailPeriod,preference:prefType,weight:prefWeight,active:true},{onConflict:"teacher_id,weekday,period,preference"});setMessage(error?error.message:"Öğretmen soft tercihi kaydedildi.")}
 async function loadCourse(id:string){setCourseId(id);const {data}=await supabase.from("course_schedule_rules").select("*").eq("course_id",id).maybeSingle();setBlockPattern((data?.block_pattern??[]).join("+"));setMaxPerDay(data?.max_per_day?String(data.max_per_day):"");setMinSpread(data?.min_distinct_days?String(data.min_distinct_days):"");setPreferredDays((data?.preferred_days??[]).join(","));setProhibitedDays((data?.prohibited_days??[]).join(","));setPreferredPeriods((data?.preferred_periods??[]).join(","));setProhibitedPeriods((data?.prohibited_periods??[]).join(","));setAvoidLast(Boolean(data?.avoid_last_period))}
 async function saveCourse(){if(!courseId)return;const {error}=await supabase.from("course_schedule_rules").upsert({course_id:courseId,block_pattern:nums(blockPattern),max_per_day:maxPerDay?Number(maxPerDay):null,min_distinct_days:minSpread?Number(minSpread):null,preferred_days:nums(preferredDays),prohibited_days:nums(prohibitedDays),preferred_periods:nums(preferredPeriods),prohibited_periods:nums(prohibitedPeriods),avoid_last_period:avoidLast,active:true,updated_at:new Date().toISOString()},{onConflict:"course_id"});setMessage(error?error.message:"Ders blok ve zaman kuralları kaydedildi.")}
 async function createGroup(){if(!groupName.trim())return;const {error}=await supabase.from("schedule_sync_groups").insert({name:groupName.trim(),class_id:groupClass||null,required_simultaneous:true,active:true});if(error)return setMessage(error.message);setGroupName("");setMessage("Eşzamanlı grup oluşturuldu.");await load()}
 const assignment=assignments.find(a=>a.teacher_assignment_id===memberAssignment);const allowedSubgroups=assignment?subgroups.filter(s=>s.class_id===assignment.class_id):[];
 async function addMember(){if(!selectedGroup||!memberAssignment)return;const {error}=await supabase.from("schedule_sync_group_members").insert({sync_group_id:selectedGroup,teacher_assignment_id:memberAssignment,subgroup_id:memberSubgroup||null,block_hours:memberBlock});setMessage(error?error.message:"Eşzamanlı grup üyesi kaydedildi.")}
 const classOptions=useMemo(()=>Array.from(new Map(assignments.map(a=>[a.class_id,a.composite_key??a.class_id])).entries()),[assignments]);
 return <AppShell title="Program Kuralları" subtitle="Hard constraint · soft tercih · blok · eşzamanlı grup" action={<SlidersHorizontal className="size-5"/>}>{message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}<Tabs defaultValue="time"><TabsList className="grid h-auto w-full grid-cols-2 sm:grid-cols-4"><TabsTrigger value="time">Zaman</TabsTrigger><TabsTrigger value="teacher">Öğretmen</TabsTrigger><TabsTrigger value="course">Ders</TabsTrigger><TabsTrigger value="sync">Eşzamanlı</TabsTrigger></TabsList>
 <TabsContent value="time" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><CalendarClock className="size-4"/>Merkezi Okul Zaman Şablonu</h2><div className="mt-3 flex flex-wrap gap-2">{days.map(d=><label key={d} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" checked={teachingDays.includes(d)} onChange={e=>setTeachingDays(e.target.checked?[...teachingDays,d].sort():teachingDays.filter(x=>x!==d))}/>{dayName[d]}</label>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label>Günlük ders saati</Label><Input type="number" min={1} max={12} value={periods} onChange={e=>setPeriods(Number(e.target.value))}/></div><div><Label>Öğle arası hangi dersten sonra?</Label><Input type="number" min={1} max={11} value={lunch} onChange={e=>setLunch(e.target.value)}/></div></div><Button className="mt-3" onClick={()=>void saveTime()}>Zaman Şablonunu Kaydet</Button></section></TabsContent>
 <TabsContent value="teacher" className="mt-4 space-y-4"><section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><Users className="size-4"/>Öğretmen Çalışma Sınırları</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={teacherId} onChange={e=>void loadTeacher(e.target.value)}><option value="">Öğretmen seçiniz</option>{teachers.map(t=><option key={t.user_id} value={t.user_id}>{t.full_name}</option>)}</select><div className="mt-3 grid gap-3 sm:grid-cols-3"><div><Label>Haftalık azami</Label><Input value={maxWeekly} onChange={e=>setMaxWeekly(e.target.value)}/></div><div><Label>Günlük azami</Label><Input value={maxDaily} onChange={e=>setMaxDaily(e.target.value)}/></div><div><Label>Ardışık azami</Label><Input value={maxConsecutive} onChange={e=>setMaxConsecutive(e.target.value)}/></div><div><Label>Azami çalışma günü</Label><Input value={maxDays} onChange={e=>setMaxDays(e.target.value)}/></div><div><Label>Asgari çalışma günü</Label><Input value={minDays} onChange={e=>setMinDays(e.target.value)}/></div><div><Label>Tercih edilen boş gün (1-7)</Label><Input value={freeDay} onChange={e=>setFreeDay(e.target.value)}/></div></div><Button className="mt-3" onClick={()=>void saveTeacher()}>Sınırları Kaydet</Button></section><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Kesin Uygun Değil / Soft Tercih</h3><div className="mt-3 grid gap-3 sm:grid-cols-4"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={unavailDay} onChange={e=>setUnavailDay(Number(e.target.value))}>{days.map(d=><option key={d} value={d}>{dayName[d]}</option>)}</select><Input type="number" min={1} max={12} value={unavailPeriod} onChange={e=>setUnavailPeriod(Number(e.target.value))}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={prefType} onChange={e=>setPrefType(e.target.value as "prefer"|"avoid")}><option value="avoid">Kaçın</option><option value="prefer">Tercih et</option></select><Input type="number" min={1} max={100} value={prefWeight} onChange={e=>setPrefWeight(Number(e.target.value))}/></div><div className="mt-3 flex gap-2"><Button variant="destructive" onClick={()=>void addUnavailable()}>Kesin Uygun Değil</Button><Button variant="outline" onClick={()=>void addPreference()}>Soft Tercih Ekle</Button></div></section></TabsContent>
 <TabsContent value="course" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Ders Dağılım / Blok Kuralları</h2><select className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={courseId} onChange={e=>void loadCourse(e.target.value)}><option value="">Ders seçiniz</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label>Blok deseni (örn. 2+2)</Label><Input value={blockPattern} onChange={e=>setBlockPattern(e.target.value)}/></div><div><Label>Günlük azami saat</Label><Input value={maxPerDay} onChange={e=>setMaxPerDay(e.target.value)}/></div><div><Label>En az kaç güne yayılsın?</Label><Input value={minSpread} onChange={e=>setMinSpread(e.target.value)}/></div><div><Label>Tercih edilen günler (1,3,5)</Label><Input value={preferredDays} onChange={e=>setPreferredDays(e.target.value)}/></div><div><Label>Yasak günler</Label><Input value={prohibitedDays} onChange={e=>setProhibitedDays(e.target.value)}/></div><div><Label>Tercih edilen ders saatleri</Label><Input value={preferredPeriods} onChange={e=>setPreferredPeriods(e.target.value)}/></div><div><Label>Yasak ders saatleri</Label><Input value={prohibitedPeriods} onChange={e=>setProhibitedPeriods(e.target.value)}/></div><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={avoidLast} onChange={e=>setAvoidLast(e.target.checked)}/>Son dersten kaçın</label></div><Button className="mt-3" onClick={()=>void saveCourse()}>Ders Kuralını Kaydet</Button></section></TabsContent>
 <TabsContent value="sync" className="mt-4 space-y-4"><section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><Link2 className="size-4"/>Eşzamanlı Grup Oluştur</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input placeholder="Örn. 9/A Kur'an Grup Dersi" value={groupName} onChange={e=>setGroupName(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={groupClass} onChange={e=>setGroupClass(e.target.value)}><option value="">Sınıf opsiyonel</option>{classOptions.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></div><Button className="mt-3 gap-2" onClick={()=>void createGroup()}><Plus className="size-4"/>Grup Oluştur</Button></section><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Gruba Öğretmen-Ders Üyesi Ekle</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={selectedGroup} onChange={e=>setSelectedGroup(e.target.value)}><option value="">Eşzamanlı grup</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={memberAssignment} onChange={e=>{setMemberAssignment(e.target.value);setMemberSubgroup("")}}><option value="">Sınıf · ders · öğretmen</option>{assignments.map(a=><option key={a.teacher_assignment_id} value={a.teacher_assignment_id}>{a.composite_key} · {a.course_name} · {a.teacher_name}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={memberSubgroup} onChange={e=>setMemberSubgroup(e.target.value)}><option value="">Tam sınıf / grup yok</option>{allowedSubgroups.map(s=><option key={s.id} value={s.id}>{s.label??s.subgroup_key}</option>)}</select><div><Label>Blok saati</Label><Input type="number" min={1} max={6} value={memberBlock} onChange={e=>setMemberBlock(Number(e.target.value))}/></div></div><Button className="mt-3" onClick={()=>void addMember()}>Üyeyi Ekle</Button></section></TabsContent>
 </Tabs><div className="mt-5 flex gap-2"><Button variant="ghost" onClick={()=>void load()} className="gap-2"><RefreshCw className="size-4"/>Yenile</Button><Link to="/schedule-solver"><Button variant="outline">Program Çözücü</Button></Link><Link to="/schedule-validation"><Button variant="outline">Doğrulama</Button></Link></div></AppShell>}
