import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, FileUp, Pencil, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { parseScheduleImport } from "@/lib/schedule-import";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/schedule")({ head:()=>({meta:[{title:"Haftalık Ders Programı — OkulOS"}]}), component:ScheduleManager });

type AssignmentOption={teacher_assignment_id:string;teacher_id:string;teacher_name:string|null;assigned_hours:number;requirement_id:string;class_id:string;class_name:string;composite_key:string|null;course_id:string;course_name:string;placed_hours:number;remaining_hours:number};
type Classroom={id:string;name:string;room_type:string;capacity:number;department:string|null};
type Subgroup={id:string;class_id:string;subgroup_key:string;label:string|null};
type Row={id:string;teacher_id:string;class_id:string|null;weekday:number;period:number;class_name:string;subject:string;classroom_id:string|null;classroom:string|null;subgroup_id:string|null;subgroup_key:string|null;is_group_split:boolean;locked:boolean;teacher_assignment_id:string|null};
type TimeProfile={teaching_days:number[];periods_per_day:number;lunch_after_period:number|null};
type Integrity={severity:"error"|"warning";code:string;affected_count:number;detail:string};
type Editor={id?:string;assignmentId:string;weekday:number;period:number;classroomId:string;subgroupId:string;locked:boolean};
const dayName:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};

function translateError(message?:string){const t=message??"";const map:Record<string,string>={SCHEDULE_SEMANTIC_LINK_REQUIRED:"Ders programı satırı müfredat ve öğretmen atamasına bağlı olmak zorunda.",TEACHER_ASSIGNMENT_HOURS_EXCEEDED:"Bu öğretmen-ders atamasının haftalık saati zaten tamamlandı.",TEACHER_DAILY_LIMIT_EXCEEDED:"Öğretmenin günlük azami ders saati aşılıyor.",TEACHER_MAX_WORKING_DAYS_EXCEEDED:"Öğretmenin azami çalışma günü sayısı aşılıyor.",COURSE_DAY_PROHIBITED:"Bu ders seçilen günde yapılamaz.",COURSE_PERIOD_PROHIBITED:"Bu ders seçilen saatte yapılamaz.",COURSE_DAILY_LIMIT_EXCEEDED:"Bu dersin günlük azami saati aşılıyor.",TEACHER_DOUBLE_BOOKING:"Öğretmen aynı saatte başka derste.",TEACHER_UNAVAILABLE:"Öğretmen bu saatte uygun değil.",TEACHER_CONSECUTIVE_LIMIT_EXCEEDED:"Öğretmenin ardışık ders sınırı aşılıyor.",ROOM_DOUBLE_BOOKING:"Derslik aynı saatte kullanımda.",ROOM_CAPACITY_EXCEEDED:"Derslik kapasitesi yetersiz.",ROOM_TYPE_MISMATCH:"Derslik türü ders kuralına uygun değil.",ROOM_DEPARTMENT_MISMATCH:"Derslik bölümü ders kuralına uygun değil.",ROOM_HARDWARE_MISMATCH:"Derslikte gerekli donanım yok.",CLASS_DOUBLE_BOOKING:"Sınıf aynı saatte başka derste.",STUDENT_GROUP_CONFLICT:"Öğrenci grupları aynı saatte çakışıyor.",SUBGROUP_CLASS_MISMATCH:"Alt grup seçilen sınıfa ait değil.",IMPORT_ASSIGNMENT_NOT_FOUND:"İçe aktarılan satır müfredat/öğretmen atamasında bulunamadı.",IMPORT_ASSIGNMENT_AMBIGUOUS:"İçe aktarılan satır birden fazla atamayla eşleşiyor; veri netleştirilmeli."};for(const [k,v] of Object.entries(map))if(t.includes(k))return v;return t||"Ders programı işlemi tamamlanamadı."}

function ScheduleManager(){
 const [assignments,setAssignments]=useState<AssignmentOption[]>([]);const [rooms,setRooms]=useState<Classroom[]>([]);const [subgroups,setSubgroups]=useState<Subgroup[]>([]);const [rows,setRows]=useState<Row[]>([]);const [profile,setProfile]=useState<TimeProfile>({teaching_days:[1,2,3,4,5],periods_per_day:8,lunch_after_period:null});const [integrity,setIntegrity]=useState<Integrity[]>([]);
 const [teacherFilter,setTeacherFilter]=useState("");const [classFilter,setClassFilter]=useState("");const [editor,setEditor]=useState<Editor|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{const [a,r,g,s,p,i]=await Promise.all([
  supabase.from("schedule_assignment_options").select("*").order("composite_key").order("course_name"),
  supabase.from("classrooms").select("id,name,room_type,capacity,department").eq("active",true).order("name"),
  supabase.from("class_subgroups").select("id,class_id,subgroup_key,label").eq("active",true).order("subgroup_key"),
  supabase.from("teacher_schedule").select("id,teacher_id,class_id,weekday,period,class_name,subject,classroom_id,classroom,subgroup_id,subgroup_key,is_group_split,locked,teacher_assignment_id").eq("active",true).order("weekday").order("period"),
  supabase.rpc("get_active_schedule_time_profile"),supabase.rpc("get_schedule_integrity_report")]);
  if(a.error||r.error||g.error||s.error){setError("Program verileri yüklenemedi.");return;}setAssignments((a.data??[]) as AssignmentOption[]);setRooms((r.data??[]) as Classroom[]);setSubgroups((g.data??[]) as Subgroup[]);setRows((s.data??[]) as Row[]);if(p.data)setProfile(p.data as TimeProfile);setIntegrity((i.data??[]) as Integrity[]);
 },[]);
 useEffect(()=>{void load();const ch=supabase.channel("schedule-v2-live").on("postgres_changes",{event:"*",schema:"public",table:"teacher_schedule"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[load]);
 const teacherNames=useMemo(()=>Array.from(new Map(assignments.map(a=>[a.teacher_id,a.teacher_name??"Öğretmen"])).entries()),[assignments]);const classNames=useMemo(()=>Array.from(new Map(assignments.map(a=>[a.class_id,a.composite_key??a.class_name])).entries()),[assignments]);
 const filtered=useMemo(()=>rows.filter(r=>(!teacherFilter||r.teacher_id===teacherFilter)&&(!classFilter||r.class_id===classFilter)),[rows,teacherFilter,classFilter]);const optionMap=useMemo(()=>Object.fromEntries(assignments.map(a=>[a.teacher_assignment_id,a])),[assignments]);const selected=editor?optionMap[editor.assignmentId]:undefined;const editorGroups=selected?subgroups.filter(g=>g.class_id===selected.class_id):[];
 const periods=Array.from({length:profile.periods_per_day},(_,i)=>i+1);
 function openNew(day=profile.teaching_days[0]??1,period=1){setEditor({assignmentId:"",weekday:day,period,classroomId:"",subgroupId:"",locked:false});setError(null)}
 function edit(r:Row){setEditor({id:r.id,assignmentId:r.teacher_assignment_id??"",weekday:r.weekday,period:r.period,classroomId:r.classroom_id??"",subgroupId:r.subgroup_id??"",locked:r.locked})}
 async function save(){if(!editor?.assignmentId)return setError("Sınıf · ders · öğretmen ataması seçilmelidir.");setBusy(true);setError(null);const {error:e}=await supabase.rpc("upsert_schedule_slot_v2",{p_teacher_assignment_id:editor.assignmentId,p_weekday:editor.weekday,p_period:editor.period,p_classroom_id:editor.classroomId||null,p_subgroup_id:editor.subgroupId||null,p_schedule_id:editor.id||null,p_locked:editor.locked,p_source_kind:"manual"});setBusy(false);if(e)return setError(translateError(e.message));setEditor(null);setSuccess("Ders, müfredat ve öğretmen atamasıyla bağlı olarak kaydedildi.");await load()}
 async function remove(id:string){const {error:e}=await supabase.from("teacher_schedule").delete().eq("id",id);if(e)return setError(translateError(e.message));setSuccess("Satır silindi. Bütünlük göstergesi eksik saati hemen gösterecek.");await load()}
 async function importFile(file:File){setBusy(true);setError(null);try{const parsed=await parseScheduleImport(file);const ext=file.name.split(".").pop()?.toLowerCase()??"";const {data,error:e}=await supabase.rpc("import_weekly_schedule",{p_file_name:file.name,p_file_type:ext,p_rows:parsed});if(e)throw e;const result=Array.isArray(data)?data[0]:data;setSuccess(`${result?.imported_rows??parsed.length} satır müfredat ve öğretmen atamasıyla eşleştirilerek aktarıldı.`);await load()}catch(e){setError(translateError(e instanceof Error?e.message:String(e)))}finally{setBusy(false);if(fileRef.current)fileRef.current.value=""}}
 const errorCount=integrity.filter(i=>i.severity==="error").reduce((n,i)=>n+i.affected_count,0);
 return <AppShell title="Haftalık Ders Programı" subtitle="Müfredat bağlantılı · hard constraint · anlık bütünlük">
  <div className="flex flex-wrap gap-2"><Button onClick={()=>openNew()} className="gap-2"><Plus className="size-4"/>Ders Ekle</Button><Button variant="outline" onClick={()=>fileRef.current?.click()} disabled={busy} className="gap-2"><FileUp className="size-4"/>e-Okul/Excel İçe Aktar</Button><Button variant="outline" onClick={()=>void load()} className="gap-2"><RefreshCw className="size-4"/>Yenile</Button><Link to="/schedule-validation"><Button variant={errorCount?"destructive":"outline"} className="gap-2"><ShieldCheck className="size-4"/>{errorCount?`${errorCount} Bütünlük Sorunu`:"Program Doğrulandı"}</Button></Link><input ref={fileRef} className="hidden" type="file" accept=".xlsx,.xls,.csv,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/></div>
  {success?<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>{success}</div>:null}{error?<div className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle className="mr-2 inline size-4"/>{error}</div>:null}
  <div className="mt-4 grid gap-2 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={teacherFilter} onChange={e=>setTeacherFilter(e.target.value)}><option value="">Tüm öğretmenler</option>{teacherNames.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="">Tüm sınıflar</option>{classNames.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></div>
  <div className="mt-4 overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[900px] text-sm"><thead><tr className="bg-muted/40"><th className="p-2 text-left">Saat</th>{profile.teaching_days.map(d=><th key={d} className="p-2 text-left">{dayName[d]??d}</th>)}</tr></thead><tbody>{periods.map(period=><tr key={period} className="border-t"><td className="p-2 font-semibold">{period}</td>{profile.teaching_days.map(day=>{const slot=filtered.filter(r=>r.weekday===day&&r.period===period);return <td key={day} className="min-w-[170px] p-2 align-top"><button type="button" onClick={()=>openNew(day,period)} className="mb-1 text-[11px] text-primary">+ ekle</button>{slot.map(r=><div key={r.id} className="mb-1 rounded-lg border bg-background p-2"><div className="flex justify-between gap-2"><div><b>{r.class_name}</b> · {r.subject}<div className="text-[11px] text-muted-foreground">{optionMap[r.teacher_assignment_id??""]?.teacher_name??"—"}{r.classroom?` · ${r.classroom}`:""}{r.subgroup_key?` · ${r.subgroup_key}`:""}</div></div><div className="flex"><Button size="icon" variant="ghost" onClick={()=>edit(r)}><Pencil className="size-3.5"/></Button><Button size="icon" variant="ghost" onClick={()=>void remove(r.id)}><Trash2 className="size-3.5"/></Button></div></div>{r.locked?<Badge variant="secondary" className="mt-1">Kilitli</Badge>:null}</div>)}</td>})}</tr>)}</tbody></table></div>
  <Dialog open={Boolean(editor)} onOpenChange={o=>{if(!o)setEditor(null)}}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{editor?.id?"Dersi Düzenle":"Ders Ekle"}</DialogTitle><DialogDescription>Ders adı serbest yazılmaz; müfredat ve öğretmen atamasından seçilir.</DialogDescription></DialogHeader>{editor?<div className="space-y-3"><div><Label>Sınıf · Ders · Öğretmen</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor.assignmentId} onChange={e=>setEditor({...editor,assignmentId:e.target.value,subgroupId:""})}><option value="">Seçiniz</option>{assignments.map(a=><option key={a.teacher_assignment_id} value={a.teacher_assignment_id}>{a.composite_key??a.class_name} · {a.course_name} · {a.teacher_name} · {a.placed_hours}/{a.assigned_hours}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><Label>Gün</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor.weekday} onChange={e=>setEditor({...editor,weekday:Number(e.target.value)})}>{profile.teaching_days.map(d=><option key={d} value={d}>{dayName[d]}</option>)}</select></div><div><Label>Ders Saati</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor.period} onChange={e=>setEditor({...editor,period:Number(e.target.value)})}>{periods.map(p=><option key={p} value={p}>{p}</option>)}</select></div></div><div><Label>Derslik</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor.classroomId} onChange={e=>setEditor({...editor,classroomId:e.target.value})}><option value="">Otomatik / boş</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name} · {r.capacity}</option>)}</select></div><div><Label>Alt Grup</Label><select disabled={!selected} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={editor.subgroupId} onChange={e=>setEditor({...editor,subgroupId:e.target.value})}><option value="">Tam sınıf</option>{editorGroups.map(g=><option key={g.id} value={g.id}>{g.label??g.subgroup_key}</option>)}</select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editor.locked} onChange={e=>setEditor({...editor,locked:e.target.checked})}/>Bu saati kilitle; otomatik çözücü yerini değiştirmesin.</label><Button className="w-full" onClick={()=>void save()} disabled={busy}>{busy?"Kaydediliyor...":"Kaydet"}</Button></div>:null}</DialogContent></Dialog>
 </AppShell>
}
