import {createFileRoute,Link} from "@tanstack/react-router";
import {useEffect,useState} from "react";
import {Activity,Cpu,Server,ShieldCheck,Zap} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {supabase} from "@/lib/supabase";
export const Route=createFileRoute("/schedule-hybrid-health")({head:()=>({meta:[{title:"Hybrid Compute Sağlığı — OkulOS"}]}),component:HybridHealth});
type Worker={worker_key:string;display_name:string;worker_type:"DB"|"CPU"|"GPU";health:string;max_parallel:number;current_load:number|string;avg_latency_ms:number|null;lease_seconds:number;heartbeat_fresh:boolean;available_slots:number;load_ratio:number|string;recommended:boolean};
type Metric={metric:string;value:number|string;detail:string};
const label:Record<string,string>={FRESH_EXTERNAL_WORKERS:"Hazır harici worker",ACTIVE_JOBS:"Aktif job",PENDING_AUDIT:"Audit bekleyen",ACCEPTED_TODAY:"Bugün kabul",REJECTED_OR_LATE_TODAY:"Bugün red/geç/tekrar"};
function HybridHealth(){const[workers,setWorkers]=useState<Worker[]>([]),[metrics,setMetrics]=useState<Metric[]>([]),[error,setError]=useState<string|null>(null);async function load(){const[w,m]=await Promise.all([supabase.rpc("get_schedule_compute_capabilities_v2"),supabase.rpc("get_schedule_hybrid_health_v2")]);if(w.error||m.error){setError((w.error??m.error)?.message??"Hybrid compute bilgisi okunamadı");return}setWorkers((w.data??[]) as Worker[]);setMetrics((m.data??[]) as Metric[]);setError(null)}useEffect(()=>{void load()},[]);return <AppShell title="Hybrid Compute Sağlığı" subtitle="Cloud DB + browser CPU/WebGPU + harici CPU/GPU · lease · budget · canonical server audit" action={<Activity className="size-5"/>}>
<div className="mb-3 flex flex-wrap gap-2"><Link to="/schedule-solver"><Button variant="outline">Çözücüye dön</Button></Link><Link to="/schedule-exact-oracle"><Button variant="outline">CP-SAT Oracle</Button></Link><Button variant="outline" onClick={()=>void load()}>Yenile</Button></div>{error?<div className="mb-3 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>:null}
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(x=><div key={x.metric} className="rounded-xl border p-4"><div className="text-2xl font-semibold">{Number(x.value)}</div><div className="font-medium">{label[x.metric]??x.metric}</div><div className="mt-1 text-xs text-muted-foreground">{x.detail}</div></div>)}</div>
<div className="mt-4 grid gap-3 lg:grid-cols-2">{workers.map(w=><div key={w.worker_key} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2">{w.worker_type==="DB"?<Server className="size-5"/>:<Cpu className="size-5"/>}<div><div className="font-semibold">{w.display_name}</div><div className="text-xs text-muted-foreground">{w.worker_type} · {w.worker_key}</div></div></div><span className={`rounded-full px-2 py-1 text-xs ${w.recommended?"bg-primary/10 text-primary":"bg-muted text-muted-foreground"}`}>{w.recommended?"HAZIR":"BEKLEMEDE"}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div>Sağlık: <b>{w.health}</b></div><div>Heartbeat: <b>{w.heartbeat_fresh?"Taze":"Eski"}</b></div><div>Boş slot: <b>{w.available_slots}/{w.max_parallel}</b></div><div>Yük: <b>{Math.round(Number(w.load_ratio)*100)}%</b></div><div>Lease: <b>{w.lease_seconds}s</b></div><div>Ort. gecikme: <b>{w.avg_latency_ms??"—"} ms</b></div></div></div>)}</div>
<div className="mt-4 rounded-xl border bg-muted/30 p-4 text-sm"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-4"/>Canonical kabul zinciri</div><p className="mt-2 text-muted-foreground">Harici CPU/GPU yalnız ham ders satırları üretir. Sonuç; deadline/lease, fingerprint ve duplicate kontrolünden sonra Cloud tarafında oda ataması, HARD doğrulama, yerleşmeyen ders ve yeniden puanlama denetiminden geçmeden aday havuzuna alınmaz.</p><div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><Zap className="size-3"/>Timeout job'u açık bırakmaz; stale lease uygun worker'a yeniden atanabilir.</div></div>
</AppShell>}
