import {createFileRoute,Link} from "@tanstack/react-router";
import {useEffect,useState} from "react";
import {Braces,RefreshCw,ShieldCheck} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {supabase} from "@/lib/supabase";
export const Route=createFileRoute("/schedule-exact-oracle")({head:()=>({meta:[{title:"CP-SAT Exact Oracle — OkulOS"}]}),component:ExactOracle});
type Health={total_runs:number;optimal_runs:number;feasible_runs:number;unsupported_runs:number;latest?:{status?:string;objective?:number;best_bound?:number;gap?:number;wall_ms?:number;unsupported?:unknown[];created_at?:string}};
type Problem={schema:string;assignments?:unknown[];locked_rows?:unknown[];teacher_unavailability?:unknown[];planning_relations?:unknown[];student_conflict_weights?:unknown[];canonical_objective_order?:string[]};
function ExactOracle(){const[health,setHealth]=useState<Health|null>(null),[problem,setProblem]=useState<Problem|null>(null),[error,setError]=useState<string|null>(null);async function load(){const[h,p]=await Promise.all([supabase.rpc("get_schedule_exact_oracle_health_v1"),supabase.rpc("get_schedule_exact_oracle_problem_v1")]);if(h.error||p.error){setError((h.error??p.error)?.message??"Oracle bilgisi okunamadı");return}setHealth(h.data as Health);setProblem(p.data as Problem);setError(null)}useEffect(()=>{void load()},[]);const latest=health?.latest??{};return <AppShell title="CP-SAT Exact Oracle" subtitle="Canonical model export · OR-Tools CP-SAT · optimum/bound/gap · unsupported constraint guard" action={<Braces className="size-5"/>}>
<div className="mb-3 flex flex-wrap gap-2"><Link to="/schedule-hybrid-health"><Button variant="outline">Hybrid compute</Button></Link><Link to="/schedule-solver"><Button variant="outline">Çözücü</Button></Link><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Yenile</Button></div>{error?<div className="mb-3 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>:null}
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card title="Oracle run" value={health?.total_runs??0}/><Card title="Optimal" value={health?.optimal_runs??0}/><Card title="Feasible" value={health?.feasible_runs??0}/><Card title="Unsupported" value={health?.unsupported_runs??0}/></div>
<div className="mt-4 grid gap-3 lg:grid-cols-2"><section className="rounded-xl border p-4"><h2 className="font-semibold">Canonical export</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div>Assignments: <b>{problem?.assignments?.length??0}</b></div><div>Locks: <b>{problem?.locked_rows?.length??0}</b></div><div>Unavailability: <b>{problem?.teacher_unavailability?.length??0}</b></div><div>Relations: <b>{problem?.planning_relations?.length??0}</b></div><div>Student conflicts: <b>{problem?.student_conflict_weights?.length??0}</b></div><div>Schema: <b>{problem?.schema??"—"}</b></div></div><div className="mt-3 text-xs text-muted-foreground">Objective order: {(problem?.canonical_objective_order??[]).join(" → ")||"—"}</div></section>
<section className="rounded-xl border p-4"><h2 className="font-semibold">Son exact/bounded sonuç</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div>Status: <b>{latest.status??"—"}</b></div><div>Wall: <b>{latest.wall_ms??"—"} ms</b></div><div>Objective: <b>{latest.objective??"—"}</b></div><div>Best bound: <b>{latest.best_bound??"—"}</b></div><div>Gap: <b>{latest.gap==null?"—":`${(latest.gap*100).toFixed(2)}%`}</b></div><div>Unsupported: <b>{latest.unsupported?.length??0}</b></div></div></section></div>
<div className="mt-4 rounded-xl border bg-muted/30 p-4 text-sm"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-4"/>Exact iddia güvenliği</div><p className="mt-2 text-muted-foreground">CP-SAT yalnız birebir modellenen constraint alt-kümesinde OPTIMAL/FEASIBLE sonucu üretir. Desteklenmeyen HARD relation varsa run UNSUPPORTED olarak kaydedilir; OkulOS bunu tam canonical model optimumu diye göstermez. CP-SAT sonuçları yayınlama authority’si değildir ve uygulanmadan önce canonical server audit gerekir.</p></div>
</AppShell>}
function Card({title,value}:{title:string;value:number}){return <div className="rounded-xl border p-4"><div className="text-2xl font-semibold">{value}</div><div className="text-sm text-muted-foreground">{title}</div></div>}
