import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Cpu, Lightbulb, Lock, RefreshCw, Settings2, Sparkles, Unlock, Zap } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { ScheduleScenarioGrid } from "@/components/okulos/ScheduleScenarioGrid";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";
import { detectLocalScheduleCompute,type LocalComputeCapability } from "@/lib/schedule-local-compute";
import { runLocalScheduleSolve,type LocalSolveMode,type LocalSolveProgress } from "@/lib/schedule-local-solver";
import { runRemoteScheduleAccelerators } from "@/lib/schedule-remote-accelerator";

export const Route=createFileRoute("/schedule-solver")({head:()=>({meta:[{title:"Akıllı Ders Programı Dağıtımı — OkulOS"}]}),component:ScheduleSolver});
type Scenario={generation_group:string;scenario_id:string;scenario_no:number;score:number;unplaced_count:number;row_count:number;hard_issue_count:number;room_issue_count:number;status:string;basis_revision:number|null;current_revision:number;stale:boolean;applicable:boolean};
type CurrentRow={id:string;teacher_id:string;class_name:string;subject:string;weekday:number;period:number;locked:boolean;profiles?:{full_name:string|null}|null};
type Unplaced={id:string;scenario_id:string;subject:string;reason:string;block_hours:number;diagnostic:Record<string,number>};
type Settings={periods_per_day:number;max_same_course_per_day:number;gap_penalty:number;late_period_penalty:number;repeated_course_penalty:number};
type Prep={category:string;code:string;status:string;affected_count:number;detail:string};
type Worker={worker_key:string;display_name:string;worker_type:"DB"|"CPU"|"GPU";health:string;max_parallel:number;current_load:number|string;avg_latency_ms:number|null;recommended:boolean};
type Suggestion={id:string;scenario_id:string;rank:number;action_code:string;title:string;description:string;legal_safe:boolean;hard_rule_impact:boolean;estimated_gain:number|null};
type ComputeMode=LocalSolveMode|"DB";
const dayNames=["","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];
const diagLabel:Record<string,string>={teacher_busy:"Öğretmen dolu",class_busy:"Sınıf dolu",teacher_unavailable:"Öğretmen uygun değil",daily_limit:"Günlük limit",working_days_limit:"Çalışma günü limiti",consecutive_limit:"Ardışık ders limiti",course_time_rule:"Ders zaman kuralı",valid_windows:"Geçerli pencere",candidate_windows:"Toplam aday"};

function ScheduleSolver(){
 const [scenarios,setScenarios]=useState<Scenario[]>([]),[current,setCurrent]=useState<CurrentRow[]>([]),[unplaced,setUnplaced]=useState<Unplaced[]>([]),[prep,setPrep]=useState<Prep[]>([]),[workers,setWorkers]=useState<Worker[]>([]),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[workerProgress,setWorkerProgress]=useState<LocalSolveProgress[]>([]);
 const [settings,setSettings]=useState<Settings>({periods_per_day:8,max_same_course_per_day:2,gap_penalty:8,late_period_penalty:2,repeated_course_penalty:12});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[prepLoadError,setPrepLoadError]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[advanced,setAdvanced]=useState(false),[candidateCount,setCandidateCount]=useState(4),[computeMode,setComputeMode]=useState<ComputeMode>("AUTO"),[preserveManual,setPreserveManual]=useState(true),[localCap,setLocalCap]=useState<LocalComputeCapability|null>(null);
 const load=useCallback(async()=>{setLoaded(false);const [c,s,p,w]=await Promise.all([supabase.from("teacher_schedule").select("id,teacher_id,class_name,subject,weekday,period,locked,profiles!teacher_schedule_teacher_id_fkey(full_name)").eq("active",true).order("weekday").order("period"),supabase.from("schedule_generation_settings").select("periods_per_day,max_same_course_per_day,gap_penalty,late_period_penalty,repeated_course_penalty").eq("id",true).maybeSingle(),supabase.rpc("get_schedule_preparation_readiness"),supabase.rpc("get_schedule_compute_capabilities_v1")]);if(c.error){setError(`Çalışma programı okunamadı: ${c.error.message}`);setCurrent([])}else setCurrent((c.data??[]) as unknown as CurrentRow[]);if(s.error)setError(`Çözücü ayarları okunamadı: ${s.error.message}`);else if(s.data)setSettings(s.data as Settings);if(p.error){setPrep([]);setPrepLoadError(p.error.message)}else{setPrep((p.data??[]) as Prep[]);setPrepLoadError(null)}if(!w.error)setWorkers((w.data??[]) as Worker[]);setLoaded(true)},[]);
 useEffect(()=>{void load();void detectLocalScheduleCompute().then(setLocalCap)},[load]);
 async function toggleLock(row:CurrentRow){const {error:e}=await supabase.from("teacher_schedule").update({locked:!row.locked}).eq("id",row.id);if(e)return setError(e.message);await load()}
 async function saveSettings(){const invalid=settings.max_same_course_per_day<1||settings.gap_penalty<0||settings.late_period_penalty<0||settings.repeated_course_penalty<0;if(invalid)return setError("Kalite ağırlıkları geçersiz.");const {error:e}=await supabase.from("schedule_generation_settings").update({...settings,updated_at:new Date().toISOString()}).eq("id",true);if(e)return setError(e.message);setMessage("Kalite tercihleri kaydedildi.")}
 function progress(p:LocalSolveProgress){setWorkerProgress(old=>{const k=`${p.kind}-${p.worker}`,i=old.findIndex(x=>`${x.kind}-${x.worker}`===k);return i<0?[...old,p]:old.map((x,n)=>n===i?p:x)})}
 async function cloudCandidates(count:number){const batches=Math.max(1,Math.ceil(count/4)),out:string[]=[];const rs=await Promise.all(Array.from({length:batches},()=>supabase.rpc("generate_schedule_scenarios_v2")));const bad=rs.find(x=>x.error);if(bad?.error)throw bad.error;for(const r of rs)for(const x of (r.data??[]) as Array<{scenario_id:string}>)out.push(x.scenario_id);return out.slice(0,count)}
 async function generate(count=4){if(prepLoadError)return setError(`Hazırlık doğrulaması okunamadı: ${prepLoadError}`);if(prep.some(x=>x.status==="error"))return setError("Hazırlık sorunları çözülmeden dağıtım başlatılamaz.");if(computeMode==="GPU"&&!localCap?.webGpu)return setError("Bu cihazda yeterli WebGPU compute desteği bulunmadı. Hibrit/CPU/Cloud seçin.");setBusy(true);setError(null);setMessage(null);setScenarios([]);setUnplaced([]);setSuggestions([]);setWorkerProgress([]);try{
  if(preserveManual){const keep=await supabase.rpc("preserve_manual_schedule_v1",{p_preserve:true});if(keep.error)throw keep.error}
  const useCloud=computeMode==="AUTO"||computeMode==="HYBRID"||computeMode==="DB",useLocal=computeMode!=="DB",useRemote=(computeMode==="AUTO"||computeMode==="HYBRID")&&workers.some(w=>w.worker_type!=="DB"&&w.recommended);const cloudCount=useCloud?(useLocal?Math.max(2,Math.ceil(count/2)):count):0,localCount=useLocal?count:0;
  const [cloud,local,remote]=await Promise.all([useCloud?cloudCandidates(cloudCount):Promise.resolve([]),useLocal?runLocalScheduleSolve({candidateCount:localCount,mode:computeMode as LocalSolveMode,onProgress:progress}):Promise.resolve({scenarioIds:[],generated:0,complete:0,useGpu:false,capability:localCap}),useRemote?runRemoteScheduleAccelerators({candidateCount:count,onProgress:p=>progress({...p,worker:p.worker+100}),timeoutMs:30000}):Promise.resolve({scenarioIds:[],used:false})]);const ids=Array.from(new Set([...cloud,...local.scenarioIds,...remote.scenarioIds]));if(!ids.length&&useLocal){const fallback=await cloudCandidates(count);ids.push(...fallback);setMessage("Hızlandırıcılar uygulanabilir aday üretemedi; Cloud çözücü otomatik devraldı.")}if(!ids.length)throw new Error("Çözücü aday üretmedi.");
  const repaired=await Promise.all(ids.map(async id=>{const r=await supabase.rpc("repair_schedule_scenario_v2",{p_scenario_id:id});if(r.error)return r.error;const rs=await supabase.rpc("rescore_schedule_scenario_v2",{p_scenario_id:id});if(rs.error)return rs.error;await supabase.rpc("refresh_schedule_repair_suggestions_v1",{p_scenario_id:id});return null}));const repairError=repaired.find(Boolean);if(repairError)throw repairError;
  const [status,u,sg]=await Promise.all([supabase.from("schedule_scenario_status_v2").select("generation_group,scenario_id,scenario_no,score,row_count,unplaced_count,status,basis_revision,current_revision,stale,hard_issue_count,room_issue_count,applicable").in("scenario_id",ids).order("score"),supabase.from("schedule_unplaced_items").select("id,scenario_id,subject,reason,block_hours,diagnostic").in("scenario_id",ids),supabase.from("schedule_repair_suggestions").select("id,scenario_id,rank,action_code,title,description,legal_safe,hard_rule_impact,estimated_gain").in("scenario_id",ids).order("rank")]);if(status.error||u.error||sg.error)throw(status.error??u.error??sg.error);setScenarios((status.data??[]) as Scenario[]);setUnplaced((u.data??[]) as Unplaced[]);setSuggestions((sg.data??[]) as Suggestion[]);setMessage(`${ids.length} bağımsız aday yarıştı · Cloud ${cloud.length} · yerel ${local.scenarioIds.length}${local.useGpu?" GPU hızlandırmalı":""} · harici ${remote.scenarioIds.length}. Tümü server hard-audit’inden geçti.`)
 }catch(e){setError(`Dağıtım tamamlanamadı: ${e instanceof Error?e.message:String(e)}`)}finally{setBusy(false)}}
 async function apply(id:string){const selected=scenarios.find(s=>s.scenario_id===id);if(selected?.stale)return setError("Bu aday eski veriye ait; yeniden dağıtın.");if(!selected?.applicable)return setError("Hard hata, derslik sorunu veya yerleşmeyen ders bulunan aday uygulanamaz.");setBusy(true);setError(null);const restore=await supabase.rpc("create_schedule_restore_point",{p_label:"Senaryo uygulanmadan önce",p_reason:`Otomatik güvenlik noktası · ${id}`});if(restore.error){setBusy(false);return setError(`Geri dönüş noktası alınamadığı için uygulama durduruldu: ${restore.error.message}`)}const {data,error:e}=await supabase.rpc("apply_schedule_scenario",{p_scenario_id:id});setBusy(false);if(e)return setError(`Senaryo uygulanamadı: ${e.message}`);setMessage(`${Number(data??0)} ders uygulandı. Önceki program için geri dönüş noktası hazır.`);await load()}
 const lockedCount=useMemo(()=>current.filter(x=>x.locked).length,[current]),prepErrors=prep.filter(x=>x.status==="error"),prepReady=loaded&&!prepLoadError&&prepErrors.length===0,best=useMemo(()=>scenarios.find(x=>x.applicable&&!x.stale)??null,[scenarios]),activeWorker=workers.find(w=>w.recommended)??workers[0];
 const externalWorkers=useMemo(()=>workers.filter(w=>w.worker_type!=="DB"),[workers]);
 return <AppShell title="Akıllı Ders Programı Dağıtımı" subtitle="Cloud + yerel/harici CPU/GPU · sert kurallar · esnek tercihler · çoklu aday · güvenli manuel müdahale" action={<Sparkles className="size-5"/>}>
  <div className="grid gap-2 sm:grid-cols-5"><Link to="/schedule-preparation"><Button variant={prepLoadError||prepErrors.length?"destructive":"outline"} className="w-full">1 · Hazırlık {prepReady?"✓":""}</Button></Link><Link to="/schedule-rules"><Button variant="outline" className="w-full">2 · Kurallar</Button></Link><Button disabled={!prepReady||busy} onClick={()=>void generate(4)} className="w-full gap-2"><Zap className="size-4"/>3 · Hızlı Dağıt</Button><Link to="/schedule-scenario-comparison"><Button variant="outline" className="w-full">4 · Karşılaştır</Button></Link><Link to="/schedule"><Button variant="outline" className="w-full">5 · Elle Düzelt</Button></Link></div>
  {message?<div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
  <section className="mt-4 grid gap-3 md:grid-cols-3"><div className={`rounded-xl border p-4 ${prepReady?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><CheckCircle2 className="size-5"/><p className="mt-2 font-semibold">Veri hazırlığı</p><p className="text-xs">{prepReady?"Tüm zorunlu girdiler hazır.":`${prepErrors.length} sorun çözülmeli.`}</p></div><div className="rounded-xl border bg-card p-4"><Cpu className="size-5"/><p className="mt-2 font-semibold">Hesaplama kaynakları</p><p className="text-xs text-muted-foreground">Yerel CPU: {localCap?`${localCap.cpuThreads} mantıksal çekirdek · ${localCap.recommendedCpuWorkers} worker`:"ölçülüyor…"}</p><p className="text-xs text-muted-foreground">Yerel GPU: {localCap?.webGpu?(localCap.gpuName??"WebGPU hazır"):"WebGPU compute yok/yetersiz"}</p><p className="text-xs text-muted-foreground">Cloud: {activeWorker?`${activeWorker.display_name} · ${activeWorker.health}`:"hazır değil"}</p><div className="mt-1 space-y-1">{externalWorkers.length===0?<p className="text-xs text-muted-foreground">Harici hızlandırıcı: bağlı değil</p>:externalWorkers.map(w=><p key={w.worker_key} className="text-xs text-muted-foreground">{w.worker_type} · {w.display_name} · yük {Number(w.current_load)}/{w.max_parallel} · {w.avg_latency_ms!=null?`${w.avg_latency_ms} ms · `:""}{w.recommended?(w.health==="DEGRADED"?"zayıf (DEGRADED)":"çalışıyor (HEALTHY)"):"bayat/çevrimdışı · heartbeat gelmiyor"}</p>)}</div></div><div className="rounded-xl border bg-card p-4"><Lock className="size-5"/><p className="mt-2 font-semibold">Manuel koruma</p><p className="text-xs text-muted-foreground">{lockedCount} ders kilitli.</p><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={preserveManual} onChange={e=>setPreserveManual(e.target.checked)}/>Elle/sesle atananlara dokunma</label></div></section>
  {workerProgress.length?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Canlı dağıtım işçileri</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{workerProgress.map(p=><div key={`${p.kind}-${p.worker}`} className="rounded-lg border p-3 text-xs"><div className="flex justify-between"><b>{p.worker>=100?`Harici ${p.kind}-${p.worker-100}`:`${p.kind}-${p.worker}`}</b><span>{p.status}</span></div><div className="mt-2 h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${Math.min(100,Math.round(p.completed/Math.max(1,p.total)*100))}%`}}/></div><p className="mt-1 text-muted-foreground">{p.completed}/{p.total}{p.durationMs?` · ${p.durationMs} ms`:""}</p></div>)}</div></section>:null}
  <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Dağıtım</h2><p className="text-xs text-muted-foreground">AUTO: Cloud, yerel CPU/GPU ve bağlı harici hızlandırıcılar aynı anda aday yarıştırır.</p></div><div className="flex gap-2"><Button disabled={!prepReady||busy} onClick={()=>void generate(4)} className="gap-2"><Zap className="size-4"/>{busy?"Dağıtılıyor…":"Hızlı Dağıt"}</Button><Button variant="outline" onClick={()=>setAdvanced(v=>!v)}><Settings2 className="mr-1 size-4"/>{advanced?"Basit Görünüm":"Gelişmiş"}</Button></div></div>{advanced?<div className="mt-4 rounded-xl border bg-muted/20 p-4"><div className="grid gap-3 sm:grid-cols-3"><div><Label>Hesaplama</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={computeMode} onChange={e=>setComputeMode(e.target.value as ComputeMode)}><option value="AUTO">Otomatik · hepsini yarıştır</option><option value="HYBRID">Hibrit · Cloud + CPU/GPU</option><option value="CPU">Yerel CPU</option><option value="GPU" disabled={!localCap?.webGpu}>GPU öncelikli</option><option value="DB">Yalnız Cloud DB</option></select></div><div><Label>Aday sayısı</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={candidateCount} onChange={e=>setCandidateCount(Number(e.target.value))}><option value={4}>4 · hızlı</option><option value={8}>8 · dengeli</option><option value={12}>12 · derin arama</option></select></div><div><Label>Günlük aynı ders üst sınırı</Label><Input type="number" min={1} value={settings.max_same_course_per_day} onChange={e=>setSettings({...settings,max_same_course_per_day:Number(e.target.value)})}/></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Button variant="secondary" onClick={()=>void saveSettings()}>Tercihleri Kaydet</Button><Button disabled={!prepReady||busy} onClick={()=>void generate(candidateCount)}>{candidateCount} Adayı Yarıştır</Button></div></div>:null}</section>
  <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Kilitler</h2><p className="text-xs text-muted-foreground">İyi yerleşmiş veya elle düzeltilmiş dersleri kilitle; sonraki dağıtım dokunmasın.</p></div><span className="text-xs font-semibold">{lockedCount} kilit</span></div><div className="mt-3 max-h-48 overflow-auto rounded-lg border"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-2 text-left">Gün/Saat</th><th className="p-2 text-left">Sınıf</th><th className="p-2 text-left">Ders</th><th className="p-2 text-left">Öğretmen</th><th className="p-2">Kilit</th></tr></thead><tbody>{current.map(r=><tr key={r.id} className="border-b"><td className="p-2">{dayNames[r.weekday]} · {r.period}</td><td className="p-2">{r.class_name}</td><td className="p-2">{r.subject}</td><td className="p-2">{r.profiles?.full_name??"—"}</td><td className="p-2 text-center"><Button size="sm" variant={r.locked?"secondary":"ghost"} onClick={()=>void toggleLock(r)}>{r.locked?<Lock className="size-4"/>:<Unlock className="size-4"/>}</Button></td></tr>)}</tbody></table></div></section>
  {best?<div className="mt-4 rounded-xl border-2 border-emerald-400 bg-emerald-50 p-4"><CheckCircle2 className="mr-2 inline size-5 text-emerald-700"/><b>Uygulanabilir en iyi aday hazır.</b> Hard hata, yerleşmeyen ders ve derslik sorunu sıfır. <Button size="sm" className="ml-3" disabled={busy} onClick={()=>void apply(best.scenario_id)}>En İyiyi Uygula</Button></div>:null}
  <div className="mt-4 grid gap-3 lg:grid-cols-2">{scenarios.map((s,index)=>{const problems=unplaced.filter(u=>u.scenario_id===s.scenario_id),tips=suggestions.filter(x=>x.scenario_id===s.scenario_id);return <section key={s.scenario_id} className={s.stale?"rounded-xl border-2 border-red-300 p-4":s.applicable&&index===0?"rounded-xl border-2 border-emerald-400 bg-emerald-50/30 p-4":"rounded-xl border bg-card p-4"}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">Aday {index+1}{s.applicable&&index===0?" · Önerilen":""}</h3><p className="text-xs text-muted-foreground">Puan {s.score} · {s.row_count} ders</p></div>{s.applicable?<CheckCircle2 className="size-5 text-emerald-600"/>:<AlertTriangle className="size-5 text-amber-600"/>}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg border p-2"><b>{s.unplaced_count}</b><br/>Yerleşmeyen</div><div className="rounded-lg border p-2"><b>{s.hard_issue_count}</b><br/>Hard hata</div><div className="rounded-lg border p-2"><b>{s.room_issue_count}</b><br/>Derslik</div></div>{problems.slice(0,3).map(p=><div key={p.id} className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs"><b>{p.subject}</b> · {p.reason}<div className="mt-1 flex flex-wrap gap-1">{Object.entries(p.diagnostic??{}).filter(([,v])=>v>0).map(([k,v])=><span key={k} className="rounded bg-white px-2 py-1">{diagLabel[k]??k}: {v}</span>)}</div></div>)}{tips.length?<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3"><div className="flex items-center gap-1 text-xs font-semibold"><Lightbulb className="size-4"/>Çözüm önerileri</div>{tips.slice(0,3).map(t=><div key={t.id} className="mt-2 text-xs"><b>{t.title}</b><p className="text-muted-foreground">{t.description}</p><span className="text-[10px]">{t.legal_safe?"Mevzuat/hard güvenli":"Hard kural etkisi var"}</span></div>)}</div>:null}<ScheduleScenarioGrid scenarioId={s.scenario_id}/><Button className="mt-3 w-full" disabled={busy||!s.applicable} onClick={()=>void apply(s.scenario_id)}>Bu Adayı Uygula</Button></section>})}</div>
  {!scenarios.length?<div className="mt-4 rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Hızlı Dağıt ile başlayın. Cloud ve cihazınızdaki/bağlı hızlandırıcılardaki uygun hesap kaynakları adayları yarıştırır; sıkışırsa nedenini ve güvenli çözümü gösterir.</div>:null}<div className="mt-5 flex flex-wrap gap-2"><Button variant="ghost" className="gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button><Link to="/schedule-optimization"><Button variant="outline">Gelişmiş Optimizasyon</Button></Link><Link to="/schedule-history"><Button variant="outline">Geri Dönüş Noktaları</Button></Link></div>
 </AppShell>
}