import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Clock3, RefreshCw, RotateCcw, Save } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-history")({head:()=>({meta:[{title:"Program Geçmişi — OkulOS"}]}),component:ScheduleHistory});
type Point={id:string;label:string;reason:string;row_count:number;created_at:string;created_by:string|null};
function ScheduleHistory(){const [points,setPoints]=useState<Point[]>([]);const [label,setLabel]=useState("Manuel çalışma kopyası");const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const {data,error:e}=await supabase.from("schedule_restore_points").select("id,label,reason,row_count,created_at,created_by").order("created_at",{ascending:false}).limit(50);if(e)return setError("Program geçmişi okunamadı.");setPoints((data??[]) as Point[]);},[]);useEffect(()=>{void load();},[load]);
 async function snapshot(){setBusy(true);setError(null);const {error:e}=await supabase.rpc("create_schedule_restore_point",{p_label:label,p_reason:"manual"});setBusy(false);if(e)return setError("Geri dönüş noktası oluşturulamadı.");setMessage("Mevcut çalışma programı geri dönüş noktası olarak kaydedildi.");await load();}
 async function restore(id:string){if(!window.confirm("Bu program sürümüne dönülsün mü? Mevcut durum da otomatik olarak ayrıca kaydedilecektir."))return;setBusy(true);setError(null);const {data,error:e}=await supabase.rpc("restore_schedule_restore_point",{p_restore_point_id:id});setBusy(false);if(e)return setError(`Program geri yüklenemedi: ${e.message}`);setMessage(`${Number(data??0)} ders geri yüklendi. Önceki mevcut durum da yeni geri dönüş noktası olarak saklandı.`);await load();}
 return <AppShell title="Program Geçmişi" subtitle="Geri al · yeniden uygula · çalışma kopyaları" action={<Clock3 className="size-5"/>}><div className="grid gap-2 sm:grid-cols-3"><Link to="/schedule"><Button variant="outline" className="w-full">Çalışma Programı</Button></Link><Link to="/schedule-solver"><Button variant="outline" className="w-full">Program Çözücü</Button></Link><Link to="/schedule-archive"><Button variant="outline" className="w-full">Yayın Arşivi</Button></Link></div>{message?<div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
 <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Şimdi Geri Dönüş Noktası Al</h2><p className="mt-1 text-xs text-muted-foreground">Büyük manuel değişikliklerden önce çalışma programının tamamını saklayın.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Kopya adı"/><Button className="gap-2 sm:w-auto" onClick={()=>void snapshot()} disabled={busy}><Save className="size-4"/>Kopya Al</Button></div></section>
 <div className="mt-4 overflow-hidden rounded-xl border bg-card"><div className="border-b px-4 py-3"><h2 className="font-semibold">Geri Dönüş Noktaları</h2><p className="text-xs text-muted-foreground">Senaryo uygulamalarından önce otomatik, istediğiniz zaman manuel kopya alınır.</p></div><div className="divide-y">{points.map(p=><div key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{p.label}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(p.created_at).toLocaleString("tr-TR")} · {p.row_count} ders · {p.reason}</p></div><Button variant="outline" className="gap-2" disabled={busy} onClick={()=>void restore(p.id)}><RotateCcw className="size-4"/>Bu Sürüme Dön</Button></div>)}{!points.length?<p className="p-6 text-center text-sm text-muted-foreground">Henüz geri dönüş noktası yok.</p>:null}</div></div><Button variant="ghost" className="mt-4 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></AppShell>}
