import {createFileRoute,Link} from "@tanstack/react-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,BarChart3,CheckCircle2,RefreshCw} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {supabase} from "@/lib/supabase";
import {analyzeScheduleGenerationBottlenecks,type ScheduleRepairSignal,type ScheduleUnplacedDiagnostic} from "@/lib/schedule-generation-bottleneck-analyzer";
import {buildScheduleDiagnosticLadder,DIAGNOSTIC_LADDER_POLICY,firstPressureLayer} from "@/lib/schedule-diagnostic-ladder";

export const Route=createFileRoute("/schedule-analysis")({head:()=>({meta:[{title:"Program Darboğaz Analizi — OkulOS"}]}),component:ScheduleAnalysis});
type Prep={code:string;affected_count:number};type RelationSummary={hard:number;medium:number;soft:number;hard_violations:number};
function ScheduleAnalysis(){const [unplaced,setUnplaced]=useState<ScheduleUnplacedDiagnostic[]>([]),[suggestions,setSuggestions]=useState<ScheduleRepairSignal[]>([]),[prep,setPrep]=useState<Prep[]>([]),[relationSummary,setRelationSummary]=useState<RelationSummary>({hard:0,medium:0,soft:0,hard_violations:0}),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setBusy(true);setError(null);const [u,s,p,r]=await Promise.all([supabase.from("schedule_unplaced_items").select("id,scenario_id,subject,reason,block_hours,diagnostic").limit(500),supabase.from("schedule_repair_suggestions").select("scenario_id,action_code,title,legal_safe,hard_rule_impact,estimated_gain").limit(300),supabase.rpc("get_schedule_preparation_readiness"),supabase.rpc("get_schedule_current_generic_relation_summary_v1")]);setBusy(false);const e=u.error??s.error??p.error??r.error;if(e){setError(e.message??"Darboğaz verileri okunamadı.");return}setUnplaced((u.data??[]) as ScheduleUnplacedDiagnostic[]);setSuggestions((s.data??[]) as ScheduleRepairSignal[]);setPrep(((p.data??[]) as Array<{code:string;affected_count:number}>).map(x=>({code:x.code,affected_count:Number(x.affected_count??0)})));const rs=Array.isArray(r.data)?r.data[0]:r.data;if(rs)setRelationSummary({hard:Number(rs.hard??0),medium:Number(rs.medium??0),soft:Number(rs.soft??0),hard_violations:Number(rs.hard_violations??0)})},[]);useEffect(()=>{void load()},[load]);const analysis=useMemo(()=>analyzeScheduleGenerationBottlenecks(unplaced,suggestions),[unplaced,suggestions]);const ladder=useMemo(()=>buildScheduleDiagnosticLadder({preparation:prep,unplaced,mediumCount:relationSummary.medium,softCount:relationSummary.soft}),[prep,unplaced,relationSummary]);const firstPressure=firstPressureLayer(ladder);
 return <AppShell title="Program Darboğaz Analizi" subtitle="Çoklu aday + katmanlı canonical teşhis; HARD kurallar değişmeden kök nedeni küçült" action={<BarChart3 className="size-5"/>}>
  <div className="flex flex-wrap gap-2"><Link to="/schedule-preparation"><Button variant="outline">← Hazırlık</Button></Link><Link to="/schedule-time-map"><Button variant="outline">Zaman Haritası</Button></Link><Link to="/schedule-solver"><Button variant="outline">Çözücü</Button></Link><Button variant="outline" disabled={busy} onClick={()=>void load()} className="gap-2"><RefreshCw className="size-4"/>{busy?"Analiz ediliyor…":"Yeniden Analiz Et"}</Button></div>
  {error?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle className="mr-2 inline size-4"/>{error}</div>:null}
  <div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.scenarioCount}</b><p className="text-sm text-muted-foreground">yerleşmeyen ders üreten aday</p></div><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.unplacedCount}</b><p className="text-sm text-muted-foreground">yerleşmeyen kayıt</p></div><div className="rounded-xl border bg-card p-4"><b className="text-2xl">{analysis.structural.length}</b><p className="text-sm text-muted-foreground">tekrarlayan yapısal darboğaz</p></div><div className="rounded-xl border bg-card p-4"><b className="text-lg">{firstPressure?.label??"Temiz"}</b><p className="text-sm text-muted-foreground">ilk baskı katmanı</p></div></div>
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Diagnostic Ladder</h2><p className="mt-1 text-sm text-muted-foreground">aSc Extended Tests fikrinin fail-safe karşılığı. Katmanlar sırayla ölçülür; production solve içinde hiçbir HARD katman kapatılmaz.</p><div className="mt-3 space-y-2">{ladder.map((x,i)=><div key={x.key} className={`rounded-lg border p-3 ${x.status==="pressure"?"border-amber-300 bg-amber-50/40":""}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><b className="text-sm">{i+1}. {x.label}</b><p className="mt-1 text-xs text-muted-foreground">{x.explanation}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{x.status==="pressure"?`${x.signalCount} baskı":"Temiz"}</span></div>{x.signals.length?<div className="mt-2 flex flex-wrap gap-1">{x.signals.map(s=><span key={s} className="rounded border bg-background px-2 py-1 text-[10px]">{s}</span>)}</div>:null}</div>)}</div><p className="mt-3 rounded-lg bg-muted/40 p-3 text-xs"><b>Güvenlik:</b> {DIAGNOSTIC_LADDER_POLICY}</p></section>
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Önce bunları çöz</h2><p className="mt-1 text-sm text-muted-foreground">aSc Analyze by Generation fikrinin canonical Okulos karşılığı: tek senaryodan ziyade adaylar boyunca tekrar eden baskı yukarı çıkar.</p>{analysis.signals.length?<div className="mt-3 space-y-2">{analysis.signals.slice(0,12).map((x,i)=><div key={x.key} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm">{i+1}. {x.label}</b><span className="rounded-full bg-muted px-2 py-1 text-xs">{x.severity} · {x.scenarioCount} aday · {x.occurrences} sinyal</span></div><p className="mt-1 text-xs text-muted-foreground">{x.explanation}</p></div>)}</div>:<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>Kayıtlı adaylarda yerleşmeyen ders darboğazı görünmüyor.</div>}</section>
  {analysis.safeSuggestions.length?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Güvenli müdahale adayları</h2><div className="mt-3 space-y-2">{analysis.safeSuggestions.slice(0,8).map((x,i)=><div key={`${x.scenario_id}-${x.action_code}-${i}`} className="rounded-lg border p-3 text-sm"><b>{x.title}</b><div className="mt-1 text-xs text-muted-foreground">{x.action_code}{x.estimated_gain!=null?` · tahmini kazanım ${x.estimated_gain}`:""}</div></div>)}</div></section>:null}
  <p className="mt-4 rounded-xl bg-muted/40 p-3 text-xs"><b>Politika:</b> {analysis.policy}</p>
 </AppShell>}
