import {createFileRoute} from "@tanstack/react-router";
import {useCallback,useEffect,useState} from "react";
import {AppShell} from "@/components/okulos/AppShell";
import {Button} from "@/components/ui/button";
import {supabase} from "@/lib/supabase";
import {normalizeOracleModel,solveExactOracle,type OracleModel,type OracleResult} from "@/lib/schedule-exact-oracle";
import type {LocalProblem} from "@/lib/schedule-local-solver-time-core";
import type {PlanningRelation} from "@/lib/schedule-planning-relations";

export const Route=createFileRoute("/schedule-oracle")({head:()=>({meta:[{title:"CP-SAT Exact Oracle — OkulOS"}]}),component:OraclePage});

async function loadProblem():Promise<LocalProblem>{
 const [a,l,u,t,c,p,rel,sw,tm]=await Promise.all([
  supabase.from("schedule_assignment_options").select("teacher_assignment_id,teacher_id,class_id,course_id,assigned_hours"),
  supabase.from("teacher_schedule").select("teacher_assignment_id,teacher_id,class_id,weekday,period,classroom_id,subgroup_id,schedule_session_id,locked").eq("active",true).eq("locked",true),
  supabase.from("teacher_unavailability").select("teacher_id,weekday,period,schedule_session_id").eq("active",true),
  supabase.from("teacher_schedule_constraints").select("teacher_id,max_daily_hours,max_consecutive_hours"),
  supabase.from("course_schedule_rules").select("course_id,block_pattern,max_per_day,prohibited_days,prohibited_periods").eq("active",true),
  supabase.rpc("get_active_schedule_time_profile"),supabase.rpc("get_schedule_planning_relations_v1"),supabase.rpc("get_schedule_assignment_student_conflict_weights_v2"),supabase.rpc("get_schedule_assignment_time_model_v1")]);
 const e=a.error||l.error||u.error||t.error||c.error||p.error||rel.error||sw.error||tm.error;if(e)throw e;const prof=p.data as {teaching_days:number[];periods_per_day:number},time=new Map((tm.data??[]).map((x:any)=>[String(x.assignment_id),x]));
 return{days:prof.teaching_days,periods:prof.periods_per_day,seed:1,assignments:(a.data??[]).filter((x:any)=>x.teacher_assignment_id).map((x:any)=>{const m:any=time.get(String(x.teacher_assignment_id))??{};return{assignment_id:String(x.teacher_assignment_id),teacher_id:String(x.teacher_id),class_id:String(x.class_id),course_id:String(x.course_id),assigned_hours:Number(x.assigned_hours),week_pattern:m.week_pattern??"ALL",valid_from:m.valid_from??null,valid_to:m.valid_to??null,term_no:m.term_no==null?null:Number(m.term_no),schedule_session_id:m.schedule_session_id?String(m.schedule_session_id):null,allowed_periods:Array.isArray(m.allowed_periods)?m.allowed_periods.map(Number):[]}}),locked:(l.data??[]).filter((x:any)=>x.teacher_assignment_id).map((x:any)=>({assignment_id:String(x.teacher_assignment_id),teacher_id:String(x.teacher_id),class_id:x.class_id?String(x.class_id):null,weekday:Number(x.weekday),period:Number(x.period),classroom_id:x.classroom_id?String(x.classroom_id):null,subgroup_id:x.subgroup_id?String(x.subgroup_id):null,schedule_session_id:x.schedule_session_id?String(x.schedule_session_id):null,locked:true})),unavailable:(u.data??[]).map((x:any)=>({...x,weekday:Number(x.weekday),period:Number(x.period),schedule_session_id:x.schedule_session_id?String(x.schedule_session_id):null})),teacherConstraints:(t.data??[]) as any,courseRules:(c.data??[]).map((x:any)=>({...x,block_pattern:Array.isArray(x.block_pattern)?x.block_pattern.map(Number):null})) as any,planningRelations:(rel.data??[]).map((x:any)=>({...x,weight:Number(x.weight),left_selector:x.left_selector??{},right_selector:x.right_selector??{},parameters:x.parameters??{}})) as PlanningRelation[],studentConflictWeights:(sw.data??[]).map((x:any)=>({left_assignment_id:String(x.left_assignment_id),right_assignment_id:String(x.right_assignment_id),student_weight:Number(x.student_weight),severity_weight:Number(x.severity_weight)}))};
}

function OraclePage(){const[model,setModel]=useState<OracleModel|null>(null),[result,setResult]=useState<OracleResult|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const load=useCallback(async()=>{setError(null);try{setModel(normalizeOracleModel(await loadProblem()))}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);useEffect(()=>{void load()},[load]);async function run(){if(!model)return;if(model.assignments.length>14){setError("Tarayıcı exact verifier en fazla 14 assignment için çalıştırılır. Daha büyük model normalized JSON ile external OR-Tools CP-SAT runner'a verilmelidir.");return}setBusy(true);setError(null);try{setResult(solveExactOracle(model,{timeLimitMs:5000,nodeLimit:500000}))}finally{setBusy(false)}}
 return <AppShell title="CP-SAT Exact Oracle" subtitle="Heuristik çözücünün optimuma uzaklığını ölçen bağımsız exact/bounded doğrulama katmanı">
  {error?<div className="mb-3 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>:null}
  <div className="grid gap-3 md:grid-cols-4"><Card t="Assignment" v={model?.assignments.length??0}/><Card t="Kilitli satır" v={model?.locked.length??0}/><Card t="Unsupported" v={model?.unsupported.length??0}/><Card t="Exact durum" v={result?.status??"—"}/></div>
  <div className="mt-4 rounded-xl border p-4"><div className="font-semibold">Oracle sözleşmesi</div><p className="mt-2 text-sm text-muted-foreground">Production oracle <code>scripts/cp-sat-oracle.py</code> ile OR-Tools CP-SAT kullanır. Tarayıcıdaki exact verifier yalnız küçük modeller için bağımsız regression oracle'dır. Desteklenmeyen constraint varsa optimum iddiası yapılmaz.</p><div className="mt-3 flex gap-2"><Button onClick={()=>void run()} disabled={busy||!model||Boolean(model.unsupported.length)}>{busy?"Çözülüyor…":"Küçük modeli exact doğrula"}</Button><Button variant="outline" onClick={()=>void load()}>Yenile</Button></div></div>
  {model?.unsupported.length?<div className="mt-4 rounded-xl border p-4"><div className="font-semibold">Unsupported constraint mapping</div>{model.unsupported.map((x,i)=><div key={`${x.code}-${i}`} className="mt-2 text-sm"><b>{x.code}</b> — {x.detail}</div>)}</div>:null}
  {result?<div className="mt-4 rounded-xl border p-4"><div className="font-semibold">Exact/bounded sonuç</div><div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><span>Durum: <b>{result.status}</b></span><span>Node: <b>{result.nodes}</b></span><span>Süre: <b>{result.elapsedMs} ms</b></span><span>HARD: <b>{result.score.hard}</b></span><span>MEDIUM: <b>{result.score.medium}</b></span><span>SOFT: <b>{result.score.soft}</b></span></div></div>:null}
 </AppShell>}
function Card({t,v}:{t:string;v:string|number}){return <div className="rounded-xl border p-3"><div className="text-xs text-muted-foreground">{t}</div><div className="mt-1 text-xl font-semibold">{v}</div></div>}
