import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Blocks, CheckCircle2, RefreshCw, Save, ShieldCheck, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";

export const Route=createFileRoute("/schedule-validation")({head:()=>({meta:[{title:"Program Doğrulama — OkulOS"}]}),component:ValidationCenter});
type Item={severity:"error"|"warning";code:string;affected_count:number;detail:string};
type StudentConflict={student_id:string;student_name:string;weekday:number;period:number;conflict_count:number;assignment_ids:string[];subjects:string[]};
type BlockIntegrity={teacher_assignment_id:string;expected_pattern:number[];actual_pattern:number[];ok:boolean};
type AssignmentLabel={teacher_assignment_id:string;composite_key:string|null;class_name:string;course_name:string;teacher_name:string|null};
const dayName:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};
const labels:Record<string,string>={UNLINKED_SCHEDULE_ROWS:"Müfredat bağı olmayan satırlar",SEMANTIC_LINK_MISMATCH:"Müfredat/öğretmen bağlantı hatası",ASSIGNMENT_HOURS_MISMATCH:"Öğretmen-ders saatleri",REQUIREMENT_HOURS_MISMATCH:"Sınıf-ders haftalık saati",CLASS_WEEKLY_HOURS_MISMATCH:"Sınıf toplam haftalık saati",TTKB_PERMISSION_PROBLEM:"TTKB alan-ders uygunluğu",TIME_PROFILE_VIOLATION:"Okul zaman şablonu",TEACHER_DOUBLE_BOOKING:"Öğretmen çakışması",CLASS_OR_STUDENT_GROUP_CONFLICT:"Sınıf/öğrenci grubu çakışması",CLASSROOM_REQUIRED:"Derslik ataması",CLASSROOM_DOUBLE_BOOKING:"Derslik çakışması",CLASSROOM_CONFIGURATION_MISMATCH:"Derslik kapasite/tip/donanım uygunluğu",CLASSROOM_ISSUE:"Uygun derslik bulunamadı",TEACHER_UNAVAILABLE:"Öğretmen kesin uygun değil saati",TEACHER_DAILY_LIMIT:"Öğretmen günlük limiti",TEACHER_WEEKLY_LIMIT:"Öğretmen haftalık limiti",TEACHER_WORKING_DAYS:"Öğretmen çalışma günleri",TEACHER_CONSECUTIVE_LIMIT:"Öğretmen ardışık ders limiti",COURSE_TIME_RULE:"Ders gün/saat kuralı",COURSE_MINIMUM_SPREAD:"Dersin haftaya yayılımı",COURSE_DAILY_LIMIT:"Ders günlük azami saati",COURSE_BLOCK_PATTERN:"Blok ders deseni",SYNC_GROUP_HOURS:"Eşzamanlı grup saatleri",SYNC_GROUP_SLOT_MISMATCH:"Eşzamanlı grup saat eşleşmesi",SOFT_PREFERENCE_PENALTY:"Tercih kalite cezası",TIME_PROFILE_CONFIGURATION_INVALID:"Zaman şablonu yapılandırması",TEACHER_CONSTRAINT_CONFIGURATION_INVALID:"Öğretmen kısıt yapılandırması",COURSE_RULE_CONFIGURATION_INVALID:"Ders kuralı yapılandırması",SYNC_GROUP_REQUIRES_TWO_MEMBERS:"Eşzamanlı grup üye sayısı",SYNC_GROUP_CLASS_MISMATCH:"Eşzamanlı grup sınıf uyuşmazlığı",SYNC_TOTAL_HOURS_EXCEED_ASSIGNMENT:"Eşzamanlı blok toplam saati"};
const pattern=(v:number[])=>v?.length?`[${v.join(", ")}]`:"—";
function fixTarget(code:string):{to:string;label:string}{if(code.startsWith("CLASSROOM")||code.includes("ROOM"))return{to:"/room-assignment",label:"Derslikleri Düzelt"};if(code.startsWith("TIME_PROFILE"))return{to:"/schedule-time-model",label:"Zaman Modelini Düzelt"};if(code.startsWith("TEACHER_")||code.startsWith("COURSE_")||code.startsWith("SYNC_")||code==="SOFT_PREFERENCE_PENALTY")return{to:"/schedule-rules",label:"Kuralları Düzelt"};if(code.includes("STUDENT_GROUP")||code.includes("STUDENT_CONFLICT"))return{to:"/student-sectioning",label:"Öğrenci Dağılımını İncele"};return{to:"/schedule",label:"Programda Düzelt"}}
function ValidationCenter(){const {can}=usePermissions();const editable=can("schedule.rules");const [items,setItems]=useState<Item[]>([]),[conflicts,setConflicts]=useState<StudentConflict[]>([]),[blocks,setBlocks]=useState<BlockIntegrity[]>([]),[assignmentLabels,setAssignmentLabels]=useState<AssignmentLabel[]>([]),[penalty,setPenalty]=useState(250),[draftPenalty,setDraftPenalty]=useState(250),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[loaded,setLoaded]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setLoaded(false);setMessage(null);const [i,c,b,a,s]=await Promise.all([supabase.rpc("get_schedule_integrity_report"),supabase.rpc("get_schedule_student_conflict_report_v2"),supabase.rpc("get_schedule_block_integrity_report_v1"),supabase.from("schedule_assignment_options").select("teacher_assignment_id,composite_key,class_name,course_name,teacher_name"),supabase.from("schedule_generation_settings").select("student_conflict_penalty").eq("id",true).maybeSingle()]);setBusy(false);const error=i.error??c.error??b.error??a.error??s.error;if(error){setItems([]);setConflicts([]);setBlocks([]);setAssignmentLabels([]);setLoadError(error.message);setLoaded(true);return}setLoadError(null);setItems((i.data??[]) as Item[]);setConflicts((c.data??[]) as StudentConflict[]);setBlocks((b.data??[]) as BlockIntegrity[]);setAssignmentLabels((a.data??[]) as AssignmentLabel[]);const p=Number(s.data?.student_conflict_penalty??250);setPenalty(p);setDraftPenalty(p);setLoaded(true)},[]);useEffect(()=>{void load()},[load]);
 const errors=useMemo(()=>items.filter(x=>x.severity==="error"),[items]),warnings=useMemo(()=>items.filter(x=>x.severity==="warning"),[items]),badBlocks=useMemo(()=>blocks.filter(x=>!x.ok),[blocks]);const affectedStudents=useMemo(()=>new Set(conflicts.map(x=>x.student_id)).size,[conflicts]),conflictEvents=useMemo(()=>conflicts.reduce((n,x)=>n+x.conflict_count,0),[conflicts]),assignmentMap=useMemo(()=>new Map(assignmentLabels.map(x=>[x.teacher_assignment_id,x])),[assignmentLabels]);const ready=loaded&&!loadError&&errors.length===0&&badBlocks.length===0;
 async function savePenalty(){if(!editable)return;const value=Math.max(0,Math.round(draftPenalty));const {error}=await supabase.from("schedule_generation_settings").update({student_conflict_penalty:value,updated_at:new Date().toISOString()}).eq("id",true);if(error)return setMessage(`Öğrenci çakışma katsayısı kaydedilemedi: ${error.message}`);setPenalty(value);setDraftPenalty(value);setMessage("Öğrenci çakışma senaryo katsayısı kaydedildi. Yeni/rescore edilen senaryolarda uygulanacak.")}
 return <AppShell title="Program Doğrulama Merkezi" subtitle="Yayın öncesi sıfır HARD hata · blok bütünlüğü · öğrenci çakışması · kalite" action={<ShieldCheck className="size-5"/>}>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="HARD constraint" value={loaded&&!loadError?errors.reduce((n,x)=>n+x.affected_count,0):"—"} tone={errors.length?"bad":"good"}/><Metric label="Blok deseni" value={loaded&&!loadError?`${blocks.length-badBlocks.length}/${blocks.length}`:"—"} tone={badBlocks.length?"bad":"good"}/><Metric label="Öğrenci çakışması (MEDIUM)" value={loaded&&!loadError?conflictEvents:"—"} tone={conflictEvents?"warn":"good"}/><Metric label="Soft kalite uyarısı" value={loaded&&!loadError?warnings.reduce((n,x)=>n+x.affected_count,0):"—"}/><Metric label="Yayın durumu" value={!loaded||busy?"KONTROL":loadError?"DOĞRULANAMADI":ready?"YAYINA HAZIR":"BLOKE"} tone={ready?"good":"bad"}/></div>
  {message?<div className="mt-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  {!loaded||busy?<div className="mt-4 rounded-xl border bg-muted/30 p-5 text-sm text-muted-foreground">Program bütünlük, blok ve öğrenci çakışma kontrolleri çalıştırılıyor…</div>:loadError?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-5 text-red-800"><AlertTriangle className="mr-2 inline size-5"/><b>Program doğrulaması çalıştırılamadı.</b><p className="mt-2 text-sm">{loadError}</p></div>:<>
   <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Blocks className="size-4"/>Blok Ders Bütünlüğü</h2><p className="mt-1 text-xs text-muted-foreground">Beklenen blok deseni ile aktif programdaki gerçek bitişik ders blokları birebir karşılaştırılır. Blok bozuksa yayın hazır sayılmaz.</p></div><Metric label="Bozuk blok" value={badBlocks.length} tone={badBlocks.length?"bad":"good"}/></div>{blocks.length?<div className="mt-3 max-h-72 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-2 text-left">Sınıf · Ders · Öğretmen</th><th className="p-2 text-left">Beklenen</th><th className="p-2 text-left">Gerçek</th><th className="p-2 text-right">Durum</th></tr></thead><tbody>{blocks.map(x=>{const a=assignmentMap.get(x.teacher_assignment_id);return <tr key={x.teacher_assignment_id} className={`border-t ${x.ok?"":"bg-red-50"}`}><td className="p-2"><b>{a?.composite_key??a?.class_name??"Atama"}</b> · {a?.course_name??x.teacher_assignment_id}<div className="text-[11px] text-muted-foreground">{a?.teacher_name??"—"}</div></td><td className="p-2 font-mono">{pattern(x.expected_pattern)}</td><td className="p-2 font-mono">{pattern(x.actual_pattern)}</td><td className={`p-2 text-right font-semibold ${x.ok?"text-emerald-600":"text-red-600"}`}>{x.ok?"UYGUN":"BOZUK"}</td></tr>})}</tbody></table></div>:<div className="mt-3 rounded-lg border bg-muted/20 p-3 text-sm text-muted-foreground">Aktif blok ders tanımı yok.</div>}</section>
   <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Users className="size-4"/>Öğrenci Çakışma Optimizasyonu</h2><p className="mt-1 text-xs text-muted-foreground">Farklı sınıf/şubelerde ortak ders talebi olan öğrencilerin eşzamanlı derslerini MEDIUM objective olarak azaltır. allow_overlap talepleri hesaba katılmaz.</p></div><div className="flex items-end gap-2"><div><Label>Senaryo skor katsayısı</Label><Input className="w-32" type="number" min={0} disabled={!editable} value={draftPenalty} onChange={e=>setDraftPenalty(Number(e.target.value))}/></div><Button disabled={!editable||draftPenalty===penalty} onClick={()=>void savePenalty()} className="gap-2"><Save className="size-4"/>Kaydet</Button></div></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Etkilenen öğrenci" value={affectedStudents}/><Metric label="Çakışma olayı" value={conflictEvents}/><Metric label="Aktif katsayı" value={penalty}/></div>{conflicts.length?<div className="mt-3 max-h-72 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-2 text-left">Öğrenci</th><th className="p-2 text-left">Zaman</th><th className="p-2 text-left">Dersler</th><th className="p-2 text-right">Çakışma</th></tr></thead><tbody>{conflicts.map((x,i)=><tr key={`${x.student_id}-${x.weekday}-${x.period}-${i}`} className="border-t"><td className="p-2">{x.student_name}</td><td className="p-2">{dayName[x.weekday]??x.weekday} · {x.period}. saat</td><td className="p-2 text-xs text-muted-foreground">{(x.subjects??[]).join(" · ")}</td><td className="p-2 text-right font-semibold">{x.conflict_count}</td></tr>)}</tbody></table></div>:<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>Öğrenci ders talebi kaynaklı çakışma yok.</div>}</section>
   {!items.length?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="mr-2 inline size-5"/><b>Tüm zorunlu kontroller geçti.</b> Program HARD bütünlük açısından yayına hazır.</div>:<div className="mt-4 space-y-2">{items.map(x=>{const fix=fixTarget(x.code);return <div key={x.code} className={x.severity==="error"?"rounded-xl border border-red-200 bg-red-50 p-4":"rounded-xl border border-amber-200 bg-amber-50 p-4"}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><AlertTriangle className={x.severity==="error"?"mt-0.5 size-5 shrink-0 text-red-600":"mt-0.5 size-5 shrink-0 text-amber-600"}/><div><div className="font-semibold">{labels[x.code]??x.code} · {x.affected_count}</div><p className="mt-1 text-sm text-muted-foreground">{x.detail}</p><code className="mt-2 block text-[11px]">{x.code}</code></div></div><Link to={fix.to as never}><Button size="sm" variant="outline">{fix.label}</Button></Link></div></div>})}</div>}
  </>}
  <div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()} disabled={busy} className="gap-2"><RefreshCw className="size-4"/>Yeniden Kontrol Et</Button><Link to="/schedule"><Button variant="outline">Programa Dön</Button></Link><Link to="/schedule-rules"><Button variant="outline">Program Kuralları</Button></Link><Link to="/schedule-scenario-comparison"><Button variant="outline">Senaryolar</Button></Link><Link to="/schedule-archive"><Button disabled={!ready}>Yayın / Arşiv</Button></Link></div>
 </AppShell>}
function Metric({label,value,tone}:{label:string;value:string|number;tone?:"good"|"bad"|"warn"}){const cls=tone==="good"?"text-emerald-600":tone==="bad"?"text-red-600":tone==="warn"?"text-amber-600":"";return <div className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-bold ${cls}`}>{value}</p></div>}