import{createFileRoute,Link}from"@tanstack/react-router";
import{useCallback,useEffect,useMemo,useState}from"react";
import{CalendarClock}from"lucide-react";
import{AppShell}from"@/components/okulos/AppShell";
import{Button}from"@/components/ui/button";
import{getScheduleSlotVisualState,scheduleSlotVisualClass,type ScheduleSlotPreferenceRow,type ScheduleSlotUnavailableRow}from"@/lib/schedule-slot-visual-state";
import{supabase}from"@/lib/supabase";

export const Route=createFileRoute("/schedule-time-map")({head:()=>({meta:[{title:"Öğretmen Zaman Uygunluk Haritası — OkulOS"}]}),component:ScheduleTimeMap});
type Teacher={user_id:string;full_name:string|null};type TimeProfile={teaching_days:number[];periods_per_day:number};
const dayName:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};
function ScheduleTimeMap(){const[teachers,setTeachers]=useState<Teacher[]>([]),[teacherId,setTeacherId]=useState(""),[unavailable,setUnavailable]=useState<ScheduleSlotUnavailableRow[]>([]),[preferences,setPreferences]=useState<ScheduleSlotPreferenceRow[]>([]),[profile,setProfile]=useState<TimeProfile>({teaching_days:[1,2,3,4,5],periods_per_day:8}),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const[t,u,p,tp]=await Promise.all([supabase.from("profiles").select("user_id,full_name").eq("role","teacher").order("full_name"),supabase.from("teacher_unavailability").select("teacher_id,weekday,period,active").eq("active",true),supabase.from("teacher_schedule_preferences").select("teacher_id,weekday,period,preference,weight,active").eq("active",true),supabase.rpc("get_active_schedule_time_profile")]);const e=t.error??u.error??p.error??tp.error;if(e){setError(e.message);return}setTeachers((t.data??[])as Teacher[]);setUnavailable((u.data??[])as ScheduleSlotUnavailableRow[]);setPreferences((p.data??[])as ScheduleSlotPreferenceRow[]);if(tp.data)setProfile({teaching_days:tp.data.teaching_days??[1,2,3,4,5],periods_per_day:tp.data.periods_per_day??8})},[]);useEffect(()=>{void load()},[load]);
 const periods=useMemo(()=>Array.from({length:profile.periods_per_day},(_,i)=>i+1),[profile.periods_per_day]);
 return <AppShell title="Öğretmen Zaman Uygunluk Haritası" subtitle="HARD yasaklar ile SOFT tercihleri aynı gridde gör; son karar canonical server doğrulamasındadır." action={<CalendarClock className="size-5"/>}><div className="mb-4 flex flex-wrap gap-2"><Link to="/schedule"><Button variant="outline">← Elle Düzelt</Button></Link><Link to="/schedule-rules"><Button variant="outline">Kurallar</Button></Link></div>{error?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}<select className="h-10 w-full rounded-md border bg-background px-3 text-sm sm:max-w-md" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Öğretmen seçiniz</option>{teachers.map(t=><option key={t.user_id} value={t.user_id}>{t.full_name??t.user_id}</option>)}</select><div className="mt-4 flex flex-wrap gap-3 text-xs"><span className="rounded border bg-emerald-50 px-2 py-1">Tercih edilir · SOFT</span><span className="rounded border bg-sky-50 px-2 py-1">Kaçınılması tercih edilir · SOFT</span><span className="rounded border bg-destructive/10 px-2 py-1">Kesin uygun değil · HARD</span><span className="rounded border px-2 py-1">Nötr</span></div>{teacherId?<div className="mt-4 overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[760px] text-sm"><thead><tr className="bg-muted/40"><th className="p-2 text-left">Saat</th>{profile.teaching_days.map(d=><th key={d} className="p-2 text-left">{dayName[d]??d}</th>)}</tr></thead><tbody>{periods.map(period=><tr key={period} className="border-t"><td className="p-2 font-semibold">{period}</td>{profile.teaching_days.map(day=>{const v=getScheduleSlotVisualState({teacherId,weekday:day,period,unavailable,preferences});return <td key={day} title={v.label} className={`min-w-[140px] p-3 align-top ${scheduleSlotVisualClass(v.state)}`}><b className="text-xs">{v.label}</b>{v.weight?<div className="mt-1 text-[11px] text-muted-foreground">Ağırlık: {v.weight}</div>:null}</td>})}</tr>)}</tbody></table></div>:<div className="mt-4 rounded-xl border bg-muted/20 p-5 text-sm text-muted-foreground">Haritayı görmek için öğretmen seçin.</div>}<p className="mt-4 rounded-xl border bg-muted/30 p-3 text-xs"><b>Otorite sınırı:</b> Bu ekran yalnız mevcut HARD/SOFT veriyi görselleştirir. Yerleştirme, taşıma veya çözüm kararı vermez; canonical validator ve server preview nihai otoritedir.</p></AppShell>}
