import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Lock, RefreshCw, Sparkles, Unlock } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/schedule-solver")({head:()=>({meta:[{title:"Ders Programı Çözücü — OkulOS"}]}),component:ScheduleSolver});
type Scenario={generation_group:string;scenario_id:string;scenario_no:number;score:number;unplaced_count:number;row_count:number};type CurrentRow={id:string;teacher_id:string;class_name:string;subject:string;weekday:number;period:number;locked:boolean;profiles?:{full_name:string|null}|null};type Unplaced={id:string;scenario_id:string;subject:string;reason:string;block_hours:number;diagnostic:Record<string,number>};type Settings={periods_per_day:number;max_same_course_per_day:number;gap_penalty:number;late_period_penalty:number;repeated_course_penalty:number};type Prep={category:string;code:string;status:string;affected_count:number;detail:string};const dayNames=["","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];
function ScheduleSolver(){const [scenarios,setScenarios]=useState<Scenario[]>([]);const [current,setCurrent]=useState<CurrentRow[]>([]);const [unplaced,setUnplaced]=useState<Unplaced[]>([]);const [prep,setPrep]=useState<Prep[]>([]);const [settings,setSettings]=useState<Settings>({periods_per_day:8,max_same_course_per_day:2,gap_penalty:8,late_period_penalty:2,repeated_course_penalty:12});const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const [c,s,p]=await Promise.all([supabase.from("teacher_schedule").select("id,teacher_id,class_name,subject,weekday,period,locked,profiles!teacher_schedule_teacher_id_fkey(full_name)").eq("active",true).order("weekday").order("period"),supabase.from("schedule_generation_settings").select("periods_per_day,max_same_course_per_day,gap_penalty,late_period_penalty,repeated_course_penalty").eq("id",true).maybeSingle(),supabase.rpc("get_schedule_preparation_readiness")]);setCurrent((c.data??[]) as unknown as CurrentRow[]);if(s.data)setSettings(s.data as Settings);setPrep((p.data??[]) as Prep[])},[]);useEffect(()=>{void load()},[load]);
 async function toggleLock(row:CurrentRow){const {error:e}=await supabase.from("teacher_schedule").update({locked:!row.locked}).eq("id",row.id);if(e)return setError(e.message);await load()}
 async function saveSettings(){const {error:e}=await supabase.from("schedule_generation_settings").update({max_same_course_per_day:settings.max_same_course_per_day,gap_penalty:settings.gap_penalty,late_period_penalty:settings.late_period_penalty,repeated_course_penalty:settings.repeated_course_penalty,updated_at:new Date().toISOString()}).eq("id",true);setMessage(e?e.message:"Çözücü kalite ayarları kaydedildi. Günlük ders sayısı merkezi zaman şablonundan alınır.")}
 async function generate(){setBusy(true);setError(null);setMessage(null);const {data,error:e}=await supabase.rpc("generate_schedule_scenarios_v2");if(e){setBusy(false);await load();return setError(`Senaryolar üretilemedi: ${e.message}`)}const generated=(data??[]) as Scenario[];for(const s of generated)await supabase.rpc("repair_schedule_scenario_v2",{p_scenario_id:s.scenario_id});if(!generated.length){setBusy(false);return}const group=generated[0].generation_group;const [fresh,u]=await Promise.all([supabase.from("schedule_scenarios").select("generation_group,id,scenario_no,score,unplaced_count,row_count").eq("generation_group",group).order("score"),supabase.from("schedule_unplaced_items").select("id,scenario_id,subject,reason,block_hours,diagnostic").in("scenario_id",generated.map(x=>x.scenario_id))]);setScenarios((fresh.data??[]).map((x:any)=>({generation_group:x.generation_group,scenario_id:x.id,scenario_no:x.scenario_no,score:x.score,unplaced_count:x.unplaced_count,row_count:x.row_count})));setUnplaced((u.data??[]) as Unplaced[]);setBusy(false);setMessage("Hazırlık kapısı geçti. 4 senaryo üretildi; repair/backtracking ve derslik atama turu tamamlandı.")}
 async function apply(id:string){setBusy(true);setError(null);const {data,error:e}=await supabase.rpc("apply_schedule_scenario",{p_scenario_id:id});setBusy(false);if(e)return setError(`Senaryo uygulanamadı: ${e.message}`);setMessage(`${Number(data??0)} ders çalışma programına uygulandı ve bütünlük kapısından geçti.`);await load()}
 const lockedCount=useMemo(()=>current.filter(x=>x.locked).length,[current]);const prepErrors=prep.filter(x=>x.status==="error");const diagLabel:Record<string,string>={teacher_busy:"Öğretmen dolu",class_busy:"Sınıf dolu",teacher_unavailable:"Öğretmen uygun değil",daily_limit:"Günlük limit",working_days_limit:"Çalışma günü limiti",consecutive_limit:"Ardışık ders limiti",course_time_rule:"Ders zaman kuralı",valid_windows:"Geçerli pencere",candidate_windows:"Toplam aday"};
 return <AppShell title="Ders Programı Çözücü" subtitle="Hard constraint · blok · eşzamanlı grup · repair/backtracking" action={<Sparkles className="size-5"/>}><div className="grid gap-2 sm:grid-cols-5"><Link to="/curriculum"><Button variant="outline" className="w-full">Müfredat</Button></Link><Link to="/schedule-rules"><Button variant="outline" className="w-full">Program Kuralları</Button></Link><Link to="/schedule-preparation"><Button variant={prepErrors.length?"destructive":"outline"} className="w-full">Hazırlık {prepErrors.length?`(${prepErrors.length})`:"✓"}</Button></Link><Link to="/schedule"><Button variant="outline" className="w-full">Çalışma Programı</Button></Link><Link to="/schedule-validation"><Button variant="outline" className="w-full">Doğrulama</Button></Link></div>{message?<div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{message}</div>:null}{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
 {prepErrors.length?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><b className="text-red-700">Program üretimi başlamadan önce {prepErrors.length} hazırlık sorunu çözülmeli.</b>{prepErrors.slice(0,5).map(x=><p key={x.code} className="mt-1 text-xs text-red-800">{x.category} · {x.code}: {x.detail} ({x.affected_count})</p>)}</div>:<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline size-4"/>Program hazırlık girdileri tamam.</div>}
 <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Kalite Ağırlıkları</h2><p className="mt-1 text-xs text-muted-foreground">Günlük ders sayısı: <b>{settings.periods_per_day}</b> · Merkezi Program Kuralları → Zaman ekranından yönetilir.</p><div className="mt-3 grid gap-3 sm:grid-cols-4"><div><Label>Aynı ders/gün</Label><Input type="number" value={settings.max_same_course_per_day} onChange={e=>setSettings({...settings,max_same_course_per_day:Number(e.target.value)})}/></div><div><Label>Boşluk cezası</Label><Input type="number" value={settings.gap_penalty} onChange={e=>setSettings({...settings,gap_penalty:Number(e.target.value)})}/></div><div><Label>Geç ders cezası</Label><Input type="number" value={settings.late_period_penalty} onChange={e=>setSettings({...settings,late_period_penalty:Number(e.target.value)})}/></div><div><Label>Tekrar cezası</Label><Input type="number" value={settings.repeated_course_penalty} onChange={e=>setSettings({...settings,repeated_course_penalty:Number(e.target.value)})}/></div></div><Button variant="secondary" className="mt-3" onClick={()=>void saveSettings()}>Kaydet</Button></section>
 <section className="mt-4 rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Kilitli Dersler</h2><p className="text-xs text-muted-foreground">{lockedCount} saat kilitli. Bu saatler atama toplamından düşülür ve yeniden üretilmez.</p></div><Button onClick={()=>void generate()} disabled={busy||prepErrors.length>0} className="gap-2"><Sparkles className="size-4"/>{busy?"Çözülüyor...":"4 Senaryo Üret"}</Button></div><div className="mt-3 max-h-64 overflow-auto rounded-lg border"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-2 text-left">Gün/Saat</th><th className="p-2 text-left">Sınıf</th><th className="p-2 text-left">Ders</th><th className="p-2 text-left">Öğretmen</th><th className="p-2">Kilit</th></tr></thead><tbody>{current.map(r=><tr key={r.id} className="border-b"><td className="p-2">{dayNames[r.weekday]} · {r.period}</td><td className="p-2">{r.class_name}</td><td className="p-2">{r.subject}</td><td className="p-2">{r.profiles?.full_name??"—"}</td><td className="p-2 text-center"><Button size="sm" variant={r.locked?"secondary":"ghost"} onClick={()=>void toggleLock(r)}>{r.locked?<Lock className="size-4"/>:<Unlock className="size-4"/>}</Button></td></tr>)}</tbody></table></div></section>
 <div className="mt-4 grid gap-3 lg:grid-cols-2">{scenarios.map((s,index)=>{const problems=unplaced.filter(u=>u.scenario_id===s.scenario_id);return <section key={s.scenario_id} className={index===0?"rounded-xl border-2 border-emerald-400 bg-emerald-50/30 p-4":"rounded-xl border bg-card p-4"}><div className="flex justify-between"><div><h3 className="font-semibold">Senaryo {s.scenario_no}{index===0?" · Önerilen":""}</h3><p className="text-xs text-muted-foreground">Puan {s.score} · {s.row_count} ders · {s.unplaced_count} yerleşmeyen</p></div>{s.unplaced_count===0?<CheckCircle2 className="size-5 text-emerald-600"/>:null}</div>{problems.map(p=><div key={p.id} className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800"><b>{p.subject}</b> · {p.block_hours} saat · {p.reason}<div className="mt-2 flex flex-wrap gap-1">{Object.entries(p.diagnostic??{}).filter(([,v])=>v>0).map(([k,v])=><span key={k} className="rounded bg-white px-2 py-1">{diagLabel[k]??k}: {v}</span>)}</div></div>)}<Button className="mt-3 w-full" disabled={busy||s.unplaced_count>0} onClick={()=>void apply(s.scenario_id)}>Bu Senaryoyu Uygula</Button></section>})}</div>{!scenarios.length?<div className="mt-4 rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Senaryo üretildiğinde hard constraint, blok, senkron grup, öğretmen tercihleri, derslik ve repair sonuçları burada karşılaştırılır.</div>:null}<Button variant="ghost" className="mt-5 gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></AppShell>}
