import {createFileRoute} from "@tanstack/react-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {CalendarClock,Clock3,RefreshCw,Save,ShieldCheck} from "lucide-react";
import {AppShell} from "@/components/okulos/AppShell";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {supabase} from "@/lib/supabase";
import {usePermissions} from "@/lib/permissions";

export const Route=createFileRoute("/schedule-time-model")({head:()=>({meta:[{title:"Zaman Modeli — OkulOS"}]}),component:TimeModelPage});
type Session={id:string;name:string;code:string;ordinal:number;starts_at:string|null;ends_at:string|null;active:boolean};
type Period={id:string;session_id:string;period:number;local_period:number|null;starts_at:string;ends_at:string;teaching_minutes:number;active:boolean};
type Cls={id:string;class_name:string;schedule_session_id:string|null};
type Assignment={id:string;week_pattern:"ALL"|"ODD"|"EVEN";valid_from:string|null;valid_to:string|null;term_no:number|null;schedule_session_id:string|null;teacher_course_assignments?:never;class_course_requirements?:{school_classes?:{class_name?:string|null};course_catalog?:{name?:string|null}}};
type Health={sessions:number;period_definitions:number;classes_without_session:number;assignments_without_session:number;scoped_assignments:number;multi_session_clock_missing:number};
const normTime=(v:string|null)=>v?v.slice(0,5):"";
function TimeModelPage(){
 const {can,any,loading:permLoading}=usePermissions();const mayView=any("schedule.view","schedule.edit","schedule.rules"),mayManage=can("schedule.edit")||can("schedule.rules");
 const [sessions,setSessions]=useState<Session[]>([]),[periods,setPeriods]=useState<Period[]>([]),[classes,setClasses]=useState<Cls[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[health,setHealth]=useState<Health|null>(null),[anchor,setAnchor]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(permLoading||!mayView)return;setError(null);const [s,p,c,a,h,tp]=await Promise.all([supabase.from("schedule_sessions").select("id,name,code,ordinal,starts_at,ends_at,active").order("ordinal"),supabase.from("schedule_period_definitions").select("id,session_id,period,local_period,starts_at,ends_at,teaching_minutes,active").order("period"),supabase.from("school_classes").select("id,class_name,schedule_session_id").eq("active",true).order("class_name"),supabase.from("teacher_course_assignments").select("id,week_pattern,valid_from,valid_to,term_no,schedule_session_id,class_course_requirements(school_classes(class_name),course_catalog(name))").order("id"),supabase.rpc("get_schedule_time_model_health_v1"),supabase.from("schedule_time_profiles").select("week_parity_anchor").eq("active",true).order("updated_at",{ascending:false}).limit(1).maybeSingle()]);const e=s.error||p.error||c.error||a.error||h.error||tp.error;if(e){setError(e.message);return;}setSessions((s.data??[]) as Session[]);setPeriods((p.data??[]) as Period[]);setClasses((c.data??[]) as Cls[]);setAssignments((a.data??[]) as unknown as Assignment[]);setHealth((h.data??null) as Health|null);setAnchor(tp.data?.week_parity_anchor??"");},[mayView,permLoading]);useEffect(()=>{void load()},[load]);
 async function saveAnchor(){if(!mayManage)return;setBusy(true);const{error:e}=await supabase.from("schedule_time_profiles").update({week_parity_anchor:anchor||null}).eq("active",true);setBusy(false);if(e)setError(e.message);else await load()}
 async function addSession(){if(!mayManage)return;const n=sessions.length+1;setBusy(true);const{error:e}=await supabase.from("schedule_sessions").insert({time_profile_id:(await supabase.from("schedule_time_profiles").select("id").eq("active",true).limit(1).single()).data?.id,code:`SESSION_${n}`,name:`Vardiya ${n}`,ordinal:n});setBusy(false);if(e)setError(e.message);else await load()}
 async function updateSession(id:string,patch:Partial<Session>){if(!mayManage)return;const{error:e}=await supabase.from("schedule_sessions").update(patch).eq("id",id);if(e)setError(e.message);else await load()}
 async function addPeriod(session:Session){if(!mayManage)return;const own=periods.filter(x=>x.session_id===session.id),local=Math.max(0,...own.map(x=>x.local_period??0))+1,canonical=Math.max(0,...periods.map(x=>x.period))+1;if(canonical>24||local>12){setError("Canonical slot 24, vardiya içi ders 12 sınırını aşamaz.");return;}setBusy(true);const{error:e}=await supabase.from("schedule_period_definitions").insert({session_id:session.id,period:canonical,local_period:local,starts_at:"08:00",ends_at:"08:40",teaching_minutes:40});setBusy(false);if(e)setError(e.message);else await load()}
 async function savePeriod(row:Period){if(!mayManage)return;setBusy(true);const mins=Math.max(1,Math.round((new Date(`1970-01-01T${row.ends_at}`).getTime()-new Date(`1970-01-01T${row.starts_at}`).getTime())/60000));const{error:e}=await supabase.from("schedule_period_definitions").update({period:row.period,local_period:row.local_period,starts_at:row.starts_at,ends_at:row.ends_at,teaching_minutes:mins}).eq("id",row.id);setBusy(false);if(e)setError(e.message);else await load()}
 async function setClassSession(id:string,value:string){const{error:e}=await supabase.from("school_classes").update({schedule_session_id:value}).eq("id",id);if(e)setError(e.message);else await load()}
 async function setAssignment(id:string,patch:Partial<Assignment>){const{error:e}=await supabase.from("teacher_course_assignments").update(patch).eq("id",id);if(e)setError(e.message);else await load()}
 const sessionName=useMemo(()=>Object.fromEntries(sessions.map(x=>[x.id,x.name])),[sessions]);
 if(permLoading)return <AppShell title="Zaman Modeli"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;
 if(!mayView)return <AppShell title="Zaman Modeli"><div className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">Ders programı görüntüleme yetkisi gerekli.</div></AppShell>;
 return <AppShell title="Zaman Modeli" subtitle="Hafta deseni · dönem · tarih · vardiya · gerçek ders saatleri" action={<Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Yenile</Button>}>
  {error?<div className="mb-4 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
  <section className="grid gap-3 md:grid-cols-6">{Object.entries(health??{}).map(([k,v])=><div key={k} className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{k.replaceAll("_"," ")}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</section>
  <section className="mt-5 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><CalendarClock className="size-4"/>Tek/Çift Hafta Referansı</h2><p className="mt-1 text-xs text-muted-foreground">Boş bırakılırsa eğitim başlangıcının bulunduğu Pazartesi baz alınır.</p></div><div className="flex items-end gap-2"><div><Label htmlFor="anchor">Referans tarih</Label><Input id="anchor" type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/></div>{mayManage?<Button disabled={busy} onClick={()=>void saveAnchor()}><Save className="mr-2 size-4"/>Kaydet</Button>:null}</div></div></section>
  <section className="mt-5"><div className="mb-2 flex items-center justify-between"><div><h2 className="font-semibold">Vardiyalar / Session</h2><p className="text-xs text-muted-foreground">Saat bilinmiyorsa uydurulmaz. Çoklu vardiyada gerçek period saatlerini tanımlayın.</p></div>{mayManage?<Button variant="outline" onClick={()=>void addSession()}>Vardiya Ekle</Button>:null}</div><div className="space-y-3">{sessions.map(s=><div key={s.id} className="rounded-xl border bg-card p-4"><div className="grid gap-3 md:grid-cols-[1.3fr_.6fr_.7fr_.7fr_auto]"><Input value={s.name} onChange={e=>setSessions(x=>x.map(y=>y.id===s.id?{...y,name:e.target.value}:y))}/><Input value={s.code} onChange={e=>setSessions(x=>x.map(y=>y.id===s.id?{...y,code:e.target.value}:y))}/><Input type="time" value={normTime(s.starts_at)} onChange={e=>setSessions(x=>x.map(y=>y.id===s.id?{...y,starts_at:e.target.value||null}:y))}/><Input type="time" value={normTime(s.ends_at)} onChange={e=>setSessions(x=>x.map(y=>y.id===s.id?{...y,ends_at:e.target.value||null}:y))}/>{mayManage?<Button onClick={()=>void updateSession(s.id,{name:s.name,code:s.code,starts_at:s.starts_at,ends_at:s.ends_at})}>Kaydet</Button>:null}</div><div className="mt-3 flex items-center justify-between"><p className="text-xs text-muted-foreground">Canonical slotlar: {periods.filter(p=>p.session_id===s.id).map(p=>p.period).join(", ")||"tanımlı değil"}</p>{mayManage?<Button size="sm" variant="outline" onClick={()=>void addPeriod(s)}><Clock3 className="mr-2 size-4"/>Ders Saati Ekle</Button>:null}</div><div className="mt-2 space-y-2">{periods.filter(p=>p.session_id===s.id).map(p=><div key={p.id} className="grid gap-2 rounded-lg bg-muted/40 p-2 md:grid-cols-[.5fr_.5fr_.7fr_.7fr_auto]"><Input type="number" min={1} max={24} value={p.period} onChange={e=>setPeriods(x=>x.map(y=>y.id===p.id?{...y,period:Number(e.target.value)}:y))}/><Input type="number" min={1} max={12} value={p.local_period??""} onChange={e=>setPeriods(x=>x.map(y=>y.id===p.id?{...y,local_period:Number(e.target.value)}:y))}/><Input type="time" value={normTime(p.starts_at)} onChange={e=>setPeriods(x=>x.map(y=>y.id===p.id?{...y,starts_at:e.target.value}:y))}/><Input type="time" value={normTime(p.ends_at)} onChange={e=>setPeriods(x=>x.map(y=>y.id===p.id?{...y,ends_at:e.target.value}:y))}/>{mayManage?<Button size="sm" onClick={()=>void savePeriod(p)}>Kaydet</Button>:null}</div>)}</div></div>)}</div></section>
  <section className="mt-6"><h2 className="mb-2 font-semibold">Sınıf → Vardiya</h2><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{classes.map(c=><div key={c.id} className="flex items-center justify-between gap-3 rounded-xl border bg-card p-3"><span className="text-sm font-medium">{c.class_name}</span><Select value={c.schedule_session_id??""} onValueChange={v=>void setClassSession(c.id,v)} disabled={!mayManage}><SelectTrigger className="w-44"><SelectValue placeholder="Vardiya"/></SelectTrigger><SelectContent>{sessions.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div>)}</div></section>
  <section className="mt-6"><div className="mb-2"><h2 className="font-semibold">Ders Ataması Zaman Kapsamı</h2><p className="text-xs text-muted-foreground">ALL/ODD/EVEN, dönem ve tarih aralığı çakışma semantiğinin parçasıdır.</p></div><div className="space-y-2">{assignments.map(a=>{const rel=(a as any).class_course_requirements;return <div key={a.id} className="grid gap-2 rounded-xl border bg-card p-3 lg:grid-cols-[1.5fr_.65fr_.65fr_1fr_1fr_1fr]"><div><p className="text-sm font-medium">{rel?.school_classes?.class_name??"Sınıf"} · {rel?.course_catalog?.name??"Ders"}</p><p className="text-xs text-muted-foreground">{sessionName[a.schedule_session_id??""]??"Vardiya yok"}</p></div><Select value={a.week_pattern} onValueChange={v=>void setAssignment(a.id,{week_pattern:v as Assignment["week_pattern"]})} disabled={!mayManage}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">Her hafta</SelectItem><SelectItem value="ODD">Tek hafta</SelectItem><SelectItem value="EVEN">Çift hafta</SelectItem></SelectContent></Select><Select value={a.term_no?.toString()??"ALL"} onValueChange={v=>void setAssignment(a.id,{term_no:v==="ALL"?null:Number(v)})} disabled={!mayManage}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">Tüm dönem</SelectItem><SelectItem value="1">1. dönem</SelectItem><SelectItem value="2">2. dönem</SelectItem></SelectContent></Select><Input type="date" value={a.valid_from??""} onChange={e=>void setAssignment(a.id,{valid_from:e.target.value||null})} disabled={!mayManage}/><Input type="date" value={a.valid_to??""} onChange={e=>void setAssignment(a.id,{valid_to:e.target.value||null})} disabled={!mayManage}/><Select value={a.schedule_session_id??""} onValueChange={v=>void setAssignment(a.id,{schedule_session_id:v})} disabled={!mayManage}><SelectTrigger><SelectValue placeholder="Vardiya"/></SelectTrigger><SelectContent>{sessions.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div>})}</div></section>
  <div className="mt-5 flex items-center gap-2 rounded-xl border bg-muted/40 p-3 text-xs text-muted-foreground"><ShieldCheck className="size-4"/>HARD çakışmalar yalnız gerçek zaman kapsamları kesişiyorsa oluşur. Bilinmeyen çoklu-vardiya saatleri güvenli tarafta kalır ve çözüm öncesi yapılandırma ister.</div>
 </AppShell>;
}
