import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BookOpenCheck, Gauge, History, Save, Settings2, ShieldCheck, Users, Wrench } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";

type Profile={profile_key:string;name:string;description:string|null;weights:Record<string,number>;active:boolean};
type Settings={active_profile_key:string;explain_scenarios:boolean;record_repairs:boolean};
type RuleMode={rule_code:string;label:string;category:string;mode:"off"|"soft"|"hard";weight:number;config:Record<string,unknown>};
type Course={id:string;name:string};
type Pedagogy={course_id:string;academic_load:number;physical_load:number;practical_load:number;attention_load:number;difficulty:number;lesson_family:string|null;is_workshop:boolean;is_vocational_practice:boolean;prefer_early:boolean;avoid_early:boolean;prefer_weekdays:number[]};
type Workshop={course_id:string;min_block:number;preferred_block:number;max_block:number;preferred_patterns:number[][];active:boolean};
type Teacher={user_id:string;full_name:string|null};
type Duty={teacher_id:string;weekday:number;max_duty_day_hours:number;anchor_period:number|null;overload_weight:number;adjacent_weight:number;hard_max:boolean;source:string};
type Audit={id:string;scenario_id:string;action_no:number;issue_code:string;description:string;score_delta:number|null;hard_issues_before:number|null;hard_issues_after:number|null;created_at:string};
const dayLabels:Record<number,string>={1:"Pazartesi",2:"Salı",3:"Çarşamba",4:"Perşembe",5:"Cuma",6:"Cumartesi",7:"Pazar"};
const nums=(value:string)=>value.split(/[,+\s]+/).map(Number).filter((n)=>Number.isInteger(n)&&n>0);

export const Route=createFileRoute("/schedule-optimization")({head:()=>({meta:[{title:"Program Optimizasyonu — OkulOS"}]}),component:ScheduleOptimization});

function ScheduleOptimization(){
 const {can}=usePermissions();const editable=can("schedule.rules");
 const [profiles,setProfiles]=useState<Profile[]>([]),[settings,setSettings]=useState<Settings|null>(null),[rules,setRules]=useState<RuleMode[]>([]),[courses,setCourses]=useState<Course[]>([]),[pedagogy,setPedagogy]=useState<Pedagogy[]>([]),[workshops,setWorkshops]=useState<Workshop[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[duties,setDuties]=useState<Duty[]>([]),[audits,setAudits]=useState<Audit[]>([]),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const [courseId,setCourseId]=useState(""),[teacherId,setTeacherId]=useState(""),[dutyDay,setDutyDay]=useState(1);
 const load=useCallback(async()=>{setMessage(null);const [p,s,r,c,pg,w,t,d,a]=await Promise.all([
  supabase.from("schedule_optimization_profiles").select("profile_key,name,description,weights,active").eq("active",true).order("name"),
  supabase.from("schedule_optimization_settings").select("active_profile_key,explain_scenarios,record_repairs").eq("id",true).maybeSingle(),
  supabase.from("schedule_rule_modes").select("rule_code,label,category,mode,weight,config").order("category").order("label"),
  supabase.from("course_catalog").select("id,name").eq("active",true).order("name"),
  supabase.from("course_pedagogy_profiles").select("course_id,academic_load,physical_load,practical_load,attention_load,difficulty,lesson_family,is_workshop,is_vocational_practice,prefer_early,avoid_early,prefer_weekdays"),
  supabase.from("schedule_workshop_policies").select("course_id,min_block,preferred_block,max_block,preferred_patterns,active"),
  supabase.from("profiles").select("user_id,full_name").eq("role","teacher").order("full_name"),
  supabase.from("schedule_duty_optimization").select("teacher_id,weekday,max_duty_day_hours,anchor_period,overload_weight,adjacent_weight,hard_max,source").order("weekday"),
  supabase.from("schedule_repair_audit").select("id,scenario_id,action_no,issue_code,description,score_delta,hard_issues_before,hard_issues_after,created_at").order("created_at",{ascending:false}).limit(30),
 ]);const err=p.error??s.error??r.error??c.error??pg.error??w.error??t.error??d.error??a.error;if(err){setMessage(`Optimizasyon verileri tam okunamadı: ${err.message}`);return;}setProfiles((p.data??[]) as Profile[]);setSettings((s.data??null) as Settings|null);setRules((r.data??[]) as RuleMode[]);setCourses((c.data??[]) as Course[]);setPedagogy((pg.data??[]) as Pedagogy[]);setWorkshops((w.data??[]) as Workshop[]);setTeachers((t.data??[]) as Teacher[]);setDuties((d.data??[]) as Duty[]);setAudits((a.data??[]) as Audit[])},[]);
 useEffect(()=>{void load()},[load]);
 const selectedPed=useMemo(()=>pedagogy.find((x)=>x.course_id===courseId),[pedagogy,courseId]);
 const selectedWorkshop=useMemo(()=>workshops.find((x)=>x.course_id===courseId),[workshops,courseId]);
 const selectedDuty=useMemo(()=>duties.find((x)=>x.teacher_id===teacherId&&x.weekday===dutyDay),[duties,teacherId,dutyDay]);
 async function applyProfile(key:string){if(!editable)return;setBusy(true);const {error}=await supabase.rpc("apply_schedule_optimization_profile_v1",{p_profile_key:key});setBusy(false);setMessage(error?`Profil uygulanamadı: ${error.message}`:"Optimizasyon profili uygulandı; ilgili fitness ağırlıkları güncellendi.");if(!error)await load()}
 async function updateRule(rule:RuleMode,patch:Partial<RuleMode>){if(!editable)return;const next={...rule,...patch};const {error}=await supabase.from("schedule_rule_modes").update({mode:next.mode,weight:next.weight,updated_at:new Date().toISOString()}).eq("rule_code",rule.rule_code);setMessage(error?`Kural kaydedilemedi: ${error.message}`:"Kural modu kaydedildi.");if(!error)setRules((current)=>current.map((x)=>x.rule_code===rule.rule_code?next:x))}
 async function savePedagogy(form:HTMLFormElement){if(!editable||!courseId)return;const fd=new FormData(form);const payload={course_id:courseId,academic_load:Number(fd.get("academic")),physical_load:Number(fd.get("physical")),practical_load:Number(fd.get("practical")),attention_load:Number(fd.get("attention")),difficulty:Number(fd.get("difficulty")),lesson_family:String(fd.get("family")||"")||null,is_workshop:fd.get("workshop")==="on",is_vocational_practice:fd.get("vocational")==="on",prefer_early:fd.get("preferEarly")==="on",avoid_early:fd.get("avoidEarly")==="on",prefer_weekdays:nums(String(fd.get("weekdays")||"")),updated_at:new Date().toISOString()};const {error}=await supabase.from("course_pedagogy_profiles").upsert(payload,{onConflict:"institution_code,course_id"});setMessage(error?`Pedagojik profil kaydedilemedi: ${error.message}`:"Pedagojik ders profili kaydedildi.");if(!error)await load()}
 async function saveWorkshop(form:HTMLFormElement){if(!editable||!courseId)return;const fd=new FormData(form);const min=Number(fd.get("min")),preferred=Number(fd.get("preferred")),max=Number(fd.get("max"));if(min>preferred||preferred>max){setMessage("Blok sırası min ≤ tercih ≤ max olmalıdır.");return;}const {error}=await supabase.from("schedule_workshop_policies").upsert({course_id:courseId,min_block:min,preferred_block:preferred,max_block:max,active:true,updated_at:new Date().toISOString()},{onConflict:"institution_code,course_id"});setMessage(error?`Atölye politikası kaydedilemedi: ${error.message}`:"Atölye blok politikası kaydedildi.");if(!error)await load()}
 async function saveDuty(form:HTMLFormElement){if(!editable||!teacherId)return;const fd=new FormData(form);const {error}=await supabase.from("schedule_duty_optimization").upsert({teacher_id:teacherId,weekday:dutyDay,max_duty_day_hours:Number(fd.get("max")),anchor_period:fd.get("anchor")?Number(fd.get("anchor")):null,overload_weight:Number(fd.get("overload")),adjacent_weight:Number(fd.get("adjacent")),hard_max:fd.get("hard")==="on",source:"manual",updated_at:new Date().toISOString()},{onConflict:"institution_code,teacher_id,weekday"});setMessage(error?`Nöbet optimizasyonu kaydedilemedi: ${error.message}`:"Nöbet günü program politikası kaydedildi.");if(!error)await load()}
 return <AppShell title="Program Optimizasyonu" subtitle="Profil · HARD/SOFT/KAPALI · pedagojik yük · atölye · nöbet · repair geçmişi">
  <div className="mb-4 flex flex-wrap gap-2"><Link to="/timetable" className="rounded-md border px-3 py-2 text-sm">← Ders Programı</Link><Link to="/schedule-scenario-comparison" className="rounded-md border px-3 py-2 text-sm">Senaryoları Karşılaştır</Link><Link to="/schedule-scoped-rules" className="rounded-md border px-3 py-2 text-sm">Kapsamlı Kurallar</Link></div>
  {!editable?<div className="mb-4 flex items-center gap-2 rounded-xl border bg-muted/30 p-3 text-sm"><ShieldCheck className="size-4"/>Salt okunur; değiştirmek için Program Kuralları yetkisi gerekir.</div>:null}{message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <Tabs defaultValue="profiles"><TabsList className="grid h-auto w-full grid-cols-2 sm:grid-cols-3 lg:grid-cols-6"><TabsTrigger value="profiles">Profil</TabsTrigger><TabsTrigger value="rules">Kural Modları</TabsTrigger><TabsTrigger value="pedagogy">Pedagoji</TabsTrigger><TabsTrigger value="workshop">Atölye</TabsTrigger><TabsTrigger value="duty">Nöbet</TabsTrigger><TabsTrigger value="audit">Repair</TabsTrigger></TabsList>
   <TabsContent value="profiles" className="mt-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{profiles.map((p)=><article key={p.profile_key} className={`rounded-xl border p-4 ${settings?.active_profile_key===p.profile_key?"border-primary bg-primary/5":"bg-card"}`}><Gauge className="size-5 text-primary"/><h3 className="mt-2 font-semibold">{p.name}</h3><p className="mt-1 min-h-10 text-xs text-muted-foreground">{p.description}</p><div className="mt-3 flex flex-wrap gap-1">{Object.entries(p.weights??{}).slice(0,6).map(([k,v])=><span key={k} className="rounded bg-muted px-2 py-1 text-[10px]">{k}: {v}</span>)}</div><Button className="mt-3 w-full" variant={settings?.active_profile_key===p.profile_key?"secondary":"default"} disabled={!editable||busy||settings?.active_profile_key===p.profile_key} onClick={()=>void applyProfile(p.profile_key)}>{settings?.active_profile_key===p.profile_key?"Aktif Profil":"Bu Profili Uygula"}</Button></article>)}</div></TabsContent>
   <TabsContent value="rules" className="mt-4 space-y-2">{rules.map((r)=><div key={r.rule_code} className="grid gap-3 rounded-xl border bg-card p-3 sm:grid-cols-[1fr_150px_120px] sm:items-center"><div><p className="font-medium">{r.label}</p><p className="text-[11px] text-muted-foreground">{r.category} · {r.rule_code}</p></div><select className="h-10 rounded-md border bg-background px-2 text-sm" disabled={!editable} value={r.mode} onChange={(e)=>void updateRule(r,{mode:e.target.value as RuleMode["mode"]})}><option value="hard">HARD</option><option value="soft">SOFT</option><option value="off">KAPALI</option></select><Input disabled={!editable||r.mode==="hard"} type="number" value={r.weight} onChange={(e)=>setRules((current)=>current.map((x)=>x.rule_code===r.rule_code?{...x,weight:Number(e.target.value)}:x))} onBlur={(e)=>void updateRule({...r,weight:Number(e.target.value)},{weight:Number(e.target.value)})}/></div>)}</TabsContent>
   <TabsContent value="pedagogy" className="mt-4"><section className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-primary"/><h2 className="font-semibold">Ders Pedagojik Profili</h2></div><select className="mt-3 h-10 w-full rounded-md border bg-background px-3" value={courseId} onChange={(e)=>setCourseId(e.target.value)}><option value="">Ders seçiniz</option>{courses.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{courseId?<form key={`p-${courseId}-${selectedPed?.difficulty??0}`} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5" onSubmit={(e)=>{e.preventDefault();void savePedagogy(e.currentTarget)}}><div><Label>Akademik yük 1-5</Label><Input name="academic" type="number" min={1} max={5} defaultValue={selectedPed?.academic_load??3}/></div><div><Label>Dikkat 1-5</Label><Input name="attention" type="number" min={1} max={5} defaultValue={selectedPed?.attention_load??3}/></div><div><Label>Fiziksel 1-5</Label><Input name="physical" type="number" min={1} max={5} defaultValue={selectedPed?.physical_load??1}/></div><div><Label>Uygulama 1-5</Label><Input name="practical" type="number" min={1} max={5} defaultValue={selectedPed?.practical_load??1}/></div><div><Label>Zorluk 1-5</Label><Input name="difficulty" type="number" min={1} max={5} defaultValue={selectedPed?.difficulty??3}/></div><div className="sm:col-span-2"><Label>Ders ailesi</Label><Input name="family" defaultValue={selectedPed?.lesson_family??""} placeholder="sayısal / dil / fiziksel / uygulama"/></div><div className="sm:col-span-2"><Label>Tercih edilen günler (1-7)</Label><Input name="weekdays" defaultValue={(selectedPed?.prefer_weekdays??[]).join(",")}/></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm"><input name="workshop" type="checkbox" defaultChecked={selectedPed?.is_workshop}/> Atölye</label><label className="text-sm"><input name="vocational" type="checkbox" defaultChecked={selectedPed?.is_vocational_practice}/> Meslek</label><label className="text-sm"><input name="preferEarly" type="checkbox" defaultChecked={selectedPed?.prefer_early}/> Erken tercih</label><label className="text-sm"><input name="avoidEarly" type="checkbox" defaultChecked={selectedPed?.avoid_early}/> Erken kaçın</label></div><Button disabled={!editable} className="sm:col-span-2 lg:col-span-5"><Save className="mr-2 size-4"/>Pedagojik Profili Kaydet</Button></form>:null}</section></TabsContent>
   <TabsContent value="workshop" className="mt-4"><section className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><Wrench className="size-5 text-primary"/><h2 className="font-semibold">Atölye / Meslek Blok Politikası</h2></div><select className="mt-3 h-10 w-full rounded-md border bg-background px-3" value={courseId} onChange={(e)=>setCourseId(e.target.value)}><option value="">Ders seçiniz</option>{courses.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{courseId?<form key={`w-${courseId}-${selectedWorkshop?.preferred_block??0}`} className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={(e)=>{e.preventDefault();void saveWorkshop(e.currentTarget)}}><div><Label>Minimum blok</Label><Input name="min" type="number" min={1} max={12} defaultValue={selectedWorkshop?.min_block??3}/></div><div><Label>Tercih blok</Label><Input name="preferred" type="number" min={1} max={12} defaultValue={selectedWorkshop?.preferred_block??5}/></div><div><Label>Maksimum blok</Label><Input name="max" type="number" min={1} max={12} defaultValue={selectedWorkshop?.max_block??7}/></div>{selectedWorkshop?.preferred_patterns?.length?<p className="text-xs text-muted-foreground sm:col-span-3">Mevcut desenler: {selectedWorkshop.preferred_patterns.map((p)=>p.join("+")).join(" · ")}</p>:null}<Button disabled={!editable} className="sm:col-span-3">Blok Politikasını Kaydet</Button></form>:null}</section></TabsContent>
   <TabsContent value="duty" className="mt-4"><section className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><Users className="size-5 text-primary"/><h2 className="font-semibold">Nöbet ↔ Ders Programı Optimizasyonu</h2></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><select className="h-10 rounded-md border bg-background px-3" value={teacherId} onChange={(e)=>setTeacherId(e.target.value)}><option value="">Öğretmen seçiniz</option>{teachers.map((t)=><option key={t.user_id} value={t.user_id}>{t.full_name}</option>)}</select><select className="h-10 rounded-md border bg-background px-3" value={dutyDay} onChange={(e)=>setDutyDay(Number(e.target.value))}>{Object.entries(dayLabels).map(([d,l])=><option key={d} value={d}>{l}</option>)}</select></div>{teacherId?<form key={`d-${teacherId}-${dutyDay}-${selectedDuty?.max_duty_day_hours??0}`} className="mt-4 grid gap-3 sm:grid-cols-5" onSubmit={(e)=>{e.preventDefault();void saveDuty(e.currentTarget)}}><div><Label>Nöbet günü max ders</Label><Input name="max" type="number" min={0} max={12} defaultValue={selectedDuty?.max_duty_day_hours??5}/></div><div><Label>Nöbet anchor saati</Label><Input name="anchor" type="number" min={1} max={12} defaultValue={selectedDuty?.anchor_period??""}/></div><div><Label>Fazla yük cezası</Label><Input name="overload" type="number" defaultValue={selectedDuty?.overload_weight??20}/></div><div><Label>Bitişik ders cezası</Label><Input name="adjacent" type="number" defaultValue={selectedDuty?.adjacent_weight??15}/></div><label className="flex items-end gap-2 pb-2 text-sm"><input name="hard" type="checkbox" defaultChecked={selectedDuty?.hard_max}/> Maksimum HARD</label><Button disabled={!editable} className="sm:col-span-5">Nöbet Politikasını Kaydet</Button></form>:null}</section></TabsContent>
   <TabsContent value="audit" className="mt-4"><section className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><History className="size-5 text-primary"/><h2 className="font-semibold">Son Repair İşlemleri</h2></div><div className="mt-3 space-y-2">{audits.length?audits.map((a)=><div key={a.id} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><b>{a.issue_code}</b><span className="text-xs text-muted-foreground">Senaryo {a.scenario_id.slice(0,8)} · #{a.action_no}</span></div><p className="mt-1 text-xs text-muted-foreground">{a.description}</p><p className="mt-2 text-xs">Hard: {a.hard_issues_before??"?"} → {a.hard_issues_after??"?"} · Score Δ {a.score_delta??0}</p></div>):<p className="text-sm text-muted-foreground">Henüz repair audit kaydı yok.</p>}</div></section></TabsContent>
  </Tabs>
 </AppShell>
}
