import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowLeft, Building2, Check, Circle, KeyRound, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { supabase } from "@/lib/supabase";
import { isValidEmail, isValidTckn, isValidTrMobile, normalizeDigits, normalizeTrPhone } from "@/lib/auth-validation";

export const Route=createFileRoute("/school-registration")({head:()=>({meta:[{title:"Okul Kaydı — OkulOS"}]}),component:SchoolRegistration});

type Status={ok:boolean;label:string;required?:boolean};
const commonSequences=["123456","12345678","abcdef","abcde","qwerty","qwertyui","asdfgh","password","parola","sifre","şifre"];
function lower(v:string){return v.toLocaleLowerCase("tr-TR").replace(/\s+/g,"");}
function passwordAssessment(password:string,confirm:string,personal:string[],unique:boolean){
 const noCommon=!commonSequences.some(x=>lower(password).includes(lower(x)));
 const noPersonal=!personal.filter(x=>lower(x).length>=4).some(x=>lower(password).includes(lower(x)));
 const rows:Status[]=[
  {ok:password.length>=8,label:"En az 8 karakter",required:true},
  {ok:password.length>=14,label:"14+ karakter (önerilen)"},
  {ok:/[A-ZÇĞİÖŞÜ]/.test(password),label:"En az bir büyük harf",required:true},
  {ok:/[a-zçğıöşü]/.test(password),label:"En az bir küçük harf",required:true},
  {ok:/\d/.test(password),label:"En az bir rakam",required:true},
  {ok:/[^A-Za-z0-9ÇĞİÖŞÜçğıöşü]/.test(password),label:"En az bir özel simge (! ? @ # * …)",required:true},
  {ok:noCommon,label:"Basit dizi / qwerty / 123456 içermiyor",required:true},
  {ok:noPersonal,label:"İsim, okul, kurum kodu, telefon veya T.C. bilgisi içermiyor",required:true},
  {ok:unique,label:"Bu hesap için ayrı ve benzersiz şifre kullanıyorum",required:true},
  {ok:Boolean(confirm)&&password===confirm,label:Boolean(confirm)&&password===confirm?"Şifreler eşleşiyor":"Şifreler uyuşmuyor",required:true},
 ];
 return {rows,valid:rows.filter(x=>x.required).every(x=>x.ok)};
}
function Checklist({rows}:{rows:Status[]}){return <div className="rounded-xl border bg-muted/25 p-3"><p className="mb-2 text-xs font-semibold">Şifre kıstasları</p><div className="space-y-1.5">{rows.map(x=><div key={x.label} className={`flex items-start gap-1.5 text-[11px] ${x.ok?"text-emerald-700":"text-muted-foreground"}`}>{x.ok?<Check className="mt-0.5 size-3.5 shrink-0"/>:<Circle className="mt-0.5 size-3.5 shrink-0"/>}<span>{x.label}</span></div>)}</div></div>}
function normalizeCode(v:string){return normalizeDigits(v).slice(0,10);}
function callbackUrl(){return typeof window==="undefined"?undefined:`${window.location.origin}/auth/callback`;}

function SchoolRegistration(){
 const navigate=useNavigate();
 const [institutionCode,setInstitutionCode]=useState(""),[schoolName,setSchoolName]=useState(""),[principalName,setPrincipalName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[tckn,setTckn]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[unique,setUnique]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[step,setStep]=useState<"form"|"verify"|"done">("form"),[otp,setOtp]=useState(""),[maskedTc,setMaskedTc]=useState("");
 const normalizedPhone=normalizeTrPhone(phone),normalizedEmail=email.trim().toLowerCase();
 const personal=useMemo(()=>[principalName,schoolName,institutionCode,normalizedPhone,tckn,normalizedEmail.split("@")[0]??""],[principalName,schoolName,institutionCode,normalizedPhone,tckn,normalizedEmail]);
 const assessment=useMemo(()=>passwordAssessment(password,confirm,personal,unique),[password,confirm,personal,unique]);
 const fieldsOk=/^\d{5,10}$/.test(institutionCode)&&schoolName.trim().length>=3&&principalName.trim().length>=3&&isValidTrMobile(normalizedPhone)&&isValidEmail(normalizedEmail)&&isValidTckn(tckn);
 async function submit(e:React.FormEvent){e.preventDefault();setError(null);if(!fieldsOk)return setError("Kurum ve müdür bilgilerini kontrol edin. T.C., e-posta ve cep telefonu biçimi geçerli olmalıdır.");if(!assessment.valid)return setError("Şifre için zorunlu kıstasların tamamını sağlayın ve iki şifreyi eşleştirin.");setBusy(true);const {data,error:fnError}=await supabase.functions.invoke("register-school",{body:{institutionCode,schoolName:schoolName.trim(),principalName:principalName.trim(),phone:normalizedPhone,email:normalizedEmail,tckn,password,redirectTo:callbackUrl()}});setBusy(false);if(fnError||!data?.ok){const code=data?.code as string|undefined;const messages:Record<string,string>={INVALID_INSTITUTION_CODE:"Kurum kodu geçerli değil.",INVALID_PHONE:"Cep telefonu geçerli değil.",INVALID_EMAIL:"E-posta adresi geçerli değil.",INVALID_IDENTITY:"T.C. Kimlik Numarası kontrol basamakları geçerli değil.",WEAK_OR_PERSONAL_PASSWORD:"Şifre kıstasları karşılanmıyor veya kişisel bilgi içeriyor.",INSTITUTION_ALREADY_REGISTERED:"Bu kurum kodu daha önce OkulOS'a kaydedilmiş.",EMAIL_ALREADY_REGISTERED:"Bu müdür e-postasıyla daha önce okul kaydı yapılmış."};return setError(messages[code??""]??"Okul kaydı başlatılamadı. Bilgileri kontrol edip tekrar deneyin.")}
 setMaskedTc(data.tcknMasked??`*******${tckn.slice(-4)}`);setTckn("");setPassword("");setConfirm("");setStep("verify");}
 async function verify(){if(otp.length!==6)return;setBusy(true);setError(null);const {error:e}=await supabase.auth.verifyOtp({email:normalizedEmail,token:otp,type:"email"});setBusy(false);if(e){setOtp("");return setError("Doğrulama kodu geçersiz veya süresi dolmuş.")}setStep("done");}
 if(step==="done")return <div className="min-h-screen bg-background px-4 py-10"><div className="mx-auto max-w-xl rounded-2xl border bg-card p-6 shadow-sm"><div className="grid size-12 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><Check className="size-6"/></div><h1 className="mt-4 text-xl font-semibold">Okul kaydı tamamlandı</h1><p className="mt-2 text-sm text-muted-foreground">{schoolName} için tenant oluşturuldu ve müdür hesabı kurum sahibi olarak tanımlandı.</p><Button className="mt-5 w-full" onClick={()=>void navigate({to:"/dashboard",replace:true})}>OkulOS'a Devam Et</Button></div></div>;
 if(step==="verify")return <div className="min-h-screen bg-background px-4 py-10"><div className="mx-auto max-w-xl rounded-2xl border bg-card p-6 shadow-sm"><KeyRound className="size-8 text-primary"/><h1 className="mt-3 text-xl font-semibold">Müdür e-postasını doğrulayın</h1><p className="mt-2 text-sm text-muted-foreground">{normalizedEmail} adresine gönderilen 6 haneli kodu girin. T.C. Kimlik Numarası veritabanında açık olarak tutulmaz; kayıtlı görünüm {maskedTc} biçimindedir.</p><div className="mt-5"><InputOTP maxLength={6} value={otp} onChange={v=>setOtp(v.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code"><InputOTPGroup>{[0,1,2,3,4,5].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></div>{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">{error}</div>:null}<Button className="mt-4 w-full" disabled={busy||otp.length!==6} onClick={()=>void verify()}>E-postayı Doğrula</Button></div></div>;
 return <div className="min-h-screen bg-background px-4 py-8 sm:py-12"><div className="mx-auto max-w-4xl"><div className="mb-5 flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Building2 className="size-5"/></div><div><h1 className="text-2xl font-semibold">Okul Kaydı</h1><p className="text-sm text-muted-foreground">OkulOS'ta yeni kurum / tenant oluştur</p></div></div></div><Link to="/"><Button variant="outline" className="gap-1"><ArrowLeft className="size-4"/>Giriş</Button></Link></div>
 <form onSubmit={submit} className="space-y-5"><section className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Kurum ve müdür bilgileri</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Kurum Kodu</Label><Input inputMode="numeric" value={institutionCode} onChange={e=>setInstitutionCode(normalizeCode(e.target.value))} placeholder="MEB kurum kodu"/><p className={`text-[11px] ${/^\d{5,10}$/.test(institutionCode)?"text-emerald-700":"text-muted-foreground"}`}>{/^\d{5,10}$/.test(institutionCode)?"✓ Kurum kodu biçimi uygun":"5–10 haneli sayısal kurum kodu"}</p></div><div className="space-y-2"><Label>Okul Adı</Label><Input value={schoolName} onChange={e=>setSchoolName(e.target.value)} autoComplete="organization"/></div><div className="space-y-2"><Label>Müdür Adı</Label><Input value={principalName} onChange={e=>setPrincipalName(e.target.value)} autoComplete="name"/></div><div className="space-y-2"><Label>Müdür Telefonu</Label><Input inputMode="tel" value={phone} onChange={e=>setPhone(normalizeTrPhone(e.target.value))} autoComplete="tel" placeholder="05xxxxxxxxx"/><p className={`text-[11px] ${isValidTrMobile(normalizedPhone)?"text-emerald-700":"text-muted-foreground"}`}>{isValidTrMobile(normalizedPhone)?"✓ Türkiye cep telefonu biçimi uygun":"05 ile başlayan 11 haneli cep telefonu"}</p></div><div className="space-y-2"><Label>Müdür E-postası</Label><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/><p className={`text-[11px] ${isValidEmail(normalizedEmail)?"text-emerald-700":"text-muted-foreground"}`}>{isValidEmail(normalizedEmail)?"✓ E-posta biçimi uygun":"Geçerli bir e-posta adresi girin"}</p></div><div className="space-y-2"><Label>T.C. Kimlik Numarası</Label><Input inputMode="numeric" type="password" maxLength={11} value={tckn} onChange={e=>setTckn(normalizeDigits(e.target.value).slice(0,11))} autoComplete="off"/><p className={`text-[11px] ${isValidTckn(tckn)?"text-emerald-700":"text-muted-foreground"}`}>{isValidTckn(tckn)?"✓ T.C. kontrol basamakları geçerli":"11 haneli T.C. Kimlik Numarası"}</p></div></div><div className="mt-4 flex items-start gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950"><ShieldCheck className="mt-0.5 size-4 shrink-0"/><p><b>T.C. Kimlik No yalnız hesap kurtarma teyidi için kullanılır.</b> Açık T.C. numarası kaydedilmez; sistemde yalnız maskeli görünüm ve tek yönlü güvenli doğrulama özeti tutulur. Uygulama modüllerine açılmaz ve başka amaçla kullanılmaz.</p></div></section>
 <section className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Güçlü şifre</h2><p className="mt-1 text-xs text-muted-foreground">Minimum 8 karakter zorunludur; 14+ karakter önerilir. Büyük/küçük harf, rakam ve özel simge birlikte kullanın.</p><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr]"><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-[1fr_280px]"><div className="space-y-2"><Label>Şifre</Label><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></div><Checklist rows={assessment.rows}/></div><div className="grid gap-3 sm:grid-cols-[1fr_280px]"><div className="space-y-2"><Label>Şifreyi Onayla</Label><Input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/><p className={`text-xs ${confirm&&password===confirm?"text-emerald-700":confirm?"text-destructive":"text-muted-foreground"}`}>{confirm?(password===confirm?"✓ Şifreler eşleşiyor":"Şifreler uyuşmuyor"):"Aynı şifreyi ikinci kez girin"}</p></div><Checklist rows={assessment.rows}/></div></div><div className="rounded-xl border bg-muted/25 p-4 text-xs text-muted-foreground"><b className="text-foreground">Kaçınılması gerekenler</b><p className="mt-2">İsim, doğum tarihi, evcil hayvan adı, memleket gibi kişisel bilgiler; 123456, abcde, qwerty gibi basit veya klavye üzerinde yan yana diziler kullanılmamalıdır.</p><label className={`mt-4 flex cursor-pointer items-start gap-2 rounded-lg border p-3 ${unique?"border-emerald-300 bg-emerald-50 text-emerald-800":"bg-card"}`}><input type="checkbox" checked={unique} onChange={e=>setUnique(e.target.checked)} className="mt-0.5"/><span>Bu şifreyi başka bir hesabımda kullanmıyorum; bu hesap için ayrı ve benzersizdir.</span></label></div></div></section>
 {error?<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}<Button type="submit" size="lg" className="w-full" disabled={busy||!fieldsOk||!assessment.valid}>{busy?"Okul kaydı oluşturuluyor…":"Okulu Kaydet ve Müdür Hesabını Oluştur"}</Button></form></div></div>;
}
