import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, FileSpreadsheet, Printer, Search } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SecuritySectionNav } from "@/components/okulos/SecuritySectionNav";
import { supabase } from "@/lib/supabase";
import { visitorStatusLabel } from "@/lib/visitor-security";

export const Route = createFileRoute("/security/visitors/ledger")({ head: () => ({ meta: [{ title: "Ziyaretçi Defteri — OkulOS" }, { name: "description", content: "OkulOS ziyaretçi defteri, filtreleme ve dışa aktarma ekranı." }] }), component: VisitorLedger });
type Row = { id: string; status: string; entry_at: string; exit_at: string | null; visit_reason: string | null; card_no: string | null; identity_method: string; visitor_people: { full_name: string; phone: string | null; tc_last4: string | null } | null };
const columns = [{ key: "visitor", label: "Ziyaretçi" }, { key: "status", label: "Durum" }, { key: "entry", label: "Giriş" }, { key: "exit", label: "Çıkış" }, { key: "reason", label: "Neden" }, { key: "method", label: "Kimlik yöntemi" }] as const;
function VisitorLedger() { const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [visible, setVisible] = useState(new Set(columns.map((column) => column.key))); const load = useCallback(async () => { let request = supabase.from("visitor_visits").select("id,status,entry_at,exit_at,visit_reason,card_no,identity_method,visitor_people(full_name,phone,tc_last4)").order("entry_at", { ascending: false }).limit(500); if (from) request = request.gte("entry_at", `${from}T00:00:00`); if (to) request = request.lte("entry_at", `${to}T23:59:59`); const { data, error } = await request; if (!error) setRows((data ?? []) as unknown as Row[]); }, [from, to]); useEffect(() => { void load(); }, [load]); const filtered = useMemo(() => rows.filter((row) => `${row.visitor_people?.full_name ?? ""} ${row.visitor_people?.phone ?? ""} ${row.visit_reason ?? ""}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [rows, query]); function exportCsv() { const lines = [columns.map((column) => column.label).join(";"), ...filtered.map((row) => [row.visitor_people?.full_name ?? "", visitorStatusLabel(row.status), row.entry_at, row.exit_at ?? "", row.visit_reason ?? "", row.identity_method].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(";"))]; const blob = new Blob([`\ufeff${lines.join("\n")}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "okulos-ziyaretci-defteri.csv"; link.click(); URL.revokeObjectURL(url); } return <AppShell title="Ziyaretçi Defteri" subtitle="Filtrele · sütun seç · Excel uyumlu dışa aktar">
    <SecuritySectionNav active="/security/visitors/ledger" /><section className="rounded-xl border bg-card p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="İsim, telefon veya ziyaret nedeni" /></div><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs font-medium text-muted-foreground">Sütunlar:</span>{columns.map((column) => <label key={column.key} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={visible.has(column.key)} onChange={() => setVisible((current) => { const next = new Set(current); if (next.has(column.key)) next.delete(column.key); else next.add(column.key); return next; })} />{column.label}</label>)}<span className="flex-1" /><Button variant="outline" size="sm" onClick={exportCsv}><FileSpreadsheet className="size-4" /> Excel/CSV</Button><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="size-4" /> Yazdır / PDF</Button></div></section><section className="mt-5 overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/30 text-left"><tr>{visible.has("visitor") ? <th className="p-3">Ziyaretçi</th> : null}{visible.has("status") ? <th className="p-3">Durum</th> : null}{visible.has("entry") ? <th className="p-3">Giriş</th> : null}{visible.has("exit") ? <th className="p-3">Çıkış</th> : null}{visible.has("reason") ? <th className="p-3">Neden</th> : null}{visible.has("method") ? <th className="p-3">Kimlik yöntemi</th> : null}</tr></thead><tbody className="divide-y">{filtered.map((row) => <tr key={row.id}>{visible.has("visitor") ? <td className="p-3 font-medium">{row.visitor_people?.full_name ?? "—"}<span className="block text-xs text-muted-foreground">{row.visitor_people?.phone ?? "Telefon yok"}</span></td> : null}{visible.has("status") ? <td className="p-3">{visitorStatusLabel(row.status)}</td> : null}{visible.has("entry") ? <td className="p-3 whitespace-nowrap">{new Date(row.entry_at).toLocaleString("tr-TR")}</td> : null}{visible.has("exit") ? <td className="p-3 whitespace-nowrap">{row.exit_at ? new Date(row.exit_at).toLocaleString("tr-TR") : "—"}</td> : null}{visible.has("reason") ? <td className="p-3">{row.visit_reason ?? "—"}</td> : null}{visible.has("method") ? <td className="p-3">{row.identity_method === "camera_live" ? "Canlı kamera" : "Manuel"}</td> : null}</tr>)}{!filtered.length ? <tr><td colSpan={6} className="p-8 text-center text-muted-foreground">Filtreye uyan kayıt yok.</td></tr> : null}</tbody></table></section>
  </AppShell>; }
