import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Check, Plus, RefreshCw, UserPlus, X } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/settings-task-roles")({head:()=>({meta:[{title:"Görev Şablonları — OkulOS"}]}),component:TaskRoleTemplates});
type Permission={code:string;module_code:string;module_label:string;label:string;description:string|null;dangerous:boolean;sort_order:number};
type Template={id:string;name:string;description:string|null;active:boolean};
type TemplatePermission={template_id:string;permission_code:string};
type Person={user_id:string;full_name:string|null;role:string};
type Assignment={id:string;user_id:string;template_id:string;valid_from:string|null;valid_until:string|null;active:boolean;assigned_at:string;note:string|null};

function TaskRoleTemplates(){
 const [permissions,setPermissions]=useState<Permission[]>([]),[templates,setTemplates]=useState<Template[]>([]),[templatePermissions,setTemplatePermissions]=useState<TemplatePermission[]>([]),[people,setPeople]=useState<Person[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]);
 const [selectedTemplate,setSelectedTemplate]=useState<string>(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[selectedCodes,setSelectedCodes]=useState<Set<string>>(new Set());
 const [personId,setPersonId]=useState(""),[from,setFrom]=useState(""),[until,setUntil]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setMessage(null);const [p,t,tp,pe,a]=await Promise.all([
   supabase.from("permission_catalog").select("code,module_code,module_label,label,description,dangerous,sort_order").eq("active",true).order("sort_order"),
   supabase.from("task_role_templates").select("id,name,description,active").eq("active",true).order("name"),
   supabase.from("task_role_template_permissions").select("template_id,permission_code"),
   supabase.rpc("get_permission_admin_matrix"),
   supabase.from("user_task_role_assignments").select("id,user_id,template_id,valid_from,valid_until,active,assigned_at,note").eq("active",true).order("assigned_at",{ascending:false}),
 ]);if(p.error||t.error||tp.error||pe.error||a.error){setMessage("Görev şablonları yüklenemedi. Bu ekran yalnız yetki yöneticileri tarafından kullanılabilir.");return;}setPermissions((p.data??[]) as Permission[]);setTemplates((t.data??[]) as Template[]);setTemplatePermissions((tp.data??[]) as TemplatePermission[]);const unique=new Map<string,Person>();for(const row of (pe.data??[]) as Array<Person&{permission_code:string|null}>){if(!unique.has(row.user_id))unique.set(row.user_id,{user_id:row.user_id,full_name:row.full_name,role:row.role});}setPeople(Array.from(unique.values()));setAssignments((a.data??[]) as Assignment[]);},[]);
 useEffect(()=>{void load();},[load]);
 const groups=useMemo(()=>Array.from(new Map(permissions.map(p=>[p.module_code,{label:p.module_label,items:permissions.filter(x=>x.module_code===p.module_code)}])).values()),[permissions]);
 const personMap=useMemo(()=>Object.fromEntries(people.map(p=>[p.user_id,p.full_name??"Personel"])),[people]);const templateMap=useMemo(()=>Object.fromEntries(templates.map(t=>[t.id,t.name])),[templates]);
 function newTemplate(){setSelectedTemplate("");setName("");setDescription("");setSelectedCodes(new Set());}
 function editTemplate(id:string){const t=templates.find(x=>x.id===id);if(!t)return;setSelectedTemplate(id);setName(t.name);setDescription(t.description??"");setSelectedCodes(new Set(templatePermissions.filter(x=>x.template_id===id).map(x=>x.permission_code)));}
 function toggle(code:string){setSelectedCodes(prev=>{const n=new Set(prev);if(n.has(code))n.delete(code);else n.add(code);return n;});}
 async function save(){if(!name.trim()){setMessage("Görev şablonu adı zorunludur.");return;}setBusy(true);const {data,error}=await supabase.rpc("save_task_role_template",{p_template_id:selectedTemplate||null,p_name:name.trim(),p_description:description||null,p_permission_codes:Array.from(selectedCodes)});setBusy(false);if(error){setMessage(`Şablon kaydedilemedi: ${error.message}`);return;}setSelectedTemplate(String(data));setMessage("Görev şablonu kaydedildi.");await load();}
 async function assign(){if(!personId||!selectedTemplate){setMessage("Personel ve görev şablonu seçin.");return;}setBusy(true);const {data,error}=await supabase.rpc("assign_task_role_template",{p_user_id:personId,p_template_id:selectedTemplate,p_valid_from:from||null,p_valid_until:until||null,p_note:note||null});setBusy(false);if(error){setMessage(`Görev atanamadı: ${error.message}`);return;}setMessage(`${Number(data??0)} işlem yetkisi görev paketiyle atandı.`);await load();}
 async function revoke(userId:string,templateId:string){setBusy(true);const {error}=await supabase.rpc("revoke_task_role_template",{p_user_id:userId,p_template_id:templateId});setBusy(false);if(error){setMessage(`Görev kaldırılamadı: ${error.message}`);return;}setMessage("Görev paketi kullanıcıdan kaldırıldı.");await load();}
 return <AppShell title="Görev Şablonları" subtitle="Okula özel tekrar kullanılabilir görev/rol paketleri" action={<BriefcaseBusiness className="size-5"/>}>
   <div className="grid gap-2 sm:grid-cols-3"><Link to="/settings/permissions"><Button variant="outline" className="w-full">Görev ve Yetki Atama</Button></Link><Button variant="outline" onClick={newTemplate}><Plus className="mr-2 size-4"/>Yeni Şablon</Button><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Yenile</Button></div>
   {message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
   <div className="mt-4 grid gap-4 lg:grid-cols-[280px_1fr]">
    <aside className="rounded-xl border bg-card p-3"><h2 className="text-sm font-semibold">Tanımlı Görevler</h2><div className="mt-2 space-y-2">{templates.map(t=><button key={t.id} onClick={()=>editTemplate(t.id)} className={`w-full rounded-lg border p-3 text-left ${selectedTemplate===t.id?"border-primary bg-primary/5":"hover:bg-muted/40"}`}><b className="text-sm">{t.name}</b><p className="mt-1 text-xs text-muted-foreground">{t.description||"Açıklama yok"}</p></button>)}{!templates.length?<p className="text-xs text-muted-foreground">Henüz görev şablonu yok.</p>:null}</div></aside>
    <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">{selectedTemplate?"Görev Şablonunu Düzenle":"Yeni Görev Şablonu"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label>Görev / Rol Adı</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Örn. Akademik İşler Müdür Yardımcısı"/></div><div><Label>Açıklama</Label><Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Görevin kapsamı"/></div></div>
     <div className="mt-4 space-y-3">{groups.map(g=><div key={g.label}><h3 className="mb-2 text-xs font-semibold text-muted-foreground">{g.label}</h3><div className="grid gap-2 md:grid-cols-2">{g.items.map(p=>{const on=selectedCodes.has(p.code);return <button type="button" key={p.code} onClick={()=>toggle(p.code)} className={`flex items-start gap-2 rounded-lg border p-2.5 text-left ${on?"border-emerald-300 bg-emerald-50":""}`}><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded ${on?"bg-emerald-600 text-white":"border"}`}>{on?<Check className="size-3"/>:null}</span><span><b className="text-xs">{p.label}</b>{p.dangerous?<span className="ml-2 text-[10px] text-amber-700">kritik</span>:null}<span className="block text-[10px] text-muted-foreground">{p.description??p.code}</span></span></button>})}</div></div>)}</div><Button className="mt-4 w-full" onClick={()=>void save()} disabled={busy}>Şablonu Kaydet</Button>
    </section>
   </div>
   {selectedTemplate?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Bu Görevi Personele Ata</h2><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><div><Label>Personel</Label><select value={personId} onChange={e=>setPersonId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Seçiniz</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.full_name??"Personel"} · {p.role}</option>)}</select></div><div><Label>Başlangıç</Label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><Label>Bitiş</Label><Input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></div><div><Label>Not</Label><Input value={note} onChange={e=>setNote(e.target.value)}/></div></div><Button className="mt-3 gap-2" onClick={()=>void assign()} disabled={busy}><UserPlus className="size-4"/>Görevi Ata</Button></section>:null}
   <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Aktif Görev Atamaları</h2><div className="mt-3 divide-y rounded-lg border">{assignments.map(a=><div key={a.id} className="flex flex-col gap-2 p-3 text-sm sm:flex-row sm:items-center"><div className="flex-1"><b>{personMap[a.user_id]??"Personel"}</b> · {templateMap[a.template_id]??"Görev"}<p className="text-xs text-muted-foreground">{a.valid_from??"Hemen"} → {a.valid_until??"Süresiz"}{a.note?` · ${a.note}`:""}</p></div><Button size="sm" variant="outline" className="gap-1" onClick={()=>void revoke(a.user_id,a.template_id)} disabled={busy}><X className="size-3.5"/>Kaldır</Button></div>)}{!assignments.length?<p className="p-4 text-xs text-muted-foreground">Aktif görev şablonu ataması yok.</p>:null}</div></section>
 </AppShell>;
}
