import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw, Shuffle, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";
import {SCHEDULE_SECTIONING_OPERATION_MODES,SECTIONING_OPERATION_POLICY,type ScheduleSectioningOperationMode} from "@/lib/schedule-sectioning-operation-mode";

export const Route=createFileRoute("/student-sectioning")({head:()=>({meta:[{title:"Öğrenci Sectioning — OkulOS"}]}),component:StudentSectioning});
const db=supabase as any;
type Student={id:string;school_number:string;full_name:string;class_id:string};
type Course={id:string;name:string;code:string|null};
type Req={id:string;student_id:string;course_id:string;priority:number;request_kind:string;alternative_group:string|null;allow_overlap:boolean;scope_mode:string};
type Free={id:string;student_id:string;weekday:number;periods:number[];mode:string;weight:number};
type Assignment={id:string;teacher_id:string;section_capacity:number|null;class_course_requirement_id:string};
type Requirement={id:string;class_id:string;course_id:string};
type SchoolClass={id:string;class_name:string};
type Profile={user_id:string;full_name:string};
type Candidate={assignment_id:string;teacher_id:string;capacity:number|null;load:number;feasible:boolean;hard_reasons:string[];medium_penalty:number;soft_penalty:number;is_current:boolean};
type Health={students_with_requests:number;active_requests:number;active_enrollments:number;open_issues:number;conflict_events:number;locked_enrollments:number;sections_at_capacity:number};
type Issue={id:string;student_id:string;request_id:string|null;code:string;detail:string|null};
type Enrollment={id:string;teacher_assignment_id:string;request_id:string|null;locked:boolean;source:string};

function StudentSectioning(){
 const {can}=usePermissions(),editable=can("schedule.generate")||can("schedule.rules");
 const [students,setStudents]=useState<Student[]>([]),[courses,setCourses]=useState<Course[]>([]),[requests,setRequests]=useState<Req[]>([]),[free,setFree]=useState<Free[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[issues,setIssues]=useState<Issue[]>([]),[enrollments,setEnrollments]=useState<Enrollment[]>([]);
 const [health,setHealth]=useState<Health|null>(null),[studentId,setStudentId]=useState(""),[requestId,setRequestId]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false),[operationMode,setOperationMode]=useState<ScheduleSectioningOperationMode>("SECTIONING_ONLY");
 const [courseId,setCourseId]=useState(""),[kind,setKind]=useState("PRIMARY"),[priority,setPriority]=useState("100"),[group,setGroup]=useState(""),[scope,setScope]=useState("HOME_CLASS"),[allowOverlap,setAllowOverlap]=useState(false);
 const [weekday,setWeekday]=useState("1"),[periods,setPeriods]=useState("1"),[freeMode,setFreeMode]=useState("SOFT"),[freeWeight,setFreeWeight]=useState("1"),[capacity,setCapacity]=useState("");
 const courseNames=useMemo(()=>Object.fromEntries(courses.map(x=>[x.id,x.name])),[courses]),classNames=useMemo(()=>Object.fromEntries(classes.map(x=>[x.id,x.class_name])),[classes]),teacherNames=useMemo(()=>Object.fromEntries(profiles.map(x=>[x.user_id,x.full_name])),[profiles]),reqById=useMemo(()=>Object.fromEntries(requests.map(x=>[x.id,x])),[requests]),reqByAssignment=useMemo(()=>{const out:Record<string,Requirement>={};for(const a of assignments){const r=requirements.find(x=>x.id===a.class_course_requirement_id);if(r)out[a.id]=r;}return out;},[assignments,requirements]);
 const selectedRequests=requests.filter(x=>x.student_id===studentId),selectedFree=free.filter(x=>x.student_id===studentId),selectedIssues=issues.filter(x=>x.student_id===studentId),selectedEnrollments=enrollments.filter(e=>studentId&&requests.some(r=>r.student_id===studentId&&r.id===e.request_id));
 const operation=SCHEDULE_SECTIONING_OPERATION_MODES[operationMode];

 const load=useCallback(async()=>{const [s,c,r,f,a,cr,cl,p,i,e,h]=await Promise.all([db.from("students").select("id,school_number,full_name,class_id").eq("active",true).order("full_name"),db.from("course_catalog").select("id,name,code").eq("active",true).order("name"),db.from("student_course_requests").select("id,student_id,course_id,priority,request_kind,alternative_group,allow_overlap,scope_mode").eq("active",true),db.from("student_free_time_requests").select("id,student_id,weekday,periods,mode,weight").eq("active",true),db.from("teacher_course_assignments").select("id,teacher_id,section_capacity,class_course_requirement_id"),db.from("class_course_requirements").select("id,class_id,course_id"),db.from("school_classes").select("id,class_name").eq("active",true),db.from("profiles").select("user_id,full_name"),db.from("student_sectioning_issues").select("id,student_id,request_id,code,detail"),db.from("student_schedule_enrollments").select("id,student_id,teacher_assignment_id,request_id,locked,source").eq("active",true),db.rpc("get_student_sectioning_health_v2")]);const err=[s,c,r,f,a,cr,cl,p,i,e,h].find(x=>x.error)?.error;if(err)return setMessage(`Sectioning verisi okunamadı: ${err.message}`);setStudents(s.data??[]);setCourses(c.data??[]);setRequests(r.data??[]);setFree(f.data??[]);setAssignments(a.data??[]);setRequirements(cr.data??[]);setClasses(cl.data??[]);setProfiles(p.data??[]);setIssues(i.data??[]);setEnrollments(e.data??[]);setHealth((h.data??[])[0]??null);if(!studentId&&s.data?.length)setStudentId(s.data[0].id);},[studentId]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!requestId){setCandidates([]);return;}void db.rpc("get_student_section_candidates_v2",{p_request_id:requestId}).then((x:any)=>x.error?setMessage(x.error.message):setCandidates(x.data??[]));},[requestId]);
 async function addRequest(){if(!editable||!studentId||!courseId)return;const {error}=await db.from("student_course_requests").insert({student_id:studentId,course_id:courseId,request_kind:kind,priority:Number(priority),alternative_group:group.trim()||null,allow_overlap:allowOverlap,scope_mode:scope,active:true});if(error)return setMessage(error.message);setMessage("Öğrenci ders talebi kaydedildi.");await load();}
 async function addFree(){const ps=periods.split(",").map(x=>Number(x.trim())).filter(x=>Number.isInteger(x)&&x>0);if(!editable||!studentId||!ps.length)return setMessage("Geçerli ders saatlerini virgülle girin.");const {error}=await db.from("student_free_time_requests").insert({student_id:studentId,weekday:Number(weekday),periods:ps,mode:freeMode,weight:Number(freeWeight),active:true});if(error)return setMessage(error.message);setMessage("Serbest-zaman tercihi kaydedildi.");await load();}
 async function runRpc(name:string,args:Record<string,unknown>={}){setBusy(true);const x=await db.rpc(name,args);setBusy(false);if(x.error)return setMessage(x.error.message);setMessage(typeof x.data==="object"?JSON.stringify(x.data):String(x.data));await load();if(requestId){const c=await db.rpc("get_student_section_candidates_v2",{p_request_id:requestId});if(!c.error)setCandidates(c.data??[]);}}
 async function saveCapacity(assignmentId:string){if(!editable||!capacity)return;const {error}=await db.from("teacher_course_assignments").update({section_capacity:Number(capacity)}).eq("id",assignmentId);if(error)return setMessage(error.message);setMessage("Section kapasitesi güncellendi.");setCapacity("");await load();}
 return <AppShell title="Öğrenci Sectioning" subtitle="Talep · alternatif · kapasite · free-time · online/batch yerleştirme · conflict repair" action={<Users className="size-5"/>}>
  <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Çalışma Modu</h2><p className="mt-1 text-xs text-muted-foreground">Timetable ve öğrenci sectioning otoritelerini açıkça ayırır; desteklenmeyen joint optimizer varmış gibi göstermez.</p><div className="mt-3 grid gap-2 md:grid-cols-3">{Object.values(SCHEDULE_SECTIONING_OPERATION_MODES).map(x=><button key={x.id} type="button" onClick={()=>setOperationMode(x.id)} className={`rounded-xl border p-3 text-left ${operationMode===x.id?"border-primary bg-primary/5 ring-1 ring-primary":"hover:bg-muted/30"}`}><b className="text-sm">{x.label}</b><p className="mt-1 text-xs text-muted-foreground">{x.description}</p></button>)}</div><p className="mt-2 text-[11px] text-muted-foreground">{SECTIONING_OPERATION_POLICY}</p><div className="mt-3 flex flex-wrap gap-2">{operation.primaryAction==="OPEN_SOLVER"?<Link to="/schedule-solver"><Button>{operationMode==="TIMETABLE_AND_SECTIONING"?"1 · Programı Üret":"Ders Programı Çözücüsünü Aç"}</Button></Link>:<Button disabled={!editable||busy} onClick={()=>void runRpc("section_students_batch_v2",{p_replace_solver:true})}><Shuffle className="mr-2 size-4"/>Mevcut Programı Sabit Tut · Section Et</Button>}{operationMode==="TIMETABLE_AND_SECTIONING"?<Button disabled={!editable||busy} variant="outline" onClick={()=>void runRpc("section_students_batch_v2",{p_replace_solver:true})}><Shuffle className="mr-2 size-4"/>2 · Öğrencileri Section Et</Button>:null}</div></section>
  <div className="mt-3 grid gap-2 sm:grid-cols-4"><Link to="/schedule"><Button variant="outline" className="w-full">Ders Programı</Button></Link><Link to="/schedule-scenario-comparison"><Button variant="outline" className="w-full">Senaryolar</Button></Link><Button disabled={!editable||busy||operationMode==="TIMETABLE_ONLY"} onClick={()=>void runRpc("section_students_batch_v2",{p_replace_solver:true})}><Shuffle className="mr-2 size-4"/>Tümünü Section Et</Button><Button disabled={!editable||busy||operationMode==="TIMETABLE_ONLY"} variant="outline" onClick={()=>void runRpc("repair_student_sectioning_conflicts_v2")}><RefreshCw className="mr-2 size-4"/>Çakışmaları Onar</Button></div>
  {message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm break-all">{message}</div>:null}
  {health?<div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-7">{[["Talep Öğrencisi",health.students_with_requests],["Aktif Talep",health.active_requests],["Enrollment",health.active_enrollments],["Açık Sorun",health.open_issues],["Çakışma",health.conflict_events],["Kilitli",health.locked_enrollments],["Dolu Section",health.sections_at_capacity]].map(([l,v])=><div key={String(l)} className="rounded-lg border bg-card p-2 text-center"><b className="text-lg">{v}</b><p className="text-[10px] text-muted-foreground">{l}</p></div>)}</div>:null}
  <section className="mt-4 rounded-xl border bg-card p-4"><Label>Öğrenci</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={studentId} onChange={e=>{setStudentId(e.target.value);setRequestId("");}}>{students.map(s=><option key={s.id} value={s.id}>{s.school_number} · {s.full_name}</option>)}</select><Button className="mt-2 w-full" disabled={!editable||!studentId||busy||operationMode==="TIMETABLE_ONLY"} onClick={()=>void runRpc("section_student_v2",{p_student_id:studentId,p_replace_solver:true})}>Bu Öğrenciyi Yeniden Section Et</Button></section>
  <div className="mt-4 grid gap-4 xl:grid-cols-2">
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Ders Talebi</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><div><Label>Ders</Label><select className="h-10 w-full rounded-md border bg-background px-2" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Seç</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label>Tür</Label><select className="h-10 w-full rounded-md border bg-background px-2" value={kind} onChange={e=>setKind(e.target.value)}>{["PRIMARY","ALTERNATIVE","SUBSTITUTE"].map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Scope</Label><select className="h-10 w-full rounded-md border bg-background px-2" value={scope} onChange={e=>setScope(e.target.value)}>{["HOME_CLASS","OFFERING","CROSS_CLASS"].map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Priority</Label><Input type="number" min={1} value={priority} onChange={e=>setPriority(e.target.value)}/></div><div><Label>Alternatif grup</Label><Input value={group} onChange={e=>setGroup(e.target.value)} placeholder="örn. SEC-1"/></div><label className="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" checked={allowOverlap} onChange={e=>setAllowOverlap(e.target.checked)}/>Çakışmaya bilinçli izin ver</label></div><Button className="mt-3 w-full" disabled={!editable||operationMode==="TIMETABLE_ONLY"} onClick={()=>void addRequest()}>Talebi Kaydet</Button></section>
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Serbest Zaman / Zaman Tercihi</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><div><Label>Gün (1–7)</Label><Input type="number" min={1} max={7} value={weekday} onChange={e=>setWeekday(e.target.value)}/></div><div><Label>Ders saatleri</Label><Input value={periods} onChange={e=>setPeriods(e.target.value)} placeholder="2,3,4"/></div><div><Label>Seviye</Label><select className="h-10 w-full rounded-md border bg-background px-2" value={freeMode} onChange={e=>setFreeMode(e.target.value)}>{["HARD","MEDIUM","SOFT","OFF"].map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Ağırlık</Label><Input type="number" min={0} value={freeWeight} onChange={e=>setFreeWeight(e.target.value)}/></div></div><Button className="mt-3 w-full" disabled={!editable||operationMode==="TIMETABLE_ONLY"} onClick={()=>void addFree()}>Zaman Tercihini Kaydet</Button></section>
  </div>
  <div className="mt-4 grid gap-4 xl:grid-cols-2">
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Talep ve Enrollment</h2><div className="mt-3 space-y-2">{selectedRequests.map(r=><button key={r.id} className={`w-full rounded-lg border p-3 text-left text-sm ${requestId===r.id?"ring-2 ring-primary":""}`} onClick={()=>setRequestId(r.id)}><b>{courseNames[r.course_id]??r.course_id}</b><p className="text-xs text-muted-foreground">{r.request_kind} · {r.scope_mode} · priority {r.priority}{r.alternative_group?` · grup ${r.alternative_group}`:""}{r.allow_overlap?" · overlap izinli":""}</p></button>)}{!selectedRequests.length?<p className="text-sm text-muted-foreground">Bu öğrenci için talep yok.</p>:null}</div><div className="mt-3 border-t pt-3 text-xs">Aktif enrollment: {selectedEnrollments.length} · Free-time kuralı: {selectedFree.length} · Sorun: {selectedIssues.length}</div>{selectedIssues.map(i=><p key={i.id} className="mt-1 rounded bg-red-50 p-2 text-xs text-red-800">{i.code}: {i.detail}</p>)}</section>
   <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Section Aday Açıklaması</h2><p className="mt-1 text-xs text-muted-foreground">Bir talep seçin. HARD nedenler kırmızı; MEDIUM/SOFT değerler optimizer sırasıdır.</p><div className="mt-3 space-y-2">{candidates.map(c=>{const rq=reqByAssignment[c.assignment_id],cl=rq?classNames[rq.class_id]:"?";return <div key={c.assignment_id} className={`rounded-lg border p-3 text-sm ${c.feasible?"bg-emerald-50/40":"bg-red-50/40"}`}><div className="flex justify-between gap-2"><b>{cl} · {teacherNames[c.teacher_id]??"Öğretmen"}</b><span>{c.feasible?"UYGUN":"UYGUN DEĞİL"}</span></div><p className="text-xs text-muted-foreground">Kapasite {c.load}/{c.capacity??"?"} · MEDIUM {c.medium_penalty} · SOFT {Number(c.soft_penalty).toFixed(2)}{c.is_current?" · mevcut section":""}</p>{c.hard_reasons?.length?<p className="mt-1 text-xs text-red-700">{c.hard_reasons.join(" · ")}</p>:null}<div className="mt-2 flex gap-2"><Input className="h-8" type="number" min={1} placeholder="Yeni kapasite" value={capacity} onChange={e=>setCapacity(e.target.value)}/><Button size="sm" variant="outline" disabled={!editable||!capacity||operationMode==="TIMETABLE_ONLY"} onClick={()=>void saveCapacity(c.assignment_id)}>Kapasiteyi Kaydet</Button></div></div>})}{requestId&&!candidates.length?<p className="text-sm text-muted-foreground">Bu scope/course için section adayı bulunamadı.</p>:null}</div></section>
  </div>
 </AppShell>;
}