import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BellRing, CheckCircle2, Lightbulb, ShieldCheck, Sparkles, UserMinus, UserPlus } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";

export const Route=createFileRoute("/substitutes")({head:()=>({meta:[{title:"Vekalet Yönetimi — OkulOS"}]}),component:SubstituteManager});
type Profile={user_id:string;full_name:string|null};type Crisis={id:string;teacher_id:string;has_medical_report:boolean;status:string};type Lesson={id:string;crisis_report_id:string;teacher_id:string;period:number;class_name:string;subject:string};type Assignment={id:string;absence_lesson_id:string;substitute_user_id:string;notified_at:string|null};type EngineAssignment={assignment_id:string;absence_lesson_id:string;substitute_user_id:string;substitute_name:string;period:number;class_name:string;subject:string};type Suggestion={absence_lesson_id:string;period:number;class_name:string;subject:string;candidate_user_id:string;candidate_name:string|null;priority:number;weekly_load:number;reason:string};
function istanbulToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function SubstituteManager(){
 const {can,any,loading:permissionLoading}=usePermissions();const mayView=any("substitutes.view","substitutes.manage"),mayManage=can("substitutes.manage");const today=useMemo(istanbulToday,[]);
 const [crises,setCrises]=useState<Crisis[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[dutyTeacherIds,setDutyTeacherIds]=useState<string[]>([]),[profiles,setProfiles]=useState<Record<string,Profile>>({}),[busy,setBusy]=useState(false),[suggestBusy,setSuggestBusy]=useState(false),[error,setError]=useState<string|null>(null),[lastEngineResult,setLastEngineResult]=useState<EngineAssignment[]>([]),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[notifiedCount,setNotifiedCount]=useState(0);
 const loadOverview=useCallback(async()=>{if(permissionLoading||!mayView)return;setError(null);const[crisisRes,lessonRes,assignmentRes,dutyRes]=await Promise.all([supabase.from("crisis_reports").select("id,teacher_id,has_medical_report,status").eq("report_date",today).order("created_at"),supabase.from("absence_lessons").select("id,crisis_report_id,teacher_id,period,class_name,subject").eq("lesson_date",today).order("period"),supabase.from("substitute_assignments").select("id,absence_lesson_id,substitute_user_id,notified_at,absence_lessons!inner(lesson_date)").eq("absence_lessons.lesson_date",today),supabase.from("teacher_duty_assignments").select("teacher_id").eq("duty_date",today)]);if(crisisRes.error||lessonRes.error||assignmentRes.error||dutyRes.error){setError("Bugünkü vekalet verileri yüklenemedi.");return;}const crisisRows=(crisisRes.data??[]) as Crisis[],lessonRows=(lessonRes.data??[]) as Lesson[],assignmentRows=(assignmentRes.data??[]).map((row:Assignment)=>({id:row.id,absence_lesson_id:row.absence_lesson_id,substitute_user_id:row.substitute_user_id,notified_at:row.notified_at})) as Assignment[],dutyIds=(dutyRes.data??[]).map((r:{teacher_id:string})=>r.teacher_id);setCrises(crisisRows);setLessons(lessonRows);setAssignments(assignmentRows);setDutyTeacherIds(dutyIds);const ids=Array.from(new Set([...crisisRows.map(r=>r.teacher_id),...assignmentRows.map(r=>r.substitute_user_id),...dutyIds]));if(ids.length){const{data}=await supabase.from("profiles").select("user_id,full_name").in("user_id",ids);setProfiles(Object.fromEntries(((data??[]) as Profile[]).map(p=>[p.user_id,p])));}},[today,mayView,permissionLoading]);useEffect(()=>{void loadOverview()},[loadOverview]);
 async function calculateSuggestions(){if(!mayView)return;setSuggestBusy(true);setError(null);const{data,error:rpcError}=await supabase.rpc("suggest_substitutes_for_day",{p_date:today});setSuggestBusy(false);if(rpcError){setError("Vekalet önerileri hesaplanamadı.");return;}setSuggestions((data??[]) as Suggestion[]);}
 async function assignSubstitutes(){if(!mayManage)return;setBusy(true);setError(null);setNotifiedCount(0);const{data,error:fnError}=await supabase.functions.invoke("assign-substitutes",{body:{date:today}});setBusy(false);if(fnError||!data?.ok){setError(data?.error==="NO_SUBSTITUTE_AVAILABLE"?"Tüm dersleri dolduracak uygun personel bulunamadı. Sistem boş sınıf bırakmamak için atamayı iptal etti.":"Vekalet ataması tamamlanamadı.");return;}setLastEngineResult((data.assignments??[]) as EngineAssignment[]);setNotifiedCount(Number(data.webPushNotified??0)+Number(data.telegramNotified??0));setSuggestions([]);await loadOverview();}
 const lessonById=Object.fromEntries(lessons.map(l=>[l.id,l]));const assignedLessonIds=new Set(assignments.map(a=>a.absence_lesson_id));const bestSuggestions=suggestions.filter((row,index,all)=>all.findIndex(other=>other.absence_lesson_id===row.absence_lesson_id)===index);
 if(permissionLoading)return <AppShell title="Vekalet Yönetimi"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;
 if(!mayView)return <AppShell title="Vekalet Yönetimi"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Bu kullanıcıya Vekalet görevi atanmadı.</div></AppShell>;
 return <AppShell title="Vekalet Yöneticisi" subtitle={`Bugün ${crises.length} devamsızlık kaydı`} action={<Badge variant="secondary">{mayManage?"Yönetebilir":"Salt okunur"}</Badge>}>
  <div className={`grid gap-2 ${mayManage?"sm:grid-cols-2":""}`}><Button size="lg" variant="outline" className="w-full gap-2" onClick={()=>void calculateSuggestions()} disabled={suggestBusy||busy}><Lightbulb className="size-4"/>{suggestBusy?"Öneriler Hesaplanıyor...":"Uygun Vekilleri Öner"}</Button>{mayManage?<Button size="lg" className="w-full gap-2" onClick={()=>void assignSubstitutes()} disabled={busy||suggestBusy}><Sparkles className="size-4"/>{busy?"Atamalar Yapılıyor...":"Vekilleri Ata (Akıllı Eşleştirme)"}</Button>:null}</div>
  {!mayManage?<div className="mt-3 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs text-blue-950"><ShieldCheck className="size-4"/>Bu hesap vekalet durumunu ve önerileri görebilir; atama yapamaz.</div>:null}
  <div className="mt-3 rounded-xl border bg-card px-4 py-3 text-xs text-muted-foreground">Öncelik: <strong className="text-foreground">nöbetçi öğretmen → nöbetçi müdür yardımcısı → diğer uygun müdür yardımcıları</strong>. Aynı grupta vekalet yükü düşük olan öne çıkar.</div>
  {bestSuggestions.length?<section className="mt-4 rounded-xl border border-primary/20 bg-primary/5 p-4"><h2 className="text-sm font-semibold">Önerilen Vekiller</h2><ul className="mt-2 space-y-2">{bestSuggestions.map(item=><li key={item.absence_lesson_id} className="flex flex-col gap-1 rounded-lg border bg-card px-3 py-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{item.period}. ders · {item.class_name} · {item.subject}</p><p className="text-xs text-muted-foreground">{item.candidate_name??"Personel"} · {item.reason}</p></div><Badge variant="secondary">Bu hafta {item.weekly_load} vekalet</Badge></li>)}</ul></section>:null}
  {notifiedCount>0?<div className="mt-3 flex items-center gap-2 rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary"><BellRing className="size-4"/>{notifiedCount} yeni vekalet bildirimi iletildi.</div>:null}{error?<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>:null}
  <section className="mt-5"><h2 className="mb-2 text-sm font-semibold text-muted-foreground">Devamsız Öğretmenler</h2><ul className="space-y-3">{crises.map(crisis=>{const teacherLessons=lessons.filter(l=>l.crisis_report_id===crisis.id);const fullyAssigned=teacherLessons.length>0&&teacherLessons.every(l=>assignedLessonIds.has(l.id));return <li key={crisis.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-destructive/10 text-destructive"><UserMinus className="size-4"/></div><div><p className="text-sm font-semibold">{profiles[crisis.teacher_id]?.full_name??"Öğretmen"}</p><p className="text-xs text-muted-foreground">{crisis.has_medical_report?"Raporlu":"Devamsızlık bildirimi"}</p></div></div><Badge variant={fullyAssigned?"secondary":"destructive"}>{fullyAssigned?"Atandı":"Bekliyor"}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{teacherLessons.map(l=><span key={l.id} className="rounded-md bg-muted px-2 py-1 text-xs">{l.period}. ders · {l.class_name} · {l.subject}</span>)}</div></li>})}{!crises.length?<li className="rounded-xl border bg-card p-4 text-sm text-muted-foreground">Bugün için devamsızlık bildirimi yok.</li>:null}</ul></section>
  <section className="mt-6"><h2 className="mb-2 text-sm font-semibold text-muted-foreground">Bugünkü Vekalet Atamaları</h2><ul className="divide-y overflow-hidden rounded-xl border bg-card">{assignments.map(a=>{const lesson=lessonById[a.absence_lesson_id];return <li key={a.id} className="flex items-center gap-3 px-4 py-3"><div className="grid size-9 place-items-center rounded-full bg-primary/10 text-primary"><CheckCircle2 className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{profiles[a.substitute_user_id]?.full_name??"Vekil personel"}</p><p className="text-xs text-muted-foreground">{lesson?`${lesson.period}. ders · ${lesson.class_name} · ${lesson.subject}`:"Ders bilgisi"}</p></div><Badge variant={a.notified_at?"secondary":"outline"}>{a.notified_at?"Bildirildi":"Atandı"}</Badge></li>})}{!assignments.length?<li className="px-4 py-3 text-sm text-muted-foreground">Henüz vekalet ataması yapılmadı.</li>:null}</ul></section>
  <section className="mt-6"><h2 className="mb-2 text-sm font-semibold text-muted-foreground">1. Öncelik · Nöbetçi Öğretmenler</h2><ul className="divide-y overflow-hidden rounded-xl border bg-card">{dutyTeacherIds.map(id=><li key={id} className="flex items-center gap-3 px-4 py-3"><div className="grid size-9 place-items-center rounded-full bg-primary/10 text-primary"><UserPlus className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{profiles[id]?.full_name??"Nöbetçi öğretmen"}</p><p className="text-xs text-muted-foreground">Uygun boş derslerde ilk sırada değerlendirilir.</p></div><Badge variant="secondary">Öncelikli</Badge></li>)}{!dutyTeacherIds.length?<li className="px-4 py-3 text-sm text-muted-foreground">Bugün için nöbetçi öğretmen kaydı bulunamadı.</li>:null}</ul></section>{lastEngineResult.length?<p className="mt-3 text-xs text-muted-foreground">Son motor çalıştırması {lastEngineResult.length} dersin vekalet planını doğruladı.</p>:null}
 </AppShell>;
}
