import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BellRing, RefreshCw, RotateCcw, ShieldCheck, Shuffle, UserMinus, Users } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";

export const Route=createFileRoute("/substitutes")({head:()=>({meta:[{title:"Vekalet & Günlük Program — OkulOS"}]}),component:SubstituteManager});
const db=supabase as any;
type Lesson={id:string;teacher_id:string;period:number;class_name:string;subject:string};type Candidate={candidate_user_id:string;candidate_name:string;qualified:boolean;duty:boolean;weekly_load:number;monthly_load:number;hard_reasons:string[];feasible:boolean;rank_score:number;reason:string};type Chain={absence_lesson_id:string;period:number;class_name:string;subject:string;primary_teacher_id:string;primary_teacher_name:string;cover_teacher_id:string;cover_teacher_name:string;total_score:number;operations:unknown};type Health={absence_lessons:number;covered:number;uncovered:number;active_overlays:number;direct_covers:number;chain_operations:number;pending_notifications:number;reverted_groups:number};type Overlay={id:string;operation_group_id:string;operation_kind:string;effective_teacher_id:string|null;effective_period:number|null;effective_class_name:string|null;effective_subject:string|null;notified_at:string|null;created_at:string};
function istanbulToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function SubstituteManager(){const {can,any,loading}=usePermissions(),mayView=any("substitutes.view","substitutes.manage"),mayManage=can("substitutes.manage");const [date,setDate]=useState(istanbulToday()),[lessons,setLessons]=useState<Lesson[]>([]),[selected,setSelected]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]),[chains,setChains]=useState<Chain[]>([]),[health,setHealth]=useState<Health|null>(null),[overlays,setOverlays]=useState<Overlay[]>([]),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(loading||!mayView)return;const [l,h,ch,o]=await Promise.all([db.from("absence_lessons").select("id,teacher_id,period,class_name,subject").eq("lesson_date",date).order("period"),db.rpc("get_substitution_day_health_v4",{p_date:date}),db.rpc("suggest_substitution_chains_v4",{p_date:date,p_limit:30}),db.from("schedule_daily_overlays").select("id,operation_group_id,operation_kind,effective_teacher_id,effective_period,effective_class_name,effective_subject,notified_at,created_at").eq("overlay_date",date).eq("status","ACTIVE").order("created_at",{ascending:false})]);const e=[l,h,ch,o].find((x:any)=>x.error)?.error;if(e){setMessage(`Vekalet verisi yüklenemedi: ${e.message}`);return}setLessons(l.data??[]);setHealth((h.data??[])[0]??null);setChains(ch.data??[]);setOverlays(o.data??[]);if(!selected&&l.data?.length)setSelected(l.data[0].id)},[date,loading,mayView,selected]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!selected){setCandidates([]);return}void db.rpc("get_substitute_candidates_v4",{p_absence_lesson_id:selected}).then((x:any)=>x.error?setMessage(x.error.message):setCandidates(x.data??[]))},[selected]);
 async function run(fn:()=>Promise<any>){setBusy(true);setMessage(null);try{const x=await fn();if(x?.error)throw x.error;setMessage(typeof x?.data==="object"?JSON.stringify(x.data):"İşlem tamamlandı.");await load();if(selected){const c=await db.rpc("get_substitute_candidates_v4",{p_absence_lesson_id:selected});if(!c.error)setCandidates(c.data??[])}}catch(e:any){setMessage(e?.message??"İşlem tamamlanamadı.")}finally{setBusy(false)}}
 async function autoAssign(){await run(async()=>supabase.functions.invoke("assign-substitutes",{body:{date}}))}
 async function applyChain(c:Chain){await run(async()=>db.rpc("apply_substitution_chain_v4",{p_absence_lesson_id:c.absence_lesson_id,p_primary_teacher_id:c.primary_teacher_id,p_cover_teacher_id:c.cover_teacher_id}))}
 async function revert(group:string){await run(async()=>db.rpc("revert_schedule_daily_overlay_v1",{p_operation_group_id:group}))}
 const groups=useMemo(()=>Array.from(new Set(overlays.map(o=>o.operation_group_id))),[overlays]),chosen=lessons.find(l=>l.id===selected);
 if(loading)return <AppShell title="Vekalet Yönetimi"><p>Yetki kontrol ediliyor…</p></AppShell>;if(!mayView)return <AppShell title="Vekalet Yönetimi"><p className="rounded-xl border p-4 text-sm">Bu ekran için yetkiniz yok.</p></AppShell>;
 return <AppShell title="Vekalet & Günlük Program" subtitle="Canonical V4: qualification · availability · fairness · chain · daily overlay · undo" action={<Badge variant="secondary">{mayManage?"Yönetebilir":"Salt okunur"}</Badge>}>
  <div className="flex flex-wrap gap-2"><Link to="/timetable"><Button variant="outline">← Ders Programı</Button></Link><Input className="w-44" type="date" value={date} onChange={e=>{setDate(e.target.value);setSelected("")}}/><Button variant="outline" onClick={()=>void load()} disabled={busy}><RefreshCw className="mr-2 size-4"/>Yenile</Button>{mayManage?<Button onClick={()=>void autoAssign()} disabled={busy}><Shuffle className="mr-2 size-4"/>Direktleri Ata + Bildir</Button>:null}</div>
  {message?<div className="mt-3 rounded-xl border bg-muted/30 p-3 text-sm break-all">{message}</div>:null}
  {health?<div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{Object.entries({"Ders":health.absence_lessons,"Karşılandı":health.covered,"Açık":health.uncovered,"Aktif overlay":health.active_overlays,"Direkt":health.direct_covers,"Chain adımı":health.chain_operations,"Bildirim":health.pending_notifications,"Geri alınan":health.reverted_groups}).map(([k,v])=><div key={k} className="rounded-lg border bg-card p-2 text-center"><b className="text-lg">{v}</b><p className="text-[10px] text-muted-foreground">{k}</p></div>)}</div>:null}
  <div className="mt-4 grid gap-4 xl:grid-cols-[340px_1fr]">
   <section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><UserMinus className="size-4"/>Devamsızlık Dersleri</h2><div className="mt-3 space-y-2">{lessons.map(l=><button key={l.id} onClick={()=>setSelected(l.id)} className={`w-full rounded-lg border p-3 text-left text-sm ${selected===l.id?"ring-2 ring-primary":""}`}><b>{l.period}. ders · {l.class_name}</b><p className="text-xs text-muted-foreground">{l.subject}</p></button>)}{!lessons.length?<p className="text-sm text-muted-foreground">Bu tarihte devamsızlık dersi yok.</p>:null}</div></section>
   <section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><Users className="size-4"/>Aday Açıklaması {chosen?`· ${chosen.period}. ders`:""}</h2><div className="mt-3 space-y-2">{candidates.slice(0,15).map(c=><div key={c.candidate_user_id} className={`rounded-lg border p-3 text-sm ${c.feasible?"bg-emerald-50/40":"bg-red-50/40"}`}><div className="flex flex-wrap items-center justify-between gap-2"><b>{c.candidate_name}</b><Badge variant={c.feasible?"secondary":"destructive"}>{c.feasible?"UYGUN":"HARD ENGEL"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{c.qualified?"Yeterli":"Yeterlilik doğrulanamadı"} · {c.duty?"Nöbetçi":"Nöbetçi değil"} · hafta {c.weekly_load} · ay {c.monthly_load} · skor {c.rank_score}</p>{c.hard_reasons?.length?<p className="mt-1 text-xs text-red-700">{c.hard_reasons.join(" · ")}</p>:<p className="mt-1 text-xs text-emerald-700">{c.reason}</p>}</div>)}{selected&&!candidates.length?<p className="text-sm text-muted-foreground">Aday bulunamadı.</p>:null}</div></section>
  </div>
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Chain Önerileri</h2><p className="mt-1 text-xs text-muted-foreground">A doluysa, A'nın kendi dersini uygun B üstlenir; A devamsız dersi karşılar. İki adım tek transaction ve HARD audit ile uygulanır.</p><div className="mt-3 grid gap-2 lg:grid-cols-2">{chains.map((c,i)=><div key={`${c.absence_lesson_id}-${c.primary_teacher_id}-${c.cover_teacher_id}-${i}`} className="rounded-lg border p-3 text-sm"><b>{c.period}. ders · {c.class_name} · {c.subject}</b><p className="mt-1 text-xs">Devamsız ders → <b>{c.primary_teacher_name}</b></p><p className="text-xs">Onun dersi → <b>{c.cover_teacher_name}</b></p><p className="text-xs text-muted-foreground">Toplam maliyet {c.total_score}</p>{mayManage?<Button className="mt-2" size="sm" variant="outline" disabled={busy} onClick={()=>void applyChain(c)}>Chain'i Uygula</Button>:null}</div>)}{!chains.length?<p className="text-sm text-muted-foreground">Gerekli/uygun chain yok.</p>:null}</div></section>
  <section className="mt-4 rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-4"/>Aktif Günlük Overlay</h2><div className="mt-3 space-y-2">{groups.map(g=>{const rows=overlays.filter(o=>o.operation_group_id===g);return <div key={g} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">{rows.map(r=>r.operation_kind).join(" → ")}</p><p className="text-xs text-muted-foreground">{rows.map(r=>`${r.effective_period??"-"}. ${r.effective_class_name??""} ${r.effective_subject??""}`).join(" · ")}</p></div><div className="flex items-center gap-2">{rows.every(r=>r.notified_at)?<Badge variant="secondary"><BellRing className="mr-1 size-3"/>Bildirildi</Badge>:<Badge variant="outline">Bildirim bekliyor</Badge>}{mayManage?<Button size="sm" variant="outline" disabled={busy} onClick={()=>void revert(g)}><RotateCcw className="mr-1 size-3"/>Geri Al</Button>:null}</div></div></div>})}{!groups.length?<p className="text-sm text-muted-foreground">Aktif günlük müdahale yok.</p>:null}</div></section>
 </AppShell>}
