import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, CheckCircle2, MessageSquare, Power, RefreshCw, ShieldAlert, Wrench, XCircle } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { LoginThemeAdmin } from "@/components/okulos/LoginThemeAdmin";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/super-admin-tenants")({head:()=>({meta:[{title:"Tenant & Sistem Kontrolü — OkulOS"}]}),component:TenantControl});

type Tenant={institution_code:string;school_name:string;approval_status:"pending"|"approved"|"rejected";approval_note:string|null;reviewed_at:string|null;principal_name:string|null;principal_email:string|null;principal_phone:string|null};
type Feature={feature_key:string;parent_key:string|null;label:string;route_prefix:string|null;enabled:boolean;maintenance:boolean;maintenance_message:string|null;sort_order:number};

function TenantControl(){
 const [allowed,setAllowed]=useState<boolean|null>(null),[tenants,setTenants]=useState<Tenant[]>([]),[features,setFeatures]=useState<Feature[]>([]),[maintenance,setMaintenance]=useState(false),[maintenanceMessage,setMaintenanceMessage]=useState("Sistem bakımı yapılmaktadır. En kısa sürede tekrar hizmete açılacaktır."),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[msgTenant,setMsgTenant]=useState(""),[msgTitle,setMsgTitle]=useState(""),[msgBody,setMsgBody]=useState(""),[msgSeverity,setMsgSeverity]=useState("info");
 const load=useCallback(async()=>{const {data:is}=await supabase.rpc("is_super_admin");setAllowed(Boolean(is));if(!is)return;const [t,f,r]=await Promise.all([supabase.rpc("super_admin_list_tenants"),supabase.rpc("get_system_feature_matrix"),supabase.from("system_runtime_settings").select("maintenance,maintenance_message").eq("singleton",true).maybeSingle()]);setTenants((t.data??[]) as Tenant[]);setFeatures(((f.data??[]) as Feature[]).filter(x=>!x.feature_key.startsWith("__")));if(r.data){setMaintenance(Boolean(r.data.maintenance));setMaintenanceMessage(r.data.maintenance_message??maintenanceMessage)}},[maintenanceMessage]);
 useEffect(()=>{void load()},[load]);
 const pending=useMemo(()=>tenants.filter(x=>x.approval_status==="pending"),[tenants]);
 async function review(code:string,decision:"approved"|"rejected"){setBusy(`review-${code}`);setNotice(null);const {error}=await supabase.rpc("super_admin_review_tenant",{p_institution_code:code,p_decision:decision,p_note:notes[code]??null});setBusy(null);setNotice(error?"Tenant kararı kaydedilemedi.":decision==="approved"?"Kurum onaylandı ve müdüre bildirim gönderildi.":"Kurum reddedildi ve müdüre bildirim gönderildi.");if(!error)await load()}
 async function sendMessage(){if(!msgTenant||!msgTitle.trim()||!msgBody.trim())return setNotice("Kurum, başlık ve mesaj zorunludur.");setBusy("message");const {error}=await supabase.rpc("super_admin_send_tenant_message",{p_institution_code:msgTenant,p_title:msgTitle.trim(),p_message:msgBody.trim(),p_severity:msgSeverity});setBusy(null);setNotice(error?"Mesaj gönderilemedi.":"Mesaj kurum müdürüne gönderildi.");if(!error){setMsgTitle("");setMsgBody("")}}
 async function setFeature(feature:Feature,next:{enabled?:boolean;maintenance?:boolean;message?:string}){setBusy(feature.feature_key);const enabled=next.enabled??feature.enabled,maint=next.maintenance??feature.maintenance,message=next.message??feature.maintenance_message;const {error}=await supabase.rpc("super_admin_set_feature",{p_feature_key:feature.feature_key,p_enabled:enabled,p_maintenance:maint,p_message:message??null});setBusy(null);setNotice(error?"Modül durumu değiştirilemedi.":`${feature.label} güncellendi. İlgili müdürlere bildirim gönderildi.`);if(!error)await load()}
 async function toggleSystem(){setBusy("system");const {error}=await supabase.rpc("super_admin_set_system_maintenance",{p_maintenance:!maintenance,p_message:maintenanceMessage});setBusy(null);setNotice(error?"Sistem bakım durumu değiştirilemedi.":!maintenance?"Sistem bakım moduna alındı. Müdürlere bildirim gönderildi.":"Sistem tekrar açıldı. Müdürlere bildirim gönderildi.");if(!error)await load()}
 if(allowed===null)return <AppShell title="Tenant & Sistem Kontrolü"><p className="text-sm text-muted-foreground">Yetki kontrol ediliyor…</p></AppShell>;
 if(!allowed)return <AppShell title="Tenant & Sistem Kontrolü"><div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">Bu ekran yalnız Süper Admin hesabına açıktır.</div></AppShell>;
 return <AppShell title="Tenant & Sistem Kontrolü" subtitle="Kurum onayı · mesajlaşma · modül aç/kapat · bakım modu · giriş temaları" action={<ShieldAlert className="size-5 text-amber-500"/>}>
   <div className="grid gap-2 sm:grid-cols-2"><Link to="/super-admin"><Button variant="outline" className="w-full">Süper Admin Merkezine Dön</Button></Link><Button variant="outline" className="gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></div>
   {notice?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{notice}</div>:null}
   <Tabs defaultValue="approvals" className="mt-5"><TabsList className="grid h-auto w-full grid-cols-2 lg:grid-cols-5"><TabsTrigger value="approvals">Onay / Red {pending.length?`(${pending.length})`:""}</TabsTrigger><TabsTrigger value="messages">Tenant Mesajları</TabsTrigger><TabsTrigger value="features">Modül Kontrolü</TabsTrigger><TabsTrigger value="maintenance">Sistem Bakımı</TabsTrigger><TabsTrigger value="login-themes">Giriş Temaları</TabsTrigger></TabsList>
   <TabsContent value="approvals" className="mt-4 space-y-3">{tenants.map(t=><section key={t.institution_code} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Building2 className="size-4 text-primary"/><h2 className="font-semibold">{t.school_name}</h2></div><p className="mt-1 text-xs text-muted-foreground">Kurum Kodu: {t.institution_code}</p><p className="mt-1 text-xs">Müdür: {t.principal_name??"—"} · {t.principal_email??"—"} · {t.principal_phone??"—"}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs ${t.approval_status==="approved"?"border-emerald-300 bg-emerald-50 text-emerald-700":t.approval_status==="rejected"?"border-destructive/30 bg-destructive/10 text-destructive":"border-amber-300 bg-amber-50 text-amber-800"}`}>{t.approval_status==="approved"?"Onaylı":t.approval_status==="rejected"?"Reddedildi":"Onay Bekliyor"}</span></div><div className="mt-3"><Label>Karar / açıklama notu</Label><Textarea value={notes[t.institution_code]??t.approval_note??""} onChange={e=>setNotes(v=>({...v,[t.institution_code]:e.target.value}))} placeholder="Kurum müdürüne gönderilecek açıklama"/></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Button disabled={busy===`review-${t.institution_code}`} onClick={()=>void review(t.institution_code,"approved")} className="gap-2"><CheckCircle2 className="size-4"/>Onayla</Button><Button disabled={busy===`review-${t.institution_code}`} variant="destructive" onClick={()=>void review(t.institution_code,"rejected")} className="gap-2"><XCircle className="size-4"/>Reddet</Button></div></section>)}{!tenants.length?<div className="rounded-xl border bg-muted/30 p-6 text-center text-sm text-muted-foreground">Kayıtlı tenant yok.</div>:null}</TabsContent>
   <TabsContent value="messages" className="mt-4"><section className="rounded-xl border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><MessageSquare className="size-4"/>Kurum Müdürüne Mesaj Gönder</h2><div className="mt-3 grid gap-3"><div><Label>Kurum</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={msgTenant} onChange={e=>setMsgTenant(e.target.value)}><option value="">Kurum seçin</option>{tenants.map(t=><option key={t.institution_code} value={t.institution_code}>{t.school_name} ({t.institution_code})</option>)}</select></div><div><Label>Başlık</Label><Input value={msgTitle} onChange={e=>setMsgTitle(e.target.value)}/></div><div><Label>Mesaj</Label><Textarea rows={5} value={msgBody} onChange={e=>setMsgBody(e.target.value)}/></div><div><Label>Önem</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={msgSeverity} onChange={e=>setMsgSeverity(e.target.value)}><option value="info">Bilgi</option><option value="warning">Uyarı</option><option value="critical">Kritik</option></select></div><Button disabled={busy==="message"} onClick={()=>void sendMessage()}>Müdüre Gönder</Button></div></section></TabsContent>
   <TabsContent value="features" className="mt-4 space-y-3">{features.map(f=><section key={f.feature_key} className={`rounded-xl border bg-card p-4 ${f.parent_key?"ml-4":""}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{f.label}</h2><p className="text-[11px] text-muted-foreground">{f.feature_key}{f.route_prefix?` · ${f.route_prefix}`:""}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={f.enabled?"default":"outline"} disabled={busy===f.feature_key} onClick={()=>void setFeature(f,{enabled:!f.enabled,maintenance:false})}><Power className="mr-1 size-3.5"/>{f.enabled?"Açık":"Kapalı"}</Button><Button size="sm" variant={f.maintenance?"destructive":"outline"} disabled={busy===f.feature_key} onClick={()=>void setFeature(f,{maintenance:!f.maintenance})}><Wrench className="mr-1 size-3.5"/>{f.maintenance?"Bakımda":"Bakım"}</Button></div></div><div className="mt-3"><Label>Kapalı / bakım mesajı</Label><Input defaultValue={f.maintenance_message??""} placeholder={`${f.label} geçici olarak kullanıma kapalıdır.`} onBlur={e=>{const v=e.currentTarget.value.trim();if(v!==(f.maintenance_message??""))void setFeature(f,{message:v})}}/></div></section>)}</TabsContent>
   <TabsContent value="maintenance" className="mt-4"><section className={`rounded-2xl border p-5 ${maintenance?"border-destructive/30 bg-destructive/10":"bg-card"}`}><div className="flex items-start gap-3"><Wrench className={`mt-0.5 size-5 ${maintenance?"text-destructive":"text-primary"}`}/><div><h2 className="font-semibold">Tüm Sistem Bakım Modu</h2><p className="mt-1 text-xs text-muted-foreground">Süper Admin hariç tüm tenant erişimini durdurur. Müdürlere başlangıç ve tekrar açılış bildirimi gönderilir.</p></div></div><div className="mt-4"><Label>Kullanıcılara gösterilecek mesaj</Label><Textarea rows={4} value={maintenanceMessage} onChange={e=>setMaintenanceMessage(e.target.value)}/></div><Button className="mt-4 w-full gap-2" variant={maintenance?"default":"destructive"} disabled={busy==="system"} onClick={()=>void toggleSystem()}>{maintenance?<><Power className="size-4"/>Sistemi Tekrar Aç</>:<><Wrench className="size-4"/>Sistemi Bakım Moduna Al</>}</Button></section></TabsContent>
   <TabsContent value="login-themes" className="mt-4"><LoginThemeAdmin tenants={tenants}/></TabsContent>
   </Tabs>
 </AppShell>;
}
