import { createFileRoute,Link } from "@tanstack/react-router";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Database,RefreshCw,Save,Search,ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/super-admin-course-pool")({head:()=>({meta:[{title:"Resmî Ders Havuzu — OkulOS"}]}),component:CoursePoolAdmin});
type Row={id:string;effective_academic_year:string;school_type:string;school_subtype:string|null;program_type:string|null;field_name:string|null;branch_name:string|null;grade_level:number;course_id:string;category:string;hour_options:number[];max_selections:number;repeat_across_years:boolean;elective_group_key:string|null;source_file_name:string|null;source_note:string|null;source_decision_no:string|null;source_page:number|null;parser_confidence:number|null;needs_review:boolean;manually_overridden:boolean;course?:{name:string;code:string|null;short_name:string|null}|null};
type Profile={id:string;effective_academic_year:string;school_type:string;school_subtype:string|null;program_type:string|null;field_name:string|null;branch_name:string|null;grade_level:number;required_course_count:number;required_hour_total:number;elective_course_min:number;elective_course_max:number|null;elective_hour_min:number;elective_hour_max:number;total_hour_min:number;total_hour_max:number;total_hour_target:number|null};
const uniq=(xs:(string|null|undefined)[])=>[...new Set(xs.filter(Boolean) as string[])].sort((a,b)=>a.localeCompare(b,"tr"));
function CoursePoolAdmin(){const[allowed,setAllowed]=useState<boolean|null>(null);const[rows,setRows]=useState<Row[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[message,setMessage]=useState<string|null>(null);const[q,setQ]=useState("");const[year,setYear]=useState("");const[school,setSchool]=useState("");const[subtype,setSubtype]=useState("");const[program,setProgram]=useState("");const[grade,setGrade]=useState("");const[selected,setSelected]=useState<Row|null>(null);const[category,setCategory]=useState("");const[hours,setHours]=useState("");const[maxSelections,setMaxSelections]=useState("");const[repeat,setRepeat]=useState(true);const[group,setGroup]=useState("");const[note,setNote]=useState("");const[reason,setReason]=useState("");
const load=useCallback(async()=>{const{data:can}=await supabase.rpc("is_super_admin");setAllowed(Boolean(can));if(!can)return;const[r,p]=await Promise.all([supabase.from("official_course_schedule_effective").select("*,course:course_catalog(name,code,short_name)").order("effective_academic_year",{ascending:false}).order("school_type").order("grade_level"),supabase.from("official_curriculum_profiles").select("*").eq("active",true).order("effective_academic_year",{ascending:false})]);if(r.error||p.error){setMessage("Ders havuzu yüklenemedi.");return;}setRows((r.data??[]) as Row[]);setProfiles((p.data??[]) as Profile[]);},[]);useEffect(()=>{void load()},[load]);
const filtered=useMemo(()=>rows.filter(r=>(!year||r.effective_academic_year===year)&&(!school||r.school_type===school)&&(!subtype||r.school_subtype===subtype)&&(!program||r.program_type===program)&&(!grade||String(r.grade_level)===grade)&&(!q||`${r.course?.name??""} ${r.course?.code??""}`.toLocaleLowerCase("tr").includes(q.toLocaleLowerCase("tr")))),[rows,year,school,subtype,program,grade,q]);
const currentProfile=profiles.find(p=>(!year||p.effective_academic_year===year)&&(!school||p.school_type===school)&&(!subtype||p.school_subtype===subtype)&&(!program||p.program_type===program)&&(!grade||String(p.grade_level)===grade));
function pick(r:Row){setSelected(r);setCategory(r.category);setHours(r.hour_options.join(","));setMaxSelections(String(r.max_selections));setRepeat(r.repeat_across_years);setGroup(r.elective_group_key??"");setNote(r.source_note??"");setReason("");}
async function save(){if(!selected||!reason.trim())return setMessage("Manuel düzeltme nedeni zorunludur.");const parsed=hours.split(/[,;\s]+/).map(Number).filter(n=>Number.isInteger(n)&&n>0&&n<=30);if(!parsed.length)return setMessage("En az bir geçerli ders saati girilmelidir.");const{error}=await supabase.rpc("super_admin_override_official_course_v1",{p_catalog_id:selected.id,p_patch:{category,hourOptions:parsed,maxSelections:Number(maxSelections)||1,repeatAcrossYears:repeat,electiveGroupKey:group||null,sourceNote:note||null},p_reason:reason.trim()});if(error)return setMessage("Düzeltme kaydedilemedi: "+error.message);setMessage("Manuel düzeltme kaydedildi; resmî parse kaydı korunuyor.");setSelected(null);await load();}
if(allowed===null)return <AppShell title="Resmî Ders Havuzu"><p>Yetki kontrol ediliyor…</p></AppShell>;if(!allowed)return <AppShell title="Resmî Ders Havuzu"><p className="text-destructive">Bu ekran yalnız Süper Admin hesabına açıktır.</p></AppShell>;
return <AppShell title="Resmî Ders Havuzu" subtitle="Çizelge parser çıktısı · okul türü/alt tür · sınıf seviyesi · seçim/saat kuralları" action={<Database className="size-5"/>}>
<div className="flex flex-wrap gap-2"><Link to="/super-admin"><Button variant="outline">Süper Admin</Button></Link><Button variant="outline" className="gap-2" onClick={()=>void load()}><RefreshCw className="size-4"/>Yenile</Button></div>
{message?<div className="mt-3 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
<section className="mt-4 rounded-xl border bg-card p-4"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><div><Label>Ara</Label><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Ders adı/kodu"/></div></div><div><Label>Eğitim Yılı</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={year} onChange={e=>setYear(e.target.value)}><option value="">Tümü</option>{uniq(rows.map(r=>r.effective_academic_year)).map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Okul Türü</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={school} onChange={e=>setSchool(e.target.value)}><option value="">Tümü</option>{uniq(rows.map(r=>r.school_type)).map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Alt Tür</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={subtype} onChange={e=>setSubtype(e.target.value)}><option value="">Tümü</option>{uniq(rows.map(r=>r.school_subtype)).map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Program</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={program} onChange={e=>setProgram(e.target.value)}><option value="">Tümü</option>{uniq(rows.map(r=>r.program_type)).map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Sınıf</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Tümü</option>{[...new Set(rows.map(r=>r.grade_level))].sort((a,b)=>a-b).map(x=><option key={x} value={x}>{x}. sınıf</option>)}</select></div></div></section>
{currentProfile?<section className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Zorunlu Ders",currentProfile.required_course_count],["Zorunlu Saat",currentProfile.required_hour_total],["Seçmeli Ders",`${currentProfile.elective_course_min}-${currentProfile.elective_course_max??"∞"}`],["Seçmeli Saat",`${currentProfile.elective_hour_min}-${currentProfile.elective_hour_max}`],["Toplam Min",currentProfile.total_hour_min],["Toplam/Hedef",currentProfile.total_hour_target??currentProfile.total_hour_max]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className="mt-1 text-xl font-semibold">{v}</div></div>)}</section>:null}
<div className="mt-4 overflow-x-auto rounded-xl border bg-card"><table className="min-w-[1100px] w-full text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-left">Ders</th><th className="p-3">Seviye</th><th className="p-3">Tür</th><th className="p-3">Saat</th><th className="p-3">Kaç kez</th><th className="p-3">Tekrar</th><th className="p-3 text-left">Grup</th><th className="p-3">Kaynak</th><th className="p-3">Durum</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="cursor-pointer border-b hover:bg-muted/30" onClick={()=>pick(r)}><td className="p-3"><div className="font-medium">{r.course?.name??r.course_id}</div><div className="text-xs text-muted-foreground">{[r.school_type,r.school_subtype,r.program_type,r.field_name,r.branch_name].filter(Boolean).join(" · ")}</div></td><td className="p-3 text-center">{r.grade_level}</td><td className="p-3 text-center"><Badge variant={r.category==="secmeli"?"secondary":"default"}>{r.category}</Badge></td><td className="p-3 text-center">{r.hour_options.join(" / ")}</td><td className="p-3 text-center">{r.max_selections}</td><td className="p-3 text-center">{r.repeat_across_years?"✓":"—"}</td><td className="p-3">{r.elective_group_key??"—"}</td><td className="p-3 text-center text-xs">{r.source_decision_no??r.source_file_name??"—"}{r.source_page?` · s.${r.source_page}`:""}</td><td className="p-3 text-center">{r.manually_overridden?<Badge>Manuel</Badge>:r.needs_review?<Badge variant="destructive">Kontrol</Badge>:<ShieldCheck className="mx-auto size-4 text-emerald-600"/>}</td></tr>)}</tbody></table></div>
{selected?<section className="mt-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">Manuel Düzeltme — {selected.course?.name}</h2><p className="mt-1 text-xs text-muted-foreground">Parser kaydı değişmez; bu form yalnız etkin override üretir.</p><div className="mt-3 grid gap-3 md:grid-cols-3"><div><Label>Tür</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={category} onChange={e=>setCategory(e.target.value)}><option value="zorunlu">Zorunlu</option><option value="secmeli">Seçmeli</option><option value="meslek">Meslek/Alan-Dal</option><option value="program">Program</option><option value="rehberlik">Rehberlik</option></select></div><div><Label>Haftalık Saat Seçenekleri</Label><Input value={hours} onChange={e=>setHours(e.target.value)} placeholder="1,2,4"/></div><div><Label>Azami Alınma Sayısı</Label><Input inputMode="numeric" value={maxSelections} onChange={e=>setMaxSelections(e.target.value.replace(/\D/g,""))}/></div><div><Label>Seçmeli Grup</Label><Input value={group} onChange={e=>setGroup(e.target.value)}/></div><div><Label>Yıllar Arası Tekrar</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={repeat?"1":"0"} onChange={e=>setRepeat(e.target.value==="1")}><option value="1">İzinli</option><option value="0">Tekrar edemez</option></select></div><div><Label>Düzeltme Nedeni *</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Çizelge/açıklama kontrolü"/></div><div className="md:col-span-3"><Label>Kaynak Açıklama / Not</Label><textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={note} onChange={e=>setNote(e.target.value)}/></div></div><div className="mt-3 flex gap-2"><Button className="gap-2" onClick={()=>void save()}><Save className="size-4"/>Düzeltmeyi Kaydet</Button><Button variant="outline" onClick={()=>setSelected(null)}>Vazgeç</Button></div></section>:null}
</AppShell>}
