import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { BookOpenCheck, FileSpreadsheet, UploadCloud } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { parseOfficialWeeklyCourseSchedule, type OfficialCourseScheduleParseResult } from "@/lib/course-schedule-import";
import { supabase } from "@/lib/supabase";

export const Route=createFileRoute("/super-admin/course-schedules")({head:()=>({meta:[{title:"Resmî Haftalık Ders Çizelgeleri — OkulOS"}]}),component:OfficialCourseSchedules});
const schoolTypes=["İlkokul","Ortaokul","İmam Hatip Ortaokulu","Anadolu Lisesi","Anadolu İmam Hatip Lisesi","Mesleki ve Teknik Anadolu Lisesi","Mesleki Eğitim Merkezi","Lise"];
function OfficialCourseSchedules(){const [file,setFile]=useState<File|null>(null),[parsed,setParsed]=useState<OfficialCourseScheduleParseResult|null>(null),[year,setYear]=useState(""),[schoolType,setSchoolType]=useState(""),[programType,setProgramType]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 async function parse(){if(!file)return;setBusy(true);setMessage(null);try{const r=await parseOfficialWeeklyCourseSchedule(file);setParsed(r);setYear(r.academicYear??"");setSchoolType(r.schoolType??"");setProgramType(r.programType??"");setMessage(`${r.rows.length} sınıf-ders kuralı çıkarıldı.`)}catch(e){setMessage(e instanceof Error?e.message:"Çizelge okunamadı.")}finally{setBusy(false)}}
 async function save(){if(!file||!parsed?.rows.length||!year||!schoolType)return;setBusy(true);const {data,error}=await supabase.rpc("super_admin_import_official_course_schedule_v1",{p_source_file_name:file.name,p_effective_academic_year:year,p_school_type:schoolType,p_program_type:programType,p_rows:parsed.rows});setBusy(false);if(error)return setMessage(`Katalog kaydedilemedi: ${error.message}`);setMessage(`Resmî katalog kaydedildi ve ilgili kurum/sınıf havuzları senkronlandı. ${JSON.stringify(data)}`)}
 return <AppShell title="Resmî Haftalık Ders Çizelgeleri" subtitle="MEB çizelgesi → parse → sistem kataloğu → sınıfa uygun ders havuzu">
  <div className="mb-4 flex gap-2"><Link to="/super-admin" className="rounded-md border px-3 py-2 text-sm">← Süper Admin</Link><Link to="/management" className="rounded-md border px-3 py-2 text-sm">Yönetim</Link></div>{message?<div className="mb-4 rounded-xl border bg-muted/30 p-3 text-sm">{message}</div>:null}
  <section className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2"><UploadCloud className="size-5 text-primary"/><h2 className="font-semibold">1 · Çizelgeyi Yükle</h2></div><p className="mt-1 text-xs text-muted-foreground">PDF, XLS veya XLSX. Dersler, sınıf sütunları, zorunlu/seçmeli bölüm ve geçerli saat seçenekleri otomatik çıkarılır.</p><Input className="mt-3" type="file" accept=".pdf,.xls,.xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setParsed(null)}}/><Button className="mt-3" disabled={!file||busy} onClick={()=>void parse()}><FileSpreadsheet className="mr-2 size-4"/>{busy?"Okunuyor...":"Parse Et"}</Button></section>
  {parsed?<><section className="mt-4 rounded-2xl border bg-card p-4"><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-primary"/><h2 className="font-semibold">2 · Kaynağı Doğrula</h2></div><div className="mt-3 grid gap-3 md:grid-cols-3"><div><Label>Eğitim-Öğretim Yılı</Label><Input className="mt-1" value={year} onChange={e=>setYear(e.target.value)} placeholder="2026-2027"/></div><div><Label>Okul Türü</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={schoolType} onChange={e=>setSchoolType(e.target.value)}><option value="">Seçiniz</option>{schoolTypes.map(x=><option key={x}>{x}</option>)}</select></div><div><Label>Program (varsa)</Label><Input className="mt-1" value={programType} onChange={e=>setProgramType(e.target.value)} placeholder="Boş = okul türünün genel çizelgesi"/></div></div>{parsed.warnings.length?<div className="mt-3 space-y-1">{parsed.warnings.map(w=><p key={w} className="text-xs text-amber-700">⚠ {w}</p>)}</div>:null}</section>
   <section className="mt-4 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">3 · Önizleme</h2><Badge>{parsed.rows.length} kural</Badge></div><div className="mt-3 max-h-[440px] overflow-auto rounded-xl border"><table className="w-full min-w-[760px] text-sm"><thead><tr className="sticky top-0 bg-muted"><th className="p-2 text-left">Sınıf</th><th className="p-2 text-left">Ders</th><th className="p-2 text-left">Tür</th><th className="p-2 text-left">Saat</th><th className="p-2 text-left">Grup</th><th className="p-2 text-left">Tekrar</th></tr></thead><tbody>{parsed.rows.map((r,i)=><tr key={`${r.gradeLevel}-${r.courseName}-${i}`} className="border-t"><td className="p-2">{r.gradeLevel}</td><td className="p-2 font-medium">{r.courseName}</td><td className="p-2">{r.category}</td><td className="p-2">{r.hourOptions.join(" / ")}</td><td className="p-2">{r.electiveGroupKey??"—"}</td><td className="p-2">{r.repeatAcrossYears?"Alabilir":"Tekrar alınamaz"}</td></tr>)}</tbody></table></div><Button className="mt-4 w-full" disabled={busy||!year||!schoolType||!parsed.rows.length} onClick={()=>void save()}>{busy?"Kaydediliyor...":"Resmî Kataloğa Kaydet ve Havuzları Güncelle"}</Button></section></>:null}
 </AppShell>}
