import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CalendarRange, ChevronRight, Columns3, GripVertical, History, Moon, PanelLeftClose, Play, RotateCcw, Save, Settings2, ShieldCheck, Sparkles, Sun, Table2, WandSparkles } from "lucide-react";
import { AppShell } from "@/components/okulos/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { usePermissions } from "@/lib/permissions";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/timetable")({head:()=>({meta:[{title:"Ders Programı Çalışma Alanı — OkulOS"}]}),component:TimetableWorkspace});
type AcademicYear={id:string;code:string;title:string;starts_on:string;ends_on:string;active:boolean};type RuleMode={rule_code:string;label:string;mode:string;config:unknown};type MenuItem={id:string;label:string;to?:string;parentId:string|null;kind:"group"|"item"};
const DEFAULT_MENU:MenuItem[]=[
 {id:"prep",label:"Veri Hazırlığı",parentId:null,kind:"group"},{id:"year",label:"Eğitim-Öğretim Yılı",to:"/academic-years",parentId:"prep",kind:"item"},{id:"classes",label:"Sınıflar",to:"/classes",parentId:"prep",kind:"item"},{id:"teachers",label:"Öğretmenler",to:"/personnel-admin",parentId:"prep",kind:"item"},{id:"curriculum",label:"Ders Havuzu & Atamalar",to:"/curriculum",parentId:"prep",kind:"item"},{id:"rooms",label:"Derslikler",to:"/classrooms",parentId:"prep",kind:"item"},
 {id:"rulesGroup",label:"Kurallar & Optimizasyon",parentId:null,kind:"group"},{id:"rules",label:"Global Kurallar",to:"/schedule-rules",parentId:"rulesGroup",kind:"item"},{id:"scoped",label:"Sınıf / Öğretmen Override",to:"/schedule-scoped-rules",parentId:"rulesGroup",kind:"item"},{id:"optimization",label:"Gelişmiş Optimizasyon",to:"/schedule-optimization",parentId:"rulesGroup",kind:"item"},
 {id:"program",label:"Üretim & Düzenleme",parentId:null,kind:"group"},{id:"weekly",label:"Haftalık Program",to:"/schedule",parentId:"program",kind:"item"},{id:"prepcheck",label:"Hazırlık Kontrolü",to:"/schedule-preparation",parentId:"program",kind:"item"},{id:"solver",label:"Program Üret",to:"/schedule-solver",parentId:"program",kind:"item"},{id:"compare",label:"Senaryo Karşılaştır",to:"/schedule-scenario-comparison",parentId:"program",kind:"item"},{id:"roomAssign",label:"Derslik Atama",to:"/room-assignment",parentId:"program",kind:"item"},
 {id:"control",label:"Kontrol & Yayın",parentId:null,kind:"group"},{id:"validation",label:"Final Kontrol",to:"/schedule-validation",parentId:"control",kind:"item"},{id:"history",label:"Geçmiş / Geri Al",to:"/schedule-history",parentId:"control",kind:"item"},{id:"archive",label:"Yayın & Arşiv",to:"/schedule-archive",parentId:"control",kind:"item"},
];
const workspaceTabs=[["Program","/schedule"],["Ders Havuzu","/curriculum"],["Kurallar","/schedule-rules"],["Override","/schedule-scoped-rules"],["Optimizasyon","/schedule-optimization"],["Senaryolar","/schedule-scenario-comparison"],["Kontrol","/schedule-validation"],["Yayın","/schedule-archive"]] as const;
function applyTheme(theme:"light"|"dark"){document.documentElement.classList.toggle("dark",theme==="dark");window.localStorage.setItem("okulos-theme",theme)}
function TimetableWorkspace(){
 const {can}=usePermissions();const [years,setYears]=useState<AcademicYear[]>([]),[rules,setRules]=useState<RuleMode[]>([]),[message,setMessage]=useState<string|null>(null),[customizing,setCustomizing]=useState(false),[dragged,setDragged]=useState<string|null>(null);
 const [menu,setMenu]=useState<MenuItem[]>(()=>{try{const raw=window.localStorage.getItem("okulos-timetable-menu-v2");return raw?JSON.parse(raw) as MenuItem[]:DEFAULT_MENU}catch{return DEFAULT_MENU}});
 const [theme,setTheme]=useState<"light"|"dark">(()=>{if(typeof window==="undefined")return"light";return window.localStorage.getItem("okulos-theme")==="dark"?"dark":"light"});
 useEffect(()=>{applyTheme(theme)},[theme]);useEffect(()=>{window.localStorage.setItem("okulos-timetable-menu-v2",JSON.stringify(menu))},[menu]);
 useEffect(()=>{void(async()=>{const [y,r]=await Promise.all([supabase.from("academic_years").select("id,code,title,starts_on,ends_on,active").order("starts_on",{ascending:false}),supabase.from("schedule_rule_modes").select("rule_code,label,mode,config").in("rule_code",["physical_education_edge_slots","music_edge_slots"])]);if(y.error||r.error){setMessage(`Ders programı çalışma alanı tam yüklenemedi: ${(y.error??r.error)?.message}`);return;}setYears((y.data??[]) as AcademicYear[]);setRules((r.data??[]) as RuleMode[])})()},[]);
 const activeYear=useMemo(()=>years.find(y=>y.active)??null,[years]),groups=useMemo(()=>menu.filter(i=>i.kind==="group"&&i.parentId===null),[menu]);const ruleEnabled=(code:string)=>rules.find(r=>r.rule_code===code)?.mode!=="off";
 async function toggleEdgeRule(code:string,enabled:boolean){if(!can("schedule.rules"))return;const {error}=await supabase.from("schedule_rule_modes").update({mode:enabled?"hard":"off",updated_at:new Date().toISOString()}).eq("rule_code",code);if(error){setMessage(`Özel yerleşim kuralı kaydedilemedi: ${error.message}`);return;}setRules(current=>current.map(r=>r.rule_code===code?{...r,mode:enabled?"hard":"off"}:r));setMessage(`${code==="physical_education_edge_slots"?"Beden Eğitimi":"Müzik"} kuralı ${enabled?"HARD":"KAPALI"} olarak kaydedildi.`)}
 function dropOn(targetId:string){if(!dragged||dragged===targetId)return;setMenu(current=>{const source=current.find(i=>i.id===dragged),target=current.find(i=>i.id===targetId);if(!source||!target)return current;const next=current.filter(i=>i.id!==dragged),moved={...source,parentId:target.kind==="group"?target.id:target.parentId};const idx=next.findIndex(i=>i.id===targetId);next.splice(Math.max(0,idx+(target.kind==="group"?1:0)),0,moved);return next});setDragged(null)}
 function resetMenu(){setMenu(DEFAULT_MENU);window.localStorage.removeItem("okulos-timetable-menu-v2")}
 return <AppShell title="Ders Programı" subtitle="Veri → kural → optimizasyon → üretim → karşılaştırma → doğrulama → yayın">
  {message?<div className="mb-4 rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>:null}
  <section className="rounded-2xl border bg-card p-3 sm:p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><Link to="/academic-years" className="inline-flex h-9 items-center gap-2 rounded-lg border bg-background px-3 text-sm font-semibold"><CalendarRange className="size-4"/>{activeYear?.code??"Yıl seçilmedi"}<ChevronRight className="size-3.5"/></Link>{activeYear?<span className="rounded-full border border-emerald-300 bg-emerald-50 px-2 py-1 text-[11px] font-semibold text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">Aktif çalışma yılı</span>:null}</div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun className="mr-1 size-4"/>:<Moon className="mr-1 size-4"/>}{theme==="dark"?"Açık Tema":"Koyu Tema"}</Button><Button variant="outline" size="sm" onClick={()=>setCustomizing(v=>!v)}><Settings2 className="mr-1 size-4"/>Menüyü Düzenle</Button></div></div><div className="mt-3 flex gap-1 overflow-x-auto pb-1">{workspaceTabs.map(([label,to])=><Link key={to} to={to as never} className="whitespace-nowrap rounded-lg border bg-background px-3 py-2 text-xs font-medium text-muted-foreground hover:border-primary/40 hover:text-foreground">{label}</Link>)}</div></section>
  <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{can("schedule.generate")?<Link to="/schedule-solver" className="inline-flex h-10 shrink-0 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><WandSparkles className="mr-2 size-4"/>Program Üret</Link>:null}<Link to="/schedule-scenario-comparison" className="inline-flex h-10 shrink-0 items-center rounded-lg border bg-card px-4 text-sm font-medium"><Columns3 className="mr-2 size-4"/>Senaryoları Karşılaştır</Link>{can("schedule.rules")?<Link to="/schedule-optimization" className="inline-flex h-10 shrink-0 items-center rounded-lg border bg-card px-4 text-sm font-medium"><Sparkles className="mr-2 size-4"/>Optimizasyon</Link>:null}{can("schedule.publish")?<Link to="/schedule-archive" className="inline-flex h-10 shrink-0 items-center rounded-lg border bg-card px-4 text-sm font-medium"><Save className="mr-2 size-4"/>Yayınla</Link>:null}{can("schedule.edit")?<Link to="/schedule" className="inline-flex h-10 shrink-0 items-center rounded-lg border bg-card px-4 text-sm font-medium"><Table2 className="mr-2 size-4"/>Ders Ekle / Taşı</Link>:null}{can("schedule.restore")?<Link to="/schedule-history" className="inline-flex h-10 shrink-0 items-center rounded-lg border bg-card px-4 text-sm font-medium"><History className="mr-2 size-4"/>Geri Al</Link>:null}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)_300px]">
   <aside className="rounded-2xl border bg-card p-3"><div className="mb-3 flex items-center justify-between"><div><p className="text-sm font-semibold">Çalışma Akışı</p><p className="text-[11px] text-muted-foreground">İlgili işler aynı grupta</p></div><PanelLeftClose className="size-4 text-muted-foreground"/></div><div className="space-y-4">{groups.map(group=><div key={group.id}><p className="mb-1.5 px-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{group.label}</p><div className="space-y-1">{menu.filter(item=>item.parentId===group.id).map(item=>item.to?<Link key={item.id} to={item.to as never} className="flex items-center justify-between rounded-lg px-2.5 py-2 text-sm hover:bg-muted"><span>{item.label}</span><ChevronRight className="size-3.5 text-muted-foreground"/></Link>:null)}</div></div>)}</div></aside>
   <main className="min-w-0 rounded-2xl border bg-card p-4">{!activeYear?<div className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100"><b>Program üretilemez:</b> Önce eğitim-öğretim yılı açıp aktif yapın. <Link to="/academic-years" className="ml-1 underline">Yıl yönetimi</Link></div>:null}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Link to="/schedule-preparation" className="rounded-xl border p-3 hover:border-primary/40"><ShieldCheck className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">1 · Hazırlık</p><p className="mt-1 text-xs text-muted-foreground">Eksik öğretmen, ders, blok, sync ve derslik sorunlarını üretimden önce yakala.</p></Link><Link to="/schedule-scoped-rules" className="rounded-xl border p-3 hover:border-primary/40"><Settings2 className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">2 · Etkin Kurallar</p><p className="mt-1 text-xs text-muted-foreground">Global → sınıf-ders → öğretmen ataması mirasını yönet.</p></Link><Link to="/schedule-optimization" className="rounded-xl border p-3 hover:border-primary/40"><Sparkles className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">3 · Optimizasyon</p><p className="mt-1 text-xs text-muted-foreground">HARD/SOFT/KAPALI, pedagoji, nöbet ve atölye profilleri.</p></Link><Link to="/schedule-solver" className="rounded-xl border p-3 hover:border-primary/40"><WandSparkles className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">4 · Akıllı Üretim</p><p className="mt-1 text-xs text-muted-foreground">Çoklu senaryo üret, repair ve hard-safe local search uygula.</p></Link><Link to="/schedule-scenario-comparison" className="rounded-xl border p-3 hover:border-primary/40"><Columns3 className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">5 · Karşılaştır</p><p className="mt-1 text-xs text-muted-foreground">Öğretmen, öğrenci, nöbet, atölye ve hard hata ölçüleriyle yan yana değerlendir.</p></Link><Link to="/schedule-validation" className="rounded-xl border p-3 hover:border-primary/40"><Play className="size-5 text-primary"/><p className="mt-2 text-sm font-semibold">6 · Doğrula / Yayınla</p><p className="mt-1 text-xs text-muted-foreground">Final validator geçmeden yayın akışına izin verme.</p></Link></div><div className="mt-4 rounded-xl border border-dashed bg-muted/15 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Haftalık program</h2><p className="mt-1 text-sm text-muted-foreground">Manuel taşıma/düzenleme ve mevcut program tablosu bu çalışma alanının merkezinde kalır.</p></div><Link to="/schedule" className="inline-flex h-10 shrink-0 items-center justify-center rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground">Programı Aç<ChevronRight className="ml-1 size-4"/></Link></div></div></main>
   <aside className="space-y-4"><section className="rounded-2xl border bg-card p-4"><h2 className="font-semibold">Özel HARD Yerleşimler</h2><p className="mt-1 text-xs text-muted-foreground">Default açık. Ayrı ayrı kapatılabilir.</p>{[["physical_education_edge_slots","Beden Eğitimi"],["music_edge_slots","Müzik"]].map(([code,label])=><label key={code} className="mt-3 flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" className="mt-1" disabled={!can("schedule.rules")} checked={ruleEnabled(code)} onChange={e=>void toggleEdgeRule(code,e.target.checked)}/><span><b className="text-sm">{label}</b><span className="mt-1 block text-xs text-muted-foreground">Pazartesi 1. ders + Cuma son ders zorunlu</span></span></label>)}</section>{customizing?<section className="rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Menü Düzeni</h2><Button variant="ghost" size="sm" onClick={resetMenu}><RotateCcw className="mr-1 size-4"/>Varsayılan</Button></div><p className="mt-1 text-xs text-muted-foreground">Öğeyi sürükleyip bir grubun veya başka öğenin üstüne bırakın. Grup üstüne bırakınca alt menü olur.</p><div className="mt-3 space-y-2">{menu.map(item=><div key={item.id} draggable onDragStart={()=>setDragged(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>dropOn(item.id)} className={cn("flex items-center gap-2 rounded-lg border p-2 text-xs",dragged===item.id&&"opacity-50",item.kind==="group"&&"font-semibold")}><GripVertical className="size-4 text-muted-foreground"/><span className="flex-1">{item.label}</span><span className="text-[10px] text-muted-foreground">{item.parentId?"alt":"ana"}</span></div>)}</div></section>:null}</aside>
  </div>
 </AppShell>
}
