import {describe,expect,test} from "bun:test";
import {IncrementalScheduleScore} from "../src/lib/schedule-local-incremental-score";
import {solveIncrementalSchedule} from "../src/lib/schedule-local-solver-incremental-core";
import type {LocalLockedRow,LocalProblem} from "../src/lib/schedule-local-solver-time-core";

const migration=await Bun.file("supabase/migrations/20260827012000_schedule_performance_indexes_v1.sql").text();
const worker=await Bun.file("src/workers/schedule-local-solver-worker.ts").text();
const pct=(a:number[],q:number)=>a.slice().sort((x,y)=>x-y)[Math.min(a.length-1,Math.ceil(a.length*q)-1)]??0;
function large(seed:number):LocalProblem{const assignments=Array.from({length:240},(_,i)=>({assignment_id:`a${i}`,teacher_id:`t${i%120}`,class_id:`c${i%120}`,course_id:`q${i%24}`,assigned_hours:1,week_pattern:i%9===0?"ODD" as const:i%9===1?"EVEN" as const:"ALL" as const,schedule_session_id:null,allowed_periods:null}));return{days:[1,2,3,4,5],periods:10,assignments,locked:[],unavailable:[],teacherConstraints:Array.from({length:120},(_,i)=>({teacher_id:`t${i}`,max_daily_hours:6,max_consecutive_hours:4})),courseRules:Array.from({length:24},(_,i)=>({course_id:`q${i}`,block_pattern:[1],max_per_day:2,prohibited_days:null,prohibited_periods:null})),planningRelations:[],studentConflictWeights:[],seed,enableLns:false}}
function fullStudent(rows:LocalLockedRow[],p:LocalProblem){const m=new Map<string,number>();for(const w of p.studentConflictWeights??[]){const n=Number(w.severity_weight)||Number(w.student_weight)||0;m.set(`${w.left_assignment_id}|${w.right_assignment_id}`,n);m.set(`${w.right_assignment_id}|${w.left_assignment_id}`,n)}let n=0;for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i]!,b=rows[j]!;if(a.weekday===b.weekday&&a.period===b.period)n+=m.get(`${a.assignment_id}|${b.assignment_id}`)??0}return n}

describe("schedule large-school performance closure",()=>{
 test("production worker uses adaptive elite wrapper over the canonical incremental solver",()=>{expect(worker).toContain("solveAdaptiveEliteSchedule");expect(worker).toContain("schedule-adaptive-elite-solver")});
 test("performance migration is compact, idempotent and non-destructive",()=>{expect((migration.match(/CREATE INDEX IF NOT EXISTS/g)??[]).length).toBe(4);expect(migration).toContain("idx_teacher_schedule_perf_active_slot");expect(migration).toContain("idx_scenario_rows_perf_slot");expect(migration).toContain("idx_student_schedule_enrollments_assignment");expect(migration).not.toMatch(/DROP\s+(TABLE|COLUMN)|DELETE\s+FROM|TRUNCATE/i)});
 test("incremental student score stays exact through add/remove",()=>{const p:LocalProblem={...large(1),assignments:[{assignment_id:"a",teacher_id:"ta",class_id:"ca",course_id:"qa",assigned_hours:1},{assignment_id:"b",teacher_id:"tb",class_id:"cb",course_id:"qb",assigned_hours:1}],studentConflictWeights:[{left_assignment_id:"a",right_assignment_id:"b",student_weight:7,severity_weight:7}],teacherConstraints:[],courseRules:[]};const rows:LocalLockedRow[]=[];const s=new IncrementalScheduleScore(p.assignments,rows,[],p.studentConflictWeights);const a:LocalLockedRow={assignment_id:"a",teacher_id:"ta",class_id:"ca",weekday:1,period:1,locked:false},b:LocalLockedRow={assignment_id:"b",teacher_id:"tb",class_id:"cb",weekday:1,period:1,locked:false};rows.push(a);s.add(a);rows.push(b);s.add(b);expect(s.score(0,0).medium).toBe(fullStudent(rows,p));s.remove(b);rows.splice(rows.indexOf(b),1);expect(s.score(0,0).medium).toBe(fullStudent(rows,p))});
 test("index memory memberships stay linear",()=>{const p=large(3),r=solveIncrementalSchedule(p),s=new IncrementalScheduleScore(p.assignments,r.rows,[],[]),st=s.stats();expect(st.memberships).toBeLessThanOrEqual(r.rows.length*5);expect(st.adjacency).toBe(0)});
 test("same seed is deterministic on 120-class instance",()=>{const a=solveIncrementalSchedule(large(77)),b=solveIncrementalSchedule(large(77));expect(a).toEqual(b);expect(a.complete).toBe(true)});
 test("120-class benchmark meets feasibility, p50/p95 and heap gates",()=>{const ms:number[]=[];let ok=0;const before=process.memoryUsage().heapUsed;for(const seed of[11,23,37,41,59]){const t=performance.now(),r=solveIncrementalSchedule(large(seed));ms.push(performance.now()-t);if(r.complete&&r.score.hard===0)ok++}const heap=Math.max(0,process.memoryUsage().heapUsed-before),p50=pct(ms,.5),p95=pct(ms,.95);console.log("SCHEDULE_PERF_BENCH",JSON.stringify({classes:120,assignments:240,runs:5,p50_ms:Math.round(p50),p95_ms:Math.round(p95),heap_delta_mb:Math.round(heap/1048576),feasible:ok}));expect(ok).toBe(5);expect(p50).toBeLessThan(5000);expect(p95).toBeLessThan(8000);expect(heap).toBeLessThan(256*1024*1024)},30000);
});
