import {describe,expect,test} from "bun:test";
import {candidateRelevantPlanningRelations,compilePlanningRelationDispatch,COMPILED_RELATION_DISPATCH_POLICY,evaluateCandidateRelationsCompiled} from "../src/lib/schedule-compiled-relation-dispatch";
import {solveLocalSchedule,type LocalProblem} from "../src/lib/schedule-local-solver-core";
import {evaluateCandidateRelations,type PlanningActivity,type PlanningRelation} from "../src/lib/schedule-planning-relations";
const candidate:PlanningActivity={activity_key:"a1",assignment_id:"A",course_id:"M",teacher_id:"T1",class_id:"C1",weekday:2,start:3,end:3,tags:["LAB"]};
const placed:PlanningActivity[]=[{activity_key:"b1",assignment_id:"B",course_id:"F",teacher_id:"T2",class_id:"C2",weekday:2,start:3,end:3},{activity_key:"c1",assignment_id:"C",course_id:"M",teacher_id:"T3",class_id:"C3",weekday:1,start:1,end:1}];
const relations:PlanningRelation[]=[
{id:"1",relation_type:"DIFFERENT_TIME",mode:"HARD",weight:1,left_selector:{assignment_id:"A"},right_selector:{assignment_id:"B"},parameters:{}},
{id:"2",relation_type:"PREFERRED_DAYS",mode:"SOFT",weight:4,left_selector:{course_id:"M"},right_selector:{},parameters:{days:[1]}},
{id:"3",relation_type:"SAME_DAY",mode:"MEDIUM",weight:2,left_selector:{assignment_id:"X"},right_selector:{assignment_id:"B"},parameters:{}},
{id:"4",relation_type:"PREFERRED_PERIODS",mode:"SOFT",weight:3,left_selector:{activity_tag:"LAB"},right_selector:{},parameters:{periods:[1,2]}},
];
function solverProblem(planningRelations:PlanningRelation[]):LocalProblem{return{days:[1,2,3,4,5],periods:8,seed:41,enableLns:false,assignments:[{assignment_id:"A",teacher_id:"T1",class_id:"C1",course_id:"M",assigned_hours:2},{assignment_id:"B",teacher_id:"T2",class_id:"C2",course_id:"F",assigned_hours:2}],locked:[],unavailable:[],teacherConstraints:[],courseRules:[{course_id:"M",block_pattern:[1,1],max_per_day:1,prohibited_days:null,prohibited_periods:null},{course_id:"F",block_pattern:[1,1],max_per_day:1,prohibited_days:null,prohibited_periods:null}],planningRelations}}
describe("compiled planning relation dispatch",()=>{
 test("compiled dispatch preserves exact canonical candidate score",()=>{const c=compilePlanningRelationDispatch(relations);expect(evaluateCandidateRelationsCompiled(candidate,placed,c)).toEqual(evaluateCandidateRelations(candidate,placed,relations))});
 test("drops relations that cannot involve the candidate while allowing harmless false positives",()=>{const picked=candidateRelevantPlanningRelations(candidate,compilePlanningRelationDispatch(relations));expect(picked.map(x=>x.id)).toContain("1");expect(picked.map(x=>x.id)).toContain("2");expect(picked.map(x=>x.id)).toContain("4");expect(picked.map(x=>x.id)).not.toContain("3")});
 test("canonical evaluator remains final scoring authority",()=>expect(COMPILED_RELATION_DISPATCH_POLICY).toContain("evaluateCandidateRelations nihai relation scorer"));
 test("large irrelevant relation set is substantially reduced",()=>{const many:PlanningRelation[]=[];for(let i=0;i<1000;i++)many.push({id:`x${i}`,relation_type:"SAME_DAY",mode:"SOFT",weight:1,left_selector:{assignment_id:`Z${i}`},right_selector:{assignment_id:`Q${i}`},parameters:{}});many.push(relations[0]!);const picked=candidateRelevantPlanningRelations(candidate,compilePlanningRelationDispatch(many));expect(picked.length).toBeLessThan(10);expect(evaluateCandidateRelationsCompiled(candidate,placed,compilePlanningRelationDispatch(many))).toEqual(evaluateCandidateRelations(candidate,placed,many))});
 test("production solver is invariant to a large set of irrelevant indexed relations",()=>{const relevant:PlanningRelation={id:"preferred-a",relation_type:"PREFERRED_PERIODS",mode:"SOFT",weight:2,left_selector:{assignment_id:"A"},right_selector:{},parameters:{periods:[1,2,3]}};const irrelevant=Array.from({length:1000},(_,i):PlanningRelation=>({id:`irrelevant-${i}`,relation_type:"SAME_DAY",mode:"SOFT",weight:1,left_selector:{assignment_id:`Z${i}`},right_selector:{assignment_id:`Q${i}`},parameters:{}}));const baseline=solveLocalSchedule(solverProblem([relevant]));const compiled=solveLocalSchedule(solverProblem([...irrelevant,relevant]));expect(compiled.score).toEqual(baseline.score);expect(compiled.failed).toBe(baseline.failed);expect(compiled.complete).toBe(baseline.complete);expect(compiled.rows).toEqual(baseline.rows)});
});
