import{describe,expect,test}from"bun:test";
import{assertLargeMtalGate,auditLargeMtal,makeLargeMtalProblem,runLargeMtalCorpus}from"../tools/schedule_mtal_large_corpus";
import{solveIncrementalSchedule}from"../src/lib/schedule-local-solver-incremental-core";
const manifest=await Bun.file("benchmarks/mtal-large/manifest.json").json();
describe("large MTAL structural corpus",()=>{
 test("is explicitly synthetic, privacy-safe and structurally large",()=>{expect(manifest.provenance).toContain("Synthetic");expect(manifest.provenance).toContain("no real");expect(manifest.profiles).toHaveLength(3);expect(Math.min(...manifest.profiles.map((p:any)=>p.classes*p.assignments_per_class))).toBeGreaterThanOrEqual(120)});
 test("generator covers blocks, workshop eligibility and shifted allowed periods",()=>{const workshop=makeLargeMtalProblem(manifest.profiles[1],17),shifted=makeLargeMtalProblem(manifest.profiles[2],17);expect(workshop.assignments.some(a=>a.assigned_hours===2)).toBe(true);expect(Object.values(workshop.roomRequirements??{}).some((r:any)=>r.required_room_type==="WORKSHOP")).toBe(true);expect(shifted.assignments.every(a=>a.allowed_periods?.length===5)).toBe(true)});
 test("one seed per profile is feasible and independently HARD-audited",()=>{for(const profile of manifest.profiles){const p=makeLargeMtalProblem(profile,1709),r=solveIncrementalSchedule(p),audit=auditLargeMtal(p,r.rows);expect(r.complete,profile.id).toBe(true);expect(audit,profile.id).toEqual({hard:0,unplaced:0,atomic:true,room_eligible:true,violations:[]})}},30000);
 test("smoke report is deterministic and gate semantics cannot weaken",async()=>{const r=await runLargeMtalCorpus(1);expect(r.results.every(x=>x.deterministic_replay)).toBe(true);expect(()=>assertLargeMtalGate(r,1,false)).not.toThrow();expect(()=>assertLargeMtalGate({...r,results:[{...r.results[0]!,hard_max:1},...r.results.slice(1)]},1)).toThrow("MTAL_CORPUS_GATE_FAILED");expect(()=>assertLargeMtalGate({...r,results:[{...r.results[0]!,budget_pass:false},...r.results.slice(1)]},1)).toThrow("MTAL_CORPUS_GATE_FAILED")},60000);
});
