import{describe,expect,it}from"bun:test";import{solveIncrementalSchedule,type JointLocalProblem}from"../src/lib/schedule-local-solver-incremental-core";
const base=(patch:Partial<JointLocalProblem>={}):JointLocalProblem=>({days:[1],periods:4,assignments:[],locked:[],unavailable:[],teacherConstraints:[],courseRules:[],seed:11,enableLns:false,...patch});
const a=(id:string,teacher:string,klass:string,hours=1)=>({assignment_id:id,teacher_id:teacher,class_id:klass,course_id:`q-${id}`,assigned_hours:hours,allowed_periods:[1,2,3,4]});
describe("joint time room solver",()=>{
 it("treats classroom as part of the placement tuple and prevents room collisions",()=>{const p=base({periods:1,assignments:[a("a","t1","c1"),a("b","t2","c2")],rooms:[{classroom_id:"R1"},{classroom_id:"R2"}]});const r=solveIncrementalSchedule(p);expect(r.complete).toBe(true);expect(r.rows).toHaveLength(2);expect(new Set(r.rows.map(x=>x.classroom_id)).size).toBe(2);expect(r.rows.every(x=>x.weekday===1&&x.period===1)).toBe(true)});
 it("enforces room type, feature and capacity requirements while selecting time",()=>{const p=base({assignments:[a("lab","t1","c1")],rooms:[{classroom_id:"SMALL",capacity:15,room_type:"LAB",features:["SINK"]},{classroom_id:"THEORY",capacity:40,room_type:"THEORY",features:["PROJECTOR"]},{classroom_id:"LAB40",capacity:40,room_type:"LAB",features:["SINK","PROJECTOR"]}],roomRequirements:{lab:{required_room_type:"LAB",required_features:["PROJECTOR"],minimum_capacity:30}}});const r=solveIncrementalSchedule(p);expect(r.complete).toBe(true);expect(new Set(r.rows.map(x=>x.classroom_id))).toEqual(new Set(["LAB40"]))});
 it("keeps one room for every period of an atomic multi-period block",()=>{const x=a("block","t1","c1",2);const p=base({assignments:[x],courseRules:[{course_id:x.course_id,block_pattern:[2],max_per_day:2,prohibited_days:null,prohibited_periods:null}],rooms:[{classroom_id:"R1"},{classroom_id:"R2"}]});const r=solveIncrementalSchedule(p);expect(r.complete).toBe(true);expect(r.rows).toHaveLength(2);expect(new Set(r.rows.map(y=>y.classroom_id)).size).toBe(1);expect(Math.abs(r.rows[0]!.period-r.rows[1]!.period)).toBe(1)});
 it("preserves locked room assignments",()=>{const x=a("locked","t1","c1");const p=base({assignments:[x],locked:[{assignment_id:x.assignment_id,teacher_id:x.teacher_id,class_id:x.class_id,weekday:1,period:2,classroom_id:"R2",locked:true}],rooms:[{classroom_id:"R1"},{classroom_id:"R2"}]});const r=solveIncrementalSchedule(p);expect(r.complete).toBe(true);expect(r.rows[0]!.classroom_id).toBe("R2");expect(r.rows[0]!.locked).toBe(true)});
 it("honors preferred rooms as a soft placement cost",()=>{const x=a("pref","t1","c1");const p=base({assignments:[x],rooms:[{classroom_id:"R1"},{classroom_id:"R2"}],roomRequirements:{pref:{preferred_classroom_ids:["R2"]}}});const r=solveIncrementalSchedule(p);expect(r.complete).toBe(true);expect(r.rows[0]!.classroom_id).toBe("R2")});
});