import {describe,expect,test} from "bun:test";
import {JOINT_SECTIONING_POLICY,solveJointScheduleSectioning,type JointSectioningProblem} from "../src/lib/schedule-joint-sectioning-solver";

const timetable={days:[1],periods:2,assignments:[{assignment_id:"math-a",teacher_id:"tm1",class_id:"c1",course_id:"math",assigned_hours:1},{assignment_id:"math-b",teacher_id:"tm2",class_id:"c2",course_id:"math",assigned_hours:1},{assignment_id:"art",teacher_id:"ta",class_id:"c3",course_id:"art",assigned_hours:1}],locked:[{assignment_id:"math-a",teacher_id:"tm1",class_id:"c1",weekday:1,period:1,locked:true},{assignment_id:"math-b",teacher_id:"tm2",class_id:"c2",weekday:1,period:2,locked:true}],unavailable:[],teacherConstraints:[],courseRules:[{course_id:"math",max_per_day:1,prohibited_days:null,prohibited_periods:null},{course_id:"art",max_per_day:1,prohibited_days:null,prohibited_periods:[2]}],seed:7,enableLns:true} satisfies JointSectioningProblem["timetable"];
const request=(student_id:string,candidates:JointSectioningProblem["requests"][number]["candidates"])=>({request_id:`r-${student_id}`,student_id,course_id:"math",request_kind:"PRIMARY" as const,priority:1,alternative_group:null,allow_overlap:false,candidates});

describe("joint timetable and student sectioning optimizer",()=>{
 test("changes the section and timetable inside one lexicographic search",()=>{const p:JointSectioningProblem={timetable,existing_locked:[{request_id:"locked-art",student_id:"s1",assignment_id:"art",locked:true,allow_overlap:false}],requests:[request("s1",[{assignment_id:"math-a",capacity:1,current_load:0,medium_penalty:0,soft_penalty:0,current:true},{assignment_id:"math-b",capacity:2,current_load:0,medium_penalty:0,soft_penalty:2}])],beam_width:8};const x=solveJointScheduleSectioning(p);expect(x.complete).toBe(true);expect(x.score.hard).toBe(0);expect(x.enrollments.find(e=>e.request_id==="r-s1")?.assignment_id).toBe("math-b");expect(x.timetable.rows.find(r=>r.assignment_id==="art")?.period).toBe(1);expect(x.score.changes).toBe(1)});
 test("capacity is fail-closed and a mandatory request cannot be called complete",()=>{const p:JointSectioningProblem={timetable,existing_locked:[],requests:[request("s2",[{assignment_id:"math-a",capacity:1,current_load:1,medium_penalty:0,soft_penalty:0}])]};const x=solveJointScheduleSectioning(p);expect(x.complete).toBe(false);expect(x.score.unassigned_primary).toBe(1);expect(x.enrollments.some(e=>e.student_id==="s2")).toBe(false)});
 test("locked enrollments participate in HARD student time conflicts",()=>{const p:JointSectioningProblem={timetable:{...timetable,periods:1,locked:[...timetable.locked.filter(r=>r.assignment_id==="math-a"),{assignment_id:"art",teacher_id:"ta",class_id:"c3",weekday:1,period:1,locked:true}]},existing_locked:[{request_id:"la",student_id:"s3",assignment_id:"art",locked:true,allow_overlap:false}],requests:[request("s3",[{assignment_id:"math-a",capacity:2,current_load:0,medium_penalty:0,soft_penalty:0}])]};const x=solveJointScheduleSectioning(p);expect(x.complete).toBe(false);expect(x.score.hard).toBeGreaterThan(0)});
 test("HARD free-time follows the selected enrollment into timetable search",()=>{const p:JointSectioningProblem={timetable:{...timetable,locked:timetable.locked.filter(r=>r.assignment_id!=="math-b")},existing_locked:[],requests:[request("s4",[{assignment_id:"math-b",capacity:2,current_load:0,medium_penalty:0,soft_penalty:0}])],hard_free_time:[{student_id:"s4",weekday:1,periods:[1]}]};const x=solveJointScheduleSectioning(p);expect(x.complete).toBe(true);expect(x.timetable.rows.find(r=>r.assignment_id==="math-b")?.period).toBe(2)});
 test("policy explicitly keeps student collision HARD",()=>expect(JOINT_SECTIONING_POLICY).toContain("HARD"));
});
