import {describe,expect,test} from "bun:test";
import {candidateDistance,solveAdaptiveEliteSchedule} from "../src/lib/schedule-adaptive-elite-solver";
import {solveIncrementalSchedule} from "../src/lib/schedule-local-solver-incremental-core";
import type {LocalProblem,LocalScore} from "../src/lib/schedule-local-solver-time-core";

const lex=(a:LocalScore,b:LocalScore)=>a.hard-b.hard||a.medium-b.medium||a.soft-b.soft;
function problem(seed=17,n=36):LocalProblem{const assignments=Array.from({length:n},(_,i)=>({assignment_id:`a${i}`,teacher_id:`t${i%18}`,class_id:`c${i%18}`,course_id:`q${i%9}`,assigned_hours:1,week_pattern:i%11===0?"ODD" as const:i%11===1?"EVEN" as const:"ALL" as const}));return{days:[1,2,3,4,5],periods:8,assignments,locked:[],unavailable:[],teacherConstraints:Array.from({length:18},(_,i)=>({teacher_id:`t${i}`,max_daily_hours:5,max_consecutive_hours:4})),courseRules:Array.from({length:9},(_,i)=>({course_id:`q${i}`,block_pattern:[1],max_per_day:2,prohibited_days:null,prohibited_periods:null})),planningRelations:[],studentConflictWeights:[],seed,enableLns:true,lnsIterations:8}}

describe("adaptive elite schedule solver",()=>{
 test("candidate distance detects diversity",()=>{const p=problem(1,8),a=solveIncrementalSchedule({...p,strategy:"TABU"}),b=solveIncrementalSchedule({...p,seed:2,strategy:"VND"});expect(candidateDistance(a,a)).toBe(0);expect(candidateDistance(a,b)).toBeGreaterThanOrEqual(0);expect(candidateDistance(a,b)).toBeLessThanOrEqual(1)});
 test("same seed reproduces candidate and adaptive telemetry",()=>{const p=problem(77),a=solveAdaptiveEliteSchedule(p,{rounds:8,eliteSize:4,stagnationRounds:3,pathRelinkEvery:3}),b=solveAdaptiveEliteSchedule(p,{rounds:8,eliteSize:4,stagnationRounds:3,pathRelinkEvery:3});expect(a.rows).toEqual(b.rows);expect(a.score).toEqual(b.score);expect(a.adaptive).toEqual(b.adaptive)});
 test("all operators receive telemetry and elite remains feasible",()=>{const r=solveAdaptiveEliteSchedule(problem(91),{rounds:10,eliteSize:4,pathRelinkEvery:3});expect(r.complete).toBe(true);expect(r.score.hard).toBe(0);expect(r.adaptive.operators).toHaveLength(5);expect(r.adaptive.operators.every(x=>x.pulls>0)).toBe(true);expect(r.adaptive.elite_size).toBeGreaterThanOrEqual(1);expect(r.adaptive.diversity).toBeGreaterThanOrEqual(0);expect(r.adaptive.path_relinks).toBeGreaterThan(0)});
 test("adaptive best is not worse than its deterministic first operator baseline",()=>{const p=problem(123),baseline=solveIncrementalSchedule({...p,strategy:"LATE_ACCEPTANCE"}),adaptive=solveAdaptiveEliteSchedule(p,{rounds:10,eliteSize:4,pathRelinkEvery:3});expect(lex(adaptive.score,baseline.score)).toBeLessThanOrEqual(0)});
 test("adaptive benchmark stays bounded",()=>{const p=problem(321,60),t=performance.now(),r=solveAdaptiveEliteSchedule(p,{rounds:8,eliteSize:4,stagnationRounds:3,pathRelinkEvery:4}),ms=performance.now()-t;console.log("SCHEDULE_ADAPTIVE_BENCH",JSON.stringify({assignments:p.assignments.length,ms:Math.round(ms),score:r.score,elite:r.adaptive.elite_size,diversity:Number(r.adaptive.diversity.toFixed(3)),restarts:r.adaptive.restarts,path_relinks:r.adaptive.path_relinks}));expect(r.complete).toBe(true);expect(r.score.hard).toBe(0);expect(ms).toBeLessThan(12000)},20000);
});
