import {describe,expect,test} from "bun:test";
import {compareSupervisionScores,solveSupervisionSchedule,validateSupervisionResult,type SupervisionProblem} from "../src/lib/schedule-supervision-solver";

const base=():SupervisionProblem=>({seed:17,positions:[{id:"yard-1",label:"Bahçe",weekday:1,period:3,required_count:2},{id:"floor-1",label:"1. Kat",weekday:1,period:4,required_count:1}],teachers:[{id:"T1",min_load:1,max_load:2,preferred_position_ids:["yard-1"]},{id:"T2",min_load:1,max_load:2},{id:"T3",min_load:1,max_load:2}],occupied_slots:[{teacher_id:"T1",weekday:1,period:4,source:"LESSON"}]});

describe("schedule supervision solver",()=>{
 test("covers all positions without assigning a teacher during a lesson",()=>{const p=base(),r=solveSupervisionSchedule(p);expect(r.complete).toBe(true);expect(r.score.hard).toBe(0);expect(r.score.unplaced).toBe(0);expect(r.assignments).toHaveLength(3);expect(r.assignments.some(x=>x.teacher_id==="T1"&&x.weekday===1&&x.period===4)).toBe(false);expect(validateSupervisionResult(p,r)).toEqual(r.score)});
 test("one teacher cannot supervise two positions in the same slot",()=>{const p:SupervisionProblem={seed:1,positions:[{id:"a",label:"A",weekday:1,period:2,required_count:1},{id:"b",label:"B",weekday:1,period:2,required_count:1}],teachers:[{id:"T1",max_load:5}],occupied_slots:[]},r=solveSupervisionSchedule(p);expect(r.assignments).toHaveLength(1);expect(r.score.unplaced).toBe(1);expect(r.complete).toBe(false)});
 test("respects position and teacher eligibility as HARD",()=>{const p:SupervisionProblem={seed:2,positions:[{id:"gate",label:"Kapı",weekday:2,period:1,required_count:1,eligible_teacher_ids:["T2"]}],teachers:[{id:"T1"},{id:"T2",eligible_position_ids:["gate"]}],occupied_slots:[]},r=solveSupervisionSchedule(p);expect(r.assignments).toEqual([{position_id:"gate",teacher_id:"T2",weekday:2,period:1}]);expect(validateSupervisionResult(p,r).hard).toBe(0)});
 test("max load is a hard cap during construction",()=>{const p:SupervisionProblem={seed:3,positions:[{id:"a",label:"A",weekday:1,period:1,required_count:1},{id:"b",label:"B",weekday:1,period:2,required_count:1}],teachers:[{id:"T1",max_load:1}],occupied_slots:[]},r=solveSupervisionSchedule(p);expect(r.teacher_loads.T1).toBe(1);expect(r.score.unplaced).toBe(1)});
 test("under-minimum and load spread are MEDIUM by default",()=>{const p:SupervisionProblem={seed:4,positions:[{id:"a",label:"A",weekday:1,period:1,required_count:1}],teachers:[{id:"T1",min_load:1},{id:"T2",min_load:1}],occupied_slots:[]},r=solveSupervisionSchedule(p);expect(r.score.hard).toBe(0);expect(r.score.medium).toBeGreaterThan(0);expect(r.score.soft).toBe(0)});
 test("preference mismatch is SOFT and never overrides lesson occupancy",()=>{const p:SupervisionProblem={seed:5,positions:[{id:"a",label:"A",weekday:3,period:2,required_count:1}],teachers:[{id:"T1",preferred_position_ids:["a"]},{id:"T2",preferred_position_ids:["other"]}],occupied_slots:[{teacher_id:"T1",weekday:3,period:2,source:"LESSON"}]},r=solveSupervisionSchedule(p);expect(r.assignments[0]?.teacher_id).toBe("T2");expect(r.score.hard).toBe(0);expect(r.score.soft).toBe(1)});
 test("HARD fairness cannot silently relax",()=>{const p:SupervisionProblem={seed:6,fairness_mode:"HARD",positions:[{id:"a",label:"A",weekday:1,period:1,required_count:1}],teachers:[{id:"T1",min_load:1},{id:"T2",min_load:1}],occupied_slots:[]},r=solveSupervisionSchedule(p);expect(r.score.hard).toBeGreaterThan(0);expect(r.complete).toBe(false)});
 test("validator detects forged occupied-slot and duplicate-slot assignments",()=>{const p=base(),r=solveSupervisionSchedule(p),forged={...r,assignments:[{position_id:"floor-1",teacher_id:"T1",weekday:1,period:4},{position_id:"floor-1",teacher_id:"T1",weekday:1,period:4}],unplaced:[]};expect(validateSupervisionResult(p,forged).hard).toBeGreaterThan(0)});
 test("same seed is deterministic",()=>{const p=base();expect(solveSupervisionSchedule(p)).toEqual(solveSupervisionSchedule(p))});
 test("score comparator is strict HARD then unplaced then MEDIUM then SOFT",()=>{expect(compareSupervisionScores({hard:0,unplaced:1,medium:0,soft:0},{hard:1,unplaced:0,medium:0,soft:0})).toBeLessThan(0);expect(compareSupervisionScores({hard:0,unplaced:0,medium:9,soft:0},{hard:0,unplaced:1,medium:0,soft:0})).toBeLessThan(0);expect(compareSupervisionScores({hard:0,unplaced:0,medium:0,soft:100},{hard:0,unplaced:0,medium:1,soft:0})).toBeLessThan(0)});
});
