import{describe,expect,test}from"bun:test";
import{assertLargeMesemGate,makeLargeMesemProblem,runLargeMesemCorpus}from"../tools/schedule_mesem_large_corpus";
import{auditLargeMtal}from"../tools/schedule_mtal_large_corpus";
import{solveIncrementalSchedule}from"../src/lib/schedule-local-solver-incremental-core";
const manifest=await Bun.file("benchmarks/mesem-large/manifest.json").json();
describe("large MESEM structural corpus",()=>{
 test("is synthetic, structurally large and keeps units under one institution identity",()=>{expect(manifest.provenance).toContain("Synthetic");expect(manifest.provenance).toContain("no real");expect(manifest.profiles).toHaveLength(3);expect(Math.min(...manifest.profiles.map((p:any)=>p.classes*p.assignments_per_class))).toBeGreaterThanOrEqual(120)});
 test("models distinct Birim IDs and enterprise-day time exclusions",()=>{for(const profile of manifest.profiles){const p=makeLargeMesemProblem(profile,17);expect(new Set(p.assignments.map(a=>a.schedule_session_id)).size).toBeGreaterThan(1);expect(p.assignments.every(a=>a.class_id?.startsWith(`${manifest.institution_code}:unit-`))).toBe(true);expect(p.courseRules.every(r=>JSON.stringify(r.prohibited_days)===JSON.stringify(profile.enterprise_weekdays))).toBe(true)}});
 test("one seed per profile is feasible with HARD and workplace/room audit clean",()=>{for(const profile of manifest.profiles){const p=makeLargeMesemProblem(profile,2089),r=solveIncrementalSchedule(p),a=auditLargeMtal(p,r.rows);expect(r.complete,profile.id).toBe(true);expect(a,profile.id).toEqual({hard:0,unplaced:0,atomic:true,room_eligible:true,violations:[]})}},30000);
 test("smoke report is deterministic and gate semantics cannot weaken",async()=>{const r=await runLargeMesemCorpus(1);expect(r.results.every(x=>x.enterprise_day_exclusion&&x.unit_identity&&x.deterministic_replay)).toBe(true);expect(()=>assertLargeMesemGate(r,1,false)).not.toThrow();expect(()=>assertLargeMesemGate({...r,results:[{...r.results[0]!,enterprise_day_exclusion:false},...r.results.slice(1)]},1)).toThrow("MESEM_CORPUS_GATE_FAILED");expect(()=>assertLargeMesemGate({...r,results:[{...r.results[0]!,budget_pass:false},...r.results.slice(1)]},1)).toThrow("MESEM_CORPUS_GATE_FAILED")},60000);
});
