import {describe,expect,test} from "bun:test";
import {compareScheduleObjectiveVectors,localCandidateObjective,SCHEDULE_OBJECTIVE_CONTRACT,SCHEDULE_OBJECTIVE_ORDER,type ScheduleObjectiveVector} from "../src/lib/schedule-objective-vector";
import {solveLocalSchedule,type LocalProblem} from "../src/lib/schedule-local-solver-time-core";

const fixture=async()=>{const text=await Bun.file("benchmarks/schedule-score-parity/objective-vectors.tsv").text();return text.trim().split("\n").slice(1).map(line=>{const[id,hard,unplaced,medium,soft,rank]=line.split("\t");return{id,vector:{hard:+hard!,unplaced:+unplaced!,medium:+medium!,soft:+soft!} satisfies ScheduleObjectiveVector,rank:+rank!}})};

describe("canonical Cloud/Web/native objective vector",()=>{
 test("Web orders the shared fixture HARD -> unplaced -> MEDIUM -> SOFT",async()=>{const rows=await fixture();rows.sort((a,b)=>compareScheduleObjectiveVectors(a.vector,b.vector));expect(rows.map(x=>x.rank)).toEqual([1,2,3,4,5,6]);expect(SCHEDULE_OBJECTIVE_CONTRACT).toBe("okulos.schedule-objective-vector.v1");expect(SCHEDULE_OBJECTIVE_ORDER).toEqual(["hard","unplaced","medium","soft"])});
 test("unplaced is no longer folded into Web HARD",()=>{const p:LocalProblem={days:[1],periods:1,seed:7,locked:[],unavailable:[],teacherConstraints:[],courseRules:[],assignments:[{assignment_id:"a",teacher_id:"t",class_id:"c",course_id:"x",assigned_hours:1},{assignment_id:"b",teacher_id:"t",class_id:"c",course_id:"y",assigned_hours:1}]};const result=solveLocalSchedule(p),vector=localCandidateObjective(result);expect(result.failed).toBe(1);expect(vector).toEqual({hard:0,unplaced:1,medium:0,soft:0})});
 test("DB contract exposes the same order and fail-closed comparator",async()=>{const sql=await Bun.file("supabase/migrations/20260902000500_schedule_objective_vector_parity.sql").text();expect(sql).toContain('"order":["hard","unplaced","medium","soft"]');expect(sql).toContain("foreach k in array array['hard','unplaced','medium','soft']");expect(sql).toContain("coalesce(jsonb_typeof(p_left->k),'null')<>'number'");expect(sql).toContain("grant execute on function public.compare_schedule_objective_vectors_v1(jsonb,jsonb) to authenticated")});
 test("native Rust executes the same shared fixture",async()=>{const bin=`/tmp/okulos-objective-${process.pid}`;const build=Bun.spawn(["rustc","--edition=2021","--test","desktop/src-tauri/src/objective.rs","-o",bin],{stdout:"pipe",stderr:"pipe"});const [code,stderr]=await Promise.all([build.exited,new Response(build.stderr).text()]);expect(code,stderr).toBe(0);const run=Bun.spawn([bin],{stdout:"pipe",stderr:"pipe"});const [runCode,out,runErr]=await Promise.all([run.exited,new Response(run.stdout).text(),new Response(run.stderr).text()]);expect(runCode,`${out}\n${runErr}`).toBe(0)});
});
