import{describe,expect,test}from"bun:test";
import{solveJointScheduleSectioning,type JointSectioningProblem}from"../src/lib/schedule-joint-sectioning-solver";
type Clock={period:number;start:number;end:number};
const clocks:Record<"ODD"|"EVEN",Clock[]>={ODD:[{period:1,start:480,end:520},{period:2,start:530,end:570},{period:3,start:580,end:620}],EVEN:[{period:1,start:540,end:575},{period:2,start:585,end:620},{period:3,start:630,end:665}]};
function physicalOverlaps(rows:{weekday:number;period:number}[],week:Clock[]){let n=0;for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){if(rows[i]!.weekday!==rows[j]!.weekday)continue;const a=week.find(x=>x.period===rows[i]!.period),b=week.find(x=>x.period===rows[j]!.period);if(a&&b&&a.start<b.end&&b.start<a.end)n++}return n}
function problem(seed:number,periods=3):JointSectioningProblem{return{timetable:{days:[1],periods,assignments:[
 {assignment_id:"alpha",teacher_id:"teacher-a",additional_teacher_ids:["shared-co"],class_id:"class-a",course_id:"course-a",assigned_hours:1,schedule_session_id:"morning"},
 {assignment_id:"beta",teacher_id:"teacher-b",class_id:"class-b",course_id:"course-b",assigned_hours:1,schedule_session_id:"morning"},
 {assignment_id:"gamma",teacher_id:"shared-co",class_id:"class-c",course_id:"course-c",assigned_hours:1,schedule_session_id:"morning"},
 ],locked:[],unavailable:[],teacherConstraints:[],courseRules:[],rooms:[{classroom_id:"a-primary"},{classroom_id:"b-primary"},{classroom_id:"shared-lab"},{classroom_id:"gamma-room"}],roomBundles:[{room_bundle_id:"bundle-a",primary_classroom_id:"a-primary",classroom_ids:["a-primary","shared-lab"]},{room_bundle_id:"bundle-b",primary_classroom_id:"b-primary",classroom_ids:["b-primary","shared-lab"]}],roomBundleOptions:{alpha:["bundle-a"],beta:["bundle-b"]},roomRequirements:{gamma:{required_classroom_ids:["gamma-room"]}},planningRelations:[],studentConflictWeights:[],seed,enableLns:true},existing_locked:[{request_id:"locked-beta",student_id:"student-1",assignment_id:"beta",locked:true,allow_overlap:false}],requests:[{request_id:"request-gamma",student_id:"student-1",course_id:"course-c",request_kind:"PRIMARY",priority:1,alternative_group:null,allow_overlap:false,candidates:[{assignment_id:"gamma",capacity:2,current_load:0,medium_penalty:0,soft_penalty:0}]}],beam_width:12,max_timetable_evaluations:12}}
const bellMigration=await Bun.file("supabase/migrations/20260901000400_multi_week_bell_schedule.sql").text();

describe("combined release edge case: sectioning + composite room + co-teacher + multi-week clock",()=>{
 test("all four dimensions remain feasible and deterministic across seeds",()=>{for(let seed=1;seed<=20;seed++){const p=problem(seed),a=solveJointScheduleSectioning(p),b=solveJointScheduleSectioning(p);expect(a).toEqual(b);expect(a.complete).toBe(true);expect(a.score.hard).toBe(0);expect(a.score.unassigned_primary).toBe(0);expect(a.enrollments.some(x=>x.request_id==="request-gamma"&&x.assignment_id==="gamma")).toBe(true);const byId=Object.fromEntries(a.timetable.rows.map(x=>[x.assignment_id,x]));expect(new Set([byId.alpha.period,byId.beta.period,byId.gamma.period]).size).toBe(3);expect(byId.alpha.room_bundle_id).toBe("bundle-a");expect(byId.beta.room_bundle_id).toBe("bundle-b");expect(byId.alpha.classroom_ids).toContain("shared-lab");expect(byId.beta.classroom_ids).toContain("shared-lab");expect(physicalOverlaps(a.timetable.rows,clocks.ODD)).toBe(0);expect(physicalOverlaps(a.timetable.rows,clocks.EVEN)).toBe(0)}});
 test("two canonical periods cannot hide the three-way HARD resource cycle",()=>{const x=solveJointScheduleSectioning(problem(77,2));expect(x.complete).toBe(false);expect(x.score.hard+x.score.unassigned_primary).toBeGreaterThan(0)});
 test("a bad date-scoped physical clock remains a release failure after canonical placement",()=>{const x=solveJointScheduleSectioning(problem(91));expect(x.complete).toBe(true);const bad:Clock[]=[{period:1,start:540,end:600},{period:2,start:580,end:620},{period:3,start:630,end:665}];expect(physicalOverlaps(x.timetable.rows,bad)).toBeGreaterThan(0);expect(bellMigration).toContain("schedule_slots_overlap_on_date_v1");expect(bellMigration).toContain("get_schedule_period_clock_for_date_v1")});
});
