import{describe,expect,test}from"bun:test";
import{assertRoomBuildingExtremeGate,auditRoomBuildingExtreme,makeRoomBuildingExtremeProblem,runRoomBuildingExtremeCorpus}from"../tools/schedule_room_building_extreme_corpus";
import{solveIncrementalSchedule}from"../src/lib/schedule-local-solver-incremental-core";
const manifest=await Bun.file("benchmarks/room-building-extreme/manifest.json").json();
describe("room/building extreme structural corpus",()=>{
 test("is synthetic, large and multi-building",()=>{expect(manifest.provenance).toContain("Synthetic");expect(manifest.provenance).toContain("no real");expect(manifest.profiles).toHaveLength(3);expect(Math.min(...manifest.profiles.map((p:any)=>p.classes*p.assignments_per_class))).toBeGreaterThanOrEqual(120);expect(manifest.profiles.every((p:any)=>p.buildings>=3)).toBe(true)});
 test("covers tight room domains, features, forbidden transfers and atomic specialists",()=>{const tight=makeRoomBuildingExtremeProblem(manifest.profiles[0],17),transfer=makeRoomBuildingExtremeProblem(manifest.profiles[1],17),special=makeRoomBuildingExtremeProblem(manifest.profiles[2],17);expect(Object.values(tight.roomRequirements??{}).every((r:any)=>r.required_classroom_ids?.length)).toBe(true);expect(Object.values(tight.roomRequirements??{}).some((r:any)=>r.required_features?.includes("projector"))).toBe(true);expect(transfer.periodBreaks?.some(b=>!b.transfer_allowed)).toBe(true);expect(special.assignments.some(a=>a.assigned_hours===2)).toBe(true);expect(Object.values(special.roomRequirements??{}).some((r:any)=>r.required_room_type==="SPECIALIST")).toBe(true)});
 test("one seed per profile is feasible and independently HARD-audited",()=>{for(const profile of manifest.profiles){const p=makeRoomBuildingExtremeProblem(profile,3181),r=solveIncrementalSchedule(p),a=auditRoomBuildingExtreme(p,r.rows);expect(r.complete,profile.id).toBe(true);expect({hard:a.hard,unplaced:a.unplaced,room_collisions:a.room_collisions,transfer_violations:a.transfer_violations,room_eligible:a.room_eligible,atomic:a.atomic},profile.id).toEqual({hard:0,unplaced:0,room_collisions:0,transfer_violations:0,room_eligible:true,atomic:true})}},30000);
 test("smoke report is deterministic and gate semantics cannot weaken",async()=>{const r=await runRoomBuildingExtremeCorpus(1);expect(r.results.every(x=>x.deterministic_replay&&x.multi_building_domain)).toBe(true);expect(()=>assertRoomBuildingExtremeGate(r,1,false)).not.toThrow();expect(()=>assertRoomBuildingExtremeGate({...r,results:[{...r.results[0]!,building_transfer_eligibility:false},...r.results.slice(1)]},1)).toThrow("ROOM_BUILDING_CORPUS_GATE_FAILED");expect(()=>assertRoomBuildingExtremeGate({...r,results:[{...r.results[0]!,budget_pass:false},...r.results.slice(1)]},1)).toThrow("ROOM_BUILDING_CORPUS_GATE_FAILED")},60000);
});
