import {describe,expect,test} from "bun:test";
import {adaptiveContextKey,buildRelinkProblem,candidateDistance,chooseAdaptiveStrategies,diversitySummary,mergeOperatorPriors,normalizeRelinkCandidate,selectElite,telemetryObservations,type OperatorPrior} from "../src/lib/schedule-adaptive-elite";
import {solveIncrementalSchedule} from "../src/lib/schedule-local-solver-incremental-core";
import type {LocalCandidate,LocalProblem} from "../src/lib/schedule-local-solver-time-core";

const migration=await Bun.file("supabase/migrations/20260827013000_schedule_adaptive_solver_v1.sql").text();
const orchestrator=await Bun.file("src/lib/schedule-local-solver.ts").text();
const health=await Bun.file("src/routes/schedule-adaptive-health.tsx").text();
function problem(seed=1):LocalProblem{const assignments=Array.from({length:36},(_,i)=>({assignment_id:`a${i}`,teacher_id:`t${i%18}`,class_id:`c${i%12}`,course_id:`q${i%9}`,assigned_hours:1,week_pattern:"ALL" as const}));return{days:[1,2,3,4,5],periods:8,assignments,locked:[],unavailable:[],teacherConstraints:Array.from({length:18},(_,i)=>({teacher_id:`t${i}`,max_daily_hours:6,max_consecutive_hours:4})),courseRules:Array.from({length:9},(_,i)=>({course_id:`q${i}`,block_pattern:[1],max_per_day:2,prohibited_days:null,prohibited_periods:null})),planningRelations:[],studentConflictWeights:[],seed,enableLns:true,lnsIterations:8}}
function fake(seed:number,shift:number,medium=0):LocalCandidate{return{rows:Array.from({length:8},(_,i)=>({assignment_id:`a${i}`,teacher_id:`t${i}`,class_id:`c${i}`,weekday:1+(i%5),period:1+((i+shift)%6),locked:false})),failed:0,complete:true,seed,score:{hard:0,medium,soft:shift},iterations:0,strategy:"TABU",lns:{enabled:false,iterations:0,accepted:0,improved:0,rejected:0,ruinedActivities:0,neighborhoods:{RANDOM_SMALL:0,TEACHER_DAY:0,CLASS_DAY:0,COURSE_BLOCK:0,CONFLICT_HOTSPOT:0,LOW_QUALITY_ZONE:0}}}}

describe("adaptive elite solver",()=>{
 test("migration is compact tenant telemetry only",()=>{expect(migration).toContain("schedule_solver_operator_telemetry");expect(migration).toContain("get_schedule_solver_operator_priors_v1");expect(migration).toContain("record_schedule_solver_operator_telemetry_v1");expect(migration).not.toMatch(/DROP\s+(TABLE|COLUMN)|TRUNCATE|DELETE\s+FROM/i)});
 test("production orchestrator uses adaptive UCB elite relinking and restart",()=>{for(const token of["chooseAdaptiveStrategies","selectElite","buildRelinkProblem","mostDiverseGuide","stagnant","restarts","record_schedule_solver_operator_telemetry_v1"])expect(orchestrator).toContain(token);expect(orchestrator).toContain("schedule-local-solver-worker.ts")});
 test("context and UCB plan are deterministic and react to learned rewards",()=>{const p=problem();expect(adaptiveContextKey(p)).toBe("SMALL:SPARSE");const priors:OperatorPrior[]=[{strategy:"TABU",attempts:20,wins:15,reward_sum:18},{strategy:"VND",attempts:20,wins:1,reward_sum:2}];const a=chooseAdaptiveStrategies(priors,8),b=chooseAdaptiveStrategies(priors,8);expect(a).toEqual(b);expect(a.filter(x=>x==="TABU").length).toBeGreaterThan(a.filter(x=>x==="VND").length)});
 test("elite pool rejects near duplicates but preserves diverse candidates",()=>{const a=fake(1,0),b=fake(2,0),c=fake(3,2);expect(candidateDistance(a,b)).toBe(0);expect(candidateDistance(a,c)).toBeGreaterThan(.1);const elite=selectElite([b,c,a],4,.08);expect(elite.length).toBe(2);const d=diversitySummary(elite);expect(d.min).toBeGreaterThan(.08)});
 test("path relinking is seed-replay deterministic and preserves manual-lock semantics",()=>{const p=problem(5),base=fake(1,0),guide=fake(2,2),a=buildRelinkProblem(p,base,guide,77,.25),b=buildRelinkProblem(p,base,guide,77,.25);expect(a).toEqual(b);expect(a.locked.length).toBeGreaterThan(0);expect(a.locked.every(r=>r.locked)).toBe(true);const x=solveIncrementalSchedule({...a,strategy:"VND",enableLns:false}),y=solveIncrementalSchedule({...b,strategy:"VND",enableLns:false});expect(x).toEqual(y);const normalized=normalizeRelinkCandidate(x,p);expect(normalized.rows.some(r=>r.locked)).toBe(false)});
 test("telemetry increments attempts/wins/rewards without losing priors",()=>{const a={...fake(1,0,0),strategy:"TABU" as const},b={...fake(2,1,2),strategy:"VND" as const},obs=telemetryObservations([a,b]);expect(obs).toHaveLength(2);expect(obs.filter(x=>x.win)).toHaveLength(1);const m=mergeOperatorPriors([{strategy:"TABU",attempts:3,wins:1,reward_sum:1.5}],obs),tabu=m.find(x=>x.strategy==="TABU")!;expect(tabu.attempts).toBe(4);expect(tabu.wins).toBe(2);expect(tabu.reward_sum).toBeGreaterThan(1.5)});
 test("adaptive health UI exposes context win rate reward and hard-safety explanation",()=>{for(const token of["schedule_solver_operator_telemetry","context_key","Kazanma %","Ort. reward","HARD kuralları"])expect(health).toContain(token)});
 test("small adaptive source pool stays feasible across all operator arms",()=>{const p=problem(91),arms=chooseAdaptiveStrategies([],5),c=arms.map((strategy,i)=>solveIncrementalSchedule({...p,seed:91+i*101,strategy,enableLns:false}));expect(c.every(x=>x.complete&&x.score.hard===0)).toBe(true);expect(selectElite(c,5,0).length).toBe(5)},20000);
});
