param([Parameter(Mandatory=$true)][string]$InstallerUrl,[string]$OutFile="$env:RUNNER_TEMP\asc-ui-tree-probe.json")
$ErrorActionPreference='Stop';Add-Type -AssemblyName UIAutomationClient;Add-Type -AssemblyName UIAutomationTypes
$tmp=Join-Path $env:RUNNER_TEMP 'asc-ui-probe';New-Item -ItemType Directory -Force $tmp|Out-Null;$installer=Join-Path $tmp 'asc.exe';Invoke-WebRequest -UseBasicParsing $InstallerUrl -OutFile $installer
$seven=Get-Command 7z.exe -ErrorAction Stop;$extract=Join-Path $tmp 'extract';New-Item -ItemType Directory -Force $extract|Out-Null;& $seven.Source x '-y' "-o$extract" $installer *> (Join-Path $tmp '7z.log')
$roz=Get-ChildItem $extract -Recurse -File -Filter roz.exe|Select-Object -First 1;if(-not $roz){throw 'ASC_ROZ_EXE_NOT_FOUND'}
$launch=Start-Process -FilePath $roz.FullName -PassThru;$tracked=@($launch.Id);try{$desktop=[System.Windows.Automation.AutomationElement]::RootElement;$deadline=(Get-Date).AddSeconds(30);$roots=@();do{Start-Sleep -Milliseconds 500;$ps=@(Get-Process -Name roz -ErrorAction SilentlyContinue);$tracked=@($tracked+@($ps.Id)|Select-Object -Unique);$tops=$desktop.FindAll([System.Windows.Automation.TreeScope]::Children,[System.Windows.Automation.Condition]::TrueCondition);$roots=@();for($i=0;$i-lt$tops.Count;$i++){try{$e=$tops.Item($i);if($tracked-contains$e.Current.ProcessId){$roots+=,$e}}catch{}}}while($roots.Count-lt 1-and(Get-Date)-lt$deadline);if($roots.Count-lt 1){throw "ASC_UI_TOPLEVEL_NOT_FOUND pids=$($tracked -join ',')"}
 $nodes=@();foreach($root in $roots){try{$c=$root.Current;$nodes+=@{name=$c.Name;automation_id=$c.AutomationId;class_name=$c.ClassName;control_type=$c.ControlType.ProgrammaticName;enabled=$c.IsEnabled;offscreen=$c.IsOffscreen;process_id=$c.ProcessId}}catch{};$all=$root.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition);for($i=0;$i-lt[Math]::Min($all.Count,1500);$i++){$e=$all.Item($i);try{$c=$e.Current;$nodes+=@{name=$c.Name;automation_id=$c.AutomationId;class_name=$c.ClassName;control_type=$c.ControlType.ProgrammaticName;enabled=$c.IsEnabled;offscreen=$c.IsOffscreen;process_id=$c.ProcessId}}catch{}}}
 $names=$nodes|Where-Object{$_.name}|Select-Object -ExpandProperty name -Unique;$r=[ordered]@{schema='OKULOS_ASC_UI_AUTOMATION_PROBE_V1';status='UI_PROBED_NOT_GENERATED';generation_status='NOT_RUN';tracked_process_ids=$tracked;root_count=$roots.Count;window_titles=@($roots|ForEach-Object{$_.Current.Name});node_count=$nodes.Count;actionable_names=@($names|Where-Object{$_-match'Create|New|Import|Export|TimeTable|Generate|Start|File|Test|Verification|Close|Cancel|OK'});nodes=$nodes;claim='UI Automation surface probe only; no timetable generation or benchmark claim.'};$r|ConvertTo-Json -Depth 8|Set-Content -Encoding utf8 $OutFile;Get-Content $OutFile
}finally{Get-Process -Name roz -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue}
