import os from "node:os";
import {solveIncrementalSchedule,type JointLocalProblem,type LocalRoomRequirement} from "../src/lib/schedule-local-solver-incremental-core";
import {auditLargeMtal,makeLargeMtalProblem} from "./schedule_mtal_large_corpus";

type Profile={id:string;classes:number;assignments_per_class:number;teachers:number;courses:number;periods:number;buildings:number;general_rooms:number;specialist_rooms:number;workshop_course_mod:number;forbidden_break_mod:number};
type Manifest={schema:string;seed_count:number;wall_clock_budget_ms:number;provenance:string;profiles:Profile[]};
type Result={profile_id:string;runs:number;assignments:number;rooms:number;buildings:number;feasible_rate:number;hard_max:number;unplaced_max:number;room_collision_0:boolean;room_eligibility:boolean;building_transfer_eligibility:boolean;multi_building_domain:boolean;atomic_blocks:boolean;deterministic_replay:boolean;runtime_p50_ms:number;runtime_p95_ms:number;runtime_max_ms:number;budget_pass:boolean};
type Report={schema:string;generated_at:string;seed_count:number;provenance:string;wall_clock_budget_ms:number;hardware:Record<string,unknown>;results:Result[]};
const manifest=await Bun.file(new URL("../benchmarks/room-building-extreme/manifest.json",import.meta.url)).json() as Manifest;
const pct=(a:number[],q:number)=>{const x=[...a].sort((m,n)=>m-n);return x[Math.min(x.length-1,Math.max(0,Math.ceil(x.length*q)-1))]??0};
const stable=(rows:any[])=>rows.map(r=>[r.assignment_id,r.weekday,r.period,r.classroom_id??null,r.activity_key??null]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));

export function makeRoomBuildingExtremeProblem(profile:Profile,seed:number):JointLocalProblem{
 const p=makeLargeMtalProblem({...profile,shifted:false,general_rooms:0,workshop_rooms:0},seed),buildings=Array.from({length:profile.buildings},(_,i)=>`b${i}`),rooms=[...Array.from({length:profile.general_rooms},(_,i)=>({classroom_id:`g${i}`,capacity:36,room_type:"GENERAL",features:Math.floor(i/profile.buildings)%2===0?["board","projector"]:["board"],building_id:buildings[i%buildings.length]})),...Array.from({length:profile.specialist_rooms},(_,i)=>({classroom_id:`s${i}`,capacity:24,room_type:"SPECIALIST",features:["safety","projector",i%2===0?"sink":"equipment"],building_id:buildings[(i+1)%buildings.length]}))];
 const general=rooms.filter(r=>r.room_type==="GENERAL"),special=rooms.filter(r=>r.room_type==="SPECIALIST"),roomRequirements:Record<string,LocalRoomRequirement>={};
 for(let i=0;i<p.assignments.length;i++){const a=p.assignments[i]!,q=Number(a.course_id.slice(1)),workshop=profile.workshop_course_mod>0&&q%profile.workshop_course_mod===0,pool=workshop?special:general,targetBuilding=buildings[(i+q)%buildings.length]!,target=pool.filter(r=>r.building_id===targetBuilding),eligible=target.length?target:pool;roomRequirements[a.assignment_id]={required_classroom_ids:eligible.map(r=>r.classroom_id),required_room_type:workshop?"SPECIALIST":"GENERAL",required_features:workshop?["safety"]:i%5===0?["projector"]:["board"],minimum_capacity:workshop?20:i%7===0?30:24,preferred_classroom_ids:eligible.slice(0,1).map(r=>r.classroom_id)}}
 const periodBreaks=Array.from({length:profile.periods-1},(_,i)=>({after_period:i+1,minutes:i%3===1?15:7,transfer_allowed:profile.forbidden_break_mod===0||(i+1)%profile.forbidden_break_mod!==0})),buildingTravel=[] as NonNullable<JointLocalProblem["buildingTravel"]>;
 for(let i=0;i<buildings.length;i++)for(let j=i+1;j<buildings.length;j++)buildingTravel.push({from_building_id:buildings[i]!,to_building_id:buildings[j]!,minutes:5+((j-i)*2)});
 return{...p,rooms,roomRequirements,periodBreaks,buildingTravel,enableLns:false};
}

export function auditRoomBuildingExtreme(p:JointLocalProblem,rows:any[]){
 const base=auditLargeMtal(p,rows),rooms=new Map((p.rooms??[]).map(r=>[r.classroom_id,r])),breaks=new Map((p.periodBreaks??[]).map(b=>[b.after_period,b])),travel=new Map((p.buildingTravel??[]).flatMap(t=>[[`${t.from_building_id}|${t.to_building_id}`,t.minutes],[`${t.to_building_id}|${t.from_building_id}`,t.minutes]] as const)),violations=[...base.violations];let transfers=0;
 const byTeacherDay=new Map<string,any[]>();for(const r of rows){const k=`${r.teacher_id}|${r.weekday}`;byTeacherDay.set(k,[...(byTeacherDay.get(k)??[]),r])}for(const rs of byTeacherDay.values()){const byPeriod=new Map(rs.map(r=>[r.period,r]));for(const r of rs){const n=byPeriod.get(r.period+1);if(!n)continue;const a=r.classroom_id?rooms.get(r.classroom_id):null,b=n.classroom_id?rooms.get(n.classroom_id):null;if(!a?.building_id||!b?.building_id||a.building_id===b.building_id)continue;transfers++;const br=breaks.get(r.period),need=travel.get(`${a.building_id}|${b.building_id}`)??0;if(!br?.transfer_allowed||br.minutes<need)violations.push(`BUILDING_TRANSFER:${r.teacher_id}:${r.weekday}:${r.period}`)}}
 const roomCollisions=violations.filter(v=>v.startsWith("ROOM_COLLISION")).length,transferViolations=violations.filter(v=>v.startsWith("BUILDING_TRANSFER")).length,multiBuilding=(p.rooms?.filter(r=>r.building_id).map(r=>r.building_id).filter((v,i,a)=>a.indexOf(v)===i).length??0)>1&&Object.values(p.roomRequirements??{}).every(q=>{const bs=new Set((q.required_classroom_ids??[]).map(id=>rooms.get(id)?.building_id));return bs.size===1});return{...base,hard:violations.length,violations,room_collisions:roomCollisions,transfer_violations:transferViolations,transfers,multi_building_domain:multiBuilding};
}

export async function runRoomBuildingExtremeCorpus(seedCount=manifest.seed_count):Promise<Report>{const seeds=Array.from({length:seedCount},(_,i)=>3181+i*7919),results:Result[]=[];for(const profile of manifest.profiles){const times:number[]=[],audits:any[]=[];let feasible=0,deterministic=true;for(let i=0;i<seeds.length;i++){const p=makeRoomBuildingExtremeProblem(profile,seeds[i]!),t=performance.now(),r=solveIncrementalSchedule(p),ms=performance.now()-t,a=auditRoomBuildingExtreme(p,r.rows);times.push(ms);audits.push(a);if(r.complete&&r.failed===0&&a.hard===0&&a.unplaced===0)feasible++;if(i===0){const replay=solveIncrementalSchedule(makeRoomBuildingExtremeProblem(profile,seeds[i]!));deterministic=JSON.stringify(stable(r.rows))===JSON.stringify(stable(replay.rows))&&JSON.stringify(r.score)===JSON.stringify(replay.score)}}results.push({profile_id:profile.id,runs:seedCount,assignments:profile.classes*profile.assignments_per_class,rooms:profile.general_rooms+profile.specialist_rooms,buildings:profile.buildings,feasible_rate:feasible/seedCount,hard_max:Math.max(...audits.map(a=>a.hard)),unplaced_max:Math.max(...audits.map(a=>a.unplaced)),room_collision_0:audits.every(a=>a.room_collisions===0),room_eligibility:audits.every(a=>a.room_eligible),building_transfer_eligibility:audits.every(a=>a.transfer_violations===0),multi_building_domain:audits.every(a=>a.multi_building_domain),atomic_blocks:audits.every(a=>a.atomic),deterministic_replay:deterministic,runtime_p50_ms:Math.round(pct(times,.5)),runtime_p95_ms:Math.round(pct(times,.95)),runtime_max_ms:Math.round(Math.max(...times)),budget_pass:times.every(ms=>ms<=manifest.wall_clock_budget_ms)})}return{schema:manifest.schema,generated_at:new Date().toISOString(),seed_count:seedCount,provenance:manifest.provenance,wall_clock_budget_ms:manifest.wall_clock_budget_ms,hardware:{platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model??"unknown",logical_cpus:os.cpus().length,bun:Bun.version},results}}
export function assertRoomBuildingExtremeGate(r:Report,minSeeds=manifest.seed_count){if(r.seed_count<minSeeds||r.results.length!==manifest.profiles.length)throw new Error("ROOM_BUILDING_CORPUS_SHAPE_FAILED");for(const x of r.results)if(x.runs<minSeeds||x.assignments<120||x.buildings<3||x.feasible_rate!==1||x.hard_max!==0||x.unplaced_max!==0||!x.room_collision_0||!x.room_eligibility||!x.building_transfer_eligibility||!x.multi_building_domain||!x.atomic_blocks||!x.deterministic_replay||!x.budget_pass)throw new Error(`ROOM_BUILDING_CORPUS_GATE_FAILED:${x.profile_id}`)}
if(import.meta.main){const args=process.argv.slice(2),oi=args.indexOf("--out"),si=args.indexOf("--seeds"),out=oi>=0?args[oi+1]:null,seeds=si>=0?Number(args[si+1]):manifest.seed_count;if(!Number.isInteger(seeds)||seeds<1)throw new Error("--seeds must be a positive integer");const report=await runRoomBuildingExtremeCorpus(seeds);console.log("SCHEDULE_ROOM_BUILDING_EXTREME",JSON.stringify(report));if(out)await Bun.write(out,JSON.stringify(report,null,2));assertRoomBuildingExtremeGate(report,manifest.seed_count)}
