import os from "node:os";
import {solveIncrementalSchedule,type JointLocalProblem,type LocalRoomRequirement} from "../src/lib/schedule-local-solver-incremental-core";
import {localScopesOverlap,type LocalAssignment,type LocalLockedRow} from "../src/lib/schedule-local-solver-time-core";

type Profile={id:string;classes:number;assignments_per_class:number;teachers:number;courses:number;periods:number;workshop_course_mod:number;shifted:boolean;general_rooms:number;workshop_rooms:number};
type Manifest={schema:string;seed_count:number;wall_clock_budget_ms:number;provenance:string;profiles:Profile[]};
type Audit={hard:number;unplaced:number;atomic:boolean;room_eligible:boolean;violations:string[]};
type Result={profile_id:string;runs:number;assignments:number;scheduled_rows:number;feasible_rate:number;hard_max:number;unplaced_max:number;atomic_blocks:boolean;room_eligibility:boolean;deterministic_replay:boolean;runtime_p50_ms:number;runtime_p95_ms:number;runtime_max_ms:number;budget_pass:boolean};
type Report={schema:string;generated_at:string;seed_count:number;provenance:string;wall_clock_budget_ms:number;hardware:Record<string,unknown>;results:Result[]};
const manifest=await Bun.file(new URL("../benchmarks/mtal-large/manifest.json",import.meta.url)).json() as Manifest;
const K=(...v:(string|number|null|undefined)[])=>v.join("|");
const pct=(a:number[],q:number)=>{const x=[...a].sort((m,n)=>m-n);return x[Math.min(x.length-1,Math.max(0,Math.ceil(x.length*q)-1))]??0};
const stable=(rows:LocalLockedRow[])=>rows.map(r=>[r.assignment_id,r.weekday,r.period,r.classroom_id??null,r.activity_key??null]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));

export function makeLargeMtalProblem(profile:Profile,seed:number):JointLocalProblem{
 const workshop=(q:number)=>profile.workshop_course_mod>0&&q%profile.workshop_course_mod===0,courseRules=Array.from({length:profile.courses},(_,q)=>({course_id:`q${q}`,block_pattern:workshop(q)?[2]:[1],max_per_day:workshop(q)?2:1,prohibited_days:null,prohibited_periods:q%11===0?[10]:null})),assignments:LocalAssignment[]=[];
 let n=0;for(let c=0;c<profile.classes;c++)for(let j=0;j<profile.assignments_per_class;j++){const q=(c*5+j*3)%profile.courses,isWorkshop=workshop(q),shift=profile.shifted?(c+j)%2:null;assignments.push({assignment_id:`a${n++}`,teacher_id:`t${(c*3+j*11)%profile.teachers}`,class_id:`c${c}`,course_id:`q${q}`,assigned_hours:isWorkshop?2:1,week_pattern:n%19===0?"ODD":n%19===1?"EVEN":"ALL",valid_from:null,valid_to:null,term_no:null,schedule_session_id:shift==null?null:shift===0?"AM":"PM",allowed_periods:shift==null?null:shift===0?[1,2,3,4,5]:[6,7,8,9,10]})}
 const rooms=[...Array.from({length:profile.general_rooms},(_,i)=>({classroom_id:`g${i}`,capacity:36,room_type:"GENERAL",features:["board"],building_id:`b${i%3}`})),...Array.from({length:profile.workshop_rooms},(_,i)=>({classroom_id:`w${i}`,capacity:24,room_type:"WORKSHOP",features:["workshop","safety"],building_id:`wb${i%2}`}))],roomRequirements:Record<string,LocalRoomRequirement>={};if(rooms.length)for(const a of assignments)roomRequirements[a.assignment_id]=workshop(Number(a.course_id.slice(1)))?{required_room_type:"WORKSHOP",required_features:["workshop"],minimum_capacity:20}:{required_room_type:"GENERAL",minimum_capacity:24};
 const unavailable=Array.from({length:Math.ceil(profile.teachers*.35)},(_,i)=>({teacher_id:`t${i}`,weekday:i%5+1,period:(i*3)%profile.periods+1,schedule_session_id:null})),teacherConstraints=Array.from({length:profile.teachers},(_,i)=>({teacher_id:`t${i}`,max_daily_hours:7,max_consecutive_hours:i%5===0?4:5})),studentConflictWeights=[] as JointLocalProblem["studentConflictWeights"];
 for(let i=0;i<assignments.length-9;i+=9)studentConflictWeights!.push({left_assignment_id:assignments[i]!.assignment_id,right_assignment_id:assignments[i+9]!.assignment_id,student_weight:2,severity_weight:2});
 return{days:[1,2,3,4,5],periods:profile.periods,assignments,locked:[],unavailable,teacherConstraints,courseRules,planningRelations:[],studentConflictWeights,rooms,roomRequirements,seed,enableLns:false};
}

export function auditLargeMtal(p:JointLocalProblem,rows:LocalLockedRow[]):Audit{
 const violations:string[]=[],byId=new Map(p.assignments.map(a=>[a.assignment_id,a])),counts=new Map<string,number>(),rooms=new Map((p.rooms??[]).map(r=>[r.classroom_id,r])),groups=new Map<string,LocalLockedRow[]>(),unavailable=new Set(p.unavailable.map(u=>K(u.teacher_id,u.weekday,u.period,u.schedule_session_id??"*")));
 for(const r of rows){const a=byId.get(r.assignment_id);if(!a){violations.push(`UNKNOWN:${r.assignment_id}`);continue}counts.set(a.assignment_id,(counts.get(a.assignment_id)??0)+1);groups.set(r.activity_key??`row:${r.assignment_id}:${r.weekday}:${r.period}`,[...(groups.get(r.activity_key??`row:${r.assignment_id}:${r.weekday}:${r.period}`)??[]),r]);if(a.allowed_periods?.length&&!a.allowed_periods.includes(r.period))violations.push(`ALLOWED:${r.assignment_id}`);if(unavailable.has(K(r.teacher_id,r.weekday,r.period,"*"))||unavailable.has(K(r.teacher_id,r.weekday,r.period,a.schedule_session_id??"*")))violations.push(`UNAVAILABLE:${r.assignment_id}`);const rule=p.courseRules.find(q=>q.course_id===a.course_id);if(rule?.prohibited_days?.includes(r.weekday)||rule?.prohibited_periods?.includes(r.period))violations.push(`COURSE_DOMAIN:${r.assignment_id}`);if(p.rooms?.length){const room=r.classroom_id?rooms.get(r.classroom_id):null,req=p.roomRequirements?.[a.assignment_id];if(!room)violations.push(`ROOM_MISSING:${r.assignment_id}`);else if((req?.required_room_type&&room.room_type!==req.required_room_type)||(req?.minimum_capacity!=null&&(room.capacity??0)<req.minimum_capacity)||(req?.required_features?.some(f=>!room.features?.includes(f))))violations.push(`ROOM_INELIGIBLE:${r.assignment_id}`)}}
 for(const a of p.assignments)if((counts.get(a.assignment_id)??0)!==a.assigned_hours)violations.push(`HOURS:${a.assignment_id}`);
 let atomic=true;for(const [g,rs]of groups){const d=new Set(rs.map(r=>r.weekday)),ps=rs.map(r=>r.period).sort((a,b)=>a-b),duration=rs[0]?.activity_duration??rs.length;if(d.size!==1||rs.length!==duration||ps.some((x,i)=>i>0&&x!==ps[i-1]!+1)){atomic=false;violations.push(`ATOMIC:${g}`)}}
 for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i]!,b=rows[j]!;if(a.weekday!==b.weekday||a.period!==b.period||!localScopesOverlap(byId.get(a.assignment_id),byId.get(b.assignment_id)))continue;if(a.teacher_id===b.teacher_id)violations.push(`TEACHER_COLLISION:${i}:${j}`);if(a.class_id&&a.class_id===b.class_id)violations.push(`CLASS_COLLISION:${i}:${j}`);if(a.classroom_id&&a.classroom_id===b.classroom_id)violations.push(`ROOM_COLLISION:${i}:${j}`)}
 const applies=(r:LocalLockedRow,ctx:"ODD"|"EVEN")=>{const w=byId.get(r.assignment_id)?.week_pattern??"ALL";return w==="ALL"||w===ctx};for(const c of p.teacherConstraints)for(const d of p.days)for(const ctx of["ODD","EVEN"]as const){const ps=rows.filter(r=>r.teacher_id===c.teacher_id&&r.weekday===d&&applies(r,ctx)).map(r=>r.period).sort((a,b)=>a-b);if(c.max_daily_hours&&ps.length>c.max_daily_hours)violations.push(`MAX_DAILY:${c.teacher_id}:${d}:${ctx}`);if(c.max_consecutive_hours){let run=0,best=0,last=-99;for(const x of[...new Set(ps)]){run=x===last+1?run+1:1;last=x;best=Math.max(best,run)}if(best>c.max_consecutive_hours)violations.push(`MAX_CONSECUTIVE:${c.teacher_id}:${d}:${ctx}`)}}
 const unplaced=p.assignments.reduce((n,a)=>n+Math.max(0,a.assigned_hours-(counts.get(a.assignment_id)??0)),0),roomEligible=!violations.some(v=>v.startsWith("ROOM_"));return{hard:violations.length,unplaced,atomic,room_eligible:roomEligible,violations};
}

export async function runLargeMtalCorpus(seedCount=manifest.seed_count):Promise<Report>{const seeds=Array.from({length:seedCount},(_,i)=>1709+i*7919),results:Result[]=[];for(const profile of manifest.profiles){const times:number[]=[],audits:Audit[]=[];let feasible=0,deterministic=true,lastRows=0;for(let i=0;i<seeds.length;i++){const p=makeLargeMtalProblem(profile,seeds[i]!),t=performance.now(),r=solveIncrementalSchedule(p),ms=performance.now()-t,a=auditLargeMtal(p,r.rows);times.push(ms);audits.push(a);lastRows=r.rows.length;if(r.complete&&r.failed===0&&a.hard===0&&a.unplaced===0)feasible++;if(i===0){const replay=solveIncrementalSchedule(makeLargeMtalProblem(profile,seeds[i]!));deterministic=JSON.stringify(stable(r.rows))===JSON.stringify(stable(replay.rows))&&JSON.stringify(r.score)===JSON.stringify(replay.score)}}results.push({profile_id:profile.id,runs:seedCount,assignments:profile.classes*profile.assignments_per_class,scheduled_rows:lastRows,feasible_rate:feasible/seedCount,hard_max:Math.max(...audits.map(a=>a.hard)),unplaced_max:Math.max(...audits.map(a=>a.unplaced)),atomic_blocks:audits.every(a=>a.atomic),room_eligibility:audits.every(a=>a.room_eligible),deterministic_replay:deterministic,runtime_p50_ms:Math.round(pct(times,.5)),runtime_p95_ms:Math.round(pct(times,.95)),runtime_max_ms:Math.round(Math.max(...times)),budget_pass:times.every(ms=>ms<=manifest.wall_clock_budget_ms)})}return{schema:manifest.schema,generated_at:new Date().toISOString(),seed_count:seedCount,provenance:manifest.provenance,wall_clock_budget_ms:manifest.wall_clock_budget_ms,hardware:{platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model??"unknown",logical_cpus:os.cpus().length,bun:Bun.version},results}}
export function assertLargeMtalGate(r:Report,minSeeds=manifest.seed_count){if(r.seed_count<minSeeds||r.results.length!==manifest.profiles.length)throw new Error("MTAL_CORPUS_SHAPE_FAILED");for(const x of r.results)if(x.runs<minSeeds||x.feasible_rate!==1||x.hard_max!==0||x.unplaced_max!==0||!x.atomic_blocks||!x.room_eligibility||!x.deterministic_replay||!x.budget_pass)throw new Error(`MTAL_CORPUS_GATE_FAILED:${x.profile_id}`)}
if(import.meta.main){const args=process.argv.slice(2),oi=args.indexOf("--out"),si=args.indexOf("--seeds"),out=oi>=0?args[oi+1]:null,seeds=si>=0?Number(args[si+1]):manifest.seed_count;if(!Number.isInteger(seeds)||seeds<1)throw new Error("--seeds must be a positive integer");const report=await runLargeMtalCorpus(seeds);console.log("SCHEDULE_MTAL_LARGE",JSON.stringify(report));if(out)await Bun.write(out,JSON.stringify(report,null,2));assertLargeMtalGate(report,manifest.seed_count)}
