import type {LocalProblem} from "../src/lib/schedule-local-solver-time-core";
const esc=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const uniq=(xs:string[])=>[...new Set(xs)].sort();
export function ascWeeks(pattern?:string|null){const p=String(pattern??"ALL").toUpperCase();if(p==="ODD")return"10";if(p==="EVEN")return"01";return"1"}
export function ascPeriodsPerWeek(hours:number,pattern?:string|null){return ascWeeks(pattern)==="1"?hours:hours/2}
export function exportAsc2012Xml(problem:LocalProblem,displayName="Okulos World Benchmark"){
 const teachers=uniq(problem.assignments.map(a=>a.teacher_id)),classes=uniq(problem.assignments.map(a=>a.class_id)),courses=uniq(problem.assignments.map(a=>a.course_id));
 const lines=[`<?xml version="1.0" encoding="utf-8"?>`,`<timetable importtype="database" options="import:idprefix:Okulos,groupstype1,decimalseparatordot" displayname="${esc(displayName)}">`,`<periods options="canadd" columns="period,name,short">`];
 for(let p=1;p<=problem.periods;p++)lines.push(`<period period="${p}" name="${p}" short="${p}"/>`);lines.push(`</periods>`,`<teachers options="canadd" columns="id,name,short">`);for(const id of teachers)lines.push(`<teacher id="${esc(id)}" name="${esc(id)}" short="${esc(id)}"/>`);lines.push(`</teachers>`,`<classes options="canadd" columns="id,name,short">`);for(const id of classes)lines.push(`<class id="${esc(id)}" name="${esc(id)}" short="${esc(id)}"/>`);lines.push(`</classes>`,`<subjects options="canadd" columns="id,name,short">`);for(const id of courses)lines.push(`<subject id="${esc(id)}" name="${esc(id)}" short="${esc(id)}"/>`);lines.push(`</subjects>`,`<lessons options="canadd" columns="id,subjectid,classid,teacherid,periodsperweek,periodspercard,weeks">`);
 for(const a of problem.assignments){const weeks=ascWeeks(a.week_pattern),ppw=ascPeriodsPerWeek(Number(a.assigned_hours),a.week_pattern);lines.push(`<lesson id="${esc(a.assignment_id)}" subjectid="${esc(a.course_id)}" classid="${esc(a.class_id)}" teacherid="${esc(a.teacher_id)}" periodsperweek="${ppw}" periodspercard="1" weeks="${weeks}"/>`)}lines.push(`</lessons>`,`</timetable>`);
 return{xml:lines.join("\n"),status:"INPUT_PARTIAL" as const,unsupported:[...(problem.teacherConstraints?.length?["TEACHER_DAILY_AND_CONSECUTIVE_LIMIT_XML_MAPPING_UNVERIFIED"]:[]),...(problem.unavailable?.length?["TEACHER_TIME_OFF_XML_MAPPING_UNVERIFIED"]:[]),...(problem.planningRelations?.length?["GENERIC_RELATION_XML_MAPPING_UNVERIFIED"]:[])],truth:"aSc XML structure/week-pattern export is prepared, but generator execution and all common-HARD constraint mappings remain unverified." as const};
}
