import os from "node:os";
import {solveIncrementalSchedule,type JointLocalProblem} from "../src/lib/schedule-local-solver-incremental-core";
import {auditLargeMtal,makeLargeMtalProblem} from "./schedule_mtal_large_corpus";

type Profile={id:string;classes:number;assignments_per_class:number;teachers:number;courses:number;periods:number;workshop_course_mod:number;shifted:boolean;general_rooms:number;workshop_rooms:number;unit_count:number;enterprise_weekdays:number[]};
type Manifest={schema:string;seed_count:number;wall_clock_budget_ms:number;provenance:string;institution_code:string;profiles:Profile[]};
type Result={profile_id:string;runs:number;assignments:number;scheduled_rows:number;feasible_rate:number;hard_max:number;unplaced_max:number;atomic_blocks:boolean;room_eligibility:boolean;enterprise_day_exclusion:boolean;unit_identity:boolean;deterministic_replay:boolean;runtime_p50_ms:number;runtime_p95_ms:number;runtime_max_ms:number;budget_pass:boolean};
type Report={schema:string;generated_at:string;seed_count:number;provenance:string;institution_code:string;wall_clock_budget_ms:number;hardware:Record<string,unknown>;results:Result[]};
const manifest=await Bun.file(new URL("../benchmarks/mesem-large/manifest.json",import.meta.url)).json() as Manifest;
const pct=(a:number[],q:number)=>{const x=[...a].sort((m,n)=>m-n);return x[Math.min(x.length-1,Math.max(0,Math.ceil(x.length*q)-1))]??0};
const stable=(rows:any[])=>rows.map(r=>[r.assignment_id,r.weekday,r.period,r.classroom_id??null,r.activity_key??null]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));

export function makeLargeMesemProblem(profile:Profile,seed:number):JointLocalProblem{
 const p=makeLargeMtalProblem(profile,seed), unitOf=(classId:string)=>Number(classId.slice(1))%profile.unit_count, sourceRules=new Map(p.courseRules.map(r=>[r.course_id,r]));
 p.assignments=p.assignments.map(a=>{const baseClass=a.class_id!,baseCourse=a.course_id;return {...a,course_id:`${baseCourse}:class-${baseClass}`,class_id:`${manifest.institution_code}:unit-${unitOf(baseClass)}:${baseClass}`,schedule_session_id:`unit-${unitOf(baseClass)}`}});
 p.courseRules=p.assignments.map(a=>{const base=a.course_id.split(":class-")[0]!,rule=sourceRules.get(base)!;return {...rule,course_id:a.course_id,prohibited_days:profile.enterprise_weekdays}});
 return p;
}

function enterpriseExcluded(p:JointLocalProblem,rows:any[]){const blocked=new Map(p.courseRules.map(r=>[r.course_id,new Set(r.prohibited_days??[])]));const assignmentById=new Map(p.assignments.map(a=>[a.assignment_id,a]));return rows.every(r=>!blocked.get(assignmentById.get(r.assignment_id)?.course_id??"")?.has(r.weekday))}
function unitIdentity(p:JointLocalProblem){const units=new Set(p.assignments.map(a=>a.schedule_session_id));return units.size>1&&p.assignments.every(a=>a.class_id?.startsWith(`${manifest.institution_code}:unit-`)&&a.schedule_session_id?.startsWith("unit-"))}

export async function runLargeMesemCorpus(seedCount=manifest.seed_count):Promise<Report>{const seeds=Array.from({length:seedCount},(_,i)=>2089+i*7919),results:Result[]=[];for(const profile of manifest.profiles){const times:number[]=[],audits:any[]=[];let feasible=0,deterministic=true,lastRows=0,enterprise=true;for(let i=0;i<seeds.length;i++){const p=makeLargeMesemProblem(profile,seeds[i]!),t=performance.now(),r=solveIncrementalSchedule(p),ms=performance.now()-t,a=auditLargeMtal(p,r.rows),e=enterpriseExcluded(p,r.rows);times.push(ms);audits.push(a);enterprise&&=e;lastRows=r.rows.length;if(r.complete&&r.failed===0&&a.hard===0&&a.unplaced===0&&e)feasible++;if(i===0){const replay=solveIncrementalSchedule(makeLargeMesemProblem(profile,seeds[i]!));deterministic=JSON.stringify(stable(r.rows))===JSON.stringify(stable(replay.rows))&&JSON.stringify(r.score)===JSON.stringify(replay.score)}}results.push({profile_id:profile.id,runs:seedCount,assignments:profile.classes*profile.assignments_per_class,scheduled_rows:lastRows,feasible_rate:feasible/seedCount,hard_max:Math.max(...audits.map(a=>a.hard)),unplaced_max:Math.max(...audits.map(a=>a.unplaced)),atomic_blocks:audits.every(a=>a.atomic),room_eligibility:audits.every(a=>a.room_eligible),enterprise_day_exclusion:enterprise,unit_identity:unitIdentity(makeLargeMesemProblem(profile,seeds[0]!)),deterministic_replay:deterministic,runtime_p50_ms:Math.round(pct(times,.5)),runtime_p95_ms:Math.round(pct(times,.95)),runtime_max_ms:Math.round(Math.max(...times)),budget_pass:times.every(ms=>ms<=manifest.wall_clock_budget_ms)})}return{schema:manifest.schema,generated_at:new Date().toISOString(),seed_count:seedCount,provenance:manifest.provenance,institution_code:manifest.institution_code,wall_clock_budget_ms:manifest.wall_clock_budget_ms,hardware:{platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model??"unknown",logical_cpus:os.cpus().length,bun:Bun.version},results}}
export function assertLargeMesemGate(r:Report,minSeeds=manifest.seed_count,enforceRuntimeBudget=true){if(r.seed_count<minSeeds||r.results.length!==manifest.profiles.length)throw new Error("MESEM_CORPUS_SHAPE_FAILED");for(const x of r.results)if(x.runs<minSeeds||x.feasible_rate!==1||x.hard_max!==0||x.unplaced_max!==0||!x.atomic_blocks||!x.room_eligibility||!x.enterprise_day_exclusion||!x.unit_identity||!x.deterministic_replay||(enforceRuntimeBudget&&!x.budget_pass))throw new Error(`MESEM_CORPUS_GATE_FAILED:${x.profile_id}`)}
if(import.meta.main){const args=process.argv.slice(2),oi=args.indexOf("--out"),si=args.indexOf("--seeds"),out=oi>=0?args[oi+1]:null,seeds=si>=0?Number(args[si+1]):manifest.seed_count;if(!Number.isInteger(seeds)||seeds<1)throw new Error("--seeds must be a positive integer");const report=await runLargeMesemCorpus(seeds);console.log("SCHEDULE_MESEM_LARGE",JSON.stringify(report));if(out)await Bun.write(out,JSON.stringify(report,null,2));assertLargeMesemGate(report,manifest.seed_count)}
