import type {LocalProblem} from "../src/lib/schedule-local-solver-time-core";
const esc=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const uniq=(xs:string[])=>[...new Set(xs)].sort();
export function ascWeeks(pattern?:string|null){const p=String(pattern??"ALL").toUpperCase();if(p==="ODD")return"10";if(p==="EVEN")return"01";return"1"}
export function ascPeriodsPerWeek(hours:number,pattern?:string|null){return ascWeeks(pattern)==="1"?hours:hours/2}
export function ascTeacherTimeoff(problem:Pick<LocalProblem,"days"|"periods"|"unavailable">,teacherId:string){const days=[...problem.days].sort((a,b)=>a-b);return days.map(day=>{const chars=["."];for(let p=1;p<=problem.periods;p++){const blocked=problem.unavailable.some(u=>u.teacher_id===teacherId&&u.weekday===day&&u.period===p);chars.push(blocked?"0":"1")}return chars.join("")}).join(",")}
export function exportAsc2012Xml(problem:LocalProblem,displayName="Okulos World Benchmark"){
 const teachers=uniq(problem.assignments.map(a=>a.teacher_id)),classes=uniq(problem.assignments.map(a=>a.class_id)),courses=uniq(problem.assignments.map(a=>a.course_id));
 const scopedUnavailable=(problem.unavailable??[]).some(u=>Boolean((u as unknown as {schedule_session_id?:string|null}).schedule_session_id));
 const lines=[`<?xml version="1.0" encoding="utf-8"?>`,`<timetable importtype="database" options="import:idprefix:Okulos,groupstype1,decimalseparatordot" displayname="${esc(displayName)}">`,`<periods options="canadd" columns="period,name,short">`];
 for(let p=1;p<=problem.periods;p++)lines.push(`<period period="${p}" name="${p}" short="${p}"/>`);lines.push(`</periods>`,`<teachers options="canadd" columns="id,name,short,timeoff">`);for(const id of teachers)lines.push(`<teacher id="${esc(id)}" name="${esc(id)}" short="${esc(id)}" timeoff="${ascTeacherTimeoff(problem,id)}"/>`);lines.push(`</teachers>`,`<classes options="canadd" columns="id,name,short">`);for(const id of classes)lines.push(`<class id="${esc(id)}" name="${esc(id)}" short="${esc(id)}"/>`);lines.push(`</classes>`,`<subjects options="canadd" columns="id,name,short">`);for(const id of courses)lines.push(`<subject id="${esc(id)}" name="${esc(id)}" short="${esc(id)}"/>`);lines.push(`</subjects>`,`<lessons options="canadd" columns="id,subjectid,classid,teacherid,periodsperweek,periodspercard,weeks">`);
 for(const a of problem.assignments){const weeks=ascWeeks(a.week_pattern),ppw=ascPeriodsPerWeek(Number(a.assigned_hours),a.week_pattern);lines.push(`<lesson id="${esc(a.assignment_id)}" subjectid="${esc(a.course_id)}" classid="${esc(a.class_id)}" teacherid="${esc(a.teacher_id)}" periodsperweek="${ppw}" periodspercard="1" weeks="${weeks}"/>`)}lines.push(`</lessons>`,`</timetable>`);
 const unsupported=[...(problem.teacherConstraints?.length?["TEACHER_DAILY_AND_CONSECUTIVE_LIMIT_XML_MAPPING_UNVERIFIED"]:[]),...(scopedUnavailable?["SCOPED_TEACHER_TIME_OFF_XML_MAPPING_UNVERIFIED"]:[]),...(problem.planningRelations?.length?["GENERIC_RELATION_XML_MAPPING_UNVERIFIED"]:[])];
 return{xml:lines.join("\n"),status:"INPUT_PARTIAL" as const,unsupported,truth:"aSc XML structure, week-pattern and unscoped teacher time-off export are prepared; generator execution plus remaining common-HARD mappings are still unverified." as const};
}
