begin;
insert into course_catalog(name,category)
select x,'uygulama' from unnest(array['Genel Matbaa','Baskı Öncesi İşlemler','Baskı Kalıpları','Baskı Sonrası İşlemler','Matbaa Teknik Resmi','Ahilik Kültürü ve Girişimcilik','Vektörel Çizim','Görüntü İşleme','Bilgisayardan Kalıba Çıkış','Dijital Baskı','Montaj','Ofset Baskı Teknikleri','Kartonaj','Ofsette Özel Baskılar','Ofsette Farklı Baskı Teknikleri','Flekso Baskı Teknikleri','Letterpress Baskı','Ambalaj','Tifdruk Baskı Teknikleri','Serigrafi Baskı','Serigrafi Kalıbı','Serigrafide Özel Baskılar','Promosyon Farklı Baskı Teknikleri','Tampon Baskı','Tampon Kalıbı','Dijital Baskı Teknikleri','Bilgisayar Destekli Tasarım','Ciltleme','Endüstriyel Ciltleme','Baskı Sonrası Teknikleri']) x on conflict(name) do nothing;
with b(branch_name) as (values ('Baskı Öncesi'),('Baskı Sonrası'),('Dijital Baskı'),('Flekso Baskı'),('Ofset Baskı'),('Serigrafi Baskı'),('Tampon Baskı'),('Tifdruk Baskı')),
g(grade_level,common_hours,vocational_hours,elective_hours,enterprise_hours,u_req,d_req,u_target,d_target) as (values (9,6,2,2,32,40,42,42,44),(10,6,4,0,32,42,44,42,44),(11,3,7,0,32,42,46,42,46),(12,2,8,0,32,42,48,42,48)),
v(schedule_variant) as (values ('USTALIK'),('DIPLOMA'))
insert into official_curriculum_profiles(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_hours,enterprise_hours,applicability_status,parsed_constraints)
select '2026-2027','MESEM','MESEM','Matbaa Teknolojisi',b.branch_name,g.grade_level,0,case when v.schedule_variant='USTALIK' then g.u_req else g.d_req end,case when g.elective_hours>0 then 1 else 0 end,case when g.elective_hours>0 then 1 else 0 end,g.elective_hours,g.elective_hours,case when v.schedule_variant='USTALIK' then g.u_target else g.d_target end,case when v.schedule_variant='USTALIK' then g.u_target else g.d_target end,case when v.schedule_variant='USTALIK' then g.u_target else g.d_target end,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_matbaa_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Matbaa Teknolojisi çizelgesi; parantezli temel ders saatleri DIPLOMA fark dersidir.',true,v.schedule_variant,case when v.schedule_variant='USTALIK' then g.common_hours else case g.grade_level when 9 then 8 when 10 then 8 when 11 then 7 else 8 end end,g.vocational_hours,g.elective_hours,g.enterprise_hours,'ACTIVE',jsonb_build_object('source','MTEGM','decision','2021-33')
from b cross join g cross join v
where not exists(select 1 from official_curriculum_profiles p where p.effective_academic_year='2026-2027' and p.school_type='MESEM' and coalesce(p.school_subtype,'')='' and coalesce(p.program_type,'')='MESEM' and p.field_name='Matbaa Teknolojisi' and p.branch_name=b.branch_name and p.grade_level=g.grade_level and coalesce(p.schedule_variant,'STANDARD')=v.schedule_variant);
with base(branch_name,grade_level,course_name,u_hour,d_hour) as (
values
('Baskı Öncesi',9,'Türk Dili ve Edebiyatı',2,2),('Baskı Öncesi',9,'Din Kültürü ve Ahlak Bilgisi',2,2),('Baskı Öncesi',9,'Matematik',2,2),('Baskı Öncesi',9,'Tarih',0,2),('Baskı Öncesi',9,'Genel Matbaa',2,2),('Baskı Öncesi',9,'İşletmelerde Mesleki Eğitim',32,32),
('Baskı Öncesi',10,'Türk Dili ve Edebiyatı',2,2),('Baskı Öncesi',10,'Din Kültürü ve Ahlak Bilgisi',2,2),('Baskı Öncesi',10,'Matematik',2,2),('Baskı Öncesi',10,'T.C. İnkılap Tarihi ve Atatürkçülük',0,2),('Baskı Öncesi',10,'Baskı Öncesi İşlemler',1,1),('Baskı Öncesi',10,'Baskı Kalıpları',1,1),('Baskı Öncesi',10,'Baskı Sonrası İşlemler',1,1),('Baskı Öncesi',10,'Matbaa Teknik Resmi',1,1),('Baskı Öncesi',10,'İşletmelerde Mesleki Eğitim',32,32),
('Baskı Öncesi',11,'Din Kültürü ve Ahlak Bilgisi',2,2),('Baskı Öncesi',11,'Matematik',1,3),('Baskı Öncesi',11,'Türk Dili ve Edebiyatı',0,2),('Baskı Öncesi',11,'Vektörel Çizim',5,5),('Baskı Öncesi',11,'Görüntü İşleme',2,2),('Baskı Öncesi',11,'İşletmelerde Mesleki Eğitim',32,32),
('Baskı Öncesi',12,'Din Kültürü ve Ahlak Bilgisi',2,2),('Baskı Öncesi',12,'Matematik',0,3),('Baskı Öncesi',12,'Türk Dili ve Edebiyatı',0,3),('Baskı Öncesi',12,'Ahilik Kültürü ve Girişimcilik',1,1),('Baskı Öncesi',12,'Bilgisayardan Kalıba Çıkış',3,3),('Baskı Öncesi',12,'Dijital Baskı',2,2),('Baskı Öncesi',12,'Montaj',2,2),('Baskı Öncesi',12,'İşletmelerde Mesleki Eğitim',32,32)
), b(branch_name) as (values ('Baskı Öncesi'),('Baskı Sonrası'),('Dijital Baskı'),('Flekso Baskı'),('Ofset Baskı'),('Serigrafi Baskı'),('Tampon Baskı'),('Tifdruk Baskı')),
common as (select b.branch_name,x.grade_level,x.course_name,x.u_hour,x.d_hour from b cross join lateral (select grade_level,course_name,u_hour,d_hour from base where branch_name='Baskı Öncesi' and (grade_level<=10 or course_name in ('Din Kültürü ve Ahlak Bilgisi','Matematik','Türk Dili ve Edebiyatı','Ahilik Kültürü ve Girişimcilik','İşletmelerde Mesleki Eğitim'))) x),
dal(branch_name,grade_level,course_name,hour) as (values
('Baskı Öncesi',11,'Vektörel Çizim',5),('Baskı Öncesi',11,'Görüntü İşleme',2),('Baskı Öncesi',12,'Bilgisayardan Kalıba Çıkış',3),('Baskı Öncesi',12,'Dijital Baskı',2),('Baskı Öncesi',12,'Montaj',2),
('Ofset Baskı',11,'Ofset Baskı Teknikleri',7),('Ofset Baskı',12,'Montaj',2),('Ofset Baskı',12,'Kartonaj',2),('Ofset Baskı',12,'Ofsette Özel Baskılar',2),('Ofset Baskı',12,'Ofsette Farklı Baskı Teknikleri',1),
('Flekso Baskı',11,'Flekso Baskı Teknikleri',5),('Flekso Baskı',11,'Letterpress Baskı',2),('Flekso Baskı',12,'Ambalaj',3),('Flekso Baskı',12,'Kartonaj',2),('Flekso Baskı',12,'Montaj',2),
('Tifdruk Baskı',11,'Tifdruk Baskı Teknikleri',7),('Tifdruk Baskı',12,'Ambalaj',3),('Tifdruk Baskı',12,'Montaj',2),('Tifdruk Baskı',12,'Kartonaj',2),
('Serigrafi Baskı',11,'Serigrafi Baskı',5),('Serigrafi Baskı',11,'Serigrafi Kalıbı',2),('Serigrafi Baskı',12,'Serigrafide Özel Baskılar',4),('Serigrafi Baskı',12,'Promosyon Farklı Baskı Teknikleri',3),
('Tampon Baskı',11,'Tampon Baskı',5),('Tampon Baskı',11,'Tampon Kalıbı',2),('Tampon Baskı',12,'Serigrafide Özel Baskılar',4),('Tampon Baskı',12,'Promosyon Farklı Baskı Teknikleri',3),
('Dijital Baskı',11,'Dijital Baskı Teknikleri',4),('Dijital Baskı',11,'Bilgisayar Destekli Tasarım',3),('Dijital Baskı',12,'Montaj',2),('Dijital Baskı',12,'Kartonaj',2),('Dijital Baskı',12,'Promosyon Farklı Baskı Teknikleri',3),
('Baskı Sonrası',11,'Ciltleme',5),('Baskı Sonrası',11,'Endüstriyel Ciltleme',2),('Baskı Sonrası',12,'Ambalaj',3),('Baskı Sonrası',12,'Kartonaj',2),('Baskı Sonrası',12,'Baskı Sonrası Teknikleri',2)
), rows as (
select branch_name,grade_level,course_name,'USTALIK'::text variant,u_hour h from common where u_hour>0 union all select branch_name,grade_level,course_name,'DIPLOMA',d_hour from common where d_hour>0 union all select branch_name,grade_level,course_name,'USTALIK',hour from dal union all select branch_name,grade_level,course_name,'DIPLOMA',hour from dal
)
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',r.grade_level,c.id,case when r.course_name='İşletmelerde Mesleki Eğitim' then 'uygulama' when r.course_name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük') then 'zorunlu' else 'uygulama' end,array[r.h]::int[],1,false,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_matbaa_mem_cop.pdf','2021-33 yaşayan MESEM Matbaa Teknolojisi haftalık ders çizelgesi',true,'Matbaa Teknolojisi',r.branch_name,jsonb_build_object('source','MTEGM','decision','2021-33'),'2021-33','Haftalık Ders Çizelgesi',1.0,false,r.variant
from rows r join course_catalog c on c.name=r.course_name
where not exists(select 1 from official_course_schedule_catalog s where s.active and s.effective_academic_year='2026-2027' and s.school_type='MESEM' and coalesce(s.program_type,'')='MESEM' and s.field_name='Matbaa Teknolojisi' and s.branch_name=r.branch_name and s.grade_level=r.grade_level and s.schedule_variant=r.variant and s.course_id=c.id);
commit;