begin;
insert into public.course_catalog(name,category) values
('Harita Bilgisi','uygulama'),('Temel Mesleki Uygulamalar','uygulama'),('Medeni Hukuk','uygulama'),('Arazi Ölçme ve Hesapları','uygulama'),('Harita Hesapları','uygulama'),('Bilgisayarla Harita Çizimi','uygulama'),('İmar Uygulamaları','uygulama'),('Yol Uygulamaları','uygulama'),('Coğrafi Bilgi Sistemleri','uygulama'),('Kadastro','uygulama')
on conflict(name) do nothing;
with g as (select generate_series(9,12)::smallint grade_level), v as (select unnest(array['USTALIK','DIPLOMA']) schedule_variant)
insert into public.official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select '2026-2027','MESEM',null,'MESEM','Harita-Tapu-Kadastro','Harita Kadastro',g.grade_level,0,
case when v.schedule_variant='USTALIK' then case g.grade_level when 9 then 40 else 42 end else case g.grade_level when 9 then 42 when 10 then 44 when 11 then 46 else 48 end end,
0,0,0,case when g.grade_level=9 then 2 else 0 end,
case when v.schedule_variant='USTALIK' then 42 else case g.grade_level when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
case when v.schedule_variant='USTALIK' then 42 else case g.grade_level when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
case when v.schedule_variant='USTALIK' then 42 else case g.grade_level when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
'[]'::jsonb,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_harita_mem_cop.pdf','2021-33','Parantezli temel ders saatleri diploma programı için ilave fark dersleridir; ustalık ve diploma profilleri ayrı tutulur.',true,v.schedule_variant,
case when v.schedule_variant='USTALIK' then case g.grade_level when 9 then 6 when 10 then 6 when 11 then 3 else 2 end else case g.grade_level when 9 then 8 when 10 then 8 when 11 then 7 else 8 end end,
case g.grade_level when 9 then 2 when 10 then 4 when 11 then 7 else 8 end,0,case when g.grade_level=9 then 2 else 0 end,0,32,'CURRENTLY_VALID',8,'{"enterpriseDays":4,"enterpriseHoursPerDay":8,"parentheticalHoursMeaning":"DIPLOMA_ADDITIONAL_DIFFERENCE_COURSES"}'::jsonb,0
from g cross join v on conflict do nothing;
insert into public.official_course_schedule_catalog(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant,parsed_constraints)
select '2026-2027','MESEM',null,'MESEM','Harita-Tapu-Kadastro','Harita Kadastro',x.grade,c.id,x.category,array[x.h]::smallint[],1,true,null,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_harita_mem_cop.pdf','MTEGM 2021-33 Harita-Tapu-Kadastro MESEM Harita Kadastro',true,'2021-33',8,'Haftalık Ders Çizelgesi',1,false,x.variant,'{}'::jsonb
from (values
(9,'USTALIK','Türk Dili ve Edebiyatı','zorunlu',2),(9,'USTALIK','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(9,'USTALIK','Matematik','zorunlu',2),(9,'USTALIK','Harita Bilgisi','uygulama',2),(9,'USTALIK','İşletmelerde Mesleki Eğitim','uygulama',32),
(9,'DIPLOMA','Türk Dili ve Edebiyatı','zorunlu',2),(9,'DIPLOMA','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(9,'DIPLOMA','Matematik','zorunlu',2),(9,'DIPLOMA','Tarih','zorunlu',2),(9,'DIPLOMA','Harita Bilgisi','uygulama',2),(9,'DIPLOMA','İşletmelerde Mesleki Eğitim','uygulama',32),
(10,'USTALIK','Türk Dili ve Edebiyatı','zorunlu',2),(10,'USTALIK','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(10,'USTALIK','Matematik','zorunlu',2),(10,'USTALIK','Temel Mesleki Uygulamalar','uygulama',2),(10,'USTALIK','Medeni Hukuk','uygulama',2),(10,'USTALIK','İşletmelerde Mesleki Eğitim','uygulama',32),
(10,'DIPLOMA','Türk Dili ve Edebiyatı','zorunlu',2),(10,'DIPLOMA','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(10,'DIPLOMA','Matematik','zorunlu',2),(10,'DIPLOMA','T.C. İnkılap Tarihi ve Atatürkçülük','zorunlu',2),(10,'DIPLOMA','Temel Mesleki Uygulamalar','uygulama',2),(10,'DIPLOMA','Medeni Hukuk','uygulama',2),(10,'DIPLOMA','İşletmelerde Mesleki Eğitim','uygulama',32),
(11,'USTALIK','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(11,'USTALIK','Matematik','zorunlu',1),(11,'USTALIK','Arazi Ölçme ve Hesapları','uygulama',3),(11,'USTALIK','Harita Hesapları','uygulama',2),(11,'USTALIK','Bilgisayarla Harita Çizimi','uygulama',2),(11,'USTALIK','İşletmelerde Mesleki Eğitim','uygulama',32),
(11,'DIPLOMA','Türk Dili ve Edebiyatı','zorunlu',2),(11,'DIPLOMA','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(11,'DIPLOMA','Matematik','zorunlu',3),(11,'DIPLOMA','Arazi Ölçme ve Hesapları','uygulama',3),(11,'DIPLOMA','Harita Hesapları','uygulama',2),(11,'DIPLOMA','Bilgisayarla Harita Çizimi','uygulama',2),(11,'DIPLOMA','İşletmelerde Mesleki Eğitim','uygulama',32),
(12,'USTALIK','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(12,'USTALIK','Ahilik Kültürü ve Girişimcilik','uygulama',1),(12,'USTALIK','İmar Uygulamaları','uygulama',2),(12,'USTALIK','Yol Uygulamaları','uygulama',2),(12,'USTALIK','Coğrafi Bilgi Sistemleri','uygulama',1),(12,'USTALIK','Kadastro','uygulama',2),(12,'USTALIK','İşletmelerde Mesleki Eğitim','uygulama',32),
(12,'DIPLOMA','Türk Dili ve Edebiyatı','zorunlu',3),(12,'DIPLOMA','Din Kültürü ve Ahlak Bilgisi','zorunlu',2),(12,'DIPLOMA','Matematik','zorunlu',3),(12,'DIPLOMA','Ahilik Kültürü ve Girişimcilik','uygulama',1),(12,'DIPLOMA','İmar Uygulamaları','uygulama',2),(12,'DIPLOMA','Yol Uygulamaları','uygulama',2),(12,'DIPLOMA','Coğrafi Bilgi Sistemleri','uygulama',1),(12,'DIPLOMA','Kadastro','uygulama',2),(12,'DIPLOMA','İşletmelerde Mesleki Eğitim','uygulama',32)
) x(grade,variant,name,category,h) join public.course_catalog c on c.name=x.name
on conflict do nothing;
insert into supabase_migrations.schema_migrations(version,name) values ('20260825004500','mesem_harita_tapu_kadastro') on conflict(version) do nothing;
commit;
