DO $$
BEGIN
CREATE TEMP TABLE _re(g int,course text,h int) ON COMMIT DROP;
INSERT INTO _re VALUES (9,'Yenilenebilir Enerji Sistemleri',2),(10,'Teknik ve Meslek Resim',1),(10,'Ingot-Wafer İşletme ve Bakım',2),(10,'Tornalama (CNC-CAM)',1),(11,'Güneş Hücre Üretimi',4),(11,'Hücre Üretim Ekipmanlarında Bakım',2),(11,'Hidrolik-Pnömatik',1),(12,'Ahilik Kültürü ve Girişimcilik',1),(12,'Güneş Paneli Üretimi ve Bakımı',4),(12,'PLC Uygulamaları',3);
INSERT INTO course_catalog(name,category) SELECT DISTINCT course,'uygulama' FROM _re ON CONFLICT(name) DO NOTHING;
INSERT INTO official_curriculum_profiles(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
SELECT effective_academic_year,school_type,program_type,'Yenilenebilir Enerji Teknolojileri (Protokol Kapsamında)','Güneş Paneli Entegre Sistemleri',grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2023_yenilenebilirpro_mem_cop.pdf','2023-17','2023-17 Protokol Kapsamındaki Okullar için MESEM Yenilenebilir Enerji Teknolojileri çizelgesi.',true,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,'CURRENTLY_VALID',5,parsed_constraints,academic_support_hours FROM official_curriculum_profiles WHERE school_type='MESEM' AND field_name='Siber Güvenlik' AND branch_name='Siber Güvenlik' AND active ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_decision_date,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2023_yenilenebilirpro_mem_cop.pdf','2023-17 Protokol MESEM Yenilenebilir Enerji Teknolojileri.',true,'Yenilenebilir Enerji Teknolojileri (Protokol Kapsamında)','Güneş Paneli Entegre Sistemleri',s.parsed_constraints,s.school_subtype,'2023-17',s.source_decision_date,5,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant FROM official_course_schedule_catalog s WHERE s.field_name='Siber Güvenlik' AND s.branch_name='Siber Güvenlik' AND s.active AND (s.category='zorunlu' OR EXISTS(SELECT 1 FROM course_catalog c WHERE c.id=s.course_id AND c.name='İşletmelerde Mesleki Eğitim')) ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT '2026-2027','MESEM','MESEM',r.g,c.id,'uygulama',ARRAY[r.h],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2023_yenilenebilirpro_mem_cop.pdf','2023-17 Protokol MESEM Yenilenebilir Enerji Teknolojileri.',true,'Yenilenebilir Enerji Teknolojileri (Protokol Kapsamında)','Güneş Paneli Entegre Sistemleri','[]'::jsonb,'2023-17',5,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant FROM _re r JOIN course_catalog c ON c.name=r.course CROSS JOIN (VALUES('USTALIK'),('DIPLOMA')) v(schedule_variant) ON CONFLICT DO NOTHING;
END $$;