DO $$
DECLARE src text:='https://meslek.meb.gov.tr/upload/cop9_mem/2021_ulastirma_mem_cop.pdf'; vv_variant text; vv_grade int; vv_course text; vv_hours int;
BEGIN
FOR vv_course,vv_hours IN SELECT * FROM (VALUES ('Ulaştırmaya Giriş',2),('Temel Lojistik',1),('Depo Yönetimi',2),('Dağıtım',1),('Ofis Programları',2),('Ahilik Kültürü ve Girişimcilik',1),('Taşıma Modelleri',4),('Lojistik Satın Alma',1),('Lojistik Paket Programları',3),('Gümrük',4))x LOOP INSERT INTO course_catalog(name,category) VALUES(vv_course,'uygulama') ON CONFLICT(name) DO NOTHING; END LOOP;
INSERT INTO official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
SELECT p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,'Ulaştırma Hizmetleri','Lojistik',p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,src,'2021-33','2021-33 yaşayan MESEM Ulaştırma Hizmetleri Lojistik çizelgesi; diğer iki 2025 dal için yayımlanmış MESEM çizelgesi doğrulanamadı.',true,p.schedule_variant,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,'CURRENTLY_VALID',7,p.parsed_constraints,p.academic_support_hours
FROM (SELECT DISTINCT ON(grade_level,schedule_variant) * FROM official_curriculum_profiles WHERE active AND school_type='MESEM' AND source_decision_no='2021-33' AND field_name='Tekstil Teknolojisi' ORDER BY grade_level,schedule_variant) p ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,school_subtype,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT s.effective_academic_year,s.school_type,s.school_subtype,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,src,'2021-33 Ulaştırma Lojistik',true,'Ulaştırma Hizmetleri','Lojistik',s.parsed_constraints,'2021-33',7,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant
FROM official_course_schedule_catalog s JOIN course_catalog cc ON cc.id=s.course_id WHERE s.active AND s.school_type='MESEM' AND s.field_name='Tekstil Teknolojisi' AND s.branch_name='Dokuma Operatörlüğü' AND (s.category='zorunlu' OR cc.name='İşletmelerde Mesleki Eğitim') ON CONFLICT DO NOTHING;
FOR vv_variant IN SELECT unnest(ARRAY['USTALIK','DIPLOMA']) LOOP
 FOR vv_grade,vv_course,vv_hours IN SELECT * FROM (VALUES (9,'Ulaştırmaya Giriş',2),(10,'Temel Lojistik',1),(10,'Depo Yönetimi',2),(10,'Dağıtım',1),(11,'Ofis Programları',2),(11,'Taşıma Modelleri',4),(11,'Lojistik Satın Alma',1),(12,'Ahilik Kültürü ve Girişimcilik',1),(12,'Lojistik Paket Programları',3),(12,'Gümrük',4))q LOOP
  INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,source_file_name,source_note,active,field_name,branch_name,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
  SELECT '2026-2027','MESEM','MESEM',vv_grade,id,'uygulama',ARRAY[vv_hours],src,'2021-33 Ulaştırma Lojistik',true,'Ulaştırma Hizmetleri','Lojistik','2021-33',7,'HAFTALIK DERS ÇİZELGESİ',1,false,vv_variant FROM course_catalog WHERE name=vv_course ON CONFLICT DO NOTHING;
 END LOOP;
END LOOP;
END $$;