begin;
with br(branch_name,page) as (values
('İplik Üretim Teknolojisi',8),('Dokuma Operatörlüğü',9),('Endüstriyel Düz Örme',10),('Endüstriyel Yuvarlak Örme',11),('Endüstriyel Çorap Örme',12),('Tekstil Baskı ve Desenciliği',13),('Tekstil Boyacılığı',14),('Tekstil Bitim İşlemleri (Apre)',15),('Dokusuz Yüzeyler',16))
insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,updated_at,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,'Tekstil Teknolojisi',br.branch_name,p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_tekstil_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Tekstil Teknolojisi çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,now(),p.schedule_variant,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,p.applicability_status,br.page,p.parsed_constraints,p.academic_support_hours
from official_curriculum_profiles p cross join br
where p.active and p.school_type='MESEM' and p.field_name='Makine Teknolojisi' and p.branch_name='Anahtarcılık ve Çilingirlik'
and not exists(select 1 from official_curriculum_profiles x where x.effective_academic_year=p.effective_academic_year and x.school_type='MESEM' and coalesce(x.school_subtype,'')=coalesce(p.school_subtype,'') and coalesce(x.program_type,'')=coalesce(p.program_type,'') and x.field_name='Tekstil Teknolojisi' and x.branch_name=br.branch_name and x.grade_level=p.grade_level and x.schedule_variant=p.schedule_variant);

with br(branch_name,page) as (values
('İplik Üretim Teknolojisi',8),('Dokuma Operatörlüğü',9),('Endüstriyel Düz Örme',10),('Endüstriyel Yuvarlak Örme',11),('Endüstriyel Çorap Örme',12),('Tekstil Baskı ve Desenciliği',13),('Tekstil Boyacılığı',14),('Tekstil Bitim İşlemleri (Apre)',15),('Dokusuz Yüzeyler',16))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,imported_at,updated_at,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_decision_date,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_tekstil_mem_cop.pdf','2021-33 yaşayan MESEM Tekstil Teknolojisi çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,now(),now(),'Tekstil Teknolojisi',br.branch_name,s.parsed_constraints,s.school_subtype,'2021-33',null,br.page,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant
from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id cross join br
where s.active and s.school_type='MESEM' and s.field_name='Makine Teknolojisi' and s.branch_name='Anahtarcılık ve Çilingirlik' and (s.category='zorunlu' or c.name='İşletmelerde Mesleki Eğitim')
and not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year=s.effective_academic_year and x.school_type='MESEM' and x.field_name='Tekstil Teknolojisi' and x.branch_name=br.branch_name and x.grade_level=s.grade_level and x.schedule_variant=s.schedule_variant and x.course_id=s.course_id);

with a(grade_level,name,h) as (values (9,'Tekstil Mesleğine Giriş',2),(10,'Tekstil Lifleri',1),(10,'Temel Tekstil Uygulamaları',3),(12,'Ahilik Kültürü ve Girişimcilik',1))
insert into course_catalog(name,category) select distinct name,'uygulama' from a on conflict(name) do nothing;

with br(branch_name,page) as (values
('İplik Üretim Teknolojisi',8),('Dokuma Operatörlüğü',9),('Endüstriyel Düz Örme',10),('Endüstriyel Yuvarlak Örme',11),('Endüstriyel Çorap Örme',12),('Tekstil Baskı ve Desenciliği',13),('Tekstil Boyacılığı',14),('Tekstil Bitim İşlemleri (Apre)',15),('Dokusuz Yüzeyler',16)),a(grade_level,name,h) as (values (9,'Tekstil Mesleğine Giriş',2),(10,'Tekstil Lifleri',1),(10,'Temel Tekstil Uygulamaları',3),(12,'Ahilik Kültürü ve Girişimcilik',1)),v(schedule_variant) as (values('USTALIK'),('DIPLOMA'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,imported_at,updated_at,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',a.grade_level,c.id,'uygulama',array[a.h],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_tekstil_mem_cop.pdf','2021-33 yaşayan MESEM Tekstil Teknolojisi çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,now(),now(),'Tekstil Teknolojisi',br.branch_name,'{"enterpriseDays":4,"enterpriseHoursPerDay":8}'::jsonb,'2021-33',br.page,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant
from a join course_catalog c on c.name=a.name cross join br cross join v
where not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year='2026-2027' and x.school_type='MESEM' and x.field_name='Tekstil Teknolojisi' and x.branch_name=br.branch_name and x.grade_level=a.grade_level and x.schedule_variant=v.schedule_variant and x.course_id=c.id);

with d(branch_name,grade_level,name,h,page) as (values
('İplik Üretim Teknolojisi',11,'Pamuk İplik Üretimi / Yün İplik Üretimi / Yapay İplik Üretimi / Fantezi İplik Üretimi',5,8),('İplik Üretim Teknolojisi',11,'İplik Üretiminde Kontroller',2,8),('İplik Üretim Teknolojisi',12,'İplik Üretiminde Bitim İşlemleri',3,8),('İplik Üretim Teknolojisi',12,'İplikte Farklı Üretim Sistemleri',2,8),('İplik Üretim Teknolojisi',12,'İplik Üretim Hesapları',2,8),
('Dokuma Operatörlüğü',11,'Dokuma Örgüleri',3,9),('Dokuma Operatörlüğü',11,'Dokumaya Hazırlık',2,9),('Dokuma Operatörlüğü',11,'Numune Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Özel Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Dokuma Makinelerinin Sistemleri',3,9),
('Endüstriyel Düz Örme',11,'Düz Örmede Analiz ve Desen',2,10),('Endüstriyel Düz Örme',11,'Düz Örme Makineleri',2,10),('Endüstriyel Düz Örme',11,'Düz Örme Giysi Kalıpları',1,10),('Endüstriyel Düz Örme',11,'Düz Örmede Model Geliştirme',2,10),('Endüstriyel Düz Örme',12,'Düz Örmede Giysi Üretimi',1,10),('Endüstriyel Düz Örme',12,'Örmede Kalite Kontrol',2,10),('Endüstriyel Düz Örme',12,'Örme Üretiminin Takibi',1,10),('Endüstriyel Düz Örme',12,'Örme Kumaşın Analizi',2,10),('Endüstriyel Düz Örme',12,'Örmede Meslek Hesapları',1,10),
('Endüstriyel Yuvarlak Örme',11,'Yuvarlak Örme Makineleri',4,11),('Endüstriyel Yuvarlak Örme',11,'Örme Üretiminin Takibi',1,11),('Endüstriyel Yuvarlak Örme',11,'Örmede Meslek Hesapları',2,11),('Endüstriyel Yuvarlak Örme',12,'Yuvarlak Örmede Analiz ve Desen',4,11),('Endüstriyel Yuvarlak Örme',12,'Örmede Kalite Kontrol',2,11),('Endüstriyel Yuvarlak Örme',12,'Örme Kumaşın Analizi',1,11),
('Endüstriyel Çorap Örme',11,'Çorap Örmede Analiz ve Desen',3,12),('Endüstriyel Çorap Örme',11,'Çorap Örme Makineleri',1,12),('Endüstriyel Çorap Örme',11,'Örmede Kalite Kontrol',2,12),('Endüstriyel Çorap Örme',11,'Örme Üretiminin Takibi',1,12),('Endüstriyel Çorap Örme',12,'Çorap Örmede Bitim İşlemleri',2,12),('Endüstriyel Çorap Örme',12,'Çorap Örmede Model Geliştirme',2,12),('Endüstriyel Çorap Örme',12,'Örme Kumaşın Analizi',2,12),('Endüstriyel Çorap Örme',12,'Örmede Meslek Hesapları',1,12),
('Tekstil Baskı ve Desenciliği',11,'Baskı Teknikleri',5,13),('Tekstil Baskı ve Desenciliği',11,'Baskı Kimyası',2,13),('Tekstil Baskı ve Desenciliği',12,'Baskı Makineleri',3,13),('Tekstil Baskı ve Desenciliği',12,'Baskı Deseni Hazırlama',2,13),('Tekstil Baskı ve Desenciliği',12,'Özel Baskılar',2,13),
('Tekstil Boyacılığı',11,'Ön Terbiye İşlemleri',5,14),('Tekstil Boyacılığı',11,'Boyama ve Apre Kimyası',2,14),('Tekstil Boyacılığı',12,'Boyama Teknikleri',4,14),('Tekstil Boyacılığı',12,'Boyama Teknolojisi',3,14),
('Tekstil Bitim İşlemleri (Apre)',11,'Genel Apre Uygulamaları',7,15),('Tekstil Bitim İşlemleri (Apre)',12,'Protein ve Sentetik Apreleri',3,15),('Tekstil Bitim İşlemleri (Apre)',12,'Selüloza Özel Apreler',2,15),('Tekstil Bitim İşlemleri (Apre)',12,'Boyama ve Apre Kimyası',2,15),
('Dokusuz Yüzeyler',11,'Dokusuz Yüzeylere Hazırlık',5,16),('Dokusuz Yüzeyler',11,'Tafting Yüzeyler',2,16),('Dokusuz Yüzeyler',12,'Doku Oluşturma',4,16),('Dokusuz Yüzeyler',12,'Bağlama Sonrası İşlemler',2,16),('Dokusuz Yüzeyler',12,'Üretim Kontrolleri',1,16))
insert into course_catalog(name,category) select distinct name,'uygulama' from d on conflict(name) do nothing;

with d(branch_name,grade_level,name,h,page) as (values
('İplik Üretim Teknolojisi',11,'Pamuk İplik Üretimi / Yün İplik Üretimi / Yapay İplik Üretimi / Fantezi İplik Üretimi',5,8),('İplik Üretim Teknolojisi',11,'İplik Üretiminde Kontroller',2,8),('İplik Üretim Teknolojisi',12,'İplik Üretiminde Bitim İşlemleri',3,8),('İplik Üretim Teknolojisi',12,'İplikte Farklı Üretim Sistemleri',2,8),('İplik Üretim Teknolojisi',12,'İplik Üretim Hesapları',2,8),
('Dokuma Operatörlüğü',11,'Dokuma Örgüleri',3,9),('Dokuma Operatörlüğü',11,'Dokumaya Hazırlık',2,9),('Dokuma Operatörlüğü',11,'Numune Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Özel Kumaş Dokuma',2,9),('Dokuma Operatörlüğü',12,'Dokuma Makinelerinin Sistemleri',3,9),
('Endüstriyel Düz Örme',11,'Düz Örmede Analiz ve Desen',2,10),('Endüstriyel Düz Örme',11,'Düz Örme Makineleri',2,10),('Endüstriyel Düz Örme',11,'Düz Örme Giysi Kalıpları',1,10),('Endüstriyel Düz Örme',11,'Düz Örmede Model Geliştirme',2,10),('Endüstriyel Düz Örme',12,'Düz Örmede Giysi Üretimi',1,10),('Endüstriyel Düz Örme',12,'Örmede Kalite Kontrol',2,10),('Endüstriyel Düz Örme',12,'Örme Üretiminin Takibi',1,10),('Endüstriyel Düz Örme',12,'Örme Kumaşın Analizi',2,10),('Endüstriyel Düz Örme',12,'Örmede Meslek Hesapları',1,10),
('Endüstriyel Yuvarlak Örme',11,'Yuvarlak Örme Makineleri',4,11),('Endüstriyel Yuvarlak Örme',11,'Örme Üretiminin Takibi',1,11),('Endüstriyel Yuvarlak Örme',11,'Örmede Meslek Hesapları',2,11),('Endüstriyel Yuvarlak Örme',12,'Yuvarlak Örmede Analiz ve Desen',4,11),('Endüstriyel Yuvarlak Örme',12,'Örmede Kalite Kontrol',2,11),('Endüstriyel Yuvarlak Örme',12,'Örme Kumaşın Analizi',1,11),
('Endüstriyel Çorap Örme',11,'Çorap Örmede Analiz ve Desen',3,12),('Endüstriyel Çorap Örme',11,'Çorap Örme Makineleri',1,12),('Endüstriyel Çorap Örme',11,'Örmede Kalite Kontrol',2,12),('Endüstriyel Çorap Örme',11,'Örme Üretiminin Takibi',1,12),('Endüstriyel Çorap Örme',12,'Çorap Örmede Bitim İşlemleri',2,12),('Endüstriyel Çorap Örme',12,'Çorap Örmede Model Geliştirme',2,12),('Endüstriyel Çorap Örme',12,'Örme Kumaşın Analizi',2,12),('Endüstriyel Çorap Örme',12,'Örmede Meslek Hesapları',1,12),
('Tekstil Baskı ve Desenciliği',11,'Baskı Teknikleri',5,13),('Tekstil Baskı ve Desenciliği',11,'Baskı Kimyası',2,13),('Tekstil Baskı ve Desenciliği',12,'Baskı Makineleri',3,13),('Tekstil Baskı ve Desenciliği',12,'Baskı Deseni Hazırlama',2,13),('Tekstil Baskı ve Desenciliği',12,'Özel Baskılar',2,13),
('Tekstil Boyacılığı',11,'Ön Terbiye İşlemleri',5,14),('Tekstil Boyacılığı',11,'Boyama ve Apre Kimyası',2,14),('Tekstil Boyacılığı',12,'Boyama Teknikleri',4,14),('Tekstil Boyacılığı',12,'Boyama Teknolojisi',3,14),
('Tekstil Bitim İşlemleri (Apre)',11,'Genel Apre Uygulamaları',7,15),('Tekstil Bitim İşlemleri (Apre)',12,'Protein ve Sentetik Apreleri',3,15),('Tekstil Bitim İşlemleri (Apre)',12,'Selüloza Özel Apreler',2,15),('Tekstil Bitim İşlemleri (Apre)',12,'Boyama ve Apre Kimyası',2,15),
('Dokusuz Yüzeyler',11,'Dokusuz Yüzeylere Hazırlık',5,16),('Dokusuz Yüzeyler',11,'Tafting Yüzeyler',2,16),('Dokusuz Yüzeyler',12,'Doku Oluşturma',4,16),('Dokusuz Yüzeyler',12,'Bağlama Sonrası İşlemler',2,16),('Dokusuz Yüzeyler',12,'Üretim Kontrolleri',1,16)),v(schedule_variant) as (values('USTALIK'),('DIPLOMA'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,imported_at,updated_at,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',d.grade_level,c.id,'uygulama',array[d.h],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2021_tekstil_mem_cop.pdf','2021-33 yaşayan MESEM Tekstil Teknolojisi çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,now(),now(),'Tekstil Teknolojisi',d.branch_name,'{"enterpriseDays":4,"enterpriseHoursPerDay":8}'::jsonb,'2021-33',d.page,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant
from d join course_catalog c on c.name=d.name cross join v
where not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year='2026-2027' and x.school_type='MESEM' and x.field_name='Tekstil Teknolojisi' and x.branch_name=d.branch_name and x.grade_level=d.grade_level and x.schedule_variant=v.schedule_variant and x.course_id=c.id);
commit;