do $$
declare src text:='https://meslek.meb.gov.tr/upload/cop11_mem/2021_muzik_mem_cop.pdf'; b text; bra text[]:=array['Mızraplı Halk Müziği Enstrümanları Yapımı','Mızraplı Sanat Müziği Enstrümanları Yapımı','Mızraplı Batı Müziği Enstrümanları Yapımı','Yaylı Enstrüman Yapımı'];
begin
foreach b in array bra loop
 insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
 select s.effective_academic_year,s.school_type,s.school_subtype,s.program_type,'Müzik Aletleri Yapımı',b,s.grade_level,s.required_course_count,s.required_hour_total,s.elective_course_min,s.elective_course_max,s.elective_hour_min,s.elective_hour_max,s.total_hour_min,s.total_hour_max,s.total_hour_target,s.group_rules,src,'2021-33','2021-33 yaşayan MESEM Müzik Aletleri Yapımı çizelgesi; parantezli temel ders saatleri DIPLOMA fark dersidir.',true,s.schedule_variant,s.common_hours,s.vocational_hours,s.elective_vocational_hours,s.elective_hours,s.guidance_hours,s.enterprise_hours,'CURRENTLY_VALID',case b when 'Mızraplı Halk Müziği Enstrümanları Yapımı' then 7 when 'Mızraplı Sanat Müziği Enstrümanları Yapımı' then 8 when 'Mızraplı Batı Müziği Enstrümanları Yapımı' then 9 else 10 end,s.parsed_constraints,s.academic_support_hours
 from official_curriculum_profiles s where s.active and s.school_type='MESEM' and s.field_name='Muhasebe ve Finansman' and s.branch_name='Muhasebe'
 and not exists(select 1 from official_curriculum_profiles x where x.active and x.effective_academic_year=s.effective_academic_year and x.school_type='MESEM' and coalesce(x.school_subtype,'')=coalesce(s.school_subtype,'') and coalesce(x.program_type,'')=coalesce(s.program_type,'') and x.field_name='Müzik Aletleri Yapımı' and x.branch_name=b and x.grade_level=s.grade_level and coalesce(x.schedule_variant,'STANDARD')=coalesce(s.schedule_variant,'STANDARD'));
end loop;
insert into course_catalog(name,category,active)
select n,'uygulama',true from unnest(array['Çalgı Yapımına Hazırlık','Temel Çalgı Yapım Teknikleri','Müzik Aletleri Teknik Resmi','Temel Müzik Kavramları','Ahilik Kültürü ve Girişimcilik','Bağlama Yapımı','Çalgı Bilgisi ve Akort Uygulamaları','Ritim ve Ezgi Uygulamaları','Bilgisayar Destekli Çizim','Oyma Cura Yapımı','Çalgı Bakım Onarım','Çalgı Süslemeciliği','Ut Yapımı','Tambur Yapımı','Klasik Gitar Yapımı','Mandolin Yapımı','Keman Yapımı','Klasik Kemençe Yapımı']) n where not exists(select 1 from course_catalog c where c.name=n);
insert into official_course_schedule_catalog(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,source_decision_no,source_page,parsed_constraints,needs_review,schedule_variant)
select p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,p.field_name,p.branch_name,p.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,src,p.source_note,true,'2021-33',p.source_page,s.parsed_constraints,false,p.schedule_variant
from official_curriculum_profiles p join official_curriculum_profiles sp on sp.active and sp.school_type='MESEM' and sp.field_name='Muhasebe ve Finansman' and sp.branch_name='Muhasebe' and sp.grade_level=p.grade_level and sp.schedule_variant=p.schedule_variant join official_course_schedule_catalog s on s.active and s.school_type='MESEM' and s.field_name='Muhasebe ve Finansman' and s.branch_name='Muhasebe' and s.grade_level=sp.grade_level and s.schedule_variant=sp.schedule_variant join course_catalog c on c.id=s.course_id
where p.active and p.school_type='MESEM' and p.field_name='Müzik Aletleri Yapımı' and (s.category='zorunlu' or c.name='İşletmelerde Mesleki Eğitim') and not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year=p.effective_academic_year and x.school_type=p.school_type and coalesce(x.school_subtype,'')=coalesce(p.school_subtype,'') and coalesce(x.program_type,'')=coalesce(p.program_type,'') and coalesce(x.field_name,'')=p.field_name and coalesce(x.branch_name,'')=p.branch_name and x.grade_level=p.grade_level and x.course_id=s.course_id and coalesce(x.schedule_variant,'STANDARD')=coalesce(p.schedule_variant,'STANDARD'));
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,course_id,category,hour_options,source_file_name,source_note,active,source_decision_no,source_page,parsed_constraints,needs_review,schedule_variant)
select p.effective_academic_year,'MESEM','MESEM','Müzik Aletleri Yapımı',p.branch_name,p.grade_level,c.id,'uygulama',array[v.h],src,p.source_note,true,'2021-33',p.source_page,'[]'::jsonb,false,p.schedule_variant
from official_curriculum_profiles p join lateral (select * from (values
(9,'*','Çalgı Yapımına Hazırlık',2),(10,'*','Temel Çalgı Yapım Teknikleri',2),(10,'*','Müzik Aletleri Teknik Resmi',1),(10,'*','Temel Müzik Kavramları',1),(12,'*','Ahilik Kültürü ve Girişimcilik',1),
(11,'Mızraplı Halk Müziği Enstrümanları Yapımı','Bağlama Yapımı',2),(11,'Mızraplı Halk Müziği Enstrümanları Yapımı','Çalgı Bilgisi ve Akort Uygulamaları',1),(11,'Mızraplı Halk Müziği Enstrümanları Yapımı','Ritim ve Ezgi Uygulamaları',2),(11,'Mızraplı Halk Müziği Enstrümanları Yapımı','Bilgisayar Destekli Çizim',2),(12,'Mızraplı Halk Müziği Enstrümanları Yapımı','Oyma Cura Yapımı',2),(12,'Mızraplı Halk Müziği Enstrümanları Yapımı','Çalgı Bakım Onarım',3),(12,'Mızraplı Halk Müziği Enstrümanları Yapımı','Çalgı Süslemeciliği',2),
(11,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Ut Yapımı',2),(11,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Çalgı Bilgisi ve Akort Uygulamaları',1),(11,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Ritim ve Ezgi Uygulamaları',2),(11,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Bilgisayar Destekli Çizim',2),(12,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Tambur Yapımı',2),(12,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Çalgı Bakım Onarım',3),(12,'Mızraplı Sanat Müziği Enstrümanları Yapımı','Çalgı Süslemeciliği',2),
(11,'Mızraplı Batı Müziği Enstrümanları Yapımı','Klasik Gitar Yapımı',2),(11,'Mızraplı Batı Müziği Enstrümanları Yapımı','Çalgı Bilgisi ve Akort Uygulamaları',1),(11,'Mızraplı Batı Müziği Enstrümanları Yapımı','Ritim ve Ezgi Uygulamaları',2),(11,'Mızraplı Batı Müziği Enstrümanları Yapımı','Bilgisayar Destekli Çizim',2),(12,'Mızraplı Batı Müziği Enstrümanları Yapımı','Mandolin Yapımı',2),(12,'Mızraplı Batı Müziği Enstrümanları Yapımı','Çalgı Bakım Onarım',3),(12,'Mızraplı Batı Müziği Enstrümanları Yapımı','Çalgı Süslemeciliği',2),
(11,'Yaylı Enstrüman Yapımı','Keman Yapımı',2),(11,'Yaylı Enstrüman Yapımı','Çalgı Bilgisi ve Akort Uygulamaları',1),(11,'Yaylı Enstrüman Yapımı','Ritim ve Ezgi Uygulamaları',2),(11,'Yaylı Enstrüman Yapımı','Bilgisayar Destekli Çizim',2),(12,'Yaylı Enstrüman Yapımı','Klasik Kemençe Yapımı',2),(12,'Yaylı Enstrüman Yapımı','Çalgı Bakım Onarım',3),(12,'Yaylı Enstrüman Yapımı','Çalgı Süslemeciliği',2))t(g,br,n,h) where t.g=p.grade_level and (t.br='*' or t.br=p.branch_name)) v on true join course_catalog c on c.name=v.n
where p.active and p.school_type='MESEM' and p.field_name='Müzik Aletleri Yapımı' and not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year=p.effective_academic_year and x.school_type='MESEM' and coalesce(x.program_type,'')='MESEM' and coalesce(x.field_name,'')='Müzik Aletleri Yapımı' and coalesce(x.branch_name,'')=p.branch_name and x.grade_level=p.grade_level and x.course_id=c.id and coalesce(x.schedule_variant,'STANDARD')=coalesce(p.schedule_variant,'STANDARD'));
end $$;