begin;
insert into course_catalog(name,category)
select x,'uygulama' from unnest(array['Temel Metal Şekillendirme Teknolojisi','Teknik Resim','Temel Kaynak İşlemleri','Ark Kaynak Teknikleri','Oksigaz Kaynağı','Metal Yüzey ve Muayene İşlemleri','Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme','İleri Ark Kaynak Teknikleri','Temel Elektrik','Metal Doğrama İşlemleri','Doğrama Resmi ve İmalatı','Çelik Yapılandırma','İleri Düzeyde Metal İşleme','Sıcak Şekillendirme','Isıl İşlem Teknikleri','Avize İmalat Teknikleri','Metal Levha İşleme','Tabela','Boya Tekniği','Plaket ve Damga','Sipariş Alma','Serigrafi Baskıya Hazırlık ve Baskı','Aydınlatma Teknolojisi','Ahşap Yapım Teknikleri','Temel Yüzey ve Boya İşlemleri','Metal Yüzey Boya Uygulamaları','Metal Yüzey Boya İşlemleri','Renklendirme ve Boyama','Boya Ekipmanları Bakım ve Onarımı']) x on conflict(name) do nothing;
with b(branch_name) as (values ('Avizecilik'),('Çelik Konstrüksiyon'),('Endüstriyel Reklam Tabelacılığı'),('Isıl İşlem'),('Karosercilik'),('Kaynakçılık'),('Metal Doğrama'),('Metal Levha İşlemeciliği'),('Metal Yüzey Boyama'),('Sac İşleri')),
g(grade_level,ch,vh,eh,imh,ur,dr,ut,dt) as (values (9,6,2,2,32,40,42,42,44),(10,6,4,0,32,42,44,42,44),(11,3,7,0,32,42,46,42,46),(12,2,8,0,32,42,48,42,48)),v(schedule_variant) as (values ('USTALIK'),('DIPLOMA'))
insert into official_curriculum_profiles(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_hours,enterprise_hours,applicability_status,parsed_constraints)
select '2026-2027','MESEM','MESEM','Metal Teknolojisi',b.branch_name,g.grade_level,0,case when v.schedule_variant='USTALIK' then ur else dr end,case when eh>0 then 1 else 0 end,case when eh>0 then 1 else 0 end,eh,eh,case when v.schedule_variant='USTALIK' then ut else dt end,case when v.schedule_variant='USTALIK' then ut else dt end,case when v.schedule_variant='USTALIK' then ut else dt end,'https://meslek.meb.gov.tr/upload/cop10_mem/2022_metal_mem_cop.pdf','2022-33','2022-33 yaşayan MESEM Metal Teknolojisi çizelgesi; parantezli temel ders saatleri DIPLOMA fark dersidir.',true,v.schedule_variant,case when v.schedule_variant='USTALIK' then ch else case grade_level when 9 then 8 when 10 then 8 when 11 then 7 else 8 end end,vh,eh,imh,'ACTIVE',jsonb_build_object('source','MTEGM','decision','2022-33') from b cross join g cross join v where not exists(select 1 from official_curriculum_profiles p where p.effective_academic_year='2026-2027' and p.school_type='MESEM' and coalesce(p.program_type,'')='MESEM' and p.field_name='Metal Teknolojisi' and p.branch_name=b.branch_name and p.grade_level=g.grade_level and p.schedule_variant=v.schedule_variant);
with b(branch_name) as (values ('Avizecilik'),('Çelik Konstrüksiyon'),('Endüstriyel Reklam Tabelacılığı'),('Isıl İşlem'),('Karosercilik'),('Kaynakçılık'),('Metal Doğrama'),('Metal Levha İşlemeciliği'),('Metal Yüzey Boyama'),('Sac İşleri')),
common0(grade_level,course_name,u,d) as (values (9,'Türk Dili ve Edebiyatı',2,2),(9,'Din Kültürü ve Ahlak Bilgisi',2,2),(9,'Matematik',2,2),(9,'Tarih',0,2),(9,'Temel Metal Şekillendirme Teknolojisi',2,2),(9,'İşletmelerde Mesleki Eğitim',32,32),(10,'Türk Dili ve Edebiyatı',2,2),(10,'Din Kültürü ve Ahlak Bilgisi',2,2),(10,'Matematik',2,2),(10,'T.C. İnkılap Tarihi ve Atatürkçülük',0,2),(10,'Teknik Resim',2,2),(10,'Temel Kaynak İşlemleri',2,2),(10,'İşletmelerde Mesleki Eğitim',32,32),(11,'Din Kültürü ve Ahlak Bilgisi',2,2),(11,'Matematik',1,3),(11,'Türk Dili ve Edebiyatı',0,2),(11,'İşletmelerde Mesleki Eğitim',32,32),(12,'Din Kültürü ve Ahlak Bilgisi',2,2),(12,'Matematik',0,3),(12,'Türk Dili ve Edebiyatı',0,3),(12,'Ahilik Kültürü ve Girişimcilik',1,1),(12,'İşletmelerde Mesleki Eğitim',32,32)),
common as (select b.branch_name,c.* from b cross join common0 c),
dal(branch_name,grade_level,course_name,h) as (values
('Kaynakçılık',11,'Ark Kaynak Teknikleri',3),('Kaynakçılık',11,'Oksigaz Kaynağı',2),('Kaynakçılık',11,'Metal Yüzey ve Muayene İşlemleri',2),('Kaynakçılık',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Kaynakçılık',12,'İleri Ark Kaynak Teknikleri',3),('Kaynakçılık',12,'Temel Elektrik',1),
('Metal Doğrama',11,'Ark Kaynak Teknikleri',3),('Metal Doğrama',11,'Metal Doğrama İşlemleri',2),('Metal Doğrama',11,'Metal Yüzey ve Muayene İşlemleri',2),('Metal Doğrama',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Metal Doğrama',12,'Doğrama Resmi ve İmalatı',3),('Metal Doğrama',12,'Temel Elektrik',1),
('Çelik Konstrüksiyon',11,'Ark Kaynak Teknikleri',3),('Çelik Konstrüksiyon',11,'Metal Doğrama İşlemleri',2),('Çelik Konstrüksiyon',11,'Metal Yüzey ve Muayene İşlemleri',2),('Çelik Konstrüksiyon',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Çelik Konstrüksiyon',12,'Çelik Yapılandırma',2),('Çelik Konstrüksiyon',12,'İleri Düzeyde Metal İşleme',1),('Çelik Konstrüksiyon',12,'Temel Elektrik',1),
('Isıl İşlem',11,'Sıcak Şekillendirme',3),('Isıl İşlem',11,'Metal Doğrama İşlemleri',2),('Isıl İşlem',11,'Metal Yüzey ve Muayene İşlemleri',2),('Isıl İşlem',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Isıl İşlem',12,'Isıl İşlem Teknikleri',3),('Isıl İşlem',12,'Temel Elektrik',1),
('Avizecilik',11,'Metal Doğrama İşlemleri',2),('Avizecilik',11,'Metal Yüzey ve Muayene İşlemleri',2),('Avizecilik',11,'Avize İmalat Teknikleri',3),('Avizecilik',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Avizecilik',12,'Metal Levha İşleme',3),('Avizecilik',12,'Temel Elektrik',1),
('Endüstriyel Reklam Tabelacılığı',11,'Tabela',2),('Endüstriyel Reklam Tabelacılığı',11,'Boya Tekniği',2),('Endüstriyel Reklam Tabelacılığı',11,'Plaket ve Damga',2),('Endüstriyel Reklam Tabelacılığı',11,'Sipariş Alma',1),('Endüstriyel Reklam Tabelacılığı',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Endüstriyel Reklam Tabelacılığı',12,'Serigrafi Baskıya Hazırlık ve Baskı',2),('Endüstriyel Reklam Tabelacılığı',12,'Dijital Baskı',1),('Endüstriyel Reklam Tabelacılığı',12,'Aydınlatma Teknolojisi',1),
('Karosercilik',11,'Ark Kaynak Teknikleri',3),('Karosercilik',11,'Metal Doğrama İşlemleri',2),('Karosercilik',11,'Metal Yüzey ve Muayene İşlemleri',2),('Karosercilik',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Karosercilik',12,'Ahşap Yapım Teknikleri',2),('Karosercilik',12,'İleri Düzeyde Metal İşleme',1),('Karosercilik',12,'Temel Elektrik',1),
('Metal Levha İşlemeciliği',11,'Ark Kaynak Teknikleri',3),('Metal Levha İşlemeciliği',11,'Metal Doğrama İşlemleri',2),('Metal Levha İşlemeciliği',11,'Metal Yüzey ve Muayene İşlemleri',2),('Metal Levha İşlemeciliği',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Metal Levha İşlemeciliği',12,'Metal Levha İşleme',3),('Metal Levha İşlemeciliği',12,'Temel Elektrik',1),
('Metal Yüzey Boyama',11,'Temel Yüzey ve Boya İşlemleri',2),('Metal Yüzey Boyama',11,'Metal Yüzey Boya Uygulamaları',3),('Metal Yüzey Boyama',11,'Metal Yüzey Boya İşlemleri',2),('Metal Yüzey Boyama',12,'Renklendirme ve Boyama',3),('Metal Yüzey Boyama',12,'Boya Ekipmanları Bakım ve Onarımı',3),('Metal Yüzey Boyama',12,'Temel Elektrik',1),
('Sac İşleri',11,'Ark Kaynak Teknikleri',3),('Sac İşleri',11,'Metal Yüzey ve Muayene İşlemleri',2),('Sac İşleri',11,'Metal Doğrama İşlemleri',2),('Sac İşleri',12,'Bilgisayarda İki Boyutlu Çizim / Bilgisayarda Katı Modelleme',3),('Sac İşleri',12,'Oksigaz Kaynağı',2),('Sac İşleri',12,'İleri Düzeyde Metal İşleme',1),('Sac İşleri',12,'Temel Elektrik',1)),
rows as (select branch_name,grade_level,course_name,'USTALIK'::text variant,u h from common where u>0 union all select branch_name,grade_level,course_name,'DIPLOMA',d from common where d>0 union all select branch_name,grade_level,course_name,'USTALIK',h from dal union all select branch_name,grade_level,course_name,'DIPLOMA',h from dal)
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',r.grade_level,c.id,case when r.course_name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük') then 'zorunlu' else 'uygulama' end,array[r.h]::int[],1,false,'https://meslek.meb.gov.tr/upload/cop10_mem/2022_metal_mem_cop.pdf','2022-33 yaşayan MESEM Metal Teknolojisi haftalık ders çizelgesi',true,'Metal Teknolojisi',r.branch_name,jsonb_build_object('source','MTEGM','decision','2022-33'),'2022-33','Haftalık Ders Çizelgesi',1.0,false,r.variant from rows r join course_catalog c on c.name=r.course_name where not exists(select 1 from official_course_schedule_catalog s where s.active and s.effective_academic_year='2026-2027' and s.school_type='MESEM' and coalesce(s.program_type,'')='MESEM' and s.field_name='Metal Teknolojisi' and s.branch_name=r.branch_name and s.grade_level=r.grade_level and s.schedule_variant=r.variant and s.course_id=c.id);
commit;