-- Official MEB weekly course schedule catalog -> tenant/class offering synchronization.
alter table public.school_classes add column if not exists school_type text;
update public.school_classes set school_type=case when grade_level between 1 and 4 then 'İlkokul' when grade_level between 5 and 8 and lower(coalesce(program_type,'')) like '%imam%' then 'İmam Hatip Ortaokulu' when grade_level between 5 and 8 then 'Ortaokul' when grade_level>=9 and lower(coalesce(program_type,'')) like '%imam%' then 'Anadolu İmam Hatip Lisesi' when grade_level>=9 then 'Lise' else school_type end where school_type is null;
create table if not exists public.official_course_schedule_catalog(id uuid primary key default gen_random_uuid(),effective_academic_year text not null,school_type text not null,program_type text,grade_level smallint not null check(grade_level between 1 and 14),course_id uuid not null references public.course_catalog(id) on delete cascade,category text not null check(category in('zorunlu','secmeli','rehberlik','uygulama','diger')),hour_options smallint[] not null,max_selections smallint not null default 1 check(max_selections between 1 and 20),repeat_across_years boolean not null default true,elective_group_key text,source_file_name text,source_note text,active boolean not null default true,imported_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(effective_academic_year,school_type,program_type,grade_level,course_id));
alter table public.official_course_schedule_catalog enable row level security;
drop policy if exists "official_course_schedule_catalog_read" on public.official_course_schedule_catalog;create policy "official_course_schedule_catalog_read" on public.official_course_schedule_catalog for select to authenticated using(true);
drop policy if exists "official_course_schedule_catalog_super_manage" on public.official_course_schedule_catalog;create policy "official_course_schedule_catalog_super_manage" on public.official_course_schedule_catalog for all to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
create index if not exists idx_official_course_schedule_match on public.official_course_schedule_catalog(effective_academic_year,school_type,grade_level,program_type) where active;
create or replace function public.infer_school_type_for_class_v1(p_grade smallint,p_program text,p_existing text) returns text language sql immutable as $$select coalesce(nullif(trim(p_existing),''),case when p_grade between 1 and 4 then 'İlkokul' when p_grade between 5 and 8 and lower(coalesce(p_program,'')) like '%imam%' then 'İmam Hatip Ortaokulu' when p_grade between 5 and 8 then 'Ortaokul' when p_grade>=9 and lower(coalesce(p_program,'')) like '%imam%' then 'Anadolu İmam Hatip Lisesi' when p_grade>=9 then 'Lise' else null end)$$;
create or replace function public.sync_official_course_offerings_for_class_v1(p_class_id uuid) returns integer language plpgsql security definer set search_path=public as $$declare c record;v_year text;v_type text;v_count int:=0;begin select s.*,y.code into c from school_classes s join academic_years y on y.id=s.academic_year_id where s.id=p_class_id and tenant_row_allowed(s.institution_code);if not found then return 0;end if;v_year:=c.code;v_type:=infer_school_type_for_class_v1(c.grade_level,c.program_type,c.school_type);if v_type is null or c.grade_level is null then return 0;end if;update school_classes set school_type=v_type where id=p_class_id and school_type is distinct from v_type;insert into course_offering_rules(institution_code,academic_year,school_level,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_note,source_file_name,active,updated_at) select c.institution_code,v_year,v_type,o.program_type,c.grade_level,o.course_id,o.category,o.hour_options,o.max_selections,o.repeat_across_years,o.elective_group_key,o.source_note,o.source_file_name,true,now() from official_course_schedule_catalog o where o.active and o.effective_academic_year=v_year and o.school_type=v_type and o.grade_level=c.grade_level and (o.program_type is null or o.program_type=c.program_type) on conflict(institution_code,academic_year,program_type,grade_level,course_id) do update set category=excluded.category,hour_options=excluded.hour_options,max_selections=excluded.max_selections,repeat_across_years=excluded.repeat_across_years,elective_group_key=excluded.elective_group_key,source_note=excluded.source_note,source_file_name=excluded.source_file_name,active=true,updated_at=now();get diagnostics v_count=row_count;return v_count;end$$;
grant execute on function public.sync_official_course_offerings_for_class_v1(uuid) to authenticated;
create or replace function public.sync_official_course_offerings_for_year_v1(p_academic_year_id uuid) returns integer language plpgsql security definer set search_path=public as $$declare x record;n int:=0;begin for x in select id from school_classes where academic_year_id=p_academic_year_id and tenant_row_allowed(institution_code) and active loop n:=n+sync_official_course_offerings_for_class_v1(x.id);end loop;return n;end$$;
grant execute on function public.sync_official_course_offerings_for_year_v1(uuid) to authenticated;
create or replace function public.super_admin_import_official_course_schedule_v1(p_source_file_name text,p_effective_academic_year text,p_school_type text,p_program_type text,p_rows jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;v_course uuid;v_name text;v_code text;v_cat text;v_hours smallint[];v_grade smallint;v_count int:=0;y record;begin if not is_super_admin() then raise exception 'SUPER_ADMIN_REQUIRED';end if;if jsonb_typeof(p_rows)<>'array' then raise exception 'ROWS_MUST_BE_ARRAY';end if;for r in select value from jsonb_array_elements(p_rows) loop v_name:=trim(r->>'courseName');v_code:=nullif(trim(r->>'courseCode'),'');v_grade:=(r->>'gradeLevel')::smallint;v_cat:=coalesce(nullif(r->>'category',''),'diger');select coalesce(array_agg(distinct z::smallint order by z::smallint),'{}'::smallint[]) into v_hours from jsonb_array_elements_text(coalesce(r->'hourOptions','[]'::jsonb)) z where z::int between 1 and 20;if v_name='' or v_grade is null or cardinality(v_hours)=0 then raise exception 'INVALID_OFFICIAL_COURSE_ROW: %',r;end if;insert into course_catalog(code,name,short_name,category,active) values(v_code,v_name,nullif(r->>'shortName',''),v_cat,true) on conflict(name) do update set code=coalesce(excluded.code,course_catalog.code),short_name=coalesce(excluded.short_name,course_catalog.short_name),active=true returning id into v_course;insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,updated_at) values(p_effective_academic_year,p_school_type,nullif(p_program_type,''),v_grade,v_course,v_cat,v_hours,coalesce((r->>'maxSelections')::smallint,1),coalesce((r->>'repeatAcrossYears')::boolean,true),nullif(r->>'electiveGroupKey',''),p_source_file_name,nullif(r->>'sourceNote',''),true,now()) on conflict(effective_academic_year,school_type,program_type,grade_level,course_id) do update set category=excluded.category,hour_options=excluded.hour_options,max_selections=excluded.max_selections,repeat_across_years=excluded.repeat_across_years,elective_group_key=excluded.elective_group_key,source_file_name=excluded.source_file_name,source_note=excluded.source_note,active=true,updated_at=now();v_count:=v_count+1;end loop;for y in select id from academic_years where code=p_effective_academic_year loop perform sync_official_course_offerings_for_year_v1(y.id);end loop;return jsonb_build_object('imported_rules',v_count,'academic_year',p_effective_academic_year,'school_type',p_school_type,'program_type',p_program_type);end$$;
grant execute on function public.super_admin_import_official_course_schedule_v1(text,text,text,text,jsonb) to authenticated;
create or replace function public.school_class_offering_sync_trigger_v1() returns trigger language plpgsql security definer set search_path=public as $$begin if new.academic_year_id is not null and new.grade_level is not null then perform sync_official_course_offerings_for_class_v1(new.id);end if;return new;end$$;
drop trigger if exists trg_school_class_offering_sync on public.school_classes;create trigger trg_school_class_offering_sync after insert or update of academic_year_id,grade_level,program_type,school_type on public.school_classes for each row execute function public.school_class_offering_sync_trigger_v1();
