begin;
with br(branch_name,page_no) as (values
('Modelistlik',8),('Deri Giyim',9),('Erkek Terziliği',10),('Kadın Terziliği',11),('Hazır Giyim Model Makineciliği',12),('İç Giyim Modelistliği',13),('Kesim',14)), src as (
select * from official_curriculum_profiles where school_type='MESEM' and field_name='Makine Teknolojisi' and branch_name='Anahtarcılık ve Çilingirlik' and active)
insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select s.effective_academic_year,s.school_type,s.school_subtype,s.program_type,'Moda Tasarım Teknolojileri',b.branch_name,s.grade_level,s.required_course_count,s.required_hour_total,s.elective_course_min,s.elective_course_max,s.elective_hour_min,s.elective_hour_max,s.total_hour_min,s.total_hour_max,s.total_hour_target,s.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_moda_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Moda Tasarım Teknolojileri çizelgesi; parantezli temel ders saatleri DIPLOMA fark dersidir.',true,s.schedule_variant,s.common_hours,s.vocational_hours,s.elective_vocational_hours,s.elective_hours,s.guidance_hours,s.enterprise_hours,'CURRENTLY_VALID',b.page_no,s.parsed_constraints,s.academic_support_hours
from src s cross join br b on conflict do nothing;
insert into course_catalog(name,category,active)
select distinct x.name,'uygulama',true from (values
('Moda Tasarımına Giriş'),('Uygulama Teknikleri'),('Kalıp Hazırlama Teknikleri'),('Giysi Teknik Çizimleri'),('Ahilik Kültürü ve Girişimcilik'),('Giysi Kalıpları'),('Üretim Organizasyonu ve Kalite Kontrol'),('Drapaj Yöntemiyle Kalıp Hazırlama'),('Giysi Üretimi'),('Tasarım ve Model Araştırmaları'),('Deri Giysi Üretimi'),('İş ve Üretim Organizasyonu'),('Deri Giysi Kalıpları'),('Deri Teknolojisi'),('Deri Kalite Kontrol'),('Erkek Giysi Dikimi'),('İş Yeri Planı ve Üretim Organizasyonu'),('Erkek Terzi Kalıpları'),('Giysi Onarımı'),('Kadın Giysi Dikimi'),('Kadın Terzi Kalıpları'),('Model Makinecilikte Üretim'),('Model Makinecilikte Kalıp'),('Bilgisayar Destekli Kalıp Hazırlama'),('İç Giyim Kalıpları'),('İç Giyim Üretimi'),('Bilgisayarla İç Giyim Kalıpları Hazırlama'),('Kesimde Kalıp Hazırlama'),('Kesim Teknikleri'),('Bilgisayar Destekli Kesim')) x(name)
where not exists(select 1 from course_catalog c where c.name=x.name);
with br(branch_name,page_no) as (values
('Modelistlik',8),('Deri Giyim',9),('Erkek Terziliği',10),('Kadın Terziliği',11),('Hazır Giyim Model Makineciliği',12),('İç Giyim Modelistliği',13),('Kesim',14)), common_src as (
select s.* from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id
where s.active and s.school_type='MESEM' and s.field_name='Makine Teknolojisi' and s.branch_name='Anahtarcılık ve Çilingirlik' and s.source_decision_no='2021-33'
and c.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','İşletmelerde Mesleki Eğitim'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_moda_mem_cop.pdf','2021-33 yaşayan MESEM Moda Tasarım Teknolojileri çizelgesi',true,'Moda Tasarım Teknolojileri',b.branch_name,s.parsed_constraints,s.school_subtype,'2021-33',b.page_no,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant
from common_src s cross join br b on conflict do nothing;
with data(branch_name,page_no,grade_level,course_name,hours) as (values
('Modelistlik',8,9,'Moda Tasarımına Giriş',2),('Modelistlik',8,10,'Uygulama Teknikleri',2),('Modelistlik',8,10,'Kalıp Hazırlama Teknikleri',2),('Modelistlik',8,11,'Giysi Teknik Çizimleri',2),('Modelistlik',8,11,'Giysi Kalıpları',4),('Modelistlik',8,11,'Üretim Organizasyonu ve Kalite Kontrol',1),('Modelistlik',8,12,'Ahilik Kültürü ve Girişimcilik',1),('Modelistlik',8,12,'Drapaj Yöntemiyle Kalıp Hazırlama',2),('Modelistlik',8,12,'Giysi Üretimi',3),('Modelistlik',8,12,'Tasarım ve Model Araştırmaları',2),
('Deri Giyim',9,9,'Moda Tasarımına Giriş',2),('Deri Giyim',9,10,'Uygulama Teknikleri',2),('Deri Giyim',9,10,'Kalıp Hazırlama Teknikleri',2),('Deri Giyim',9,11,'Giysi Teknik Çizimleri',2),('Deri Giyim',9,11,'Deri Giysi Üretimi',4),('Deri Giyim',9,11,'İş ve Üretim Organizasyonu',1),('Deri Giyim',9,12,'Ahilik Kültürü ve Girişimcilik',1),('Deri Giyim',9,12,'Deri Giysi Kalıpları',3),('Deri Giyim',9,12,'Deri Teknolojisi',1),('Deri Giyim',9,12,'Deri Kalite Kontrol',1),('Deri Giyim',9,12,'Tasarım ve Model Araştırmaları',2),
('Erkek Terziliği',10,9,'Moda Tasarımına Giriş',2),('Erkek Terziliği',10,10,'Uygulama Teknikleri',2),('Erkek Terziliği',10,10,'Kalıp Hazırlama Teknikleri',2),('Erkek Terziliği',10,11,'Giysi Teknik Çizimleri',2),('Erkek Terziliği',10,11,'Erkek Giysi Dikimi',4),('Erkek Terziliği',10,11,'İş Yeri Planı ve Üretim Organizasyonu',1),('Erkek Terziliği',10,12,'Ahilik Kültürü ve Girişimcilik',1),('Erkek Terziliği',10,12,'Erkek Terzi Kalıpları',4),('Erkek Terziliği',10,12,'Giysi Onarımı',1),('Erkek Terziliği',10,12,'Tasarım ve Model Araştırmaları',2),
('Kadın Terziliği',11,9,'Moda Tasarımına Giriş',2),('Kadın Terziliği',11,10,'Uygulama Teknikleri',2),('Kadın Terziliği',11,10,'Kalıp Hazırlama Teknikleri',2),('Kadın Terziliği',11,11,'Giysi Teknik Çizimleri',2),('Kadın Terziliği',11,11,'Kadın Giysi Dikimi',4),('Kadın Terziliği',11,11,'İş Yeri Planı ve Üretim Organizasyonu',1),('Kadın Terziliği',11,12,'Ahilik Kültürü ve Girişimcilik',1),('Kadın Terziliği',11,12,'Kadın Terzi Kalıpları',2),('Kadın Terziliği',11,12,'Drapaj Yöntemiyle Kalıp Hazırlama',2),('Kadın Terziliği',11,12,'Giysi Onarımı',1),('Kadın Terziliği',11,12,'Tasarım ve Model Araştırmaları',2),
('Hazır Giyim Model Makineciliği',12,9,'Moda Tasarımına Giriş',2),('Hazır Giyim Model Makineciliği',12,10,'Uygulama Teknikleri',2),('Hazır Giyim Model Makineciliği',12,10,'Kalıp Hazırlama Teknikleri',2),('Hazır Giyim Model Makineciliği',12,11,'Giysi Teknik Çizimleri',2),('Hazır Giyim Model Makineciliği',12,11,'Model Makinecilikte Üretim',4),('Hazır Giyim Model Makineciliği',12,11,'Üretim Organizasyonu ve Kalite Kontrol',1),('Hazır Giyim Model Makineciliği',12,12,'Ahilik Kültürü ve Girişimcilik',1),('Hazır Giyim Model Makineciliği',12,12,'Model Makinecilikte Kalıp',3),('Hazır Giyim Model Makineciliği',12,12,'Bilgisayar Destekli Kalıp Hazırlama',2),('Hazır Giyim Model Makineciliği',12,12,'Tasarım ve Model Araştırmaları',2),
('İç Giyim Modelistliği',13,9,'Moda Tasarımına Giriş',2),('İç Giyim Modelistliği',13,10,'Uygulama Teknikleri',2),('İç Giyim Modelistliği',13,10,'Kalıp Hazırlama Teknikleri',2),('İç Giyim Modelistliği',13,11,'Giysi Teknik Çizimleri',2),('İç Giyim Modelistliği',13,11,'İç Giyim Kalıpları',4),('İç Giyim Modelistliği',13,11,'Üretim Organizasyonu ve Kalite Kontrol',1),('İç Giyim Modelistliği',13,12,'Ahilik Kültürü ve Girişimcilik',1),('İç Giyim Modelistliği',13,12,'İç Giyim Üretimi',3),('İç Giyim Modelistliği',13,12,'Bilgisayarla İç Giyim Kalıpları Hazırlama',2),('İç Giyim Modelistliği',13,12,'Tasarım ve Model Araştırmaları',2),
('Kesim',14,9,'Moda Tasarımına Giriş',2),('Kesim',14,10,'Uygulama Teknikleri',2),('Kesim',14,10,'Kalıp Hazırlama Teknikleri',2),('Kesim',14,11,'Giysi Teknik Çizimleri',2),('Kesim',14,11,'Kesimde Kalıp Hazırlama',4),('Kesim',14,11,'Üretim Organizasyonu ve Kalite Kontrol',1),('Kesim',14,12,'Ahilik Kültürü ve Girişimcilik',1),('Kesim',14,12,'Kesim Teknikleri',3),('Kesim',14,12,'Bilgisayar Destekli Kesim',2),('Kesim',14,12,'Tasarım ve Model Araştırmaları',2)), vars(schedule_variant) as (values('USTALIK'),('DIPLOMA'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',d.grade_level,c.id,'uygulama',array[d.hours],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_moda_mem_cop.pdf','2021-33 yaşayan MESEM Moda Tasarım Teknolojileri çizelgesi',true,'Moda Tasarım Teknolojileri',d.branch_name,'[]'::jsonb,null,'2021-33',d.page_no,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant
from data d join course_catalog c on c.name=d.course_name cross join vars v on conflict do nothing;
commit;