DO $$
DECLARE r record; cid uuid;
BEGIN
CREATE TEMP TABLE _yb(branch text,g int,course text,h int) ON COMMIT DROP;
INSERT INTO _yb VALUES
('Aşçılık',9,'Beslenme İlkeleri ve Hijyen',2),('Aşçılık',10,'Temel Yiyecek Üretimi',3),('Aşçılık',10,'Servis Hazırlıkları',1),('Aşçılık',11,'Mutfak Uygulamaları',5),('Aşçılık',11,'Açık Büfe',2),('Aşçılık',12,'Ahilik Kültürü ve Girişimcilik',1),('Aşçılık',12,'Türk Mutfağı Yemekleri',3),('Aşçılık',12,'Hamur Ürünleri',2),('Aşçılık',12,'Tatlı Yapım Teknikleri',2),('Pasta ve Tatlı Yapımı',9,'Beslenme İlkeleri ve Hijyen',2),('Pasta ve Tatlı Yapımı',10,'Temel Yiyecek Üretimi',3),('Pasta ve Tatlı Yapımı',10,'Servis Hazırlıkları',1),('Pasta ve Tatlı Yapımı',11,'Temel Hamur Teknikleri',6),('Pasta ve Tatlı Yapımı',11,'Açık Büfe',1),('Pasta ve Tatlı Yapımı',12,'Ahilik Kültürü ve Girişimcilik',1),('Pasta ve Tatlı Yapımı',12,'Pasta Yapım Teknikleri',4),('Pasta ve Tatlı Yapımı',12,'Pastane Organizasyonu',1),('Pasta ve Tatlı Yapımı',12,'Tatlı Yapım Teknikleri',2),('Servis',9,'Beslenme İlkeleri ve Hijyen',2),('Servis',10,'Temel Yiyecek Üretimi',3),('Servis',10,'Servis Hazırlıkları',1),('Servis',11,'Yiyecek Servisi',5),('Servis',11,'İçecek Servisi',2),('Servis',12,'Ahilik Kültürü ve Girişimcilik',1),('Servis',12,'Konuk Masasında Servis',4),('Servis',12,'Yemek Gruplarının Servisi',3),('Fırıncılık',9,'Beslenme İlkeleri ve Hijyen',2),('Fırıncılık',10,'Temel Yiyecek Üretimi',3),('Fırıncılık',10,'Servis Hazırlıkları',1),('Fırıncılık',11,'Ekmek Yapımı',5),('Fırıncılık',11,'Simit Yapımı',2),('Fırıncılık',12,'Ahilik Kültürü ve Girişimcilik',1),('Fırıncılık',12,'Pide Yapımı',4),('Fırıncılık',12,'Ürün Alımı ve Satışı',3),('Kantin İşletmeciliği',9,'Beslenme İlkeleri ve Hijyen',2),('Kantin İşletmeciliği',10,'Temel Yiyecek Üretimi',3),('Kantin İşletmeciliği',10,'Servis Hazırlıkları',1),('Kantin İşletmeciliği',11,'Yiyecek Hazırlama',5),('Kantin İşletmeciliği',11,'İçecek Servisi',2),('Kantin İşletmeciliği',12,'Ahilik Kültürü ve Girişimcilik',1),('Kantin İşletmeciliği',12,'Ürün Alımı ve Satışı',3),('Kantin İşletmeciliği',12,'Hızlı Hazır Yiyecekler',4),('Kasaplık',9,'Beslenme İlkeleri ve Hijyen',2),('Kasaplık',10,'Kesimlik Hayvanlar',4),('Kasaplık',11,'Et İşleme',4),('Kasaplık',11,'Geleneksel Et Ürünleri ve Sakatatlar',3),('Kasaplık',12,'Ahilik Kültürü ve Girişimcilik',1),('Kasaplık',12,'Et Pişirme',4),('Kasaplık',12,'Ürün Alımı ve Satışı',3);
INSERT INTO course_catalog(name,category) SELECT DISTINCT course,'uygulama' FROM _yb ON CONFLICT(name) DO NOTHING;
FOR r IN SELECT branch_name FROM official_vocational_branches b JOIN official_vocational_fields f ON f.id=b.field_id WHERE f.institution_type='MESEM' AND f.field_name='Yiyecek İçecek Hizmetleri' AND b.active LOOP
 INSERT INTO official_curriculum_profiles(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
 SELECT effective_academic_year,school_type,program_type,'Yiyecek İçecek Hizmetleri',r.branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,'https://meslek.meb.gov.tr/upload/cop12_mem/2021_yiyecek_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Yiyecek İçecek Hizmetleri çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,'CURRENTLY_VALID',CASE r.branch_name WHEN 'Aşçılık' THEN 8 WHEN 'Pasta ve Tatlı Yapımı' THEN 9 WHEN 'Servis' THEN 10 WHEN 'Fırıncılık' THEN 11 WHEN 'Kantin İşletmeciliği' THEN 12 ELSE 13 END,parsed_constraints,academic_support_hours FROM official_curriculum_profiles WHERE school_type='MESEM' AND field_name='Makine Teknolojisi' AND branch_name='Anahtarcılık ve Çilingirlik' AND source_decision_no='2021-33' AND active ON CONFLICT DO NOTHING;
END LOOP;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_decision_date,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop12_mem/2021_yiyecek_mem_cop.pdf','2021-33 yaşayan MESEM Yiyecek İçecek Hizmetleri çizelgesi.',true,'Yiyecek İçecek Hizmetleri',b.branch,s.parsed_constraints,s.school_subtype,'2021-33',s.source_decision_date,CASE b.branch WHEN 'Aşçılık' THEN 8 WHEN 'Pasta ve Tatlı Yapımı' THEN 9 WHEN 'Servis' THEN 10 WHEN 'Fırıncılık' THEN 11 WHEN 'Kantin İşletmeciliği' THEN 12 ELSE 13 END,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant FROM official_course_schedule_catalog s CROSS JOIN (SELECT DISTINCT branch FROM _yb) b WHERE s.field_name='Makine Teknolojisi' AND s.branch_name='Anahtarcılık ve Çilingirlik' AND s.source_decision_no='2021-33' AND s.active AND (s.category='zorunlu' OR EXISTS(SELECT 1 FROM course_catalog c WHERE c.id=s.course_id AND c.name='İşletmelerde Mesleki Eğitim')) ON CONFLICT DO NOTHING;
FOR r IN SELECT * FROM _yb LOOP
 SELECT id INTO cid FROM course_catalog WHERE name=r.course;
 INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
 SELECT '2026-2027','MESEM','MESEM',r.g,cid,'uygulama',ARRAY[r.h],1,true,'https://meslek.meb.gov.tr/upload/cop12_mem/2021_yiyecek_mem_cop.pdf','2021-33 yaşayan MESEM Yiyecek İçecek Hizmetleri çizelgesi.',true,'Yiyecek İçecek Hizmetleri',r.branch,'[]'::jsonb,'2021-33',CASE r.branch WHEN 'Aşçılık' THEN 8 WHEN 'Pasta ve Tatlı Yapımı' THEN 9 WHEN 'Servis' THEN 10 WHEN 'Fırıncılık' THEN 11 WHEN 'Kantin İşletmeciliği' THEN 12 ELSE 13 END,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant FROM (VALUES('USTALIK'),('DIPLOMA')) v(schedule_variant) ON CONFLICT DO NOTHING;
END LOOP;
END $$;