do $$
declare br text; v text; g int; src uuid;
begin
for br in select unnest(array['Otomotiv Boya','Otomotiv Mekanikerliği','Otomotiv Motor Yenileştirmeciliği','Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı','Motorlu Araçlar LPG Sistemleri Bakım ve Onarımcılığı','Motosiklet Tamirciliği','Otomotiv Elektrikçiliği','Ön Düzen Ayarcılığı ve Lastikçilik']) loop
  for v in select unnest(array['USTALIK','DIPLOMA']) loop
    for g in 9..12 loop
      select p.id into src from official_curriculum_profiles p where p.active and p.school_type='MESEM' and p.field_name='Motorlu Araçlar Teknolojisi' and p.branch_name='Otomotiv Elektromekanik' and p.grade_level=g and p.schedule_variant=v limit 1;
      insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
      select p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,p.field_name,br,p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Motorlu Araçlar Teknolojisi çizelgesi; parantezli saatler diploma fark dersidir.',true,v,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,'CURRENTLY_VALID',p.source_page,p.parsed_constraints,p.academic_support_hours from official_curriculum_profiles p where p.id=src
      on conflict (effective_academic_year,school_type,coalesce(school_subtype,''),coalesce(program_type,''),coalesce(field_name,''),coalesce(branch_name,''),grade_level,coalesce(schedule_variant,'STANDARD')) do update set active=true,source_file_name=excluded.source_file_name,source_decision_no=excluded.source_decision_no,source_note=excluded.source_note,updated_at=now();
      delete from official_course_schedule_catalog x where x.active and x.school_type='MESEM' and x.field_name='Motorlu Araçlar Teknolojisi' and x.branch_name=br and x.grade_level=g and x.schedule_variant=v;
      insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
      select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33 Motorlu Araçlar',true,s.field_name,br,s.parsed_constraints,s.school_subtype,'2021-33',s.source_page,s.source_section,1,false,v
      from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id
      where s.active and s.school_type='MESEM' and s.field_name='Motorlu Araçlar Teknolojisi' and s.branch_name='Otomotiv Elektromekanik' and s.grade_level=g and s.schedule_variant=v
      and c.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','Temel Araç Bilgisi','Araç Teknolojisi','Araçlarda Hidrolik Pnömatik Sistemler','Ahilik Kültürü ve Girişimcilik','Otomotiv Teknik Resmi','Otomotiv Meslek Resmi','İşletmelerde Mesleki Eğitim');
    end loop;
  end loop;
end loop;

insert into course_catalog(name,category,active) select x,'uygulama',true from unnest(array['Otomotiv Temel Boya','Otomotiv Boya Teknolojisi','Otomotiv Boya Uygulamaları','Otomotiv Boya Renk Uygulamaları','Otomotiv Mekanik Teknolojisi','Otomotiv Konfor Sistemleri','Dizel Yakıt Sistemleri','Hareket Kontrol Sistemleri','Supap Sistemi Yenileştirme','Düz Yüzey Yenileştirme Teknolojisi','Krank Mili ve Piston-Biyel Yenileştirme','Silindir Yenileştirme','Motor Yenileştirmede Arıza Tespiti','Dizel Motor Yakıt Sistemleri Teknolojisi','Dizel Motor Pompa Ayarları','Dizel Motor Enjektör Ayarları','Dizel Motor Servisi','LPG Yakıt Sistemleri Teknolojisi','LPG Yakıt Sistemleri Uygulamaları','LPG Yakıt Sistemleri Arıza Tespiti','Motosiklet Hareket Kontrol Sistemleri Teknolojisi','Elektrikli Motosikletler','Hasarlı Araç İşlemleri','Motosiklet Teknolojisi','Otomotiv Elektrik Teknolojisi','Otomotiv Elektrik Uygulamaları','Otomotiv Elektrik Arıza Tespiti','Ön Düzen Teknolojisi','Ofis Programları','Ön Düzen Ayarları','Ön Düzen Arızaları']) x where not exists(select 1 from course_catalog c where c.name=x);

with d(br,g,n,h) as (values
('Otomotiv Boya',11,'Otomotiv Temel Boya',3),('Otomotiv Boya',11,'Otomotiv Boya Teknolojisi',2),('Otomotiv Boya',12,'Otomotiv Boya Uygulamaları',3),('Otomotiv Boya',12,'Otomotiv Boya Renk Uygulamaları',2),
('Otomotiv Mekanikerliği',11,'Otomotiv Mekanik Teknolojisi',3),('Otomotiv Mekanikerliği',11,'Otomotiv Konfor Sistemleri',2),('Otomotiv Mekanikerliği',12,'Dizel Yakıt Sistemleri',2),('Otomotiv Mekanikerliği',12,'Hareket Kontrol Sistemleri',3),
('Otomotiv Motor Yenileştirmeciliği',11,'Supap Sistemi Yenileştirme',3),('Otomotiv Motor Yenileştirmeciliği',11,'Düz Yüzey Yenileştirme Teknolojisi',2),('Otomotiv Motor Yenileştirmeciliği',12,'Krank Mili ve Piston-Biyel Yenileştirme',2),('Otomotiv Motor Yenileştirmeciliği',12,'Silindir Yenileştirme',2),('Otomotiv Motor Yenileştirmeciliği',12,'Motor Yenileştirmede Arıza Tespiti',1),
('Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı',11,'Dizel Motor Yakıt Sistemleri Teknolojisi',5),('Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı',12,'Dizel Motor Pompa Ayarları',2),('Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı',12,'Dizel Motor Enjektör Ayarları',2),('Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı',12,'Dizel Motor Servisi',1),
('Motorlu Araçlar LPG Sistemleri Bakım ve Onarımcılığı',11,'LPG Yakıt Sistemleri Teknolojisi',5),('Motorlu Araçlar LPG Sistemleri Bakım ve Onarımcılığı',12,'LPG Yakıt Sistemleri Uygulamaları',3),('Motorlu Araçlar LPG Sistemleri Bakım ve Onarımcılığı',12,'LPG Yakıt Sistemleri Arıza Tespiti',2),
('Motosiklet Tamirciliği',11,'Motosiklet Hareket Kontrol Sistemleri Teknolojisi',3),('Motosiklet Tamirciliği',11,'Elektrikli Motosikletler',2),('Motosiklet Tamirciliği',12,'Hasarlı Araç İşlemleri',1),('Motosiklet Tamirciliği',12,'Motosiklet Teknolojisi',4),
('Otomotiv Elektrikçiliği',11,'Otomotiv Elektrik Teknolojisi',3),('Otomotiv Elektrikçiliği',11,'Otomotiv Elektrik Uygulamaları',2),('Otomotiv Elektrikçiliği',12,'Otomotiv Elektrik Arıza Tespiti',3),('Otomotiv Elektrikçiliği',12,'Otomotiv Konfor Sistemleri',2),
('Ön Düzen Ayarcılığı ve Lastikçilik',11,'Ön Düzen Teknolojisi',3),('Ön Düzen Ayarcılığı ve Lastikçilik',11,'Ofis Programları',2),('Ön Düzen Ayarcılığı ve Lastikçilik',12,'Ön Düzen Ayarları',2),('Ön Düzen Ayarcılığı ve Lastikçilik',12,'Ön Düzen Arızaları',3))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',d.g,c.id,'uygulama',array[d.h],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33 Motorlu Araçlar',true,'Motorlu Araçlar Teknolojisi',d.br,'[]'::jsonb,'2021-33',case d.br when 'Otomotiv Boya' then 9 when 'Otomotiv Mekanikerliği' then 10 when 'Otomotiv Motor Yenileştirmeciliği' then 11 when 'Dizel Motorları Yakıt Pompası ve Enjektör Ayarcılığı' then 12 when 'Motorlu Araçlar LPG Sistemleri Bakım ve Onarımcılığı' then 13 when 'Motosiklet Tamirciliği' then 14 when 'Otomotiv Elektrikçiliği' then 15 else 16 end,1,false,v.v
from d join course_catalog c on c.name=d.n cross join (values('USTALIK'),('DIPLOMA')) v(v);
end $$;