do $$
declare src text:='https://meslek.meb.gov.tr/upload/cop9_mem/2021_seramik_mem_cop.pdf'; br text; p record; r record;
begin
for br in select * from (values ('Alçı Model Kalıp'),('Çinicilik'),('Dekoratif Cam'),('Endüstriyel Cam'),('Serbest Seramik Şekillendirme'),('Sır Üstü Dekorlama'),('Tornada Form Şekillendirme')) v(x) loop
 for p in select * from official_curriculum_profiles where active and school_type='MESEM' and field_name='Plastik Teknolojisi' and branch_name='Plastik İşleme' and effective_academic_year='2026-2027' loop
  if not exists(select 1 from official_curriculum_profiles x where x.active and x.effective_academic_year='2026-2027' and x.school_type='MESEM' and coalesce(x.school_subtype,'')=coalesce(p.school_subtype,'') and coalesce(x.program_type,'')=coalesce(p.program_type,'') and x.field_name='Seramik ve Cam Teknolojisi' and x.branch_name=br and x.grade_level=p.grade_level and coalesce(x.schedule_variant,'STANDARD')=coalesce(p.schedule_variant,'STANDARD')) then
   insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
   values('2026-2027','MESEM',p.school_subtype,'MESEM','Seramik ve Cam Teknolojisi',br,p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,src,'2021-33','2021-33 yaşayan MESEM Seramik ve Cam Teknolojisi çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,p.schedule_variant,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,'CURRENTLY_VALID',case br when 'Alçı Model Kalıp' then 9 when 'Çinicilik' then 10 when 'Dekoratif Cam' then 11 when 'Endüstriyel Cam' then 12 when 'Serbest Seramik Şekillendirme' then 13 when 'Sır Üstü Dekorlama' then 14 else 15 end,p.parsed_constraints,p.academic_support_hours);
  end if;
 end loop;
end loop;
for br in select * from (values ('Alçı Model Kalıp'),('Çinicilik'),('Dekoratif Cam'),('Endüstriyel Cam'),('Serbest Seramik Şekillendirme'),('Sır Üstü Dekorlama'),('Tornada Form Şekillendirme')) v(x) loop
 for p in select grade_level,schedule_variant from official_curriculum_profiles where active and school_type='MESEM' and field_name='Seramik ve Cam Teknolojisi' and branch_name=br and effective_academic_year='2026-2027' loop
  for r in select s.*,cc.name from official_course_schedule_catalog s join course_catalog cc on cc.id=s.course_id where s.active and s.school_type='MESEM' and s.field_name='Plastik Teknolojisi' and s.branch_name='Plastik İşleme' and s.grade_level=p.grade_level and s.schedule_variant=p.schedule_variant and cc.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','İşletmelerde Mesleki Eğitim') loop
   if not exists(select 1 from official_course_schedule_catalog x where x.active and x.school_type='MESEM' and x.field_name='Seramik ve Cam Teknolojisi' and x.branch_name=br and x.grade_level=p.grade_level and x.schedule_variant=p.schedule_variant and x.course_id=r.course_id) then
    insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
    values('2026-2027','MESEM','MESEM',p.grade_level,r.course_id,r.category,r.hour_options,r.max_selections,r.repeat_across_years,r.elective_group_key,src,'2021-33 Seramik ve Cam Teknolojisi',true,'Seramik ve Cam Teknolojisi',br,r.parsed_constraints,r.school_subtype,'2021-33',case br when 'Alçı Model Kalıp' then 9 when 'Çinicilik' then 10 when 'Dekoratif Cam' then 11 when 'Endüstriyel Cam' then 12 when 'Serbest Seramik Şekillendirme' then 13 when 'Sır Üstü Dekorlama' then 14 else 15 end,'HAFTALIK DERS ÇİZELGESİ',1,false,p.schedule_variant);
   end if;
  end loop;
 end loop;
end loop;
create temporary table _v(branch text,grade int,name text,h int) on commit drop;
insert into _v values
('Alçı Model Kalıp',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Alçı Model Kalıp',10,'Temel Seramik ve Cam',2),('Alçı Model Kalıp',10,'Seramik ve Cam Tasarımı',1),('Alçı Model Kalıp',10,'Temel Desen',1),('Alçı Model Kalıp',11,'Alçı Şekillendirme',6),('Alçı Model Kalıp',11,'Bilgisayar Destekli Desen Çizimi',1),('Alçı Model Kalıp',12,'Ahilik Kültürü ve Girişimcilik',1),('Alçı Model Kalıp',12,'Parçalı Model ve Kalıp',1),('Alçı Model Kalıp',12,'Desen',2),('Alçı Model Kalıp',12,'Döküm ve Sır',2),('Alçı Model Kalıp',12,'Sanat ve Seramik Tarihi',2),
('Çinicilik',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Çinicilik',10,'Temel Seramik ve Cam',2),('Çinicilik',10,'Seramik ve Cam Tasarımı',1),('Çinicilik',10,'Temel Desen',1),('Çinicilik',11,'Türk Motifleri',3),('Çinicilik',11,'Çini Dekor Uygulamalarına Giriş',3),('Çinicilik',11,'Bilgisayar Destekli Desen Çizimi',1),('Çinicilik',12,'Ahilik Kültürü ve Girişimcilik',1),('Çinicilik',12,'Dik Formlarda Çini Uygulamaları',2),('Çinicilik',12,'Duvar Çini Uygulamaları',1),('Çinicilik',12,'Desen',2),('Çinicilik',12,'Sanat ve Seramik Tarihi',2),
('Dekoratif Cam',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Dekoratif Cam',10,'Temel Seramik ve Cam',2),('Dekoratif Cam',10,'Seramik ve Cam Tasarımı',1),('Dekoratif Cam',10,'Temel Desen',1),('Dekoratif Cam',11,'Cam Yüzey Aşındırma Teknikleri',3),('Dekoratif Cam',11,'Cam Füzyon',2),('Dekoratif Cam',11,'Cama Desen Hazırlama',2),('Dekoratif Cam',12,'Ahilik Kültürü ve Girişimcilik',1),('Dekoratif Cam',12,'Vitray',4),('Dekoratif Cam',12,'Camı Alevle Şekillendirme',2),('Dekoratif Cam',12,'Cam Dekor Teknikleri',1),
('Endüstriyel Cam',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Endüstriyel Cam',10,'Temel Seramik ve Cam',2),('Endüstriyel Cam',10,'Seramik ve Cam Tasarımı',1),('Endüstriyel Cam',10,'Temel Desen',1),('Endüstriyel Cam',11,'Camda Talaşlı İşleme Teknikleri',4),('Endüstriyel Cam',11,'Cam Füzyon',2),('Endüstriyel Cam',11,'Bilgisayar Destekli Desen Çizimi',1),('Endüstriyel Cam',12,'Ahilik Kültürü ve Girişimcilik',1),('Endüstriyel Cam',12,'Camda Isıl İşlem',4),('Endüstriyel Cam',12,'Elek Baskı',2),('Endüstriyel Cam',12,'Yalıtımlı Cam ve Kaplama',1),
('Serbest Seramik Şekillendirme',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Serbest Seramik Şekillendirme',10,'Temel Seramik ve Cam',2),('Serbest Seramik Şekillendirme',10,'Seramik ve Cam Tasarımı',1),('Serbest Seramik Şekillendirme',10,'Temel Desen',1),('Serbest Seramik Şekillendirme',11,'Artistik Seramik Uygulamaları',6),('Serbest Seramik Şekillendirme',11,'Bilgisayar Destekli Desen Çizimi',1),('Serbest Seramik Şekillendirme',12,'Ahilik Kültürü ve Girişimcilik',1),('Serbest Seramik Şekillendirme',12,'Çağdaş Form Uygulamaları',1),('Serbest Seramik Şekillendirme',12,'Desen',2),('Serbest Seramik Şekillendirme',12,'Döküm ve Sır',2),('Serbest Seramik Şekillendirme',12,'Sanat ve Seramik Tarihi',2),
('Sır Üstü Dekorlama',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Sır Üstü Dekorlama',10,'Temel Seramik ve Cam',2),('Sır Üstü Dekorlama',10,'Seramik ve Cam Tasarımı',1),('Sır Üstü Dekorlama',10,'Temel Desen',1),('Sır Üstü Dekorlama',11,'Seramik El Dekorları',6),('Sır Üstü Dekorlama',11,'Bilgisayar Destekli Desen Çizimi',1),('Sır Üstü Dekorlama',12,'Ahilik Kültürü ve Girişimcilik',1),('Sır Üstü Dekorlama',12,'Elek Baskı',1),('Sır Üstü Dekorlama',12,'Desen',2),('Sır Üstü Dekorlama',12,'Döküm ve Sır',2),('Sır Üstü Dekorlama',12,'Sanat ve Seramik Tarihi',2),
('Tornada Form Şekillendirme',9,'Seramik ve Cam Teknolojisinin Temelleri',2),('Tornada Form Şekillendirme',10,'Temel Seramik ve Cam',2),('Tornada Form Şekillendirme',10,'Seramik ve Cam Tasarımı',1),('Tornada Form Şekillendirme',10,'Temel Desen',1),('Tornada Form Şekillendirme',11,'Çamur Tornası Temel Uygulamaları',5),('Tornada Form Şekillendirme',11,'Şablon Torna',1),('Tornada Form Şekillendirme',11,'Bilgisayar Destekli Desen Çizimi',1),('Tornada Form Şekillendirme',12,'Ahilik Kültürü ve Girişimcilik',1),('Tornada Form Şekillendirme',12,'Çamur Tornasında Tasarım Uygulamaları',1),('Tornada Form Şekillendirme',12,'Desen',2),('Tornada Form Şekillendirme',12,'Döküm ve Sır',2),('Tornada Form Şekillendirme',12,'Sanat ve Seramik Tarihi',2);
insert into course_catalog(name,category,active) select distinct v.name,'uygulama',true from _v v where not exists(select 1 from course_catalog cc where cc.name=v.name);
for r in select v.*,cc.id course_id from _v v join course_catalog cc on cc.name=v.name loop
 for p in select schedule_variant from official_curriculum_profiles where active and school_type='MESEM' and field_name='Seramik ve Cam Teknolojisi' and branch_name=r.branch and grade_level=r.grade and effective_academic_year='2026-2027' loop
  if not exists(select 1 from official_course_schedule_catalog x where x.active and x.school_type='MESEM' and x.field_name='Seramik ve Cam Teknolojisi' and x.branch_name=r.branch and x.grade_level=r.grade and x.schedule_variant=p.schedule_variant and x.course_id=r.course_id) then
   insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
   values('2026-2027','MESEM','MESEM',r.grade,r.course_id,'uygulama',array[r.h],src,'2021-33 Seramik ve Cam Teknolojisi',true,'Seramik ve Cam Teknolojisi',r.branch,'[]'::jsonb,'2021-33',case r.branch when 'Alçı Model Kalıp' then 9 when 'Çinicilik' then 10 when 'Dekoratif Cam' then 11 when 'Endüstriyel Cam' then 12 when 'Serbest Seramik Şekillendirme' then 13 when 'Sır Üstü Dekorlama' then 14 else 15 end,'HAFTALIK DERS ÇİZELGESİ',1,false,p.schedule_variant);
  end if;
 end loop;
end loop;
end $$;