begin;
insert into public.course_catalog(name,category)
select x,'uygulama' from unnest(array['Mesleğe Giriş','Temel Bakım','Kozmetik','Mesleki Resim','Temel Anatomi ve Fizyoloji','Cilt Bakım Teknikleri','Temel Makyaj','Epilasyon','Depilasyon','Temel Beslenme','İleri Makyaj','Vücut Bakımı','El Ayak Bakımı','Diksiyon','Kadın Saç Şekillendirme ve Renklendirme','Kadın Saç Kesim Teknikleri','Erkek Saç Şekillendirme ve Renklendirme','Erkek Saç Kesim Teknikleri','Sakal Bıyık Tıraşı']) x on conflict(name) do nothing;
with b(branch_name,source_page) as (values ('Cilt Bakımı ve Makyaj',7::smallint),('Kadın Kuaförlüğü',8::smallint),('Erkek Kuaförlüğü',9::smallint))
insert into public.official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select t.effective_academic_year,t.school_type,t.school_subtype,t.program_type,'Güzellik ve Saç Bakım Hizmetleri',b.branch_name,t.grade_level,t.required_course_count,t.required_hour_total,t.elective_course_min,t.elective_course_max,t.elective_hour_min,t.elective_hour_max,t.total_hour_min,t.total_hour_max,t.total_hour_target,t.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_guzellik_mem_cop.pdf','2021-33','MTEGM 2021-33 Güzellik ve Saç Bakım Hizmetleri MESEM; parantezli saatler diploma fark dersleridir.',true,t.schedule_variant,t.common_hours,t.vocational_hours,t.elective_vocational_hours,t.elective_hours,t.guidance_hours,t.enterprise_hours,'CURRENTLY_VALID',b.source_page,t.parsed_constraints,t.academic_support_hours
from public.official_curriculum_profiles t cross join b
where t.school_type='MESEM' and t.field_name='Ayakkabı ve Saraciye Teknolojisi' and t.branch_name='Ayakkabı Modelistliği'
and not exists(select 1 from public.official_curriculum_profiles z where z.effective_academic_year=t.effective_academic_year and z.school_type='MESEM' and z.program_type='MESEM' and z.field_name='Güzellik ve Saç Bakım Hizmetleri' and z.branch_name=b.branch_name and z.grade_level=t.grade_level and z.schedule_variant=t.schedule_variant);
with b(branch_name,source_page) as (values ('Cilt Bakımı ve Makyaj',7::smallint),('Kadın Kuaförlüğü',8::smallint),('Erkek Kuaförlüğü',9::smallint)), generic_names(name) as (values ('Türk Dili ve Edebiyatı'),('Din Kültürü ve Ahlak Bilgisi'),('Matematik'),('Tarih'),('T.C. İnkılap Tarihi ve Atatürkçülük'),('İşletmelerde Mesleki Eğitim'))
insert into public.official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,'MESEM','MESEM',s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_guzellik_mem_cop.pdf','MTEGM 2021-33 Güzellik ve Saç Bakım Hizmetleri MESEM',true,'Güzellik ve Saç Bakım Hizmetleri',b.branch_name,s.parsed_constraints,s.school_subtype,'2021-33',b.source_page,'Haftalık Ders Çizelgesi',1.000,false,s.schedule_variant
from public.official_course_schedule_catalog s join public.course_catalog c on c.id=s.course_id cross join b
where s.school_type='MESEM' and s.field_name='Ayakkabı ve Saraciye Teknolojisi' and s.branch_name='Ayakkabı Modelistliği' and c.name in(select name from generic_names)
and not exists(select 1 from public.official_course_schedule_catalog z where z.effective_academic_year=s.effective_academic_year and z.school_type='MESEM' and coalesce(z.program_type,'')='MESEM' and coalesce(z.field_name,'')='Güzellik ve Saç Bakım Hizmetleri' and coalesce(z.branch_name,'')=b.branch_name and z.grade_level=s.grade_level and z.course_id=s.course_id and coalesce(z.schedule_variant,'STANDARD')=coalesce(s.schedule_variant,'STANDARD'));
with v(branch_name,source_page,grade_level,course_name,hours) as (values
('Cilt Bakımı ve Makyaj',7,9,'Mesleğe Giriş',2),('Cilt Bakımı ve Makyaj',7,10,'Temel Bakım',1),('Cilt Bakımı ve Makyaj',7,10,'Kozmetik',1),('Cilt Bakımı ve Makyaj',7,10,'Mesleki Resim',1),('Cilt Bakımı ve Makyaj',7,10,'Temel Anatomi ve Fizyoloji',1),('Cilt Bakımı ve Makyaj',7,11,'Cilt Bakım Teknikleri',2),('Cilt Bakımı ve Makyaj',7,11,'Temel Makyaj',2),('Cilt Bakımı ve Makyaj',7,11,'Epilasyon',2),('Cilt Bakımı ve Makyaj',7,11,'Depilasyon',1),('Cilt Bakımı ve Makyaj',7,12,'Ahilik Kültürü ve Girişimcilik',1),('Cilt Bakımı ve Makyaj',7,12,'Temel Beslenme',1),('Cilt Bakımı ve Makyaj',7,12,'İleri Makyaj',2),('Cilt Bakımı ve Makyaj',7,12,'Vücut Bakımı',1),('Cilt Bakımı ve Makyaj',7,12,'El Ayak Bakımı',2),('Cilt Bakımı ve Makyaj',7,12,'Diksiyon',1),
('Kadın Kuaförlüğü',8,9,'Mesleğe Giriş',2),('Kadın Kuaförlüğü',8,10,'Temel Bakım',1),('Kadın Kuaförlüğü',8,10,'Kozmetik',1),('Kadın Kuaförlüğü',8,10,'Mesleki Resim',1),('Kadın Kuaförlüğü',8,10,'Temel Anatomi ve Fizyoloji',1),('Kadın Kuaförlüğü',8,11,'Kadın Saç Şekillendirme ve Renklendirme',4),('Kadın Kuaförlüğü',8,11,'Kadın Saç Kesim Teknikleri',3),('Kadın Kuaförlüğü',8,12,'Ahilik Kültürü ve Girişimcilik',1),('Kadın Kuaförlüğü',8,12,'Temel Beslenme',1),('Kadın Kuaförlüğü',8,12,'Temel Makyaj',2),('Kadın Kuaförlüğü',8,12,'Depilasyon',1),('Kadın Kuaförlüğü',8,12,'El Ayak Bakımı',2),('Kadın Kuaförlüğü',8,12,'Diksiyon',1),
('Erkek Kuaförlüğü',9,9,'Mesleğe Giriş',2),('Erkek Kuaförlüğü',9,10,'Temel Bakım',1),('Erkek Kuaförlüğü',9,10,'Kozmetik',1),('Erkek Kuaförlüğü',9,10,'Mesleki Resim',1),('Erkek Kuaförlüğü',9,10,'Temel Anatomi ve Fizyoloji',1),('Erkek Kuaförlüğü',9,11,'Erkek Saç Şekillendirme ve Renklendirme',3),('Erkek Kuaförlüğü',9,11,'Erkek Saç Kesim Teknikleri',3),('Erkek Kuaförlüğü',9,11,'Sakal Bıyık Tıraşı',1),('Erkek Kuaförlüğü',9,12,'Ahilik Kültürü ve Girişimcilik',1),('Erkek Kuaförlüğü',9,12,'Temel Beslenme',1),('Erkek Kuaförlüğü',9,12,'Temel Makyaj',2),('Erkek Kuaförlüğü',9,12,'Depilasyon',1),('Erkek Kuaförlüğü',9,12,'El Ayak Bakımı',2),('Erkek Kuaförlüğü',9,12,'Diksiyon',1)), variants(v) as (values ('USTALIK'),('DIPLOMA'))
insert into public.official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',v.grade_level,c.id,'uygulama',array[v.hours]::smallint[],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_guzellik_mem_cop.pdf','MTEGM 2021-33 Güzellik ve Saç Bakım Hizmetleri MESEM',true,'Güzellik ve Saç Bakım Hizmetleri',v.branch_name,'{}'::jsonb,'2021-33',v.source_page,'Haftalık Ders Çizelgesi',1.000,false,x.v
from v join public.course_catalog c on c.name=v.course_name cross join variants x
where not exists(select 1 from public.official_course_schedule_catalog z where z.effective_academic_year='2026-2027' and z.school_type='MESEM' and coalesce(z.program_type,'')='MESEM' and coalesce(z.field_name,'')='Güzellik ve Saç Bakım Hizmetleri' and coalesce(z.branch_name,'')=v.branch_name and z.grade_level=v.grade_level and z.course_id=c.id and coalesce(z.schedule_variant,'STANDARD')=x.v);
commit;
