begin;
insert into public.course_catalog(name,category)
select x,'uygulama' from unnest(array['Grafik Tasarım ve Fotoğrafçılık','Temel Tasarım','Temel Fotoğraf','Temel Desen','Perspektif','Ahilik Kültürü ve Girişimcilik','Bilgisayar Destekli Grafik Tasarım','Desen','Grafik Desen','İllüstrasyon','Grafik ve Sanat Tarihi','Ambalaj Tasarımı','Yayın Grafiği','Fotoğraf Çekimi','Bilgisayarda Fotoğraf','Görüntü Yorumlama','Video Çekimi','Çekim Teknikleri','Fotoğraf Sunumu','Animasyon Atölyesi','İki ve Üç Boyutlu Animasyon','Karakter Tasarımı','Animasyon Projesi']) x on conflict(name) do nothing;
with b(branch_name,source_page) as (values ('Grafik',7::smallint),('Fotoğraf',8::smallint),('Animasyon',9::smallint))
insert into public.official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select t.effective_academic_year,t.school_type,t.school_subtype,t.program_type,'Grafik ve Fotoğraf',b.branch_name,t.grade_level,t.required_course_count,t.required_hour_total,t.elective_course_min,t.elective_course_max,t.elective_hour_min,t.elective_hour_max,t.total_hour_min,t.total_hour_max,t.total_hour_target,t.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_grafik_mem_cop.pdf','2021-33','MTEGM 2021-33 Grafik ve Fotoğraf MESEM; parantezli saatler diploma fark dersleridir.',true,t.schedule_variant,t.common_hours,t.vocational_hours,t.elective_vocational_hours,t.elective_hours,t.guidance_hours,t.enterprise_hours,'CURRENTLY_VALID',b.source_page,t.parsed_constraints,t.academic_support_hours
from public.official_curriculum_profiles t cross join b
where t.school_type='MESEM' and t.field_name='Ayakkabı ve Saraciye Teknolojisi' and t.branch_name='Ayakkabı Modelistliği'
and not exists(select 1 from public.official_curriculum_profiles z where z.effective_academic_year=t.effective_academic_year and z.school_type='MESEM' and z.program_type='MESEM' and z.field_name='Grafik ve Fotoğraf' and z.branch_name=b.branch_name and z.grade_level=t.grade_level and z.schedule_variant=t.schedule_variant);
with b(branch_name,source_page) as (values ('Grafik',7::smallint),('Fotoğraf',8::smallint),('Animasyon',9::smallint)), generic_names(name) as (values ('Türk Dili ve Edebiyatı'),('Din Kültürü ve Ahlak Bilgisi'),('Matematik'),('Tarih'),('T.C. İnkılap Tarihi ve Atatürkçülük'),('İşletmelerde Mesleki Eğitim'))
insert into public.official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,'MESEM','MESEM',s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_grafik_mem_cop.pdf','MTEGM 2021-33 Grafik ve Fotoğraf MESEM',true,'Grafik ve Fotoğraf',b.branch_name,s.parsed_constraints,s.school_subtype,'2021-33',b.source_page,'Haftalık Ders Çizelgesi',1.000,false,s.schedule_variant
from public.official_course_schedule_catalog s join public.course_catalog c on c.id=s.course_id cross join b
where s.school_type='MESEM' and s.field_name='Ayakkabı ve Saraciye Teknolojisi' and s.branch_name='Ayakkabı Modelistliği' and c.name in(select name from generic_names)
and not exists(select 1 from public.official_course_schedule_catalog z where z.effective_academic_year=s.effective_academic_year and z.school_type='MESEM' and coalesce(z.program_type,'')='MESEM' and coalesce(z.field_name,'')='Grafik ve Fotoğraf' and coalesce(z.branch_name,'')=b.branch_name and z.grade_level=s.grade_level and z.course_id=s.course_id and coalesce(z.schedule_variant,'STANDARD')=coalesce(s.schedule_variant,'STANDARD'));
with v(branch_name,source_page,grade_level,course_name,hours) as (values
('Grafik',7,9,'Grafik Tasarım ve Fotoğrafçılık',2),('Grafik',7,10,'Temel Tasarım',1),('Grafik',7,10,'Temel Fotoğraf',1),('Grafik',7,10,'Temel Desen',1),('Grafik',7,10,'Perspektif',1),('Grafik',7,11,'Bilgisayar Destekli Grafik Tasarım',4),('Grafik',7,11,'Desen',1),('Grafik',7,11,'Grafik Desen',2),('Grafik',7,12,'Ahilik Kültürü ve Girişimcilik',1),('Grafik',7,12,'İllüstrasyon',2),('Grafik',7,12,'Grafik ve Sanat Tarihi',1),('Grafik',7,12,'Ambalaj Tasarımı',2),('Grafik',7,12,'Yayın Grafiği',2),
('Fotoğraf',8,9,'Grafik Tasarım ve Fotoğrafçılık',2),('Fotoğraf',8,10,'Temel Tasarım',1),('Fotoğraf',8,10,'Temel Fotoğraf',1),('Fotoğraf',8,10,'Temel Desen',1),('Fotoğraf',8,10,'Perspektif',1),('Fotoğraf',8,11,'Fotoğraf Çekimi',3),('Fotoğraf',8,11,'Bilgisayarda Fotoğraf',3),('Fotoğraf',8,11,'Görüntü Yorumlama',1),('Fotoğraf',8,12,'Ahilik Kültürü ve Girişimcilik',1),('Fotoğraf',8,12,'Video Çekimi',2),('Fotoğraf',8,12,'Çekim Teknikleri',4),('Fotoğraf',8,12,'Fotoğraf Sunumu',1),
('Animasyon',9,9,'Grafik Tasarım ve Fotoğrafçılık',2),('Animasyon',9,10,'Temel Tasarım',1),('Animasyon',9,10,'Temel Fotoğraf',1),('Animasyon',9,10,'Temel Desen',1),('Animasyon',9,10,'Perspektif',1),('Animasyon',9,11,'Animasyon Atölyesi',3),('Animasyon',9,11,'İki ve Üç Boyutlu Animasyon',4),('Animasyon',9,12,'Ahilik Kültürü ve Girişimcilik',1),('Animasyon',9,12,'Karakter Tasarımı',3),('Animasyon',9,12,'Animasyon Projesi',4)), variants(v) as (values ('USTALIK'),('DIPLOMA'))
insert into public.official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',v.grade_level,c.id,'uygulama',array[v.hours]::smallint[],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_grafik_mem_cop.pdf','MTEGM 2021-33 Grafik ve Fotoğraf MESEM',true,'Grafik ve Fotoğraf',v.branch_name,'{}'::jsonb,'2021-33',v.source_page,'Haftalık Ders Çizelgesi',1.000,false,x.v
from v join public.course_catalog c on c.name=v.course_name cross join variants x
where not exists(select 1 from public.official_course_schedule_catalog z where z.effective_academic_year='2026-2027' and z.school_type='MESEM' and coalesce(z.program_type,'')='MESEM' and coalesce(z.field_name,'')='Grafik ve Fotoğraf' and coalesce(z.branch_name,'')=v.branch_name and z.grade_level=v.grade_level and z.course_id=c.id and coalesce(z.schedule_variant,'STANDARD')=x.v);
commit;
