DO $$
DECLARE src text:='https://meslek.meb.gov.tr/upload/cop9_mem/2021_tesisat_mem_cop.pdf'; vv_branch text; vv_variant text; vv_grade int; vv_course text; vv_hours int;
BEGIN
CREATE TEMP TABLE _tb(branch text, grade int, course text, hours int) ON COMMIT DROP;
INSERT INTO _tb VALUES
('Gaz Tesisat Sistemleri',11,'Doğal Gaz Bina İçi Tesisatı',4),('Gaz Tesisat Sistemleri',11,'Biyogaz Sistemleri',3),('Gaz Tesisat Sistemleri',12,'Doğal Gaz Altyapım ve İşletme',4),('Gaz Tesisat Sistemleri',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Gaz Yakıcı Cihazlar ve Servis',11,'Doğal Gaz Bina İçi Tesisatı',4),('Gaz Yakıcı Cihazlar ve Servis',11,'Bacalar ve Yanma Verimliliği',3),('Gaz Yakıcı Cihazlar ve Servis',12,'Gaz Yakıcı Cihazlar',4),('Gaz Yakıcı Cihazlar ve Servis',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Isıtma ve Sıhhi Tesisat Sistemleri',11,'Isıtma Tesisatı',4),('Isıtma ve Sıhhi Tesisat Sistemleri',11,'Isıtma Sistemleri Servisi',3),('Isıtma ve Sıhhi Tesisat Sistemleri',12,'Sıhhi Tesisat',4),('Isıtma ve Sıhhi Tesisat Sistemleri',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Kazan Yakma ve Bakımı',11,'Yakıtlar ve Yanma Teknolojisi',1),('Kazan Yakma ve Bakımı',11,'Bacalar ve Yanma Verimliliği',3),('Kazan Yakma ve Bakımı',11,'Kazan Yakma Teknikleri',3),('Kazan Yakma ve Bakımı',12,'Endüstriyel Kazanlar',4),('Kazan Yakma ve Bakımı',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Güneş Enerjisi ve Tesisat Sistemleri',11,'Alternatif Enerji Kaynakları',3),('Güneş Enerjisi ve Tesisat Sistemleri',11,'Sıhhi Tesisat',4),('Güneş Enerjisi ve Tesisat Sistemleri',12,'Sıhhi Tesisat Servis Hizmetleri',2),('Güneş Enerjisi ve Tesisat Sistemleri',12,'Güneş Isıl İşlemleri',2),('Güneş Enerjisi ve Tesisat Sistemleri',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Su Arıtma Sistemleri',11,'Su Arıtma ve Atık Su',3),('Su Arıtma Sistemleri',11,'Sıhhi Tesisat',4),('Su Arıtma Sistemleri',12,'Vanalar ve Pompalar',4),('Su Arıtma Sistemleri',12,'Bilgisayar Destekli Tesisat Meslek Resmi',3),
('Soğutma Sistemleri',11,'Basit Soğutma Devreleri',4),('Soğutma Sistemleri',11,'Soğuk Oda Montajı',3),('Soğutma Sistemleri',12,'Soğutucuların Bakım ve Onarımı',3),('Soğutma Sistemleri',12,'Frigorifik Araç ve Araç Klimaları',1),('Soğutma Sistemleri',12,'Bilgisayar Destekli Soğutma Meslek Resmi',3),
('İklimlendirme Sistemleri',11,'Basit Soğutma Devreleri',4),('İklimlendirme Sistemleri',11,'Klimaların Bakım ve Onarımı',3),('İklimlendirme Sistemleri',12,'Havalandırma Sistemleri',3),('İklimlendirme Sistemleri',12,'Frigorifik Araç ve Araç Klimaları',1),('İklimlendirme Sistemleri',12,'Bilgisayar Destekli İklimlendirme Meslek Resmi',3);
CREATE TEMP TABLE _branches AS SELECT ob.branch_name branch FROM official_vocational_branches ob JOIN official_vocational_fields f ON f.id=ob.field_id WHERE f.institution_type='MESEM' AND f.field_name='Tesisat Teknolojisi ve İklimlendirme' AND ob.active;
FOR vv_course,vv_hours IN SELECT t.course,t.hours FROM _tb t UNION SELECT x.course,x.hours FROM (VALUES ('Tesisat Teknolojisine Giriş',2),('Tesisat',1),('Boru Kaynakçılığı',1),('Tesisat Teknik Resmi',1),('Tesisat Elektriği',1),('Ahilik Kültürü ve Girişimcilik',1))x(course,hours) LOOP INSERT INTO course_catalog(name,category) VALUES(vv_course,'uygulama') ON CONFLICT(name) DO NOTHING; END LOOP;
INSERT INTO official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
SELECT p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,'Tesisat Teknolojisi ve İklimlendirme',bb.branch,p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,src,'2021-33','2021-33 yaşayan MESEM Tesisat Teknolojisi ve İklimlendirme çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,p.schedule_variant,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,'CURRENTLY_VALID',10,p.parsed_constraints,p.academic_support_hours
FROM (SELECT DISTINCT ON(grade_level,schedule_variant) * FROM official_curriculum_profiles WHERE active AND school_type='MESEM' AND source_decision_no='2021-33' AND field_name='Tekstil Teknolojisi' ORDER BY grade_level,schedule_variant) p CROSS JOIN _branches bb ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,school_subtype,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT s.effective_academic_year,s.school_type,s.school_subtype,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,src,'2021-33 Tesisat',true,'Tesisat Teknolojisi ve İklimlendirme',bb.branch,s.parsed_constraints,'2021-33',10,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant
FROM official_course_schedule_catalog s JOIN course_catalog cc ON cc.id=s.course_id CROSS JOIN _branches bb WHERE s.active AND s.school_type='MESEM' AND s.field_name='Tekstil Teknolojisi' AND s.branch_name='Dokuma Operatörlüğü' AND (s.category='zorunlu' OR cc.name='İşletmelerde Mesleki Eğitim') ON CONFLICT DO NOTHING;
FOR vv_branch IN SELECT branch FROM _branches LOOP
 FOR vv_variant IN SELECT unnest(ARRAY['USTALIK','DIPLOMA']) LOOP
  FOR vv_grade,vv_course,vv_hours IN SELECT * FROM (VALUES (9,'Tesisat Teknolojisine Giriş',2),(10,'Tesisat',1),(10,'Boru Kaynakçılığı',1),(10,'Tesisat Teknik Resmi',1),(10,'Tesisat Elektriği',1),(12,'Ahilik Kültürü ve Girişimcilik',1))q LOOP
   INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,source_file_name,source_note,active,field_name,branch_name,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
   SELECT '2026-2027','MESEM','MESEM',vv_grade,id,'uygulama',ARRAY[vv_hours],src,'2021-33 Tesisat',true,'Tesisat Teknolojisi ve İklimlendirme',vv_branch,'2021-33',10,'HAFTALIK DERS ÇİZELGESİ',1,false,vv_variant FROM course_catalog WHERE name=vv_course ON CONFLICT DO NOTHING;
  END LOOP;
 END LOOP;
END LOOP;
FOR vv_branch,vv_grade,vv_course,vv_hours IN SELECT t.branch,t.grade,t.course,t.hours FROM _tb t LOOP
 FOR vv_variant IN SELECT unnest(ARRAY['USTALIK','DIPLOMA']) LOOP
  INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,source_file_name,source_note,active,field_name,branch_name,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
  SELECT '2026-2027','MESEM','MESEM',vv_grade,id,'uygulama',ARRAY[vv_hours],src,'2021-33 Tesisat',true,'Tesisat Teknolojisi ve İklimlendirme',vv_branch,'2021-33',CASE WHEN vv_grade=11 THEN 10 ELSE 11 END,'HAFTALIK DERS ÇİZELGESİ',1,false,vv_variant FROM course_catalog WHERE name=vv_course ON CONFLICT DO NOTHING;
 END LOOP;
END LOOP;
END $$;