do $$
declare v text; g int; src uuid;
begin
for v in select unnest(array['USTALIK','DIPLOMA']) loop
 for g in 9..12 loop
  select p.id into src from official_curriculum_profiles p where p.active and p.school_type='MESEM' and p.field_name='Makine Teknolojisi' and p.branch_name='Anahtarcılık ve Çilingirlik' and p.grade_level=g and p.schedule_variant=v limit 1;
  insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
  select p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,'Muhasebe ve Finansman','Muhasebe',p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_muhasebe_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Muhasebe ve Finansman çizelgesi; parantezli saatler diploma fark dersidir.',true,v,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,'CURRENTLY_VALID',5,p.parsed_constraints,p.academic_support_hours from official_curriculum_profiles p where p.id=src
  on conflict (effective_academic_year,school_type,coalesce(school_subtype,''),coalesce(program_type,''),coalesce(field_name,''),coalesce(branch_name,''),grade_level,coalesce(schedule_variant,'STANDARD')) do update set active=true,source_file_name=excluded.source_file_name,source_decision_no=excluded.source_decision_no,source_note=excluded.source_note,updated_at=now();
  delete from official_course_schedule_catalog x where x.active and x.school_type='MESEM' and x.field_name='Muhasebe ve Finansman' and x.branch_name='Muhasebe' and x.grade_level=g and x.schedule_variant=v;
  insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
  select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_muhasebe_mem_cop.pdf','2021-33 Muhasebe',true,'Muhasebe ve Finansman','Muhasebe',s.parsed_constraints,s.school_subtype,'2021-33',5,s.source_section,1,false,v from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id where s.active and s.school_type='MESEM' and s.field_name='Makine Teknolojisi' and s.branch_name='Anahtarcılık ve Çilingirlik' and s.grade_level=g and s.schedule_variant=v and c.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','İşletmelerde Mesleki Eğitim');
 end loop;
end loop;
insert into course_catalog(name,category,active) select x,'uygulama',true from unnest(array['Muhasebeye Giriş','Temel Muhasebe','Mesleki Matematik','Ekonomi','Klavye Teknikleri','Ofis Uygulamaları','Temel Hukuk','Ahilik Kültürü ve Girişimcilik','Genel Muhasebe','Vergi ve Beyannameler','Bilgisayarlı Muhasebe','Şirketler Muhasebesi','Maliyet Muhasebesi','Girişimcilik ve İşletme Yönetimi']) x where not exists(select 1 from course_catalog c where c.name=x);
with d(g,n,h) as (values (9,'Muhasebeye Giriş',2),(10,'Temel Muhasebe',2),(10,'Mesleki Matematik',1),(10,'Ekonomi',1),(11,'Klavye Teknikleri',2),(11,'Ofis Uygulamaları',1),(11,'Temel Hukuk',1),(11,'Genel Muhasebe',2),(11,'Vergi ve Beyannameler',1),(12,'Ahilik Kültürü ve Girişimcilik',1),(12,'Bilgisayarlı Muhasebe',4),(12,'Şirketler Muhasebesi',1),(12,'Maliyet Muhasebesi',1),(12,'Girişimcilik ve İşletme Yönetimi',1)) insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,parser_confidence,needs_review,schedule_variant) select '2026-2027','MESEM','MESEM',d.g,c.id,'uygulama',array[d.h],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_muhasebe_mem_cop.pdf','2021-33 Muhasebe',true,'Muhasebe ve Finansman','Muhasebe','[]'::jsonb,'2021-33',5,1,false,v.v from d join course_catalog c on c.name=d.n cross join (values('USTALIK'),('DIPLOMA')) v(v);
end $$;