begin;
with br(branch_name,page) as (values
('Endüstri Bitkileri Yetiştiriciliği',13),('Mantar Yetiştiriciliği',14),('Meyve Yetiştiriciliği',15),('Orman Yetiştiriciliği',16),('Sebze Yetiştiriciliği',17),('Seracılık',18),('Tarla Bitkileri Yetiştiriciliği',19),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',20))
insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,updated_at,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select p.effective_academic_year,p.school_type,p.school_subtype,p.program_type,p.field_name,br.branch_name,p.grade_level,p.required_course_count,p.required_hour_total,p.elective_course_min,p.elective_course_max,p.elective_hour_min,p.elective_hour_max,p.total_hour_min,p.total_hour_max,p.total_hour_target,p.group_rules,p.source_file_name,p.source_decision_no,p.source_note,p.active,now(),p.schedule_variant,p.common_hours,p.vocational_hours,p.elective_vocational_hours,p.elective_hours,p.guidance_hours,p.enterprise_hours,p.applicability_status,br.page,p.parsed_constraints,p.academic_support_hours
from official_curriculum_profiles p cross join br
where p.active and p.school_type='MESEM' and p.field_name='Tarım' and p.branch_name='Bağcılık'
and not exists(select 1 from official_curriculum_profiles x where x.effective_academic_year=p.effective_academic_year and x.school_type=p.school_type and coalesce(x.school_subtype,'')=coalesce(p.school_subtype,'') and coalesce(x.program_type,'')=coalesce(p.program_type,'') and x.field_name='Tarım' and x.branch_name=br.branch_name and x.grade_level=p.grade_level and x.schedule_variant=p.schedule_variant);

with br(branch_name,page) as (values
('Endüstri Bitkileri Yetiştiriciliği',13),('Mantar Yetiştiriciliği',14),('Meyve Yetiştiriciliği',15),('Orman Yetiştiriciliği',16),('Sebze Yetiştiriciliği',17),('Seracılık',18),('Tarla Bitkileri Yetiştiriciliği',19),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',20)),
common(name) as (values ('Türk Dili ve Edebiyatı'),('Din Kültürü ve Ahlak Bilgisi'),('Matematik'),('Tarih'),('T.C. İnkılap Tarihi ve Atatürkçülük'),('Tarımsal Üretime Giriş'),('Üretme ve Çoğaltma Teknikleri'),('Sürdürülebilir Tarım Teknikleri'),('Temel Bitki Sağlığı'),('Toprak ve Bitki Besleme'),('Ahilik Kültürü ve Girişimcilik'),('İşletmelerde Mesleki Eğitim'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,imported_at,updated_at,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_decision_date,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,s.source_file_name,s.source_note,true,now(),now(),'Tarım',br.branch_name,s.parsed_constraints,s.school_subtype,s.source_decision_no,s.source_decision_date,br.page,s.source_section,s.parser_confidence,false,s.schedule_variant
from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id join common cm on cm.name=c.name cross join br
where s.active and s.school_type='MESEM' and s.field_name='Tarım' and s.branch_name='Bağcılık'
and not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year=s.effective_academic_year and x.school_type=s.school_type and coalesce(x.school_subtype,'')=coalesce(s.school_subtype,'') and coalesce(x.program_type,'')=coalesce(s.program_type,'') and x.field_name='Tarım' and x.branch_name=br.branch_name and x.grade_level=s.grade_level and x.schedule_variant=s.schedule_variant and x.course_id=s.course_id);

with d(branch_name,grade_level,name,h,page) as (values
('Endüstri Bitkileri Yetiştiriciliği',11,'Yağ Bitkileri',2,13),('Endüstri Bitkileri Yetiştiriciliği',12,'Nişasta ve Şeker Bitkileri',4,13),('Endüstri Bitkileri Yetiştiriciliği',12,'Lif ve Keyf Bitkileri',3,13),
('Mantar Yetiştiriciliği',11,'Mantar Üretim Hazırlıkları',2,14),('Mantar Yetiştiriciliği',12,'Kompost Yapım Tekniği',3,14),('Mantar Yetiştiriciliği',12,'Mantar Üretimi',4,14),
('Meyve Yetiştiriciliği',11,'Fidan Üretimi',2,15),('Meyve Yetiştiriciliği',12,'Meyve Ağaçlarında Budama ve Terbiye',2,15),('Meyve Yetiştiriciliği',12,'Ilıman İklim Meyveleri',3,15),('Meyve Yetiştiriciliği',12,'Sıcak İklim Meyveleri',2,15),
('Orman Yetiştiriciliği',11,'Temel Ormancılık Bilgisi',2,16),('Orman Yetiştiriciliği',12,'Ağaçlandırma',2,16),('Orman Yetiştiriciliği',12,'Silvikültür Tekniği',3,16),('Orman Yetiştiriciliği',12,'Odun Dışı Ürünler',2,16),
('Sebze Yetiştiriciliği',11,'Alternatif Tarım Teknikleri',2,17),('Sebze Yetiştiriciliği',12,'Örtü Altı Sistemleri',2,17),('Sebze Yetiştiriciliği',12,'Yazlık Sebzeler',2,17),('Sebze Yetiştiriciliği',12,'Kışlık Sebzeler',3,17),
('Seracılık',11,'Alternatif Tarım Teknikleri',2,18),('Seracılık',12,'Örtü Altı Sistemleri',2,18),('Seracılık',12,'Örtü Altı Yetiştiriciliği',5,18),
('Tarla Bitkileri Yetiştiriciliği',11,'Yemeklik Tane Baklagiller',2,19),('Tarla Bitkileri Yetiştiriciliği',12,'Tahıllar',4,19),('Tarla Bitkileri Yetiştiriciliği',12,'Çayır-Mera ve Yem Bitkileri',3,19),
('Tıbbi Aromatik Bitkiler Yetiştiriciliği',11,'Tıbbi Aromatik Bitkiler',2,20),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',12,'Tek ve Çok Yıllık Tıbbi Aromatik Bitkilerin Üretimi',4,20),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',12,'Tıbbi Aromatik Bitkilerde Hasat ve Drog Hazırlama',3,20))
insert into course_catalog(name,category)
select distinct name,'uygulama' from d on conflict(name) do nothing;

with d(branch_name,grade_level,name,h,page) as (values
('Endüstri Bitkileri Yetiştiriciliği',11,'Yağ Bitkileri',2,13),('Endüstri Bitkileri Yetiştiriciliği',12,'Nişasta ve Şeker Bitkileri',4,13),('Endüstri Bitkileri Yetiştiriciliği',12,'Lif ve Keyf Bitkileri',3,13),
('Mantar Yetiştiriciliği',11,'Mantar Üretim Hazırlıkları',2,14),('Mantar Yetiştiriciliği',12,'Kompost Yapım Tekniği',3,14),('Mantar Yetiştiriciliği',12,'Mantar Üretimi',4,14),
('Meyve Yetiştiriciliği',11,'Fidan Üretimi',2,15),('Meyve Yetiştiriciliği',12,'Meyve Ağaçlarında Budama ve Terbiye',2,15),('Meyve Yetiştiriciliği',12,'Ilıman İklim Meyveleri',3,15),('Meyve Yetiştiriciliği',12,'Sıcak İklim Meyveleri',2,15),
('Orman Yetiştiriciliği',11,'Temel Ormancılık Bilgisi',2,16),('Orman Yetiştiriciliği',12,'Ağaçlandırma',2,16),('Orman Yetiştiriciliği',12,'Silvikültür Tekniği',3,16),('Orman Yetiştiriciliği',12,'Odun Dışı Ürünler',2,16),
('Sebze Yetiştiriciliği',11,'Alternatif Tarım Teknikleri',2,17),('Sebze Yetiştiriciliği',12,'Örtü Altı Sistemleri',2,17),('Sebze Yetiştiriciliği',12,'Yazlık Sebzeler',2,17),('Sebze Yetiştiriciliği',12,'Kışlık Sebzeler',3,17),
('Seracılık',11,'Alternatif Tarım Teknikleri',2,18),('Seracılık',12,'Örtü Altı Sistemleri',2,18),('Seracılık',12,'Örtü Altı Yetiştiriciliği',5,18),
('Tarla Bitkileri Yetiştiriciliği',11,'Yemeklik Tane Baklagiller',2,19),('Tarla Bitkileri Yetiştiriciliği',12,'Tahıllar',4,19),('Tarla Bitkileri Yetiştiriciliği',12,'Çayır-Mera ve Yem Bitkileri',3,19),
('Tıbbi Aromatik Bitkiler Yetiştiriciliği',11,'Tıbbi Aromatik Bitkiler',2,20),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',12,'Tek ve Çok Yıllık Tıbbi Aromatik Bitkilerin Üretimi',4,20),('Tıbbi Aromatik Bitkiler Yetiştiriciliği',12,'Tıbbi Aromatik Bitkilerde Hasat ve Drog Hazırlama',3,20)),v(schedule_variant) as (values('USTALIK'),('DIPLOMA'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,imported_at,updated_at,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',d.grade_level,c.id,'uygulama',array[d.h],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2022_tarim_mem_cop.pdf','2023-3 yaşayan MESEM Tarım çizelgesi; parantezli saatler DIPLOMA fark dersidir.',true,now(),now(),'Tarım',d.branch_name,'{"enterpriseDays":4,"enterpriseHoursPerDay":8}'::jsonb,'2023-3',d.page,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant
from d join course_catalog c on c.name=d.name cross join v
where not exists(select 1 from official_course_schedule_catalog x where x.active and x.effective_academic_year='2026-2027' and x.school_type='MESEM' and coalesce(x.program_type,'')='MESEM' and x.field_name='Tarım' and x.branch_name=d.branch_name and x.grade_level=d.grade_level and x.schedule_variant=v.schedule_variant and x.course_id=c.id);
commit;