CREATE TABLE IF NOT EXISTS public.schedule_solver_operator_telemetry(institution_code text NOT NULL,context_key text NOT NULL,strategy text NOT NULL CHECK(strategy IN('LATE_ACCEPTANCE','TABU','SIMULATED_ANNEALING','GREAT_DELUGE','VND')),attempts bigint NOT NULL DEFAULT 0,wins bigint NOT NULL DEFAULT 0,reward_sum double precision NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(institution_code,context_key,strategy));
ALTER TABLE public.schedule_solver_operator_telemetry ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS schedule_solver_operator_telemetry_tenant ON public.schedule_solver_operator_telemetry;
CREATE POLICY schedule_solver_operator_telemetry_tenant ON public.schedule_solver_operator_telemetry USING(institution_code=current_tenant_code()) WITH CHECK(institution_code=current_tenant_code());
CREATE OR REPLACE FUNCTION public.get_schedule_solver_operator_priors_v1(p_context_key text) RETURNS TABLE(strategy text,attempts bigint,wins bigint,reward_sum double precision) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT t.strategy,t.attempts,t.wins,t.reward_sum FROM public.schedule_solver_operator_telemetry t WHERE t.institution_code=current_tenant_code() AND t.context_key=p_context_key ORDER BY t.strategy $$;
CREATE OR REPLACE FUNCTION public.record_schedule_solver_operator_telemetry_v1(p_context_key text,p_observations jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_tenant text:=current_tenant_code(); r jsonb; BEGIN IF v_tenant IS NULL THEN RAISE EXCEPTION 'TENANT_REQUIRED'; END IF; FOR r IN SELECT value FROM jsonb_array_elements(COALESCE(p_observations,'[]'::jsonb)) LOOP INSERT INTO public.schedule_solver_operator_telemetry(institution_code,context_key,strategy,attempts,wins,reward_sum,updated_at) VALUES(v_tenant,p_context_key,r->>'strategy',1,CASE WHEN COALESCE((r->>'win')::boolean,false) THEN 1 ELSE 0 END,COALESCE((r->>'reward')::double precision,0),now()) ON CONFLICT(institution_code,context_key,strategy) DO UPDATE SET attempts=schedule_solver_operator_telemetry.attempts+1,wins=schedule_solver_operator_telemetry.wins+EXCLUDED.wins,reward_sum=schedule_solver_operator_telemetry.reward_sum+EXCLUDED.reward_sum,updated_at=now(); END LOOP; END $$;
GRANT SELECT ON public.schedule_solver_operator_telemetry TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_schedule_solver_operator_priors_v1(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_schedule_solver_operator_telemetry_v1(text,jsonb) TO authenticated;
