create table if not exists official_curriculum_catalog_status(institution_type text not null,field_name text not null,branch_name text not null,status text not null check(status in('FULL_PROGRAM','MODULAR_PARTIAL','PROTOCOL_ONLY','PROGRAM_PENDING')),reason text,source_url text,updated_at timestamptz not null default now(),primary key(institution_type,field_name,branch_name));
insert into official_curriculum_catalog_status(institution_type,field_name,branch_name,status,reason,source_url) values
('MESEM','Ulaştırma Hizmetleri','Kargo ve Kurye Hizmetleri','MODULAR_PARTIAL','Resmî MESEM alan-dal listesinde; modüler içerik doğrulandı, bağımsız haftalık çizelge henüz doğrulanmadı','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Ulaştırma Hizmetleri','Otopark ve Vale Hizmetleri','PROGRAM_PENDING','Resmî MESEM alan-dal listesinde; yayımlanmış haftalık çizelge henüz doğrulanmadı','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Gazetecilik (Protokol Kapsamında)','Medya Yazılımı','PROTOCOL_ONLY','Resmî MESEM alan-dal listesinde protokol kapsamında; genel MEM haftalık çizelgesi yayımlı değil','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Gazetecilik (Protokol Kapsamında)','Sosyal Medya','PROTOCOL_ONLY','Resmî MESEM alan-dal listesinde protokol kapsamında; genel MEM haftalık çizelgesi yayımlı değil','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Gazetecilik (Protokol Kapsamında)','Web İçerik Editörü','PROTOCOL_ONLY','Resmî MESEM alan-dal listesinde protokol kapsamında; genel MEM haftalık çizelgesi yayımlı değil','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Radyo-Televizyon (Protokol Kapsamında)','Video, Ses Üretim ve Kurgu','PROTOCOL_ONLY','Resmî MESEM alan-dal listesinde protokol kapsamında; genel MEM haftalık çizelgesi yayımlı değil','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MESEM','Uçak Bakım (Protokol Kapsamında)','Hava Aracı Montaj','PROTOCOL_ONLY','Resmî MESEM alan-dal listesinde protokol kapsamında; genel MEM haftalık çizelgesi yayımlı değil','https://meslek.meb.gov.tr/dokumanlar/alan_dal_listesi_08092025.pdf'),
('MTAL','Gastronomi ve Mutfak Sanatları','Mutfak Sanatları','PROGRAM_PENDING','2026-2027 bölgesel program biliniyor; doğrulanmış haftalık PDF sisteme alınamadı',null),
('MTAL','Gastronomi ve Mutfak Sanatları','Pastacılık ve Ekmekçilik','PROGRAM_PENDING','2026-2027 bölgesel program biliniyor; doğrulanmış haftalık PDF sisteme alınamadı',null),
('MTAL','Gastronomi ve Mutfak Sanatları','Servis ve Kahve Hazırlama','PROGRAM_PENDING','2026-2027 bölgesel program biliniyor; doğrulanmış haftalık PDF sisteme alınamadı',null)
on conflict(institution_type,field_name,branch_name) do update set status=excluded.status,reason=excluded.reason,source_url=excluded.source_url,updated_at=now();
create or replace function audit_mesem_catalog_completeness_v1() returns table(issue_type text,field_name text,branch_name text,reason text) language sql stable set search_path='public' as $$ with f as(select id,field_name from official_vocational_fields where active and institution_type='MESEM'), b as(select f.field_name,b.branch_name from f join official_vocational_branches b on b.field_id=f.id and b.active), x as(select field_name,branch_name,status from official_curriculum_catalog_status where institution_type='MESEM') select 'MISSING_FIELD',f.field_name,null::text,'39 alan referansında var, aktif MESEM profili veya yönetilen istisna yok' from f where not exists(select 1 from official_curriculum_profiles p where p.active and p.school_type='MESEM' and p.field_name=f.field_name) and not exists(select 1 from x where x.field_name=f.field_name and x.status<>'FULL_PROGRAM') union all select 'MISSING_BRANCH',b.field_name,b.branch_name,'193 dal referansında var, aktif MESEM profili veya yönetilen istisna yok' from b where not exists(select 1 from official_curriculum_profiles p where p.active and p.school_type='MESEM' and p.field_name=b.field_name and p.branch_name=b.branch_name) and coalesce((select x.status from x where x.field_name=b.field_name and x.branch_name=b.branch_name),'FULL_PROGRAM')='FULL_PROGRAM' order by 1,2,3; $$;
create or replace function audit_mtal_catalog_completeness_v1() returns table(issue_type text,field_name text,branch_name text,reason text) language sql stable set search_path='public' as $$ with f as(select id,field_name from official_vocational_fields where active and institution_type='MTAL'), b as(select f.field_name,b.branch_name from f join official_vocational_branches b on b.field_id=f.id and b.active), x as(select field_name,branch_name,status from official_curriculum_catalog_status where institution_type='MTAL') select 'MISSING_FIELD',f.field_name,null::text,'56 alan referansında var, aktif MTAL profili veya yönetilen istisna yok' from f where not exists(select 1 from official_curriculum_profiles p where p.active and p.school_type='MTAL' and p.field_name=f.field_name) and not exists(select 1 from x where x.field_name=f.field_name and x.status<>'FULL_PROGRAM') union all select 'MISSING_BRANCH',b.field_name,b.branch_name,'119 dal referansında var, aktif MTAL profili veya yönetilen istisna yok' from b where not exists(select 1 from official_curriculum_profiles p where p.active and p.school_type='MTAL' and p.field_name=b.field_name and p.branch_name=b.branch_name) and coalesce((select x.status from x where x.field_name=b.field_name and x.branch_name=b.branch_name),'FULL_PROGRAM')='FULL_PROGRAM' order by 1,2,3; $$;
