DO $$
BEGIN
CREATE TEMP TABLE _b(branch text,g int,course text,h int) ON COMMIT DROP;
INSERT INTO _b VALUES ('Bilgisayar Teknik Servisi',9,'Bilişim Sistemleri',2),('Bilgisayar Teknik Servisi',10,'Bilişim Teknolojilerinin Temelleri',1),('Bilgisayar Teknik Servisi',10,'Programlama Temelleri',2),('Bilgisayar Teknik Servisi',10,'Bilgisayarlı Tasarım Uygulamaları',1),('Bilgisayar Teknik Servisi',11,'Açık Kaynak İşletim Sistemi',2),('Bilgisayar Teknik Servisi',11,'Bilgisayar Destekli Uygulamalar',2),('Bilgisayar Teknik Servisi',11,'Elektronik Uygulamaları',3),('Bilgisayar Teknik Servisi',12,'Ahilik Kültürü ve Girişimcilik',1),('Bilgisayar Teknik Servisi',12,'Mikrodenetleyici',2),('Bilgisayar Teknik Servisi',12,'Sistem Bakım ve Onarım',5),('Yazılım Geliştirme',9,'Bilişim Sistemleri',2),('Yazılım Geliştirme',10,'Bilişim Teknolojilerinin Temelleri',1),('Yazılım Geliştirme',10,'Programlama Temelleri',2),('Yazılım Geliştirme',10,'Bilgisayarlı Tasarım Uygulamaları',1),('Yazılım Geliştirme',11,'Robotik ve Kodlama',2),('Yazılım Geliştirme',11,'Nesne Tabanlı Programlama',4),('Yazılım Geliştirme',11,'Grafik ve Canlandırma',1),('Yazılım Geliştirme',12,'Ahilik Kültürü ve Girişimcilik',1),('Yazılım Geliştirme',12,'Web Tabanlı Uygulama Geliştirme',4),('Yazılım Geliştirme',12,'Mobil Uygulamalar',2),('Yazılım Geliştirme',12,'Yapay Zekâ ve Makine Öğrenmesi',1);
CREATE TEMP TABLE _c(g int,course text,uh int,dh int) ON COMMIT DROP;
INSERT INTO _c VALUES (9,'Türk Dili ve Edebiyatı',2,2),(9,'Din Kültürü ve Ahlak Bilgisi',2,2),(9,'Matematik',2,2),(9,'Tarih',0,2),(10,'Türk Dili ve Edebiyatı',2,2),(10,'Din Kültürü ve Ahlak Bilgisi',2,2),(10,'Matematik',2,2),(10,'T.C. İnkılap Tarihi ve Atatürkçülük',0,2),(11,'Türk Dili ve Edebiyatı',0,2),(11,'Din Kültürü ve Ahlak Bilgisi',2,2),(11,'Matematik',1,4),(12,'Türk Dili ve Edebiyatı',0,3),(12,'Din Kültürü ve Ahlak Bilgisi',2,2),(12,'Matematik',0,3);
INSERT INTO course_catalog(name,category) SELECT DISTINCT course,'uygulama' FROM _b ON CONFLICT(name) DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT '2026-2027','MESEM','MESEM',x.g,c.id,'zorunlu',ARRAY[x.h],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2022_bilisim_mem_cop.pdf','2022-5 yaşayan MESEM Bilişim Teknolojileri çizelgesi.',true,'Bilişim Teknolojileri',b.branch,'[]'::jsonb,'2022-5',CASE b.branch WHEN 'Bilgisayar Teknik Servisi' THEN 7 ELSE 8 END,'HAFTALIK DERS ÇİZELGESİ',1,false,x.variant FROM (SELECT g,course,'USTALIK' variant,uh h FROM _c WHERE uh>0 UNION ALL SELECT g,course,'DIPLOMA',dh FROM _c WHERE dh>0) x JOIN course_catalog c ON c.name=x.course CROSS JOIN (SELECT DISTINCT branch FROM _b)b ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT '2026-2027','MESEM','MESEM',g.g,c.id,'uygulama',ARRAY[32],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2022_bilisim_mem_cop.pdf','2022-5 yaşayan MESEM Bilişim Teknolojileri çizelgesi.',true,'Bilişim Teknolojileri',b.branch,'[]'::jsonb,'2022-5',CASE b.branch WHEN 'Bilgisayar Teknik Servisi' THEN 7 ELSE 8 END,'HAFTALIK DERS ÇİZELGESİ',1,false,v.variant FROM (select generate_series(9,12) g) g CROSS JOIN (SELECT DISTINCT branch FROM _b)b CROSS JOIN (VALUES('USTALIK'),('DIPLOMA'))v(variant) CROSS JOIN (SELECT id FROM course_catalog WHERE name='İşletmelerde Mesleki Eğitim') c ON CONFLICT DO NOTHING;
INSERT INTO official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
SELECT '2026-2027','MESEM','MESEM',b.g,c.id,'uygulama',ARRAY[b.h],1,true,'https://meslek.meb.gov.tr/upload/cop11_mem/2022_bilisim_mem_cop.pdf','2022-5 yaşayan MESEM Bilişim Teknolojileri çizelgesi.',true,'Bilişim Teknolojileri',b.branch,'[]'::jsonb,'2022-5',CASE b.branch WHEN 'Bilgisayar Teknik Servisi' THEN 7 ELSE 8 END,'HAFTALIK DERS ÇİZELGESİ',1,false,v.variant FROM _b b JOIN course_catalog c ON c.name=b.course CROSS JOIN (VALUES('USTALIK'),('DIPLOMA'))v(variant) ON CONFLICT DO NOTHING;
END $$;