begin;
with br(branch_name,page_no) as (values ('Otomotiv Elektromekanik',9),('İş Makineleri',10),('Otomotiv Gövde',11)), src as (select * from official_curriculum_profiles where school_type='MESEM' and field_name='Makine Teknolojisi' and branch_name='Anahtarcılık ve Çilingirlik' and active)
insert into official_curriculum_profiles(effective_academic_year,school_type,school_subtype,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,group_rules,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_vocational_hours,elective_hours,guidance_hours,enterprise_hours,applicability_status,source_page,parsed_constraints,academic_support_hours)
select s.effective_academic_year,s.school_type,s.school_subtype,s.program_type,'Motorlu Araçlar Teknolojisi',b.branch_name,s.grade_level,s.required_course_count,s.required_hour_total,s.elective_course_min,s.elective_course_max,s.elective_hour_min,s.elective_hour_max,s.total_hour_min,s.total_hour_max,s.total_hour_target,s.group_rules,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33','2021-33 yaşayan MESEM Motorlu Araçlar Teknolojisi çizelgesi; parantezli temel ders saatleri DIPLOMA fark dersidir.',true,s.schedule_variant,s.common_hours,s.vocational_hours,s.elective_vocational_hours,s.elective_hours,s.guidance_hours,s.enterprise_hours,'CURRENTLY_VALID',b.page_no,s.parsed_constraints,s.academic_support_hours from src s cross join br b on conflict do nothing;
insert into course_catalog(name,category,active)
select distinct x.name,'uygulama',true from (values ('Temel Araç Bilgisi'),('Araç Teknolojisi'),('Araçlarda Hidrolik Pnömatik Sistemler'),('Ahilik Kültürü ve Girişimcilik'),('Otomotiv Teknik Resmi'),('Otomotiv Meslek Resmi'),('Otomotiv Elektromekanik Teknolojisi'),('Dizel Yakıt Sistemleri'),('Hareket Kontrol Sistemleri'),('İş Makineleri Teknolojisi'),('İş Makineleri Hareket Kontrol Sistemleri'),('İş Makineleri Hidroelektriği'),('Otomotiv Gövde Kaynak'),('Otomotiv Gövde Teknolojisi'),('Otomotiv Gövde Onarımı'),('Otomotiv Gövde Mekaniği')) x(name) where not exists(select 1 from course_catalog c where c.name=x.name);
with br(branch_name,page_no) as (values ('Otomotiv Elektromekanik',9),('İş Makineleri',10),('Otomotiv Gövde',11)), common_src as (select s.* from official_course_schedule_catalog s join course_catalog c on c.id=s.course_id where s.active and s.school_type='MESEM' and s.field_name='Makine Teknolojisi' and s.branch_name='Anahtarcılık ve Çilingirlik' and s.source_decision_no='2021-33' and c.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','İşletmelerde Mesleki Eğitim'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,elective_group_key,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select s.effective_academic_year,s.school_type,s.program_type,s.grade_level,s.course_id,s.category,s.hour_options,s.max_selections,s.repeat_across_years,s.elective_group_key,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33 yaşayan MESEM Motorlu Araçlar Teknolojisi çizelgesi',true,'Motorlu Araçlar Teknolojisi',b.branch_name,s.parsed_constraints,s.school_subtype,'2021-33',b.page_no,'HAFTALIK DERS ÇİZELGESİ',1,false,s.schedule_variant from common_src s cross join br b on conflict do nothing;
with data(branch_name,page_no,grade_level,course_name,hours) as (values
('Otomotiv Elektromekanik',9,9,'Temel Araç Bilgisi',2),('Otomotiv Elektromekanik',9,10,'Araç Teknolojisi',3),('Otomotiv Elektromekanik',9,10,'Araçlarda Hidrolik Pnömatik Sistemler',1),('Otomotiv Elektromekanik',9,11,'Otomotiv Teknik Resmi',2),('Otomotiv Elektromekanik',9,11,'Otomotiv Elektromekanik Teknolojisi',5),('Otomotiv Elektromekanik',9,12,'Ahilik Kültürü ve Girişimcilik',1),('Otomotiv Elektromekanik',9,12,'Otomotiv Meslek Resmi',2),('Otomotiv Elektromekanik',9,12,'Dizel Yakıt Sistemleri',2),('Otomotiv Elektromekanik',9,12,'Hareket Kontrol Sistemleri',3),('İş Makineleri',10,9,'Temel Araç Bilgisi',2),('İş Makineleri',10,10,'Araç Teknolojisi',3),('İş Makineleri',10,10,'Araçlarda Hidrolik Pnömatik Sistemler',1),('İş Makineleri',10,11,'Otomotiv Teknik Resmi',2),('İş Makineleri',10,11,'İş Makineleri Teknolojisi',5),('İş Makineleri',10,12,'Ahilik Kültürü ve Girişimcilik',1),('İş Makineleri',10,12,'Otomotiv Meslek Resmi',2),('İş Makineleri',10,12,'İş Makineleri Hareket Kontrol Sistemleri',2),('İş Makineleri',10,12,'İş Makineleri Hidroelektriği',3),('Otomotiv Gövde',11,9,'Temel Araç Bilgisi',2),('Otomotiv Gövde',11,10,'Araç Teknolojisi',3),('Otomotiv Gövde',11,10,'Araçlarda Hidrolik Pnömatik Sistemler',1),('Otomotiv Gövde',11,11,'Otomotiv Teknik Resmi',2),('Otomotiv Gövde',11,11,'Otomotiv Gövde Kaynak',3),('Otomotiv Gövde',11,11,'Otomotiv Gövde Teknolojisi',2),('Otomotiv Gövde',11,12,'Ahilik Kültürü ve Girişimcilik',1),('Otomotiv Gövde',11,12,'Otomotiv Meslek Resmi',2),('Otomotiv Gövde',11,12,'Otomotiv Gövde Onarımı',3),('Otomotiv Gövde',11,12,'Otomotiv Gövde Mekaniği',2)), vars(schedule_variant) as (values('USTALIK'),('DIPLOMA'))
insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,parsed_constraints,school_subtype,source_decision_no,source_page,source_section,parser_confidence,needs_review,schedule_variant)
select '2026-2027','MESEM','MESEM',d.grade_level,c.id,'uygulama',array[d.hours],1,true,'https://meslek.meb.gov.tr/upload/cop9_mem/2021_motorlu_mem_cop.pdf','2021-33 yaşayan MESEM Motorlu Araçlar Teknolojisi çizelgesi',true,'Motorlu Araçlar Teknolojisi',d.branch_name,'[]'::jsonb,null,'2021-33',d.page_no,'HAFTALIK DERS ÇİZELGESİ',1,false,v.schedule_variant from data d join course_catalog c on c.name=d.course_name cross join vars v on conflict do nothing;
commit;