do $$
declare branch_v text; grade_v int; variant_v text;
begin
  foreach branch_v in array array['Ahşap Doğrama Teknolojisi','İç Mekân ve Mobilya Teknolojisi','Mobilya İskeleti ve Döşemesi','Mobilya Süsleme Sanatları','Oto Döşemeciliği'] loop
    for grade_v in 9..12 loop
      foreach variant_v in array array['USTALIK','DIPLOMA'] loop
        insert into official_curriculum_profiles(effective_academic_year,school_type,program_type,field_name,branch_name,grade_level,required_course_count,required_hour_total,elective_course_min,elective_course_max,elective_hour_min,elective_hour_max,total_hour_min,total_hour_max,total_hour_target,source_file_name,source_decision_no,source_note,active,schedule_variant,common_hours,vocational_hours,elective_hours,guidance_hours,enterprise_hours,academic_support_hours,applicability_status)
        select '2026-2027','MESEM','MESEM','Mobilya ve İç Mekân Tasarımı',branch_v,grade_v,0,
          case when variant_v='USTALIK' then case grade_v when 9 then 40 else 42 end else case grade_v when 9 then 42 when 10 then 44 when 11 then 46 else 48 end end,
          0,0,0,case when grade_v=9 then 2 else 0 end,
          case when variant_v='USTALIK' then 42 else case grade_v when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
          case when variant_v='USTALIK' then 42 else case grade_v when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
          case when variant_v='USTALIK' then 42 else case grade_v when 9 then 44 when 10 then 44 when 11 then 46 else 48 end end,
          'https://meslek.meb.gov.tr/upload/cop12_mem/2022_mobilya_mem_cop.pdf','2022-33','2022-33 yaşayan MESEM Mobilya ve İç Mekân Tasarımı çizelgesi.',true,variant_v,
          case when variant_v='USTALIK' then case grade_v when 9 then 6 when 10 then 6 when 11 then 3 else 2 end else case grade_v when 9 then 8 when 10 then 8 when 11 then 7 else 8 end end,
          case grade_v when 9 then 2 when 10 then 4 when 11 then 7 else 8 end,
          case when grade_v=9 then 2 else 0 end,0,32,0,'ACTIVE'
        on conflict (effective_academic_year,school_type,coalesce(school_subtype,''),coalesce(program_type,''),coalesce(field_name,''),coalesce(branch_name,''),grade_level,coalesce(schedule_variant,'STANDARD')) do update set source_decision_no=excluded.source_decision_no,source_file_name=excluded.source_file_name,source_note=excluded.source_note,active=true,updated_at=now();
      end loop;
    end loop;
  end loop;

  insert into course_catalog(name,category,active)
  select x,'uygulama',true from unnest(array['Mobilya Üretimi','Mobilya Yapım Teknikleri','Mobilya Teknik Resmi','Bilgisayar Destekli Mobilya Çizimi','Ahilik Kültürü ve Girişimcilik','Üst Yüzey İşlemleri','Mobilya Süsleme Teknikleri','Mobilya Süsleme Resmi','Bilgisayarda Mobilya Süsleme Resmi','Bilgisayar Kontrollü Makinelerde Üretim (CNC)','Mobilya İç Mekân Elemanları','Bilgisayarlı Mobilya Resmi','Bilgisayarlı Mobilya İç Mekân Resmi','İç ve Dış Mekân Doğramaları','Bilgisayarlı İç Mekân Doğrama Resmi','Bilgisayarlı Dış Mekân Doğrama Resmi','Mobilya İskeleti ve Döşeme Teknikleri','Bilgisayar Destekli İskelet Resmi','Bilgisayar Destekli İskelet ve Döşeme Tasarımı','Oto Koltuğu Döşeme Teknikleri','Oto Yanları Döşeme Teknikleri','Oto Taban Döşeme Teknikleri','Oto Tavan Döşeme Teknikleri']) x
  where not exists(select 1 from course_catalog c where c.name=x);

  delete from official_course_schedule_catalog where school_type='MESEM' and field_name='Mobilya ve İç Mekân Tasarımı' and effective_academic_year='2026-2027';

  insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,source_decision_no,source_page,parser_confidence,needs_review,schedule_variant)
  select '2026-2027','MESEM','MESEM',m.grade_level,m.course_id,m.category,m.hour_options,m.max_selections,m.repeat_across_years,'https://meslek.meb.gov.tr/upload/cop12_mem/2022_mobilya_mem_cop.pdf','2022-33 Mobilya; ortak temel dersler doğrulanmış MESEM şablonundan.',true,'Mobilya ve İç Mekân Tasarımı',br.branch_name,'2022-33',case br.branch_name when 'Mobilya Süsleme Sanatları' then 7 when 'İç Mekân ve Mobilya Teknolojisi' then 8 when 'Ahşap Doğrama Teknolojisi' then 9 when 'Mobilya İskeleti ve Döşemesi' then 10 else 11 end,1,false,m.schedule_variant
  from official_course_schedule_catalog m cross join unnest(array['Ahşap Doğrama Teknolojisi','İç Mekân ve Mobilya Teknolojisi','Mobilya İskeleti ve Döşemesi','Mobilya Süsleme Sanatları','Oto Döşemeciliği']) as br(branch_name)
  join course_catalog c on c.id=m.course_id
  where m.active and m.school_type='MESEM' and m.field_name='Makine Teknolojisi' and m.branch_name='Makine Bakım Onarım' and m.effective_academic_year='2026-2027' and c.name in ('Türk Dili ve Edebiyatı','Din Kültürü ve Ahlak Bilgisi','Matematik','Tarih','T.C. İnkılap Tarihi ve Atatürkçülük','İşletmelerde Mesleki Eğitim');

  insert into official_course_schedule_catalog(effective_academic_year,school_type,program_type,grade_level,course_id,category,hour_options,max_selections,repeat_across_years,source_file_name,source_note,active,field_name,branch_name,source_decision_no,source_page,parser_confidence,needs_review,schedule_variant)
  select '2026-2027','MESEM','MESEM',x.grade_level,c.id,'uygulama',array[x.hours],1,false,'https://meslek.meb.gov.tr/upload/cop12_mem/2022_mobilya_mem_cop.pdf','2022-33 Mobilya resmî haftalık çizelgesi.',true,'Mobilya ve İç Mekân Tasarımı',x.branch_name,'2022-33',case x.branch_name when 'Mobilya Süsleme Sanatları' then 7 when 'İç Mekân ve Mobilya Teknolojisi' then 8 when 'Ahşap Doğrama Teknolojisi' then 9 when 'Mobilya İskeleti ve Döşemesi' then 10 else 11 end,1,false,var.variant_name
  from (values
    ('Mobilya Süsleme Sanatları',9,'Mobilya Üretimi',2),('Mobilya Süsleme Sanatları',10,'Mobilya Yapım Teknikleri',1),('Mobilya Süsleme Sanatları',10,'Mobilya Teknik Resmi',2),('Mobilya Süsleme Sanatları',10,'Bilgisayar Destekli Mobilya Çizimi',1),('Mobilya Süsleme Sanatları',11,'Mobilya Süsleme Teknikleri',3),('Mobilya Süsleme Sanatları',11,'Mobilya Süsleme Resmi',4),('Mobilya Süsleme Sanatları',12,'Ahilik Kültürü ve Girişimcilik',1),('Mobilya Süsleme Sanatları',12,'Üst Yüzey İşlemleri',1),('Mobilya Süsleme Sanatları',12,'Bilgisayarda Mobilya Süsleme Resmi',4),('Mobilya Süsleme Sanatları',12,'Bilgisayar Kontrollü Makinelerde Üretim (CNC)',2),
    ('İç Mekân ve Mobilya Teknolojisi',9,'Mobilya Üretimi',2),('İç Mekân ve Mobilya Teknolojisi',10,'Mobilya Yapım Teknikleri',1),('İç Mekân ve Mobilya Teknolojisi',10,'Mobilya Teknik Resmi',2),('İç Mekân ve Mobilya Teknolojisi',10,'Bilgisayar Destekli Mobilya Çizimi',1),('İç Mekân ve Mobilya Teknolojisi',11,'Mobilya İç Mekân Elemanları',3),('İç Mekân ve Mobilya Teknolojisi',11,'Bilgisayarlı Mobilya Resmi',4),('İç Mekân ve Mobilya Teknolojisi',12,'Ahilik Kültürü ve Girişimcilik',1),('İç Mekân ve Mobilya Teknolojisi',12,'Üst Yüzey İşlemleri',1),('İç Mekân ve Mobilya Teknolojisi',12,'Bilgisayarlı Mobilya İç Mekân Resmi',4),('İç Mekân ve Mobilya Teknolojisi',12,'Bilgisayar Kontrollü Makinelerde Üretim (CNC)',2),
    ('Ahşap Doğrama Teknolojisi',9,'Mobilya Üretimi',2),('Ahşap Doğrama Teknolojisi',10,'Mobilya Yapım Teknikleri',1),('Ahşap Doğrama Teknolojisi',10,'Mobilya Teknik Resmi',2),('Ahşap Doğrama Teknolojisi',10,'Bilgisayar Destekli Mobilya Çizimi',1),('Ahşap Doğrama Teknolojisi',11,'İç ve Dış Mekân Doğramaları',3),('Ahşap Doğrama Teknolojisi',11,'Bilgisayarlı İç Mekân Doğrama Resmi',4),('Ahşap Doğrama Teknolojisi',12,'Ahilik Kültürü ve Girişimcilik',1),('Ahşap Doğrama Teknolojisi',12,'Üst Yüzey İşlemleri',1),('Ahşap Doğrama Teknolojisi',12,'Bilgisayarlı Dış Mekân Doğrama Resmi',4),('Ahşap Doğrama Teknolojisi',12,'Bilgisayar Kontrollü Makinelerde Üretim (CNC)',2),
    ('Mobilya İskeleti ve Döşemesi',9,'Mobilya Üretimi',2),('Mobilya İskeleti ve Döşemesi',10,'Mobilya Yapım Teknikleri',1),('Mobilya İskeleti ve Döşemesi',10,'Mobilya Teknik Resmi',2),('Mobilya İskeleti ve Döşemesi',10,'Bilgisayar Destekli Mobilya Çizimi',1),('Mobilya İskeleti ve Döşemesi',11,'Mobilya İskeleti ve Döşeme Teknikleri',3),('Mobilya İskeleti ve Döşemesi',11,'Bilgisayar Destekli İskelet Resmi',4),('Mobilya İskeleti ve Döşemesi',12,'Ahilik Kültürü ve Girişimcilik',1),('Mobilya İskeleti ve Döşemesi',12,'Üst Yüzey İşlemleri',1),('Mobilya İskeleti ve Döşemesi',12,'Bilgisayar Destekli İskelet ve Döşeme Tasarımı',4),('Mobilya İskeleti ve Döşemesi',12,'Bilgisayar Kontrollü Makinelerde Üretim (CNC)',2),
    ('Oto Döşemeciliği',9,'Mobilya Üretimi',2),('Oto Döşemeciliği',10,'Mobilya Yapım Teknikleri',1),('Oto Döşemeciliği',10,'Mobilya Teknik Resmi',2),('Oto Döşemeciliği',10,'Bilgisayar Destekli Mobilya Çizimi',1),('Oto Döşemeciliği',11,'Oto Koltuğu Döşeme Teknikleri',3),('Oto Döşemeciliği',11,'Oto Yanları Döşeme Teknikleri',4),('Oto Döşemeciliği',12,'Ahilik Kültürü ve Girişimcilik',1),('Oto Döşemeciliği',12,'Üst Yüzey İşlemleri',1),('Oto Döşemeciliği',12,'Oto Taban Döşeme Teknikleri',3),('Oto Döşemeciliği',12,'Oto Tavan Döşeme Teknikleri',3)
  ) x(branch_name,grade_level,course_name,hours)
  join course_catalog c on c.name=x.course_name cross join unnest(array['USTALIK','DIPLOMA']) as var(variant_name);
end$$;